### ISSUE TITLE
Submenu rendering is jittery

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JFormDesigner/FlatLaf#10]
This is not seen in the demo app since it doesn't have secondary level menus.

You'll need a couple of primary items that open secondary content, each one with different texts and icons. As you roll over the primary items, the newly opened secondary menu shows the old content (from the previously opened secondary menu) for a split second, and then shows the correct content.

**Comment by DevCharly** [comment]
Thanks, I can reproduce it

**Comment by DevCharly** [comment]
fixed in 0.20
