### ISSUE TITLE
ComboBox editor component with custom border is not respected

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#102]
Using this test case: [ComboBoxEditorBorderTest.zip](https://github.com/JFormDesigner/FlatLaf/files/4628147/ComboBoxEditorBorderTest.zip)
the system look and feel respects the border that is set on the editor component but not FlatLaf:
![ComboBoxEditorWithBorder](https://user-images.githubusercontent.com/1174202/81932769-900fda80-95ec-11ea-87b8-935249a62186.png)

Note that the Windows button seems to have a space on its left, but that space is part of the button (you can click on it).

**Comment by Chrriis** [comment]
My previous test case illustrated the issue but did not show how important this can be.
Changing the border is a way to insert things like icons without overlapping the text. These indications can have an important meaning for the user.

Here is a dummy example of an inserted icon (Windows vs FlatLaf):
![ComboBoxEditorWithBorder2](https://user-images.githubusercontent.com/1174202/82184667-4d018000-98e8-11ea-87a8-ee057404596c.png)

And here is the corresponding test case: [ComboBoxEditorBorderTest.zip](https://github.com/JFormDesigner/FlatLaf/files/4642596/ComboBoxEditorBorderTest.zip)

**Comment by DevCharly** [comment]
Nice. I know this icon-in-border trick. Used it for text fields 😄 

I'll check whether I can implement some "compatibility mode" for combobox to support such tricks.

For the "error indication" border there is now a better solution in FlatLaf (in master branch) that works without hacking borders. Simply set the client property `JComponent.outline` to `error`, `warning` or any `java.awt.Color` changes the component border color. Works with all components that have a border in FlatLaf. Uses darker border color for focused components.

![image](https://user-images.githubusercontent.com/5604048/82214790-a54f7680-9916-11ea-8272-859559fdbc72.png)

~~~java
comp1.putClientProperty("JComponent.outline", "error");
comp2.putClientProperty("JComponent.outline", "warning");
comp3.putClientProperty("JComponent.outline", Color.magenta);
~~~

I plan to add two additional client properties to textfields, combobox and spinner to allow adding custom components to the left and right side. This will make it very easy to extend those components without hacking the border.

**Comment by Chrriis** [comment]
The validation color capability is nice! Unfortunately, the icons I am talking about are not related to data validation so colors are not applicable as a replacement. Also, FlatLaf is not the default look and feel (for now) so I cannot make use of FlatLaf specific features...

**Comment by DevCharly** [comment]
now fixed in master branch

**Comment by Chrriis** [comment]
Thanks a lot! I tested on my real-world case and it works as advirtised! 😉
