### ISSUE TITLE
FlatLaf fails when accessed from a JAR file

### ISSUE THREAD

**Issue by uwemock** [JFormDesigner/FlatLaf#104]
I have integrated Flatlaf in a Swing application, and everything is fine when I run the application from Eclipse. As soon as I create a JAR file and run the JAR file, the program hangs.

Error log is attached.

[flatlaf_errorfile.txt](https://github.com/JFormDesigner/FlatLaf/files/4652499/flatlaf_errorfile.txt)

**Comment by uwemock** [comment]
Ok, got this one. FlatLaf needs to be excluded from shading. This should be documented!

<filter>
  <artifact>com.formdev:flatlaf</artifact>
  <includes>
    <include>**</include>
  </includes>
</filter>

**Comment by DevCharly** [comment]
Are you using [Apache Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/) and let it rename all classes?
Isn't there a high risk with all 3rd party libraries that this breaks something?

FlatLaf class names are used in `.properties` files within the `flatlaf.jar`.
Maybe the Shade plugin can rename them too, but I can not guarantee that this works.

**Comment by uwemock** [comment]
I don't let the plugin rename anything, but it's the only possibility that I am aware of to get one single JAR file.
Usually, everything works well, except for libraries that instantiate classes through reflection. However, this is documented in most cases.

**Comment by dinix2008** [comment]
Hello! We use the maven-shade-plugin to get a single JAR file with FlatLaf and everything works fine. Even on the latest (0.35) version.

**Comment by uwemock** [comment]
@dinix2008 
And you haven't configured the plugin to leave the whole of the FlatLaf artifact in the JAR??

**Comment by dinix2008** [comment]
@uwemock 
Here are my plugin settings if that helps:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <configuration>
        <transformers>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
            <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                <manifestEntries>
                    <Main-Class>Launcher</Main-Class>
                    <SplashScreen-Image>splash.gif</SplashScreen-Image>
                </manifestEntries>
            </transformer>
        </transformers>

        <filters>
            <filter>
                <artifact>*:*</artifact>
                <excludes>
                    <exclude>module-info.class</exclude>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>META-INF/maven/**</exclude>
                    <exclude>META-INF/MANIFEST.MF</exclude>
                    <exclude>licenses/**</exclude>
                    <exclude>**/LICENSE</exclude>
                    <exclude>**/LICENSE.txt</exclude>
                    <exclude>**/license</exclude>
                    <exclude>**/license.txt</exclude>
                    <exclude>**/NOTICE*</exclude>
                    <exclude>**/notice*</exclude>
                    <exclude>**/README*</exclude>
                    <exclude>**/readme*</exclude>
                    <exclude>INSTALL.html</exclude>
                </excludes>
            </filter>
        </filters>
    </configuration>
</plugin>
```

**Comment by uwemock** [comment]
I have
`<minimizeJar>true</minimizeJar>`
in my configuration.

**Comment by dinix2008** [comment]
@uwemock 
I think this is the reason. Try adding FlatLaf to filter section
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <configuration>
        ...
        <minimizeJar>true</minimizeJar>
        <filters>
            ...
            <filter>
                <artifact>com.formdev:flatlaf</artifact>
                <includes>
                    <include>**</include>
                </includes>
            </filter>
        </filters>
    </configuration>
</plugin>
```

**Comment by uwemock** [comment]
See [this post](https://github.com/JFormDesigner/FlatLaf/issues/104#issuecomment-631023537).

**Comment by dinix2008** [comment]
> See [this post](https://github.com/JFormDesigner/FlatLaf/issues/104#issuecomment-631023537).

ok, did not see this comment
