### ISSUE TITLE
Fonts are not properly rendered on Ubuntu 20.04

### ISSUE THREAD

**Issue by mbiebl** [JFormDesigner/FlatLaf#105]
Hi,

first of all, thanks for this awesome LaF. I really like it.

While testing it on various Linux distributions, I noticed that FlatLaf integrates really nicely on Debian GNOME and Fedora GNOME, but looks out of place on Ubuntu.
If attached a few screenshots. The fonts that are picked on Ubuntu are not the default system fonts, they appear to thin and big.

Debian:
![Screenshot_debian10_2020-05-20_16:25:41](https://user-images.githubusercontent.com/3609611/82459951-d9629d00-9ab8-11ea-8477-7af0ed9175a6.png)
Fedora:
![Screenshot_fedora-rawhide_2020-05-20_16:36:16](https://user-images.githubusercontent.com/3609611/82459973-e089ab00-9ab8-11ea-9c4f-ad4b8f20003c.png)
Ubuntu:
![Screenshot_ubuntu20 04_2020-05-20_16:37:56](https://user-images.githubusercontent.com/3609611/82459980-e4b5c880-9ab8-11ea-9ee2-c5f04cc05a69.png)

**Comment by DevCharly** [comment]
Thanks. That does not look good.

I can reproduce it when using OpenJDK.
When using JetBrains VM it looks OK.
In both cases FlatLaf uses the font "Ubuntu".
Seems to be a rendering issue of the Java distribution.

You can verify this when you change to "GTK+" look and feel in FlatLaf Demo (left-bottom combobox). FlatLaf basically uses the same mechanism as GTK Laf to pick the font.

What Java distributions do you use on the different platforms?

**Comment by mbiebl** [comment]
Those are basically pristine test VMs using Fedora 32, Debian 10 and Ubuntu 20.04

Fedora 32
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
Debian
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3, mixed mode, sharing)
```

On Ubuntu 20.04 I tried both
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
and
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

The result was basically the same. I can confirm that the GTK+ L&F on Ubuntu has the same fonts problem (see screenshot)
![Screenshot_ubuntu20 04_2020-05-20_18:42:56](https://user-images.githubusercontent.com/3609611/82473415-d0c69280-9ac9-11ea-9720-1b6b193a4bac.png)

**Comment by mbiebl** [comment]
I.e. it looks really out of place

**Comment by mbiebl** [comment]
I can confirm your findings: Intellij looks fine and seems to pick up the correct system font and font sizes.

I also tried netbeans, which shows the same problem as the FlatLaf demo.

Last but not least I also tested apache jmeter (which uses DarkLaf). I'm not 100% sure if it uses the system font, but the result looks much more pleasing (screenshot attached)
![Screenshot_ubuntu20 04_2020-05-20_19:01:21](https://user-images.githubusercontent.com/3609611/82475269-84308680-9acc-11ea-9a85-9a2e8d963c49.png)

**Comment by DevCharly** [comment]
Thanks for all the info. I'll looking for a fix/workaround...

I think JMeter uses the default Java font named "Dialog".
You can try this font out in the FlatLaf Demo: in the menu bar choose "Font > Dialog".
It looks better, but is not the Ubuntu font...

**Comment by mbiebl** [comment]
@DevCharly I did some more digging and it seems, Intellj ships its own, patched JRE.
If I use that JRE, fonts look fine. In the Intellij installation folder, use `./jbr/bin/java -jar flatlaf-demo-0.35.jar`

**Comment by mbiebl** [comment]
I wonder if the Jetbrains guys could be convinced to contribute those changes to OpenJDK directly.

**Comment by mbiebl** [comment]
```
$ ./jbr/bin/java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+8-b765.40)
OpenJDK 64-Bit Server VM (build 11.0.6+8-b765.40, mixed mode)

$ ./jbr/bin/java -jar /home/michael/Downloads/flatlaf-demo-0.35.jar` 
```
![Bildschirmfoto vom 2020-05-20 23-23-32](https://user-images.githubusercontent.com/3609611/82498863-f5823080-9af0-11ea-9a21-4a134d50273a.png)

**Comment by mbiebl** [comment]
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime

**Comment by mbiebl** [comment]
In case one doesn't want to install the full IntelliJ suite you can pull the JBR from
https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-linux-x64/912.1#files

This makes a huge difference on Ubuntu (also for the GTK L&F)

**Comment by mbiebl** [comment]
Some more experiments.
On Debian GNOME (using the Noto font), the difference between openjdk and jbr is noticeable, but much more subtle.

Debian/openjdk
![debian-openjdk](https://user-images.githubusercontent.com/3609611/82505365-d50ca300-9afd-11ea-8220-4058a8816d58.png)
Debian/jbr
![debian-jbr](https://user-images.githubusercontent.com/3609611/82505370-db9b1a80-9afd-11ea-8c71-51a5c52fa5a1.png)

In contrast, on Ubuntu, the difference is striking
Ubuntu/openjdk
![ubuntu-openjdk](https://user-images.githubusercontent.com/3609611/82505388-e8b80980-9afd-11ea-875b-8b85e88dfb93.png)
Ubuntu/jbr
![ubuntu-jbr](https://user-images.githubusercontent.com/3609611/82505395-ed7cbd80-9afd-11ea-9e08-4e7cdb99f286.png)

**Comment by mbiebl** [comment]
So I guess this might just boil down to the Ubuntu Font being very poorly rendered with the default OpenJDK JRE.

**Comment by DevCharly** [comment]
@mbiebl many thanks for all your experiments and for sharing the details.

> So I guess this might just boil down to the Ubuntu Font being very poorly rendered with the default OpenJDK JRE.

I agree. I've changed it in a way that the default Java font (seems to be DejaVu Sans on Ubuntu) is used instead of Ubuntu font (except if running in JetBrains VM). The change is in master branch.

I've also extended the FlatLaf Demo. It now shows the used font near the Java version at the bottom of the window. Also the "Font" menu now has checkmarks at the active font family and font size.

**Comment by mbiebl** [comment]
@DevCharly I built the latest git master. See attached screenshot.
Still doesn't look right.
![Bildschirmfoto vom 2020-05-21 20-26-28](https://user-images.githubusercontent.com/3609611/82592644-83b5ef80-9ba1-11ea-8286-267eb06531ac.png)

**Comment by mbiebl** [comment]
The font size (15) seems to be off. According to gnome-tweaks, the font size is 11.

**Comment by DevCharly** [comment]
It does not look as good as the Cantarell font on Debian and Fedora, but better than the Ubuntu font.
I've just tried the DejaVu Sans font (aka SansSerif) on Fedora 31 and it looks the same as on Ubuntu.

Unfortunately Cantarell font is not preinstalled on Ubuntu.
Maybe there is another font preinstalled on Ubuntu that works better for Java...
Will try some...
BTW just pushed a commit that updates FlatLaf font when system font is changed in Tweaks app.

Regarding the different font sizes in GNOME and Java apps: the font sizes are measured in "points" (not pixels). GNOME apps use 72 DPI as base, but Java uses 96 DPI.
So `javaFontSize = gnomeFontSize * (96 / 72)` or `javaFontSize = gnomeFontSize * 1.33333`.

The font size in the latest screenshot seems to be OK. It is 11 pixels for letter 'D', which is the same as in your screenshots from Debian, Fedora and JetBrains VM on Ubuntu.

BTW JMeter uses also the DejaVu Sans font but with size 12, which results in 9px for letter 'D'.

**Comment by DevCharly** [comment]
Tried all "regular" fonts on Ubuntu 20.04 and there are only few alternative font that work OK in Java.

As reference the Ubuntu font:

![image](https://user-images.githubusercontent.com/5604048/82692771-94796a80-9c60-11ea-8212-f60b2a228ed8.png)

As reference the currently used DejaVu Sans (aka SansSerif):

![image](https://user-images.githubusercontent.com/5604048/82692036-3e57f780-9c5f-11ea-939f-b8ad10b9deef.png)

Liberation Sans (font looks nice and component heights are equal to DejaVu/Ubuntu fonts):

![image](https://user-images.githubusercontent.com/5604048/82692173-8414c000-9c5f-11ea-90ae-63d68ca21ae0.png)

Noto Sans CJK JP (font looks nice, components slightly greater than DejaVu/Ubuntu fonts):

![image](https://user-images.githubusercontent.com/5604048/82692131-6fd0c300-9c5f-11ea-9dc2-8cecf3c705b9.png)


Loma (font looks OK, but components are large):

![image](https://user-images.githubusercontent.com/5604048/82692187-8b3bce00-9c5f-11ea-9de9-7dba9f61059e.png)

Waree (font looks OK, but components are too large):

![image](https://user-images.githubusercontent.com/5604048/82692201-8ecf5500-9c5f-11ea-8716-44fd31b075d8.png)

**Comment by DevCharly** [comment]
Liberation Sans is now the default font for FlatLaf on Ubuntu (except if running in JetBrains VM)

**Comment by mbiebl** [comment]
Thanks @DevCharly.
Although it is still noticeable that FlatLaf is not using the default Ubuntu font, with Liberation Sans it looks much better then before, so I think it is an acceptable compromise.

Would still be awesome though to see this fixed in OpenJDK proper. I wonder if there is a reason why those JetBrains improvements (which appear to be open source) are not forwarded / applied to OpenJDK.

**Comment by DevCharly** [comment]
Maybe they already tried to contribute it to OpenJDK and it was not (yet) accepted. I don't know.

Here I found more information about Font rendering in JetBrains VM:
https://confluence.jetbrains.com/display/JBR/Fonts+Layout+Rendering
