### ISSUE TITLE
Problem in tables' renderer for cell including checkbox since 0.35

### ISSUE THREAD

**Issue by Poivin** [JFormDesigner/FlatLaf#107]
Hi @DevCharly,

since 0.35 i have a regression in the background/border of cells including checkbox in tables (my tables have an alternate row renderer) : 

![image](https://user-images.githubusercontent.com/61098745/83166999-fd089180-a10f-11ea-88e0-794f1382c53c.png)

Do you think it is a regression in flatLAF? 

Thanks

**Comment by Poivin** [comment]
Previous display : 
![image](https://user-images.githubusercontent.com/61098745/83168231-7654b400-a111-11ea-97e5-0fd891c295a5.png)

**Comment by DevCharly** [comment]
Yes, there is a change in 0.35. The default checkbox table renderer was non-opaque in 0.34 and is opaque in 0.35. The change is in commit d3a70b8bb299744ce1d333e4f66299705a799b72 for issue #77.

Do you use a custom renderer for the checkboxes?
Does your renderer work with Metal or Windows LaF?

**Comment by Poivin** [comment]
Yes it is a specific renderer that works in metal LAF (the difference between alternate colors are low) : 
![image](https://user-images.githubusercontent.com/61098745/83195396-72895780-a13a-11ea-8b9b-b0f9ca9e5706.png)


but in nimbus LAF it does not work...
![image](https://user-images.githubusercontent.com/61098745/83195504-99478e00-a13a-11ea-9e68-3d615a20a160.png)

The row selection background is also not propagated to the checkbox cell

It is ok in flatLAFdemo we will check our renderer regarding your commit and then close this issue 

Thanks Karl!
