### ISSUE TITLE
JInternalFrame with disabled shadow has an invisible transparent border and cannot be set opaque

### ISSUE THREAD

**Issue by electriq** [JFormDesigner/FlatLaf#109]
We want to set all `JInternalFrames` opaque because it hugely speeds up redrawing (moving and switching frames) if we have many internal frames. We found that `internalFrame.setOpaque(true);` causes visible gray border if shadows are disabled because there still is an invisible border. The borders of the internal frames with FlatLaf do not have rounding so the frames suit well for setting opaque.

BTW, I found experimentally that
`UIManager.put("InternalFrame.dropShadowPainted", false);`
only works if invoked _before_ setting lnf
`UIManager.setLookAndFeel(new FlatLightLaf());`.

P.S. Thank you for FlatLaf, we were waiting for it for years!

**Comment by DevCharly** [comment]
There is an "invisible" border around each internal frame that is used for resizing.
So if the internal frame is opaque, there are some options to fix the gray border:

a) remove the invisible border with
~~~java
UIManager.put("InternalFrame.borderMargins", new Insets(1,1,1,1));
~~~
but this makes it hard to resize the internal frames

b) make the border thicker
~~~java
UIManager.put("InternalFrame.borderLineWidth", 4);
UIManager.put("InternalFrame.borderMargins", new Insets(4,4,4,4));
~~~
does not look as nice as the thin border, but resizing is easy

c) set the internal frame background color to the same color as the container.
E.g. if the internal frames are children of a `JDesktopPane` use:
~~~java
internalFrame.setBackground( UIManager.getColor( "Desktop.background" ) );
~~~

> Thank you for FlatLaf, we were waiting for it for years!

Glad that it is useful 😄 

PS don't forget to "star" FlatLaf here on github 😉

**Comment by electriq** [comment]
> There is an "invisible" border around each internal frame that is used for resizing.

Thank you, I didn't know that. So you can tag it 'won't fix' because of that, I think.

The combination of b) and c) works nice, thank you for the quick suggestion!
