### ISSUE TITLE
cannot find package, gradle, intelliJ

### ISSUE THREAD

**Issue by sstephans** [JFormDesigner/FlatLaf#111]
I posted this as a reply to a previous issue, then noted it was closed so I don't think anyone will see it. Feel free to merge these issues if that's appropriate. 

This line `UIManager.setLookAndFeel(new FlatLightLaf());` as well as `FlatLightLaf.install();` both produce the error
```
java: cannot find symbol
symbol: class FlatLightLaf
```
Including the statement `import com.formdev.flatlaf.FlatLightLaf;` produces the error
`java package com.formdev.flatlaf does not exist`

I'm running the IntelliJ IDE, Java version 8, using gradle build tools. I have this line in my gradle build dependencies
`runtime group: 'com.formdev', name: 'flatlaf', version: '0.35'`

Every time I refresh gradle, it shows the package in my list of runtime and test runtime dependencies. I have also tried versions 0.32-0.35 and all produce the same error when compiling.

I have also tried removing the line in gradle.build and creating a manual link to the downloaded jar file (version 0.35) using the project structure menu under dependencies. It lists it in my external libraries, but the problem persists. 

edit:
I have now reproduced the issue with a newly created project using IntelliJ and Maven as a build tool instead of gradle. 

edit2:
Manually linking to the jar file with the Maven version of the project compiled without errors and the look was loaded. Version 0.35 for reference.

**Comment by DevCharly** [comment]
> ~~~
> runtime group: 'com.formdev', name: 'flatlaf', version: '0.35'
> ~~~

I think you have to change this to
~~~
implementation group: 'com.formdev', name: 'flatlaf', version: '0.35'
~~~

`runtime` dependencies are used when running the project, but not when compiling it.

**Comment by DevCharly** [comment]
Does it work now?

**Comment by DevCharly** [comment]
Assume that it works now...
