### ISSUE TITLE
Option to set disabledBackground for FlatButtonUI

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#112]
as you see in https://github.com/JFormDesigner/FlatLaf/blob/fd99af5fe6e256bbd52869df2dc05e1a6246f2bf/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatButtonUI.java#L357-L380 there is no way to set the background color for a disabled button without creating your own ButtonUI class.

Would be nice if you could add a property to set the disabled background for buttons

**Comment by DevCharly** [comment]
Yes, that's missing.

Is now implemented in master branch.

**Comment by mlaggner** [comment]
Thanks!
