### ISSUE TITLE
Option for unified JComboBoxUI style

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#114]
at the moment we have different styles for editable and non editable `JComboBox` (especially the part with the arrow button):
![image](https://user-images.githubusercontent.com/1523778/84737281-e1263c00-afa7-11ea-84cd-4d597468cb9d.png)
![image](https://user-images.githubusercontent.com/1523778/84737257-cfdd2f80-afa7-11ea-83fb-cf33501999de.png)

would be nice if we get a property to force one of those styles regardless of the editable state (I'd prefer the upper style if that matters)

**Comment by DevCharly** [comment]
Good idea. Should be no problem...

**Comment by DevCharly** [comment]
Now implemented in master branch.

Use following to always use first style shown in above screenshot:
~~~java
UIManager.put( "ComboBox.buttonStyle", "button" );
~~~
or following to always use second style shown in above screenshot:
~~~java
UIManager.put( "ComboBox.buttonStyle", "none" );
~~~

"none" button style is also available for spinners:

![image](https://user-images.githubusercontent.com/5604048/85156320-31c4c000-b25a-11ea-98df-277d1980d242.png)

~~~java
UIManager.put( "Spinner.buttonStyle", "none" );
~~~

**Comment by mlaggner** [comment]
thanks, you rock :+1: 

cannot await 0.37 to be released
