### ISSUE TITLE
HTML rendering problem

### ISSUE THREAD

**Issue by lbalazscs** [JFormDesigner/FlatLaf#12]
I am using version 0.13 from Maven. The following code illustrates the problem:

```java
public class HTMLProblem {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(HTMLProblem::runOnEDT);
    }

    private static void runOnEDT() {
        try {
//            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarculaLaf");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        String msg = "<html>I like <b>bold</b>,"
                + "<br> and I like <i>italic</i>,"
                + "<br> and I like to have"
                + "<br> many lines."
                + "<br> Lots of lines.";
        JOptionPane.showMessageDialog(null, msg);
    }
}
```

Here's the result, notice how at the end HTML tags are not interpreted anymore:
![flatlaf](https://user-images.githubusercontent.com/9939454/67104669-a5906380-f1c7-11e9-9560-e86a5917d535.png)

Here's the correctly rendered result when using Nimbus:
![nimbushtml](https://user-images.githubusercontent.com/9939454/67104915-22234200-f1c8-11e9-88b8-fd57a7584236.png)

**Comment by DevCharly** [comment]
This is because FlatFaf enables JOptionPane's line wrapping (at 80 characters), which splits the HTML text into multiple JLabels. So it is actually a bug in Swing. Anyway I'll fix it in the next release.
 
You can workaround the issue by disabling line wrapping:
~~~java
UIManager.put( "OptionPane.maxCharactersPerLine", 0 );
~~~
