### ISSUE TITLE
Cursor doesn't change state if custom window decorations are enabled

### ISSUE THREAD

**Issue by schliepRon** [JFormDesigner/FlatLaf#125]
I was testing the new embedded MenuBar feature with the swing framework in my company and realized that the cursor doesn't switch if it should. 

Then I tried it with a default JTable (resizing) and it was the same.

I tried it with the swing windows LAF and there the cursor changes states. So it seems to be a FlatLaf issue.

**Comment by DevCharly** [comment]
Many thanks for reporting.
This issue is now fixed in master branch.
