### ISSUE TITLE
Checkbox and Radio button colors broken

### ISSUE THREAD

**Issue by AndyAtTV** [JFormDesigner/FlatLaf#126]
Just been testing 0,37 and noticed that "Selected" Checkbox and Radio buttons no longer pick up the color from the theme. They are always the default "Flat IntelliJ" color. Went back to 0,36 and it works fine.

Run the demo and try "Arc - Orange" on 0.36 and 0.37 to see the difference. It appears that "Checkbox.Background.Selected" from the json file, and probably others are being ignored.

**Comment by DevCharly** [comment]
Thx, fixed in 0.38
