### ISSUE TITLE
Is there a way to change titled Border color on panel using directly l&f tools?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#127]
Hello @JFormDesigner,

When I set a color through, `UIManager.put( "Panel.background", new Color(199,209,210) );`, the whole panel is overwhelmed with current color and even the titled borders aren't visible any more.  And... I kinda have many titled borders on my panel... I use this code to each of 'em: `Panel1.setBorder(BorderFactory.createTitledBorder(a[4]));`... It's very tiresome to assign a return value to each variable and change color individually.

Is there any general solution like `UIManager.put("TitledBordedFactory.backgroundColor", new Color(xxx,xxx,xxx))`?

**Comment by DevCharly** [comment]
To change line color use:
~~~java
UIManager.put( "TitledBorder.border", new FlatLineBorder( new Insets(1,1,1,1), Color.blue ) );
~~~
or
~~~java
UIManager.put( "TitledBorder.border", new LineBorder( Color.blue, 1 ) );
~~~

To also change the title text color use:
~~~java
UIManager.put( "TitledBorder.titleColor", Color.red );
~~~

**Comment by UltimateYZ** [comment]
Thanks for the help.

**Comment by UltimateYZ** [comment]
Sorry... But the font mechanism is the same right? `UIManager.put( "TitledBorder.font", new Font(Liberation Sans));`?

**Comment by DevCharly** [comment]
Yes, see:

https://github.com/openjdk/jdk/blob/be2e015fd3c033a2f02dc93e39264b20ce51b4b5/src/java.desktop/share/classes/javax/swing/border/TitledBorder.java#L473

**Comment by UltimateYZ** [comment]
Thanks.
