### ISSUE TITLE
How can I Change Selected dot color on Flat Radio Button?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#128]
Hello @JFormDesigner,

I'm facing some troubles trying to change the focus color and some others stuffs on Radio button using the class, UIManager(). I tried this: `UIManager.put( "RadioButton.focus", new ColorUIResource(33,176,228) );`. And... It doesn't work...

>` hoverTrackColor = UIManager.getColor( "ScrollBar.hoverTrackColor" );`

Even that doesn't seems to work... I don't know why... I tried this: `UIManager.put("ScrollBar.hoverTrackColor", new Color(12,200,220));`

This too:

> `pressedTrackColor = UIManager.getColor( "ScrollBar.pressedTrackColor" );`

I want to change the radio button selection/checked color for a music player I'm developing...

**Comment by schliepRon** [comment]
Hey @UltimateYZ 
the FlatRadioButtonIcon inherits from the FlatCheckBoxIcon. 
The UIManagerkeys you are looking for are something like CheckBox.icon.selectedBorderColor 

You can lookup the needed keys in the code here:

https://github.com/JFormDesigner/FlatLaf/blob/8603ca827efa40014b8d66cd5d6cb1c51b58fe35/flatlaf-core/src/main/java/com/formdev/flatlaf/icons/FlatCheckBoxIcon.java#L39

**Comment by UltimateYZ** [comment]
Okay... I'm kinda new to these stuffs. How can I override it?

**Comment by UltimateYZ** [comment]
Hmm... Then If change the default color for the CheckBox JComponent, radio Button is changed too?

**Comment by schliepRon** [comment]
Yes,
but you can do this:

UIManager.put("RadioButton.icon.borderColor", Color.RED);
myRadioButton.setIcon(new FlatRadioButtonIcon(){
@Override
	protected void paintBorder( Graphics2D g2 ) {
                g2.setColor(UIManager.getColor("RadioButton.icon.borderColor"));
		g2.fillOval( 0, 0, 15, 15 );
	}
});

**Comment by UltimateYZ** [comment]
What is **`myRadioButton`**?

**Comment by schliepRon** [comment]
The JRadioButton Component

**Comment by UltimateYZ** [comment]
![Screenshot from 2020-07-14 18-28-08](https://user-images.githubusercontent.com/55871338/87451214-db9c3000-c5ff-11ea-9dce-4cedb99d702b.png)

I received that...

**Comment by UltimateYZ** [comment]
Okay... sorry about the deleted comment... I didn't pay attention.... But the scrollbar hover track color problem still persists... I could override it in my method, but later it brings some undesired problems...

**Comment by UltimateYZ** [comment]
Hum... It looks like the key I was looking for was check mark color. Thanks for the help by the way... I will create a new issue for hover track color later.
