### ISSUE TITLE
Problems with key "ScrollBar.pressedTrackColor" and "ScrollBar.hoverTrackColor", Linux (Ubuntu 20.04)

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#130]
Hello @JFormDesigner devs,
I'm facing some problems with the keys mentioned above, aren't working... 

~~~java
UIManager.put("ScrollBar.pressedTrackColor",new ColorUIResource(12,200,220));
UIManager.put("ScrollBar.hoverTrackColor",  new ColorUIResource(12,200,220));
~~~

**Comment by DevCharly** [comment]
Hmm, works fine for me:

![image](https://user-images.githubusercontent.com/5604048/87665557-651a4200-c767-11ea-9f59-fc35ec156ef8.png)

There is no "pressed" feedback because the hover and pressed colors are equal.

**Comment by UltimateYZ** [comment]
No... I meant the track, not the thumb of scrollbar...
**`UIManager.put( "ScrollBar.pressedTrackColor",new ColorUIResource(12,200,220).darker());
    UIManager.put("ScrollBar.hoverTrackColor", new ColorUIResource(12,200,220));`**

**Comment by DevCharly** [comment]
Yes, the cyan part in above screenshot is the track. Here is a video:

![track](https://user-images.githubusercontent.com/5604048/87678090-d1eb0780-c77a-11ea-9046-34d44a521f9e.gif)

**Comment by UltimateYZ** [comment]
Hum... It looks like this code was messing up with me... Okay, try it again with this code:
**`UIManager.put( "ScrollBar.trackInsets", new Insets( 2, 4, 2, 4 ) );`**
