### ISSUE TITLE
JInternalFrame title panel shrinks when the control icons are removed

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#132]
The title panel of a JInternalFrame usually has constant a constant height, but with FlatLaf 0.38 the title panel shrinks if the frame is built without the maximize/iconify/close buttons:

![image](https://user-images.githubusercontent.com/54304/87947884-45a35200-caa4-11ea-888f-c9af01ac8344.png)

**Comment by DevCharly** [comment]
Thx, didn't notice this until now...

**Comment by DevCharly** [comment]
now fixed in master branch
