### ISSUE TITLE
JComboBox Dropdown List Scrollbar Covers Content

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#137]
If a dropdown item has very long text, the scrollbar on the dropdown partially covers the text at the end. 

![Screen Shot 2020-07-30 at 2 40 47 PM](https://user-images.githubusercontent.com/1026658/88874224-a97f0500-d272-11ea-89a6-4f9857cd9ca9.png)

**Comment by DevCharly** [comment]
Thx, good catch 👍 

Fixed in master branch.
