### ISSUE TITLE
Parts of the painted String on a JProgressBar is not visible for some Themes

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#138]
For some of the Flat themes, parts of the painted String are not visible in the areas where the progress bar doesn't paint the value. 

See this example, where the progress bar value is set at 70, with a maximum of 100. The painted String is "Testing JProgressBar"

Using `FlatMonokaiProContrastIJTheme` produces missing parts of the  String

![](https://i.imgur.com/uNiM96i.png)

Using `FlatDarculaLaf` produces correct result

![](https://i.imgur.com/gLyf0rE.png)

I have gone through all the available themes and I noticed the themes that are not rendering properly are all from the `materialthemeuilite` package.

The painted String is visible for these themes, but it is hard to read due to clash of similar colours
- FlatGradiantoDarkFuchsiaIJTheme
- FlatGruvboxDarkHardIJTheme, FlatGruvboxDarkMediumIJTheme, FlatGruvboxDarkSoftIJTheme
- FlatHiberbeeDarkIJTheme
- FlatHighContrastIJTheme

**Comment by DevCharly** [comment]
The reason for the wrong text colors in progress bars is that they are not used in IntelliJ and the authors of IntelliJ themes do not specify them.

Fixed in master branch.

Please let me know if there is still something wrong....

**Comment by grimlock81** [comment]
Thanks for the quick fix @DevCharly looks good.
![](https://i.imgur.com/SU002bX.png)
