### ISSUE TITLE
Will on near future FlatLaf provide any support for decorated windows title bar?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#139]
Hi @JFormDesigner,
Will by any chance the l&f provide support for a decorated windows title bar like this:
![image](https://user-images.githubusercontent.com/55871338/88960794-56be4100-d2a4-11ea-92f3-9a2003e7d21f.png)

The frame components are very well sophisticated with the addition of the lnf, the programs are portable and all (They provide a modern vibe to deprecated Swing widget toolkit)... That is good! But at some cases the top level JFrame title bar provided by underlying OS are ugly or not suitable for some types of software...

**Comment by DevCharly** [comment]
This is already implemented, but only for Windows 10. Try the latest FlatLaf Demo on Windows 10 😉 

![image](https://user-images.githubusercontent.com/5604048/86024426-44df4900-ba2d-11ea-8a0e-292dfa210dcd.png)

Not yet decided whether support other platforms too.
But the code is there. Maybe works too on macOS/Linux, but the look does not match the OS look...
