### ISSUE TITLE
Controlling focus border width per component

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#140]
I know about the following properties of setting the focus border width

```
UIManager.put( "Component.focusWidth", 1 );
UIManager.put( "Component.innerFocusWidth", 1 );
```

but they affect all components. Is there a way to control it per component? 

I have an issue when using a JTextField as a table cell editor via `javax.swing.DefaultCellEditor` the focus borders make the text obscured. See:

![](https://i.imgur.com/T3F0BC9.png)

I'd like to reduce the border width for JTextField used in a DefaultCellEditor when but keep the focus borders for the other components

**Comment by DevCharly** [comment]
Try setting client property `JComboBox.isTableCellEditor` on editor text field to `true`.

~~~java
textField.putClientProperty( "JComboBox.isTableCellEditor", true );
~~~

This is used for combo box table cell editors, but should work for text fields too:

![image](https://user-images.githubusercontent.com/5604048/88982251-12449c80-d2c8-11ea-841d-6dc2f64d366f.png)


Another way would be to create a sublcass of `com.formdev.flatlaf.ui.FlatTextBorder`, override `getFocusWidth()` to return `1` and use this border for the table cell editor text field.

https://github.com/JFormDesigner/FlatLaf/blob/7057e3c6ad123de451f6d2e73eea7c84956d1a1f/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatBorder.java#L222-L224

**Comment by grimlock81** [comment]
Great, the first fix does what I need.

**Comment by DevCharly** [comment]
@grimlock81 made some changes to border in commit f29d3d84d404fd07aec15cc54ed416f0fcce0c4e. Top and bottom insets are now removed, which gives the text field more root to paint its selection.
