### ISSUE TITLE
JFileChooser: rename file text field is too small to fit content 

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#143]
When renaming a file within JFileChooser, the insets cover the text content, making it difficult to read.

<img width="185" alt="Screen Shot 2020-07-31 at 1 54 13 PM" src="https://user-images.githubusercontent.com/1026658/88991641-51f59d80-d335-11ea-8ed5-64ef0d6fad9e.png">

**Comment by DevCharly** [comment]
Many thx. Fixed in master branch.
