### ISSUE TITLE
Does FlatLaf support customization through xml file?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#145]
Hello @JFormDesigner,
I wondering if the l&f support some modifications and configurations through a XML file, if that is the case what are the components which can be modified? And... How can I modify 'em?

**Comment by stanio** [comment]
Not through XML file but using Properties or JSON.  Have you looked at the [_IntelliJ Platform Themes_](https://www.formdev.com/flatlaf/themes/#intellij_platform_themes) (`.theme.json`)?  Make sure you give the very nice [FlatLaf Demo](https://www.formdev.com/flatlaf/#demo) a try.

For the `.properties` approach see #119:

> To use a properties file in the own application either use class [FlatPropertiesLaf](/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatPropertiesLaf.java) or create a subclass of [FlatLightLaf](/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLightLaf.java) with the same base name as the properties file and in the same package as the properties file. See [FlatIntelliJLaf](/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatIntelliJLaf.java).

Check out the [_Customizing_](https://www.formdev.com/flatlaf/customizing/) page as well.

**Comment by UltimateYZ** [comment]
Thanks for the help.

**Comment by DevCharly** [comment]
Here is a short description how to use own properties files to make modifications to themes:
https://github.com/JFormDesigner/FlatLaf/issues/159#issuecomment-671957742
