### ISSUE TITLE
How to add svg icons

### ISSUE THREAD

**Issue by iamabs2001** [JFormDesigner/FlatLaf#146]
i want to add svg icons from flatlaf extras.

to JMenu

**Comment by DevCharly** [comment]
Use something like:
~~~java
myMenuItem.setIcon( new FlatSVGIcon( "com/myapp/icons/myIcon.svg" ) );
~~~

Here is the code used in the FlatLaf demo:

https://github.com/JFormDesigner/FlatLaf/blob/b1d24680b210b23627127e26c3edd2a518952e5b/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java#L607-L612

If you're looking for icons, search
https://jetbrains.github.io/ui/resources/icons_list/

**Comment by DevCharly** [comment]
BTW @iamabs2001 you have a very cool GitHub [contribution graph](https://github.com/iamabs2001?tab=overview&from=2019-12-01&to=2019-12-31) 💯 🥇 


![image](https://user-images.githubusercontent.com/5604048/89120398-56958f80-d4b6-11ea-85f6-51d4632fff57.png)

**Comment by iamabs2001** [comment]
> BTW @iamabs2001 you have a very cool GitHub [contribution graph](https://github.com/iamabs2001?tab=overview&from=2019-12-01&to=2019-12-31) 💯 🥇 
> 
> 
> ![image](https://user-images.githubusercontent.com/5604048/89120398-56958f80-d4b6-11ea-85f6-51d4632fff57.png)
> 

Haha hello! 😁

**Comment by iamabs2001** [comment]
is Salamander Dependency Required ?

**Comment by iamabs2001** [comment]
I'm still getting NullPointerException(yes i'm poor java 8 user)

**Code** : MyRunMenu.setIcon(new FlatSVGIcon("com/sigma/sigmastudio/icons/run.svg"));

_whats wrong here ?_

**Comment by DevCharly** [comment]
> is Salamander Dependency Required ?

Yes, svgSalamander parses and renders SVG.

> I'm still getting NullPointerException...

Probably your IDE did not yet copy the .svg files from source folder to bin/classes/output folder...

**Comment by iamabs2001** [comment]
Very poor documentations 😔
