### ISSUE TITLE
Dialogs get wrong size (custom decorations, JetBrains Runtime 11, HiDPI)

### ISSUE THREAD

**Issue by remcopoelstra** [JFormDesigner/FlatLaf#149]
I am trying to use the FlatDarculaLaf with custom (native) decorations on Dialogs, when running on JetBrains Runtime 11 my Dialogs are too small on HiDPI displays (tested on 125% and 200%).

I have tried releases 0.38 and 0.39 and jbr-11_0_4 and jbr_11_0_7, below is a small class demonstrating the problem:

```
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.formdev.flatlaf.FlatDarculaLaf;

public class DialogTest {


	public DialogTest() {

		try {
			UIManager.setLookAndFeel(new FlatDarculaLaf());
			JFrame.setDefaultLookAndFeelDecorated(true);
			JDialog.setDefaultLookAndFeelDecorated(true);
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}

		JFrame frame = new JFrame("JFrame");
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(850, 650);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		System.out.println("frame.getSize() = " + frame.getSize());
		//Prints frame.getSize() = java.awt.Dimension[width=850,height=650]

		Timer timer = new Timer(1000, new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {

				JDialog dialog = new JDialog(frame);
				dialog.setTitle("JDialog");
				dialog.setSize(new Dimension(800, 600));
				dialog.setLocationRelativeTo(frame);
				dialog.setVisible(true);
				System.out.println("dialog.getSize() = " + dialog.getSize());
				//Prints dialog.getSize() = java.awt.Dimension[width=400,height=300]

			}
		});
		timer.setRepeats(false);
		timer.start();

	}

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				new DialogTest();
			}
		});
	}

}
```

**Comment by DevCharly** [comment]
Yes, that's strange. On my machine, at 150%, the dialog also is not centered to the frame.

I'm trying to figure out what causes the problem...

Following workaround works for me:
~~~java
//dialog.setSize(new Dimension(800, 600));
dialog.setPreferredSize( new Dimension(800, 600) );
dialog.pack();
~~~

**Comment by DevCharly** [comment]
The dialog bounds are somewhere scaled within native method `sun.awt.windows.WFramePeer.createAwtFrame(WComponentPeer parent)` ([source](https://github.com/JetBrains/JetBrainsRuntime/blob/f517bb3380784ca1ebfd26a1735068d1dbe08c1e/src/java.desktop/windows/native/libawt/windows/awt_Frame.cpp#L2063-L2073)), which is invoked from within `dialog.setVisible(true);`. 

This happens only if JetBrains custom window decorations are enabled.

It is also strange that `frame.setVisible(true)` also invokes `WFramePeer.createAwtFrame`, but does not scale bounds...

**Comment by DevCharly** [comment]
BTW another workaround is:
~~~java
dialog.pack();
dialog.setSize(new Dimension(800, 600));
~~~

This works because `pack()` invokes `WFramePeer.createAwtFrame()` (within `addNotify()`) and then `setSize()` overwrites the bounds.

**Comment by remcopoelstra** [comment]
Thanks for the workarounds! I think using `setPreferredSize()` and `pack()` is probably a better way to display dialogs so I updated my code using this suggestion. The wrong size/location when using `setSize()` looks like a bug in the JetBrains Runtime.

Thanks!
