### ISSUE TITLE
Is FlatLaf offering any apart Layout Manager?

### ISSUE THREAD

**Issue by UltimateYZ** [JFormDesigner/FlatLaf#155]
Hi @JFormDesigner devs,
I'm wondering if the l&f offers some cool Layout Managers, other than these Oracle offers and says: **"are flexible"**. I'm not big fan of using GUI builder (that is for lazy guys or ol'mans), in past I used to work with absolute layout to avoid some undesirable constraints with layout manager but... Now I need to work with layout managers for better scalability and component management.

**Comment by DevCharly** [comment]
No, FlatLaf does not provide any general use layout managers.

Use MigLayout (https://github.com/mikaelgrev/miglayout), which is easy to use, flexible and powerful.

Check out the [Quick Start Guide](http://www.miglayout.com/mavensite/docs/QuickStart.pdf), the [Cheat Sheet](http://www.migcalendar.com/miglayout/mavensite/docs/cheatsheet.pdf) and the [White Paper](https://www.formdev.com/jformdesigner/doc/layouts/miglayout-whitepaper/).

Use either version 5.2 from maven central:
https://repo1.maven.org/maven2/com/miglayout/miglayout-swing/

or 5.3-SNAPSHOT from Sonatype repo:
https://oss.sonatype.org/content/repositories/snapshots/com/miglayout/miglayout-swing/

in which case you need to add the Sonatype repo to your build. E.g.
https://github.com/JFormDesigner/FlatLaf/blob/8bcf9dbcaf84e9b63267fea5b99c02ffcf74f8ca/flatlaf-testing/build.gradle.kts#L21-L26

https://github.com/JFormDesigner/FlatLaf/blob/8bcf9dbcaf84e9b63267fea5b99c02ffcf74f8ca/flatlaf-testing/build.gradle.kts#L36

5.3-SNAPSHOT has the advantage that it uses the user scaling factor from FlatLaf.

**Comment by UltimateYZ** [comment]
Oh! Thanks, I guess.
