### ISSUE TITLE
JFrame loses focus at startup (Custom Window Decorations, JetBrains Runtime 11)

### ISSUE THREAD

**Issue by remcopoelstra** [JFormDesigner/FlatLaf#157]
I store the size and extended-state of my application in the preferences and reload them at startup, I noticed if the extended-state is set to `MAXIMIZED_BOTH` before `setVisible(true)` is called the JFrame will lose it's focus, the `WindowListener` I added to the frame also doesn't fire it's `windowActivated()` method.

This only seems to happen when using custom (native) window decorations on JetBrains Runtime 11.

For now I solved this by calling `frame.setExtendedState(JFrame.MAXIMIZED_BOTH)` after the frame is shown (in the `windowActivated()` method), but I think it looks better if the frame goes to the extended state immediately.

I can provide code which demonstrates the issue if needed.

**Comment by DevCharly** [comment]
I can reproduce it.

The frame does not get focus and is not activated. In my case the IDE is still active and focused.
If I click at the frame, it gets focus and fires `windowActivated` event.

It works fine with JetBrains Runtime if custom window decorations are disabled.
It also works fine with OpenJDK and custom window decorations enabled or disabled.

I'm trying to figure out what causes the problem...

BTW another workaround is to invoke `frame.toFront()` after `frame.setVisible(true)`

**Comment by remcopoelstra** [comment]
Yes, I also noticed it only happens with the combination of JBR + custom window decorations enabled. Using `frame.toFront()` is indeed a better workaround, I implemented it and this looks much better, thanks!

**Comment by DevCharly** [comment]
FlatLaf 2 now uses own window decorations (see #454) by default, which does not have this issue.
(system property `flatlaf.useJetBrainsCustomDecorations` is now `false` by default)
