### ISSUE TITLE
Solarized Themes NullPointer

### ISSUE THREAD

**Issue by MioBlanco** [JFormDesigner/FlatLaf#159]
Since the solarized themes were updated, they no longer work properly. Everytime I start an app with the solarized themes I constantly get the NullPointerException below. I tested most of the other themes, but they all work fine.
If you want to reproduce it, you can use the FlatLaf-Demo (just select a solarized theme, click around and wait a bit).
The issue #158 found the same exception.

**_offtopic question_**
Is there any easy way to use the default FlatDarkLaf with a white Foreground/Font, because overriding values in the UIManager seems the cause some problems with my code and changing the FlatDarkLaf.properties isn't really possible, since I want to use the jar.

Message:
    java.lang.NullPointerException
Level:
    WARNING
Stack Trace:
null
    com.formdev.flatlaf.util.HSLColor.fromRGB(HSLColor.java:264)
    com.formdev.flatlaf.util.ColorFunctions.applyFunctions(ColorFunctions.java:29)
    com.formdev.flatlaf.util.DerivedColor.derive(DerivedColor.java:47)
    com.formdev.flatlaf.ui.FlatUIUtils.deriveColor(FlatUIUtils.java:214)
    com.formdev.flatlaf.ui.FlatScrollBarUI.getTrackColor(FlatScrollBarUI.java:271)
    com.formdev.flatlaf.ui.FlatScrollBarUI.paintTrack(FlatScrollBarUI.java:224)
    javax.swing.plaf.basic.BasicScrollBarUI.paint(BasicScrollBarUI.java:430)
    com.formdev.flatlaf.ui.FlatScrollBarUI.paint(FlatScrollBarUI.java:219)
    javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    javax.swing.JComponent.paintComponent(JComponent.java:780)
    javax.swing.JComponent.paint(JComponent.java:1056)
    javax.swing.JComponent.paintChildren(JComponent.java:889)
    javax.swing.JComponent.paint(JComponent.java:1065)
    javax.swing.JComponent.paintChildren(JComponent.java:889)
    javax.swing.JComponent.paint(JComponent.java:1065)
    org.jdesktop.jxlayer.JXLayer.paint(Unknown Source)
    org.jdesktop.jxlayer.plaf.AbstractLayerUI.paintLayer(Unknown Source)
    com.isp.lea.desktop.components.InfoLayerUI.paintLayer(InfoLayerUI.java:86)
    org.jdesktop.jxlayer.plaf.AbstractLayerUI.paint(Unknown Source)
    javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    javax.swing.JComponent.paintComponent(JComponent.java:780)
    org.jdesktop.jxlayer.JXLayer.paint(Unknown Source)
    javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
    javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
    javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
    javax.swing.RepaintManager.paint(RepaintManager.java:1272)
    javax.swing.JComponent._paintImmediately(JComponent.java:5158)
    javax.swing.JComponent.paintImmediately(JComponent.java:4969)
    javax.swing.RepaintManager$4.run(RepaintManager.java:831)
    javax.swing.RepaintManager$4.run(RepaintManager.java:814)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
    javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
    javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
    javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
    javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
    java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:709)
    java.awt.EventQueue$3.run(EventQueue.java:703)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by DevCharly** [comment]
Thx, fixed in commit 5a27d03faa25413b4078c87764fe1126a88dac52 and released in FlatLaf 0.40

**Comment by DevCharly** [comment]
Regarding your offtopic question: Yes this is possible but currently requires adding a service to your application.

Here are the steps:

A) Create a properties file `src/main/resources/myapp/FlatDarkLaf.properties` (change package `myapp` to whatever you want) and add the white foreground color:
~~~
@foreground=#fff
~~~

Check core [FlatDarkLaf.properties](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties) and [FlatLaf.properties](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties) for possible keys and values.

B) Create a (empty) service class in the **same package** as the properties file. E.g. `src/main/java/myapp/MyAppFlatLafAddon.java`:
~~~java
package myapp;

import com.formdev.flatlaf.FlatDefaultsAddon;

public class MyAppFlatLafAddon
	extends FlatDefaultsAddon
{
}
~~~

C) Create a services file `src/main/resources/META-INF/services/com.formdev.flatlaf.FlatDefaultsAddon` (do not change file name) that contains the class name of your service implementation:
~~~
myapp.MyAppFlatLafAddon
~~~

And here is a little program for testing `src/main/java/myapp/MyApp.java`:
~~~
package myapp;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatDarkLaf;

public class MyApp
{
	public static void main( String[] args ) {
		SwingUtilities.invokeLater( () -> {
			FlatDarkLaf.install();
			JOptionPane.showMessageDialog( null, "hello" );
		} );
	}
}
~~~

Maybe I should add some API to FlatLaf to register a package that may contain properties files. 
Then steps B) and C) would be obsolete...

**Comment by MioBlanco** [comment]
Works perfectly, thanks a lot for the explanation 👍 

An API could be benefitial, since the FlatDarkLaf looks way better than all the other IntelliJ-Themes in my opinion, but changing the theme is a bit more difficult. 
You could also add the explanation for changing FlatLaf-Themes on your website in case someone else is wondering how to do it.
Are you planing on integrading the FlatLaf-Themes in the themeeditor or only IntelliJ-Themes ?, because this would probably make the API obsolete.

**Comment by DevCharly** [comment]
@MioBlanco since commit b208017117503e25a9ea8a13a7e1b7e475828667 (in master branch) there is a new API available that makes it easier to use own properties files to customize FlatLaf in applications.

Instead of using steps B) and C) from above, simply invoke `FlatLaf.registerCustomDefaultsSource("some.package")` before setting any look and feel. E.g.

https://github.com/JFormDesigner/FlatLaf/blob/b208017117503e25a9ea8a13a7e1b7e475828667/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatTestFrame.java#L81

Here are the properties files used in the test programs:
https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-testing/src/main/resources/com/formdev/flatlaf/testing/customdefaults
