### ISSUE TITLE
No effect after setting JButton.setSelected(true) in JTooBar

### ISSUE THREAD

**Issue by Yaqiang** [JFormDesigner/FlatLaf#161]
In my program I need to know which button was clicked by setting selected attribute of the button in the toobar. It is normal in Windows LAF with shadow background color:
![laf_windows](https://user-images.githubusercontent.com/4408029/90719326-a9f54380-e2e6-11ea-81af-af7894c498a6.PNG)

But there is no shadow background color of the button in Flat... LAF:
![laf_FlatLight](https://user-images.githubusercontent.com/4408029/90719350-b6799c00-e2e6-11ea-9a3d-33292de9ea7a.PNG)

**Comment by DevCharly** [comment]
@Yaqiang although you've already solved it in your program, I've implemented "selected" state for `JButton` in master branch for improved compatibility with Windows LaF.

**Comment by Yaqiang** [comment]
Good news!
