### ISSUE TITLE
JTree paint ghosting

### ISSUE THREAD

**Issue by alemberg2020** [JFormDesigner/FlatLaf#162]
Description
---
I have an application which shows a JTree. After the window appears, everything is fine. But if I maximize the window, then the tree component paints ghosting (see screenshots). If I revert the maximization, everything is fine. If I manually resize the window, everything is fine. 

Steps
---
Unfortunately, I have no reproduction steps. I can't reproduce this behavior with the demo application.

Screenshots
---
_With ghosting_:

![grafik](https://user-images.githubusercontent.com/70012846/90876293-b2ab4f80-e3a2-11ea-8ea8-4f5eba77747d.png)

_Without ghosting_:
![grafik](https://user-images.githubusercontent.com/70012846/90876123-6e1fb400-e3a2-11ea-9cc5-c313ad7b6acb.png)

I tested this behavior with the following FlatLaf version:
---
- 0.35 --> Ghosting appears immediately
- 0.38 --> Ghosting appears after window is maximized
- 0.40 --> Ghosting appears after window is maximized

My environment:
---
- openjdk1.8.0_191_x64
- Eclipse 2019-09 R

**Comment by alemberg2020** [comment]
### To your questions:
1. I did'n't changed any opaque
2. I haven't any custom renderer

### --> But ...
After hours of research, I found the reason. The cause is the tree background color. With the change from Tiny to FlatLaf, I changed also the tree background color from white to a color with transparency. And this is it. 
For some reason, painting with transparency doesn't work properly within trees.

### Example
To reproduce this behavior, simply changed the tree background color to any color with alpha:

> UIManager.put("Tree.background", new ColorUIResource(new Color(0, 255, 0, 100)));

![grafik](https://user-images.githubusercontent.com/70012846/91023036-4c1e6f80-e5f6-11ea-8127-2c207ce21a35.png)

Here a little test program, which containts two ui initializer methods. To show the error, use "initializeLookAndFeelDoesntWork" and use "initializeLookAndFeelWorksFine" to show a tree without the error:
[TestTree.java.txt](https://github.com/JFormDesigner/FlatLaf/files/5116720/TestTree.java.txt)

**Comment by DevCharly** [comment]
@alemberg2020 using background color with transparency for a component could work only if the component is not opaque (`comp.setOpaque(false)`). But `JTree` is opaque. So if Swing paints (parts of) the tree it does not paint trees parent before, which would fill the background. On the other hand, if the tree is not opaque, it does not paint its background (see `ComponentUI.update()`). So this does not work. I would avoid using transparent colors for background of components 😉 

Anyway, the problem shown in your second comment looks different to me than the problem in your initial post 😕

**Comment by alemberg2020** [comment]
@DevCharly your comment makes sense
