### ISSUE TITLE
Add custom Classloader in FlatSVGIcon class

### ISSUE THREAD

**Issue by Yaqiang** [JFormDesigner/FlatLaf#163]
The getting icon URL method in FlatSVGIcon class use a certain ClassLoader of FlatSVGIcon class.

```
	private URL getIconURL( String name, boolean dark ) {
		if( dark ) {
			int dotIndex = name.lastIndexOf( '.' );
			name = name.substring( 0, dotIndex ) + "_dark" + name.substring( dotIndex );
		}
		return FlatSVGIcon.class.getClassLoader().getResource( name );
	}
```

In my program of MeteoInfo, some plugin jar files need to be loaded on the fly with a new URLClassLoader (loadPlugins method in FrmMain.java: https://github.com/meteoinfo/MeteoInfo/blob/d33344093c3c39b8820979ec2960620afcd30b3f/MeteoInfoMap/src/main/java/org/meteoinfo/desktop/forms/FrmMain.java#L2327). The SVG icons in plugin jar can not be loaded using the ClassLoader of FlatSVGIcon class. So I have to write a new FlatSVGIcon class which includes a new ``classLoader`` variable and a new constructor function to set it (https://github.com/meteoinfo/MeteoInfo/blob/master/MeteoInfoLib/src/main/java/org/meteoinfo/image/svg/FlatSVGIcon.java). Then the svg icons in the plugin jar can be loaded by the URLClassLoader of the jar. 

The example code for setting SVG icon in the plugin jar file:
```
        ClassLoader classLoader = FrmPlugin.class.getClassLoader();
        jButton_NewVerifyCase.setIcon(new FlatSVGIcon("org/meteothink/imep/icons/file-new.svg", classLoader));
```

The above solution is ok for my MeteoInfo software with plugin svg icons loading. So I am thinking this modification of FlatSVGIcon maybe accepted by FlatLaf. Or I am also looking forward to a better solution on it.

**Comment by DevCharly** [comment]
Thx @Yaqiang

I've added a new constructor to `FlatSVGIcon` (in master branch) that accepts an `ClassLoader`.
There is also a new method `boolean hasFound()` that can be used to check whether the SVG file was found.

**Comment by Yaqiang** [comment]
Glad to see such an improvement and thanks for your and JFormDesigner's effet on this excellent look & feel!
