### ISSUE TITLE
Font size conversion issue using Style in JTextPane with HTML

### ISSUE THREAD

**Issue by samuelhallstrom** [JFormDesigner/FlatLaf#165]
Hi,

I have found an issue related to font sizes when I use Styles within HTML documents. Below you find a small program that reproduces this. Basically, what happens is that if I set the font size for a Style, and then retrieve it, I do not always get the same value back, and this can cause very tiny fonts in the text pane, given a font size. The main reason is probably a bug in OpenJDK that I link to below (in short, different conversion tables are used to convert to and from points to CSS size in the StyleSheet class), but perhaps something can be done in Flatlaf.

A side note: Even if I use really ugly hacks to use the same conversion tables, a given font size seems smaller in the text pane than the rest of the application.

Link to bug: https://bugs.openjdk.java.net/browse/JDK-7022164?focusedCommentId=12231004&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

Small program that reproduces the issue below (couldn't get the code formatting good, sorry). The font size 12 is set on a Style, but when retrieving it, it is 10. The same font size is set on the text pane in another panel and that shows how size 12 should look I think. Comment out the setLookAndFeel call and this problem disappears (on my Win 10 at leats).

Cheers,

Sam

Oh by the way, I really, really like this LAF. Good job!

~~~java
public class FlatLafTest {

   public static void main(String[] args) throws ClassNotFoundException, UnsupportedLookAndFeelException, InstantiationException, IllegalAccessException, BadLocationException, NoSuchFieldException {
      UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
      int fontSize = 12;

      JTextPane textPane = new JTextPane();
      textPane.setContentType("text/html");
      Style basicStyle = textPane.addStyle("basic", null);
      
      // Set font size 12
      StyleConstants.setFontSize(basicStyle, fontSize);
      
      // Immediately retrieve it. It is 10 with Flatlaf
      final int retrievedFontSize = StyleConstants.getFontSize(basicStyle);

      JFrame frame = new JFrame("Style bug");
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      frame.setVisible(true);
      JPanel panel = new JPanel();
      frame.add(panel);

      textPane.getDocument().insertString(0, "Font size " + fontSize + " set but retrieved: " + retrievedFontSize, basicStyle);
      panel.add(textPane);

      JTextPane textPane2 = new JTextPane();
      textPane2.setContentType("text/html");
      HTMLDocument doc2 = new HTMLDocument();
      textPane2.setDocument(doc2);
      final Font font = textPane2.getFont();
      final Font font1 = new Font("Monospace", Font.PLAIN, fontSize);
      textPane2.setFont(font1);
      doc2.insertString(0, "Font size for text added without styles, using textPane.setFont(font): " + font1.getSize(), null);
      panel.add(textPane2);
      frame.pack();
   }

}
~~~

**Comment by stanio** [comment]
As far as I've found out it is related to [`JEditorPane.html.HONOR_DISPLAY_PROPERTIES`](https://docs.oracle.com/javase/8/docs/api/javax/swing/JEditorPane.html#HONOR_DISPLAY_PROPERTIES):

> Key for a client property used to indicate whether the default font and foreground color from the component are used if a font or foreground color is not specified in the styled text.
>
> The default varies based on the look and feel; to enable it set the client [property](https://docs.oracle.com/javase/8/docs/api/javax/swing/JComponent.html#putClientProperty-java.lang.Object-java.lang.Object-) with this name to `Boolean.TRUE`.

If I add to your example:

```java
        textPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.FALSE);
```

I get _"Font size 12 set but retrieved: 12"_ using both of Metal and FlatLaf.  So it appears Metal and FlatLaf use different defaults for that property, but I'm still not sure why:

```java
        textPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
```

would affect:

```java
        // Set font size 12
        StyleConstants.setFontSize(basicStyle, fontSize);

        // Immediately retrieve it. It is 10 with Flatlaf
        final int retrievedFontSize = StyleConstants.getFontSize(basicStyle);
```

given the font size is set explicitly to that style.  Happens with both Metal and FlatLaf so I suspect it's not a FlatLaf problem.

**Comment by stanio** [comment]
> I'm still not sure why:
> 
> ```java
>         textPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
> ```
> 
> would affect:
> 
> ```java
>         // Set font size 12
>         StyleConstants.setFontSize(basicStyle, fontSize);
> 
>         // Immediately retrieve it. It is 10 with Flatlaf
>         final int retrievedFontSize = StyleConstants.getFontSize(basicStyle);
> ```
> 
> given the font size is set explicitly to that style.

There's some _styleConstantsValueToCSSValue_ transformations happening in the `javax.swing.text.html.CSS` class, so:

```java
        StyleConstants.setFontSize(basicStyle, fontSize);
```

sets a size which is closest to a set of predefined sizes like `[8, 10, 12, 14, 18, 24, 36]` (matching HTML `<font size="2">`) and might not set the exact given size.  For some reason, with `HONOR_DISPLAY_PROPERTIES=true` this predefined set ends up different just for `StyleConstants.getFontSize(basicStyle)` (vs. `StyleConstants.setFontSize(...)`), f.e. `[6, 8, 10, 12, 15, 20, 30]`, hence the discrepancy observed.

You may also use:

```java
        System.out.println(((HTMLDocument) textPane.getStyledDocument()).getStyleSheet());
```

to compare the "default" styles with `HONOR_DISPLAY_PROPERTIES=true` and `HONOR_DISPLAY_PROPERTIES=false`.

**Comment by stanio** [comment]
So, the behavior appears the same as with other L&Fs when setting `HONOR_DISPLAY_PROPERTIES` explicitly, but the problem observed when `HONOR_DISPLAY_PROPERTIES=true` (which happens to be FlatLaf default) doesn't seem like a FlatLaf bug.

**Comment by samuelhallstrom** [comment]
Thanks a lot for your replies.

I think the main problem is that bug in OpenJDK that you also found now, but I guess I was hoping that there may be a way to work around this from FlatLaf.

Setting `HONOR_DISPLAY_PROPERTIES=true` seems to be what make that transformation table change (I guess by resulting in a call to `doc.getStyleSheet().addRule( "BASE_SIZE ", newBaseSize)`. Then that OpenJDK bug uses the old transformation table for one of the conversions: Look in `StyleSheets.java` , the method `Object fromStyleConstants(StyleConstants key, Object value)` directly uses `StyleSheet.sizeMapDefault` and not the getter method.

I agree with your conclusion that this is not a FlatLaf bug.

Thanks for looking at it.

**Comment by KlemenDEV** [comment]
I can notice this also happening with e.g. JLabel using HTML inside. Sometimes the size also changes randomly when the component is re-rendered

**Comment by DevCharly** [comment]
Closing because it is not a FlatLaf issue.

The behavior of `StyleConstants.setFontSize(MutableAttributeSet a, int size)`
for HTML documents (contentType is "text/html") is "surprising".
I recommend not to use this method for HTML documents.

As already noted, it always maps the given font size to one of [the 7 predefined sizes](https://github.com/openjdk/jdk/blob/8aeada105acd143b38b02123377ef86513eee266/src/java.desktop/share/classes/javax/swing/text/html/StyleSheet.java#L3486). Following code demonstrates this:

```java
import javax.swing.*;
import javax.swing.text.*;

public class StyleFontSizeTest
{
    public static void main( String[] args ) {
        JTextPane textPane = new JTextPane();
        textPane.setContentType( "text/html" );

        Style basicStyle = textPane.addStyle( "basic", null );
        for( int i = 4; i <= 40; i++ ) {
            StyleConstants.setFontSize( basicStyle, i );
            System.out.println( i + " -> " + StyleConstants.getFontSize( basicStyle ) );
        }
    }
}
```
It outputs:

```
4 -> 8
5 -> 8
6 -> 8
7 -> 8
8 -> 8
9 -> 10
10 -> 10
11 -> 12
12 -> 12
13 -> 14
14 -> 14
15 -> 18
16 -> 18
17 -> 18
18 -> 18
19 -> 24
20 -> 24
21 -> 24
22 -> 24
23 -> 24
24 -> 24
25 -> 36
26 -> 36
27 -> 36
28 -> 36
29 -> 36
30 -> 36
31 -> 36
32 -> 36
33 -> 36
34 -> 36
35 -> 36
36 -> 36
37 -> 36
38 -> 36
39 -> 36
40 -> 36
```

Java bug [JDK-7022164](https://bugs.openjdk.org/browse/JDK-7022164) totally breaks `StyleConstants.setFontSize()`.

```java
import java.awt.*;
import javax.swing.*;
import javax.swing.text.*;

public class StyleFontSizeTest2
{
    public static void main( String[] args ) {
        JTextPane textPane = new JTextPane();
        textPane.setContentType( "text/html" );

        // same as doc.getStyleSheet().addRule( "BASE_SIZE 30" );
        textPane.setFont( new Font( Font.DIALOG, Font.PLAIN, 30 ) );
        textPane.putClientProperty( JEditorPane.HONOR_DISPLAY_PROPERTIES, true );

        Style basicStyle = textPane.addStyle( "basic", null );
        for( int i = 4; i <= 40; i++ ) {
            StyleConstants.setFontSize( basicStyle, i );
            System.out.println( i + " -> " + StyleConstants.getFontSize( basicStyle ) );
        }
    }
}
```

Outputs:

```
4 -> 17
5 -> 17
6 -> 17
7 -> 17
8 -> 17
9 -> 21
10 -> 21
11 -> 25
12 -> 25
13 -> 30
14 -> 30
15 -> 38
16 -> 38
17 -> 38
18 -> 38
19 -> 51
20 -> 51
21 -> 51
22 -> 51
23 -> 51
24 -> 51
25 -> 77
26 -> 77
27 -> 77
28 -> 77
29 -> 77
30 -> 77
31 -> 77
32 -> 77
33 -> 77
34 -> 77
35 -> 77
36 -> 77
37 -> 77
38 -> 77
39 -> 77
40 -> 77
```
