### ISSUE TITLE
How can I add an online documentation (javadoc) to gradle Gluon Mobile apis based project?  Apache NetBeans 12 - Liberica JDK 14

### ISSUE THREAD

**Issue by UltraBurstXD** [JFormDesigner/FlatLaf#167]
I started working on JavaFX gluon mobile apis today, I want add javadoc, https://docs.gluonhq.com/charm/javadoc/5.0.1/, to simplify newly complex functionalities found. But it's being to difficult to me add it on `gradle.build` file... I tried:
 ~~~groovy 
apply plugin: 'idea'
idea.module.downloadJavadoc = true
~~~  
It makes things worse because the newly downloaded jfx gluon mobile dependencies aren't embedded on BellSoft Liberica environment...

Any suggestions?

**Comment by DevCharly** [comment]
This is unrelated to FlatLaf.
