### ISSUE TITLE
IntelliJ JDK8 cannot access FlatLaf classes

### ISSUE THREAD

**Issue by JeffDerk** [JFormDesigner/FlatLaf#168]
Using IntelliJ and project is compiled with JDK8.

```
error: cannot access FlatPropertiesLaf
class file for com.formdev.flatlaf.FlatPropertiesLaf not found
```
With gradle dependency as:
`implementation group: 'com.formdev', name: 'flatlaf', version: '0.40'`

**Comment by JeffDerk** [comment]
I have project A dependent on B. B has the FlatLaf dependency.
Adding the dependency to A as well seems to solve the issue.

**Comment by stanio** [comment]
If you try to access `implementation` dependency of B from project A – it won't work.  You need to declare it explicitly in A as well.  Alternatively, you may declare flatlaf as `api` dependency of B – that way A will use flatlaf classes as if they were B's.

**Comment by DevCharly** [comment]
Thx @stanio for solving the issue 👍
