### ISSUE TITLE
PasswordField inner bounds go beyond capslock icon

### ISSUE THREAD

**Issue by Blanco27** [JFormDesigner/FlatLaf#172]
![incorrect bounds](https://user-images.githubusercontent.com/56546322/92487900-28f6e100-f1ee-11ea-8f12-8c2cd906ed8e.png)

Instead the bounds should stop right before the capslock icon. As it looks really weird if it goes beyond it.
This would require dynamically changing the bounds and maybe the viewport when capslock is being toggled, as the selection could be where the capslock icon will appear.

**EDIT**:
Also, is there a way to disable the icon? Setting the UIManager key to `null` didn't appear to work.

**Comment by DevCharly** [comment]
Yes, this looks a little bit weird, but is rare IMHO. Usually password field should be wide enough to avoid vertical scrolling. And releasing Caps Lock fixes the issue 😉  

Anyway, I'll fix it when #173 is fixed.
BTW on macOS (native and Java Aqua LaF), the Caps Lock icon also hides text...

Disabling Caps Lock icon is now possible in FlatLaf 0.42 with:
~~~java
UIManager.put( "PasswordField.showCapsLock", false );
~~~

**Comment by DevCharly** [comment]
fixed in main branch

**Comment by Bios-Marcel** [comment]
Thanks :)
