### ISSUE TITLE
Add an eye to the JPasswordField in order to toggle masking character

### ISSUE THREAD

**Issue by Blanco27** [JFormDesigner/FlatLaf#173]
I assume this would be a nice addition to the GUI, as many inexperienced users would appreciate this feature. Especially people that rarely ever use a keyboard. The same problematics described in #172 should probably be taken into consideration here as well.
I assume that if this added, it should be toggleable via the UIManager and disabled by default.

Here's what it could look like (This is our messy and hacky non-look-and-feel way of doing it):

![iQXeU7HEGV](https://user-images.githubusercontent.com/56546322/92488550-ff8a8500-f1ee-11ea-9666-e9e62f8adf3d.gif)

**Comment by DevCharly** [comment]
Nice idea 👍 

I'll add this later.
But first I need to extend FlatTextFieldUI so that it is possible to add icons/components to left and right sides of text field...

**Comment by Bios-Marcel** [comment]
Hey, do you already have some kind of API in mind and is it supposed to be something internal or something external?
I am assuming internal though, as adding public API to the UI class is probably not something you desire and this doesn't sound like something that makes sense via `JComponent#putClientProperty`.

I'd like to try working on this and fix #172 as well.

**Comment by DevCharly** [comment]
finally implemented in PR #442 😄
