### ISSUE TITLE
Reconsider choice of default foreground color in the dark version of the theme

### ISSUE THREAD

**Issue by MioBlanco** [JFormDesigner/FlatLaf#174]
Currently the contrast isn't all too high. The current color is rgb(172,172,172). Intellij for example uses rgb(187,187,187). Both me and my coworkers prefer the lighter one. Same goes for the disabled color, which is rgb(119,119,119) and intellij uses rgb(128,128,128). While I know that there is a way to change the colors, it'd be cool to have a satisfying default.

**Comment by DevCharly** [comment]
I'm open to suggestions for improvements, but I can't follow your numbers regarding foregound color for **enabled** components.
Can't find rgb(172,172,172) or `#acacac` anywhere in FlatLaf.

Can you post a screenshot?

You're taking about [FlatDarkLaf](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties), right?

General foreground color in FlatLaf Dark is `#bbbbbb` or rgb(187,187,187), which is the same as in IntelliJ IDEA 2020.2:
https://github.com/JFormDesigner/FlatLaf/blob/d0079ab66bd56446495362acaee05017098b8dbb/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties#L24

General background color is `#3c3f41` in FlatLaf Dark and in IntelliJ Darcula.

Regarding **disabled** foreground (text) color, there are indeed some differences between FlatLaf and IntelliJ:
- FlatLaf uses `#777777` or rgb(119,119,119) for all disabled text.
- IntelliJ uses
  - `#777777` for buttons
  - `#808080` or rgb(128,128,128) for labels and menuitems 
  - `#999999` for checkboxes, radiobuttons, textcomponents and togglebuttons

Will try these colors in FlatLaf, which should improve the contrast of disabled components.
Will also check whether there are more differences...

**Comment by Bios-Marcel** [comment]
Hm, maybe we were mistaken. We'll get back to you on monday.

**Comment by DevCharly** [comment]
Thx.

While working on this, I found out that text in **disabled** text components does use wrong (enabled) color in dark themes...

![image](https://user-images.githubusercontent.com/5604048/93000006-a2ac0900-f525-11ea-82d4-3c5530e0fa76.png)

**Comment by Bios-Marcel** [comment]
You are right. Must've made some mistake when comparing the colors. Sorry for wasting your time and thanks for fixing the disabled colors anyways.

**Comment by DevCharly** [comment]
I've changed disabled text color to `#888` (for all components) in a8744b2, which improves readability.
