### ISSUE TITLE
Approach for finding DPI scaling factor is faulty

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#175]
While the approach sounds quite smart at first, using the font size isn't always correct.
In Windows 10, you can change the font-size separately from the scaling. So whenever the font-size is scaling, the application scales as well, even though that's not what the user wanted. And if the user activates both scaling and font scaling, everything gets scaled twice.

This for example is 225% font scaling + 225% scaling. The screen is 2560x1440 and a usually tiny dialog almost takes up the whole screen. Aren't there any System APIs we can make use of? I assume this is also a problem we just have on Java 8, I've heard that scaling is supposed to be fixed starting with Java 9. In that case, it might be acceptable I guess.

![grafik](https://user-images.githubusercontent.com/19377618/92899886-7f973180-f41f-11ea-922c-4d938fde7b60.png)

**Comment by stanio** [comment]
> This for example is 225% font scaling + 225% scaling.

What do you refer to by "font scaling" in there – is this the "Make text bigger" in the "Ease of Access display settings"?

![ease-of-access-display-settings](https://user-images.githubusercontent.com/1247730/93094915-2c391380-f6ab-11ea-9c25-0f1851504b8d.png)

If yes, why would you need such a drastic text size increase over the base screen scaling factor?  Isn't every other app (f.e. Windows Explorer) displaying similarly to what you're seeing with FlatLaf?

BTW, on Windows I think you should have adjusted the Java 8 executable:

![javaw-dpi-scaling-override](https://user-images.githubusercontent.com/1247730/93097019-b97d6780-f6ad-11ea-9888-19131797c78c.png)

?

**Comment by Bios-Marcel** [comment]
I am not saying that this is a likely scenario. Especially not with such high numbers. I was just wondering whether there is a surefire way.

Will changing the windows setting for java always a base fontsize instead?

**Comment by stanio** [comment]
> I am not saying that this is a likely scenario. Especially not with such high numbers. I was just wondering whether there is a surefire way.

I was asking for a comparison with other applications – if there's no general difference, not sure what's the problem with it.

> Will changing the windows setting for java always a base fontsize instead?

I was trying to figure out your exact runtime configuration.  With "standard" (Oracle) Java 8 I can't achieve the hires effect you've given without tweaking the given hi-dpi override setting.  It's not necessary with Java 9+.

**Comment by DevCharly** [comment]
225% + 225% is 500% in reality (100 x 2,25 x 2,25 = 506%). This is huge. :flushed:
The font size in the dialog seems to be the same as in its title, which comes from Windows 10.
This is OK and the label actually gives the dialog the large size.
Having smaller gaps and smaller button insets would reduce the dialog not that much...

### What Windows 10 does

- "screen scaling" scales everything (text, icons, gaps, etc); each screen can have its own scale factor
- "text scaling" scales only text, but not icons, gaps, etc\
  (this seems to work not very well on my machine; some text is larger, some text not...)

### What FlatLaf does

**Java 8** does not scale, but it gets a scaled font from Windows that combines the Windows screen and text scale factors. FlatLaf uses the font size to calculate the scale factor that it uses to scale everything.

In case of 225 + 225%, Windows passes a font size of **60pt** to Java (default is 12pt at 100%).
So the resulting FlatLaf scale factor is 5x (60 / 12 = 5).

**Java 9 and later** use the Windows "screen scaling" factor to scale everything (text, icon, gaps, etc) and the Windows "text scaling" factor to scale the font only.

In case of 225 + 225%, Java uses a general 225% scaling and Windows passes a font size of **27pt** to Java (default is 12pt at 100%). So the resulting FlatLaf scale factor is 2.25x (27 / 12 = 2.25). Plus the 225% Java scaling, the whole UI is scaled by 500%.

**So the difference is that FlatLaf currently uses the Windows "text scaling" factor also to scale icons, gaps, etc.**

This could be easy solved when running on Java 9+, where the two scaling factors are separated, but in Java 8 they are combined. There is no API to determine Windows screen scaling factor in Java 8 (as far as I know). Anyway, I found a way to calculate it from desktop property "win.defaultGUI.font", which is scaled using Windows screen scaling factor. Default font is Tahoma 11pt at 100%.

https://github.com/JFormDesigner/FlatLaf/blob/932ca6f9d480b67023f96b20e95562f26fa3baf1/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatDesktopPropertiesDump.java#L63-L71

So could change class `UIScale` to use same screen scaling factor for FlatLaf when running on Windows. On Linux and macOS the situation is different.

This would look like this (screen scaling 100%, text scaling 200%, icons and gaps are not scaled):

![image](https://user-images.githubusercontent.com/5604048/94033170-fc7fbf00-fdc0-11ea-8bf2-b9ac6671413b.png)

### Layout Managers

An additional problem are scaling layout manager like MigLayout (v5.2 and older) and JGoodies FormLayout. Both use the font to compute its own scale factor and then scale gaps, minimum widths/heights, etc.

For FormLayout you could probably solve it by invoking `DefaultUnitConverter.setDefaultDialogFont(Font)` with a font that is scaled with the screen scale factor.

For MigLayout you have to use version 5.3-SNAPSHOT, which uses the scaling factor from FlatLaf: https://github.com/mikaelgrev/miglayout/pull/76

### Conclusion

FlatLaf scaling is only different to Windows scaling if text size is increased in Windows settings.

I'll implement a Windows 10 compatible scaling factor calculation.
But I'm not sure whether I like to enable it by default or make it optional...
Enabling it would make FlatLaf scaling compatible to Windows scaling.
On the other hand, if applications implement some font changing mechanism (e.g. in Preferences dialog or via `Ctrl++`/`Ctrl+-` keys as in web browsers), it would be great if the whole UI would scale...

**Comment by Bios-Marcel** [comment]
> Default font is Tahoma 11pt at 100%.

Weird. I thought the default font is Segoe 12pt. Tahoma should be the Windows XP font afaik. But I guess it doesn't really matter as long as it can be used to determine scaling correctly.

> But I'm not sure whether I like to enable it by default or make it optional...

What downside would there be to justify leaving it disabled by default?

> An additional problem are scaling layout manager like MigLayout (v5.2 and older) and JGoodies FormLayout.

Maybe we could PR this into JGoodies/FormLayout.


Either way, thanks for looking into this.

A random side question, do you happen to accept donations anywhere?

**Comment by Bios-Marcel** [comment]
@DevCharly Btw, if you write "Fixes #XXX" in your commits, GitHub will automatically close them :+1:

**Comment by stanio** [comment]
BTW, I've noticed many of the Microsoft own applications behave like FlatLaf previousy – using a bigger text scaling (in the Ease of Access display settings) makes their UI bigger:

_Text scale 100%_
![text-100%](https://user-images.githubusercontent.com/1247730/95114697-00122f00-074d-11eb-99cc-5fe6e9bd9ecb.png)

_Text scale 120%_
![text-120%](https://user-images.githubusercontent.com/1247730/95114766-1ae4a380-074d-11eb-9981-aecae6696dd6.png)

Not sure I like this, but I wonder if the new behavior wouldn't cause too much difference between platforms – that is, making the text bigger on Mac or Linux would scale the UI, while on Windows it wouldn't.
