### ISSUE TITLE
NPE in FlatSpinnerUI with button-less JSpinner

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#181]
Hi,

I use a custom JSpinner with the buttons removed (the value is increased/decreased with the mousewheel instead). In this situation with FlatLaf 0.42 I get a NullPointerException in `FlatSpinnerUI`:

    Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    	at com.formdev.flatlaf.ui.FlatSpinnerUI.update(FlatSpinnerUI.java:272)
    	at javax.swing.JComponent.paintComponent(JComponent.java:780)
    	at javax.swing.JComponent.paint(JComponent.java:1056)

Here is a minimal test case to reproduce the issue:

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            FlatDarkLaf.install();
            JFrame frame = new JFrame("FlatLaf SpinnerUI Test");
            frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            frame.setSize(800, 600);
            frame.setLocation(100, 100);
            frame.setVisible(true);
            frame.getContentPane().setLayout(new FlowLayout());

            JSpinner spinner = new JSpinner();
            for (Component component : spinner.getComponents()) {
                if (component.getName() != null && component.getName().endsWith("Button")) {
                    spinner.remove(component);
                }
            }

            frame.getContentPane().add(spinner);
        });
    }

**Comment by DevCharly** [comment]
Interesting use case 👍 

Thx for reporting. Fixed in master branch.
