### ISSUE TITLE
Customize decorator

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#184]
On Windows 10 the native decorator is white.

In the application with light colors isn't easy to distinguish the decorator from the rest of the application.

![image](https://user-images.githubusercontent.com/17149962/95171959-f7564300-07b6-11eb-8520-0ca9a3438000.png).

There are a way to add a border in the top of all windows, under the decorator?

Like this:
![image](https://user-images.githubusercontent.com/17149962/95172606-d9d5a900-07b7-11eb-9528-40ce5840b3ca.png)

Thanks

**Comment by DevCharly** [comment]
This is now implemented in master branch.

To enable use (e.g.):
~~~java
UIManager.put( "TitlePane.borderColor", Color.magenta );
~~~

To give it the same color as the menu bar separator:
~~~java
UIManager.put( "TitlePane.borderColor", UIManager.getColor( "MenuBar.borderColor" ) );
~~~
