### ISSUE TITLE
Enhancement: Focus border for custom scrollpane-like components

### ISSUE THREAD

**Issue by electriq** [JFormDesigner/FlatLaf#185]
The colored focus borders looks really nice. But we have a custom focusable component which is nested inside a custom scrolling object (just a `JComponent` with two `JScrollBars` and the scrolling component in the center). 

Focused border in `FlatBorder` works perfect if we set such a border to the focusable inner component (calling `setBorder(UIManager.getBorder("ScrollPane.border"))`, checking if for null before). But we need to set this border to the outer component with scroll bars to look more consistent.

I see the code in `FlatBorder.isFocused(c)` for handling `JScrollPanes`, it just checks the focused state of the scrollpane's view component.

So my idea is to make some simple interface like 'ViewportContainer' with one method `getView()` for custom scrollpane-like panels to find the actual focused state of their views. And add to the `FlatBorder.isFocused(c)` method:

```
if (c instanceof ViewportContainer) {
  Component view = ((ViewportContainer) c).getView();
  if (view != null && FlatUIUtils.isPermanentFocusOwner( view ))
    return true;
}
```
Is it a good idea for FlatLaf?

**Comment by electriq** [comment]
Thank you for the comment. Yes, I understand that my idea is very specific.

I personally don't like the architecture with subclassing of `FlatBorder` because of increased coupling:
1) There is no guarantee that FlatLaf will use `FlatBorder` as a border for other scroll panes (it is LNF internal decision what border to apply and the border class may even be private in the LNF);
2) We will need to add 'ifs' for selection of the border for different LNF; so `ourCustomScrollPane.setBorder( UIManager.getBorder("ScrollPane.border"))` appears to be more universal.

**Comment by DevCharly** [comment]
Hey @electriq, sorry forgot to let you know that since FlatLaf 1.0 there is a client property that gives you more control over the focus indicator. You can add something like following code to a (non-focusable) component that uses e.g. `FlatBorder` and check whether e.g. a child component is focused.

~~~java
myComponent.putClientProperty( "JComponent.focusOwner",
    (Predicate) c -> {
        return ...; // check here
    } );
}
~~~

**Comment by electriq** [comment]
@DevCharly, thank you, that's great! Yes, I didn't noticed this commit, thank you for mentioning. I have just implemented it and it works excellent, without explicit FlatLaf classes import (even ``setBorder(UIManager.getBorder("ScrollPane.border"));``). Just added ``repaint()`` on the internal component's focus gained/loss.
