### ISSUE TITLE
Idea: add option to force heavy weight popups

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#189]
In my application I heave the need to force heavy weight popups for all systems (not only Linux/MacOS).

at the moment I need to copy/inherit the FlatPopupFactory, copy over almost all code (because most of it is private), just to _remove_ the if statement from https://github.com/JFormDesigner/FlatLaf/blob/5444719895a0a50d0e085859af87901203a87679/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatPopupFactory.java#L75

So my idea was to introduce a property to force heavy weight popups for all (or to make most of the code protected). What do you think?

**Comment by DevCharly** [comment]
Out of interest, what's the reason for always needing heavy weight popups?

**Comment by mlaggner** [comment]
I have a problem with JToolTips from my JTable columns which leave artifacts after disappearing. Looks like only the JTable columns get re-rendered after hiding of the tooltips, but the columns are transparent and the drawing on the JViewPort/JScrollPane does not get re-rendered.

The only workaround I've found so far is to force heave weight popups

**Comment by DevCharly** [comment]
Have you checked whether the `opaque` property is `false` on the transparent component?
This is important because when the repaint manager paints only parts of the window, it checks the `opaque` property.
If `true`, it does not paint the parent.

**Comment by mlaggner** [comment]
all components were set to opaque = false; but I found out, that the code to redraw (dunno where I found that years ago) did not handle the clip bounds the right way - so just the part which got covered by the tooltip did not get redrawn 🤦 but thanks for pointing me in the right direction - I've already spend hours to search for this issue

nevertheless, more flexibility to configuration would be great - don't you think?

**Comment by DevCharly** [comment]
So it works now with light weight tooltips?

> nevertheless, more flexibility to configuration would be great - don't you think?

👍  Yes, I'll make some changes to `FlatPopupFactory`...

**Comment by mlaggner** [comment]
yes it works as it should ;) thanks again for your help

**Comment by DevCharly** [comment]
Since commit 6c8b8e894921fbaf3dcbf5a27ae9f6314872c984 it is possible to force heavy weight popups with (for all popups in application):

~~~java
UIManager.put( "Popup.forceHeavyWeight", true );
~~~

For forcing heavy weight popups only for individual components, use:
~~~java
popupOwnerComponent.putClientProperty( "Popup.forceHeavyWeight", true );
~~~
