### ISSUE TITLE
Light elements in file chooser under dark skin

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JFormDesigner/FlatLaf#19]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/52874/67231435-50459380-f40d-11e9-8a5f-159363d8c582.png">

Also, how do I go up into the parent folder? It seems to be missing the entire navigation bar as here in Nimbus:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/52874/67231569-884cd680-f40d-11e9-830d-82a040c88937.png">

**Comment by DevCharly** [comment]
FileChooserUI is not yet implemented (see issue #5).

Currently plain `AquaFileChooserUI` is used on Mac and `MetalFileChooserUI` on other platforms.

The file chooser of the Aqua LaF seems not have more controls than those shown in the first screen shot. Have to look at the source code...

To go to the parent folder, you can use the combobox above the file list.

**Comment by DevCharly** [comment]
fixed in 0.20, based on `MetalFileChooserUI` on all platforms
