### ISSUE TITLE
FlatSVGIcon explicit scaling

### ISSUE THREAD

**Issue by xDUDSSx** [JFormDesigner/FlatLaf#196]
Hello,
I was wondering if there is any way to set a FlatSVGIcon's size directly that it would scale the svg itself into given dimensions like 16x16, eg. the same size as a 16x16 pixel ImageIcon.
From what I understand right now. The svg icon renders in whatever size the source .svg file has defined in the file itself.

To elaborate on why I'm interested in such functionality. When I download an .svg file from, say, an online icon library. It's not necessarily going to be 16x16 pixels and I have to use some tools to scale it into the size I desire. 

Another issue arises when I want to have a set of 16 pixel icons and a bigger set that is like 24 pixels big for some other use cases. One would think that when I'm already using svg icons such icons could be generated by just scaling the same .svg file. 

The ability to support multiple sizes is certainly part of the appeal of using svg icons. Am I missing something or is there no way to achieve that so it would work with hiDpi scaling and so on?

**Comment by electriq** [comment]
It will be also useful to be able to create multiple FlatSVGIcon with different sizes from the same SVG file once loaded. So we have a single SVG icon file and can use it with size 16x16 in the main menu, 24x24 in the toolbar and 32x32 as an icon in the message dialog window, for example. Looks like overriding size in constructor is a good idea: `Icon icon16 = new FlatSVGIcon(resourceName, 16, 16);`. Or it may be implemented as a cloning method, sharing the SVGDiagram (but it seems it's too little resources to optimize here), like `FlatSVGIcon icon16 = icon32.scaledInstance(16, 16);` Now we actually need to store two or more identical SVG files with different sizes in resources.

**Comment by DevCharly** [comment]
Thx, this is now implemented in master branch.

There are additional constructors in `FlatSVGIcon`  where you can pass width and height:
https://github.com/JFormDesigner/FlatLaf/blob/4c141fe47c49dd5c6601d81062e4c4f670c1239d/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGIcon.java#L91-L101

or a scale factor:
https://github.com/JFormDesigner/FlatLaf/blob/4c141fe47c49dd5c6601d81062e4c4f670c1239d/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGIcon.java#L121-L132

There are also `derive` methods that allow quick creation of icons in various sizes:
https://github.com/JFormDesigner/FlatLaf/blob/4c141fe47c49dd5c6601d81062e4c4f670c1239d/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatSVGIcon.java#L161-L168

**Comment by xDUDSSx** [comment]
Exactly what I had in mind. Works well, good job. Not just with this but with the project overall. Looks great and it's nice to see all the progress you're making with each update.  👍
