### ISSUE TITLE
Give unique names to some of the default themes listed in FlatAllIJThemes

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#201]
Some of the themes listed in `FlatAllIJThemes.INFOS` have the same name for different Java classes:

- Arc Dark 
- Dracula 
- Solarized Dark 
- Solarized Light

Can we give these ones unique names? This is because in my application I list all the available themes allowing the user to select the theme. Currently with those 4 names, the user cannot distinguish between the two variants. Thanks.

**Comment by DevCharly** [comment]
Hmm, maybe I should change all names of the material UI lite collection to differ them from non material themes.
Something like "Arc Dark (Material)"

**Comment by grimlock81** [comment]
Yes that would be great.

**Comment by DevCharly** [comment]
Fixed in latest snapshot
