### ISSUE TITLE
custom Properties

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#203]
Hi, I would want to change only some global properties.
For example I would want change the default cyan used in the:

- checkbox
- radioButton
-  button selection
-  ecc
with a different color.

I have tried to edit the file DemoLaf.properties and launch FlatLafDemo, but the modifications are not applied.

Probably I'm wrong. How it works?

**Comment by DevCharly** [comment]
> I have tried to edit the file DemoLaf.properties and launch FlatLafDemo, but the modifications are not applied.

Is "DemoLaf" in the list of themes? And is it selected? (see screenshot)

![image](https://user-images.githubusercontent.com/5604048/98274535-d2124b80-1f93-11eb-8be5-fda963691286.png)

Here is the `DemoLaf.properties` used for the above screenshot:
~~~
# base theme (light, dark, intellij or darcula)
@baseTheme=light

# selection color in lists, tables, trees, menus and text components
@selectionBackground=#f0f

# component border if focused
Component.focusedBorderColor=#f00

# outer focus border color 
#   see https://www.formdev.com/flatlaf/customizing/#outer_focus_width
Component.focusColor=#f00

# for checkbox and radiobutton
CheckBox.icon.checkmarkColor=#f00
CheckBox.icon.focusedBorderColor=#f00

# border that marks "default" button
Button.default.borderColor=#0f0

# active tab
TabbedPane.underlineColor=#0ff
~~~

**Comment by basix86** [comment]
ok. I haven't seen DemoLaF in the theme list. Thank's!
