### ISSUE TITLE
FlatLaf is not right synchronized

### ISSUE THREAD

**Issue by GeniuZ666** [JFormDesigner/FlatLaf#206]
I get this error:
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "javax.swing.JProgressBar.isIndeterminate()" because "this.progressBar" is null
at com.formdev.flatlaf.ui.FlatProgressBarUI.paint(FlatProgressBarUI.java:166)`

From reading your code, exception is caused by reference to "progressBar" field inside paint() function after I call dispose(). I assume uninstallUI() method is not synchronized with progressBar references, so when uninstallUI() method is called, progressBar is nulled, but active code can be inside paint() function. I think this can be issue cross your GUI if other elements are similar as progress bar.

Regards

**Comment by DevCharly** [comment]
Java Swing is not synchronized.

You have to invoke all UI related methods on the AWT thread.

If you invoke dispose() on another thread, this can happen.
In any LaF.

Use `SwingUtilities.invokeLater()` to dispose the window on the AWT thread.

**Comment by GeniuZ666** [comment]
Oh, so this is my ignorance, thank you for explanation.
