### ISSUE TITLE
Tabbed pane – More tabs menu with empty title tabs

### ISSUE THREAD

**Issue by stanio** [JFormDesigner/FlatLaf#207]
Not a bug but a request for comments on possible edge-case accessibility improvement.

Using FlatLaf 0.44-SNAPSHOT including #190 which makes `TabbedPane.hiddenTabsNavigation=moreTabsButton` the default.  Having a tabbed pane with empty tab titles and tab labels painted by custom components:

```java
//package ;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.beans.PropertyChangeListener;

import javax.accessibility.AccessibleContext;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLightLaf;

public class TabbedPaneTest extends JFrame {

    public TabbedPaneTest() {
        super("Tabbed Pane Test");
        super.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        Container contentPane = getContentPane();
        if (contentPane instanceof JComponent) {
            ((JComponent) contentPane)
                    .setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        }

        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane.putClientProperty("JTabbedPane.hiddenTabsNavigation", "moreTabsButton");
        //tabbedPane.putClientProperty("JTabbedPane.hiddenTabsNavigation", "arrowButtons");

        PropertyChangeListener tabNameListener = evt -> {
            int tabIndex = (int) evt.getNewValue();
            AccessibleContext tabPage = tabbedPane.getAccessibleContext().getAccessibleChild(tabIndex).getAccessibleContext();
            Component tabComponent = tabbedPane.getTabComponentAt(tabIndex);
            if (isNullOrEmpty(tabPage.getAccessibleName()) && tabComponent != null) {
                //tabbedPane.setTitleAt(tabIndex, tabComponent.getAccessibleContext().getAccessibleName());
                tabPage.setAccessibleName(tabComponent.getAccessibleContext().getAccessibleName());
            }
        };
        tabbedPane.addPropertyChangeListener("indexForTabComponent", tabNameListener);
        tabbedPane.addPropertyChangeListener("indexForTitle", tabNameListener);

        tabbedPane.addTab(null, newContentComponent("1"));
        tabbedPane.setTabComponentAt(0, newTitleComponent("Lorem ipsum"));
        tabbedPane.addTab(null, newContentComponent("2"));
        tabbedPane.setTabComponentAt(1, newTitleComponent("Dolor sit amet"));
        tabbedPane.addTab(null, newContentComponent("3"));
        tabbedPane.setTabComponentAt(2, newTitleComponent("Consectetur adipiscing"));
        tabbedPane.addTab(null, newContentComponent("4"));
        tabbedPane.setTabComponentAt(3, newTitleComponent("Etiam volutpat"));

        contentPane.add(tabbedPane);
    }

    private static JLabel newContentComponent(String content) {
        return new JLabel(content, SwingConstants.CENTER);
    }

    private static Component newTitleComponent(String name) {
        JPanel panel = new JPanel(new BorderLayout());
        JLabel label = new JLabel(name);
        label.setLabelFor(panel);
        panel.add(label);
        panel.setOpaque(false);
        return panel;
    }

    private static boolean isNullOrEmpty(String value) {
        return value == null || value.isEmpty();
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            FlatLightLaf.install();

            TabbedPaneTest frame = new TabbedPaneTest();
            frame.setLocation(50, 50);
            frame.pack();
            frame.setSize(frame.getWidth() + 100, frame.getHeight() + 100);
            frame.setVisible(true);
        });
    }

}
```

In this case, the "more tabs" menu ends up with empty-label items:

![tabs-more-menu-empty](https://user-images.githubusercontent.com/1247730/98532569-8c52cd00-228a-11eb-87dc-e99573e25ece.png)

Is it feasible to fall back to using the `JTabbedPane.accessibleContext.accessibleChild[i].accessibleContext.accessibleName` when `JTabbedPane.titleAt[i]` happens to be empty?  Here's the tabbed-pane accessible context hierarchy for the given example:

```
JTabbedPane
|
+-- Page: Lorem ipsum
|   |
|   \-- JLabel: 1
|
+-- Page: Dolor sit amet
|   |
|   \-- JLabel: 2
|
+-- Page: Consectetur adipiscing
|   |
|   \-- JLabel: 3
|
\-- Page: Etiam volutpat
    |
    \-- JLabel: 4
```

(Normally the tab page `accessibleName` is taken from the tab title, but one could explicitly set it, also.)

So finally:

![tabs-more-menu-text](https://user-images.githubusercontent.com/1247730/98538918-2703d980-2294-11eb-9d1e-90ce58b53d1f.png)

**Comment by DevCharly** [comment]
Thx for looking into this.

I tried it but I'm not sure where there is an advantage in using accessible context,
because it is still necessary to explicitly set it.
So one could also set the tab title explicitly.

I considered painting custom tab components into a popup menu items,
but this would be strange if using "active" components in the tab
(e.g. own close button) because they would be dead.

So based on the idea of using accessible name, thought why not simply search for a label in the custom tab component and use its text in the "more tabs" popup menu. This is implemented in commit 8594e782876e63f529a9ba20eb4a8a43ff503e68

**Comment by stanio** [comment]
> I tried it but I'm not sure where there is an advantage in using accessible context,
> because it is still necessary to explicitly set it.
> So one could also set the tab title explicitly.

While I agree setting the tab title is best, the tab titles are set to empty just for visual purposes in my case (working around another L&F – JGoodies Plastic bugs), so setting the accessible name of tabs would still be necessary to maintain accessibility.  That's why I've thought of using the accessible name if it is already non-empty.

> So based on the idea of using accessible name, thought why not simply search for a label in the custom tab component...

I think it is good enough, although in theory, the custom tab component might not contain a label (text might be painted in another way).  Subjectively, having no label component is less likely than having a non-empty accessible name of the custom tab component, so thank you for implementing your solution to this.

**Comment by DevCharly** [comment]
@stanio based on your feedback I've further improved finding a useful tab name for the popup:

https://github.com/JFormDesigner/FlatLaf/blob/cbc1fe27ef5cc6abc0f7edeea31167ab78e79be6/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java#L1557-L1562

Now it is sure that menu items are not empty 😉
