### ISSUE TITLE
Title Bar Incorrectly Shown for Full Screen Windows with setDefaultLookAndFeelDecorated(true)

### ISSUE THREAD

**Issue by PicoMitchell** [JFormDesigner/FlatLaf#212]
I have a couple full screen JFrame windows in my app using the following code to set fullscreen:

```
GraphicsDevice defaultScreenDevice = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

if (defaultScreenDevice.isFullScreenSupported()) {
    defaultScreenDevice.setFullScreenWindow(this);
} else {
    setExtendedState(JFrame.MAXIMIZED_BOTH);
}
```

When using `JFrame.setDefaultLookAndFeelDecorated(true)` on Windows 10, the titlebar for these windows are still shown when they shouldn't be shown with a fullscreen window (titlebar was not shown before using the fantastic FlatLaf).

If I set `setDefaultLookAndFeelDecorated(false)` for these specific JFrame classes, the titlebar is still shown the first time one of the windows is opened, but then is properly not shown on subsequent openings of these window.

**Comment by DevCharly** [comment]
Thx for reporting.

Fixed in main branch.
Could you please try the latest snapshot and let me know whether it works for you?
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by PicoMitchell** [comment]
Thanks so much! The latest snapshot successfully does not draw the titlebar for the fullscreen window, but does still draw a 1px border around the edge of the full screen window.

I noticed this because my app is a refurbishment testing tool and one of my full screen windows is simply a solid color screen test.

**Comment by DevCharly** [comment]
Thx. Did not notice the 1px border 😉 
Fixed in latest snapshot.

**Comment by PicoMitchell** [comment]
The latest snapshot looks like it handles full screen windows perfectly on Windows 10 with setDefaultLookAndFeelDecorated(true)!

Thanks so much for your very quick fixes and for FlatLaf in general! It really is wonderful to be able to have such a flexible and functional modern GUI for Java Swing apps :-)
