### ISSUE TITLE
Table.showHorizontalLines/Table.showVerticalLines has no effect on JXTable.

### ISSUE THREAD

**Issue by mwithake** [JFormDesigner/FlatLaf#213]
JXTable vertical- and horizontal lines are deactivated by default as is the case by JTable. But Table.showHorizontalLines and Table.showVerticalLines setting to true has no effect on a JXTable, even table.setShowHorizontalLines(true) has no effect. JTable is working.
We are using FlatDarkLaf and FlatLightLaf version 0.44.

**Comment by DevCharly** [comment]
That's because there is no space between the cells for the grid lines.
In other words: the grid is painted, but then the (opaque) cells are painted over the grid.

Set intercell spacing to 1,1 to see the grid:
~~~java
myTable.setIntercellSpacing(new Dimension(1, 1));
~~~

**Comment by mwithake** [comment]
That works, thank you for your help.
