### ISSUE TITLE
how to add the FlatLaf for netbeans based java swing project

### ISSUE THREAD

**Issue by chenuraJpura** [JFormDesigner/FlatLaf#215]
how to add the FlatLaf for netbeans based java swing project?i am beginner to programming.please help me.give me a guide to "how to add the this library to the netbeans based java swing project"

**Comment by basix86** [comment]
You should check how you can add a maven depencency in our project or the jar of flatlaf.

After you should install the look and feel in you main with UIManager.setLookAndFeel()

**Comment by chenuraJpura** [comment]
> 
> 
> You should check how you can add a maven depencency in our project or the jar of flatlaf.
> 
> After you should install the look and feel in you main with UIManager.setLookAndFeel()

thank you for your response!! it works!!
