### ISSUE TITLE
Add title pane embedded underline selection color

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#216]
Suppose this use case with embedded title pane and underline enabled.

> UIManager.put("MenuBar.background", new ColorUIResource( Color.BLUE));
UIManager.put("MenuBar.foreground", new ColorUIResource( Color.WHITE));
UIManager.put("TitlePane.embeddedForeground", new ColorUIResource( Color.WHITE));
UIManager.put("TitlePane.background", new ColorUIResource(Color.BLUE));
UIManager.put("TitlePane.foreground", new ColorUIResource(Color.WHITE));
UIManager.put("MenuItem.underlineSelectionColor", new ColorUIResource(Color.BLUE));
UIManager.put("MenuItem.selectionType", "underline");

![image](https://user-images.githubusercontent.com/17149962/100464166-63756900-30cd-11eb-996f-5ae1d2217197.png)

We need a new key  (for example TitlePane.underlineSelectionColor) to have underline WHITE in the TitlePane and BLUE in MenuItem

**Comment by DevCharly** [comment]
@basix86 thanks for the PR.

I've extended it to also support different `underlineSelectionBackground` and `underlineSelectionHeight` for menu bars.

~~~java
UIManager.put("MenuBar.underlineSelectionColor", Color.white);
UIManager.put("MenuBar.underlineSelectionBackground", Color.red);
UIManager.put("MenuBar.underlineSelectionHeight", 5);
~~~
