### ISSUE TITLE
Add support for JXTitledPanel

### ISSUE THREAD

**Issue by martinm1000** [JFormDesigner/FlatLaf#22]
I'm still trying to see if I have my own border and options interfering with this control, but would an official addon for this component make it look better ?

**Comment by DevCharly** [comment]
> would an official addon for this component make it look better?

Probably, I'll have a look...

BTW does `JXTitledPanel` work normally for you?
When I add it to `FlatSwingXTest` test app, painting of app window becomes very slow.
Very strange...

**Comment by martinm1000** [comment]
I didn't try adding it to this codebase and this theme, but I never experienced slowness in my application that use quite many of them.

**Comment by DevCharly** [comment]
implemented in 0.20
