### ISSUE TITLE
Focused button has blue background

### ISSUE THREAD

**Issue by DanielLyi** [JFormDesigner/FlatLaf#220]
Hi. Sorry, if it's an easy to solve question. But I can't find how to make JButton in FlatLightLaf not becoming blue inside, when focused? Is it even possible? I'm using FlatLaf 0.44. For now, I just make every button not focusable, but it's definitely not the way to work with it. How can it be solved?
Thank you

![Button](https://user-images.githubusercontent.com/52933151/100552902-f14e8100-3292-11eb-9a41-3e2ba12a6142.png)

**Comment by DevCharly** [comment]
Following works:
~~~java
UIManager.put( "Button.focusedBackground", UIManager.getColor( "Button.background" ) );
UIManager.put( "Button.default.focusedBackground", UIManager.getColor( "Button.default.background" ) );
~~~
(invoke after setting look and feel)

**Comment by DanielLyi** [comment]
> Following works:
> 
> ```java
> UIManager.put( "Button.focusedBackground", UIManager.getColor( "Button.background" ) );
> UIManager.put( "Button.default.focusedBackground", UIManager.getColor( "Button.default.background" ) );
> ```
> 
> (invoke after setting look and feel)

Thank you! It worked for me. 
But I'm curious why do we have both default and just focused background? What's the difference?
