### ISSUE TITLE
Request: Consider adding themes.json to main jar

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#221]
This is a request. The flatlaf-demo.jar file contains a `themes.json` file under `com\formdev\flatlaf\demo\intellijthemes`

This file contains the list of all available FlatLAF themes (I assume it's all of them) as well as useful metadata about each theme including whether it's a **dark** theme or not. It would be useful to have this information available in the main flatlaf.jar file as I would like to offer the user the choice of which theme to use, and I would like to group the themes into Light Theme and Dark Theme groups.

Currently I get the list of available FlatLAF themes from the `com.formdev.flatlaf.intellijthemes.FlatAllIJThemes.INFOS` which only offers the name of the theme and not whether it's a dark theme or not.

Alternatively, is there a way of finding out whether a theme is dark or not without having to instantiate an instance of the `ThemeLaf` implementation. Thanks.

**Comment by DevCharly** [comment]
Don't want to ship `themes.json` because this may change in the future...

So I have added the dark flag to `FlatAllIJThemes.INFOS` in recent commit.
