### ISSUE TITLE
Tooltips have a weird incorrect shadow

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#224]
Happens on Java 11 with flatlaf 0.45:

![grafik](https://user-images.githubusercontent.com/19377618/102060449-7c328e00-3df2-11eb-9409-f20eaaa1281e.png)

I am assuming the thing on the right is a shadow.

I've added the tooltips via the `Action.SHORT_DESCRIPTION` of an action.
Weirdly this only happens if the tooltip is rendered inside the window. Try both the top left and the bottom right corner of the button:

Demo:

```java
package com.isp.examples.table;

import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

import com.formdev.flatlaf.FlatLightLaf;

public class Bug
{
  public static void main( final String[] args )
  {
    FlatLightLaf.install();
    final JFrame frame = new JFrame();
    final JButton jButton = new JButton();
    jButton.setAction( new AbstractAction()
    {
      {
        putValue( Action.NAME, "Test" );
        putValue( Action.SHORT_DESCRIPTION, "LOOOOOOOOOOOOOONG TEXT" );
      }

      @Override
      public void actionPerformed( final ActionEvent e )
      {
      }
    } );
    frame.add( jButton );
    frame.setSize( 400, 400 );
    frame.setLocationRelativeTo( null );
    frame.setDefaultCloseOperation( WindowConstants.EXIT_ON_CLOSE );
    frame.setVisible( true );
  }
}
```

**Comment by DevCharly** [comment]
Good catch. The drop shadow looks good, but the tooltip is too small. Fixed in master branch.

> Weirdly this only happens if the tooltip is rendered inside the window

That's because light weight popups are used if tooltip fit into window.
If partly outside of window, heavy weight popups are used.

**Comment by Bios-Marcel** [comment]
Thanks
