### ISSUE TITLE
Big menus aren't scrollable

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#225]
I think it'd be a very nice addition for people using a high zoomfactor, if menus were scrollable via the mouse-wheel including an indicator at the top and bottom whether there's still "content" (menu items) left. I assume this could be done with a slightly customized scrollpane. Is this something the look and feel could do, or should this be an external thing, e.g. each application has to do this itself?

**Comment by dinix2008** [comment]
Another interesting option would be to arrange the menu in several columns instead of scrolling.

**Comment by Bios-Marcel** [comment]
I am not sure whether that's nice if you have submenus. It might confuse the user. Maybe I am wrong though.

**Comment by dinix2008** [comment]
@Bios-Marcel, this behavior was still in Windows 7 in the classical start menu. The start menu supported several columns and there were no special problems, in my opinion, this did not cause. Here is an example of a large menu 
![image](https://user-images.githubusercontent.com/1597289/102097489-0866a480-3e37-11eb-8f2e-f39f254af0c5.png)

**Comment by Bios-Marcel** [comment]
Yeah, you are right, doesn't look bad.

**Comment by dinix2008** [comment]
@Bios-Marcel, In our project we use scrolling in the menu in some special cases, but it looks so unassuming and inconvenient :-) The code was taken from here https://tips4java.wordpress.com/2009/02/01/menu-scroller/

**Comment by Bios-Marcel** [comment]
Well, I assumed scrolled might be good, as it will always fit, no matter how much horizontal or vertical space is left.
However, the thing that makes multi-column menus (your idea) better, is that you can at once skim all items and be more efficient in finding what you need or realizing that what you need won't be there.

**Comment by DevCharly** [comment]
Scrolling big menus is now implemented in main branch.

It works similar to macOS, Firefix, Chrome, etc:
- rotate mouse wheel scrolls the menu
- scroll arrows appear at top and/or bottom or menu and moving mouse over scroll arrows scrolls the menu

![image](https://user-images.githubusercontent.com/5604048/158159833-75438679-4a18-4a36-b100-a94b08bc40a1.png)
