### ISSUE TITLE
NPE in UIScale.getSystemScaleFactor(Graphics2D)

### ISSUE THREAD

**Issue by Nibby** [JFormDesigner/FlatLaf#226]
This method crashes for some 3rd party Graphics2D implementations that returns null for g2d.getDeviceConfiguration(). For example, UI printing functionalities that use FlatLaf crashes when using [org.apache.batik.svggen.SVGGraphics2D](https://github.com/iconfinder/batik/blob/master/sources/org/apache/batik/svggen/SVGGraphics2D.java) to paint components.

**Comment by DevCharly** [comment]
The NPE is fixed in master branch.
Please try the latest [snapshot](https://github.com/JFormDesigner/FlatLaf#snapshots) and let me know whether there are other issues. Thx.

**Comment by Nibby** [comment]
@DevCharly Can confirm the issue is fixed in the latest snapshot, thanks!
