### ISSUE TITLE
ColorFunctions$HSLIncreaseDecrease not serializable

### ISSUE THREAD

**Issue by patrickhuang112** [JFormDesigner/FlatLaf#231]
Hello,

I was using FlatLafDark as a look and feel for a java swing app I was developing. In the app (it's a paint and draw app), I am allowing users to save files by serializing an object that contains all the data associated with the work they have done. The main issue is that when I try to serialize my object through the writeObject method while using this look and feel, I get 
"java.io.NotSerializableException: com.formdev.flatlaf.util.ColorFunctions$HSLIncreaseDecrease". Is there any way for this class and other parts of the look and feel to be serializable?

EDIT: also let me know if there is any more information required to help solve this issue. I can include a video showcasing the problem or screenshots if needed.

**Comment by DevCharly** [comment]
Nope, FlatLaf is not serializable and IMHO there is no need to serialize a look and feel.

Why would you like serialize look and feel classes with data? That makes no sense to me.
Look and feel classes are UI related to display data on screen.
You do not need to serialize the UI.
Only the data.

If you like to remember the current Laf in some serialized state, then only store the Laf class name:
~~~java
// write
String lafClassName = UIManager.getLookAndFeel().getClass().getName();
writeUTTF( lafClassName );

// read
String lafClassName = readUTF();
UIManager.setLookAndFeel( lafClassName );
~~~

**Comment by patrickhuang112** [comment]
I think my issue was that I trying serialize some UI components (like JPanels and other stuff) as well as data. I changed how I did that so i don't have the issue anymore.
