### ISSUE TITLE
Support configurable accent color for FlatLaf themes

### ISSUE THREAD

**Issue by k-kirill** [JFormDesigner/FlatLaf#233]
Light, Dark, IntelliJ and Darcula themes use blue as the accent color and there is no easy way to change it to something else.

Windows, macOS support changing accent color, on Linux one can easily change themes, so to make Java Swing apps fit the overall appearance that configurable accent color for FlatLaf would be really handy.

**Comment by DevCharly** [comment]
Yes, this is already on my TODO list 👍

**Comment by JohnatanRoss** [comment]
I could really use this right now.
As a crude workaround, which Flatlaf component properties do I have to change to have a custom coloring on all of them (Including the focus highlights). Found almost no documentation for this, it's like fishing for the magical goldfish.

**Comment by DevCharly** [comment]
Coming soon 😄 
See PR #375
