### ISSUE TITLE
SwingX's DatePickerUI as a table cell editor

### ISSUE THREAD

**Issue by martinm1000** [JFormDesigner/FlatLaf#24]
There is a problem with a insets or a border when the DatePicker is used as a table cell editor. I think this has to be detected in the code and something removed when being used as a cell editor.

![2019-11-25_13-06-21](https://user-images.githubusercontent.com/3790866/69570209-5f2fe080-0f8d-11ea-8e0c-718b39be7360.png)

**Comment by DevCharly** [comment]
thanks, fixed in master branch

**Comment by DevCharly** [comment]
fixed in 0.20
