### ISSUE TITLE
Menu accelerators are not visible in the 'Monocai' theme

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#243]
I'm not sure if this is a bug or just a bad colour choice in the theme itself. The menu accelerators are not visible in the Monocai theme until the mouse if over the menu item itself. I haven't seen it in any other theme (so far)

![](https://i.imgur.com/b5pHe9r.gif)

**Comment by DevCharly** [comment]
That's a bug in the Monocai theme.
It is also the case when using the Monocai theme plugin in IntelliJ IDEA.
Anyway, fixed it in FlatLaf.

**Comment by mont1985** [comment]
### [****](`=`) #354
