### ISSUE TITLE
Windows have no shadow under "window decorations" mode

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#244]
If I enable "window decorations" ,then all the window have no shadow and inconsistent with system behavior

**Comment by DevCharly** [comment]
Yes, this is a known limitation of Java on Windows:
when invoking `frame.setUndecorated(true)`, the drop shadow is gone 😞 

Some native Windows code would be necessary to fix this.
I'll maybe implement this in the future.

An alternative it to use JetBrains Runtime 11 on Windows:
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime
This JRE (used by IntelliJ IDEA) supports undecorated frames/dialogs with drop shadows and system behavior.
And FlatLaf supports JetBrains Runtime:
https://github.com/JFormDesigner/FlatLaf/blob/63193feebe22a71b3ccae993baf45b2b87d124cd/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/JBRCustomDecorations.java#L47-L52

**Comment by rememberber** [comment]
@DevCharly I tried， and it works! Thanks a lot!
and I also find a line above the window, is it usual look?

![image](https://user-images.githubusercontent.com/4653893/105451520-a744b300-5cb7-11eb-828c-fc994e387ee6.png)

**Comment by DevCharly** [comment]
No, this does not look normal.
Could be also the case that the lines on the other 3 edges are missing...
Will try...

**Comment by DevCharly** [comment]
The wrong top border is now fixed in main branch. Thanks for reporting.

**Comment by rememberber** [comment]
Wow! Pretty Good! @DevCharly Thanks a lot!

**Comment by DevCharly** [comment]
@rememberber FlatLaf 1.1 now supports native window decorations with all JREs. See PR #267

**Comment by rememberber** [comment]
> @rememberber FlatLaf 1.1 now supports native window decorations with all JREs. See PR #267

@DevCharly Amazing!
