### ISSUE TITLE
Undecorated dialog

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#251]
I have a question.
The idea is create an un-closeable JDialog (e.g. waiter dialog), in particular a dialog without X button.

There are a way to create a dialog without title bar?

With other look and feels we need only `dialog.setUndecorated( true ); ` but it seems not works on Windows, because we have always a title bar.

**Comment by DevCharly** [comment]
You have enabled custom window decorations (with following code) in your app, right?

~~~java
JFrame.setDefaultLookAndFeelDecorated( true );
JDialog.setDefaultLookAndFeelDecorated( true );
~~~

So when the Laf supports them, as FlatLaf on Windows 10, then Swing does following in `JDialog.dialogInit()` when creating a new dialog:

~~~java
if (JDialog.isDefaultLookAndFeelDecorated() &&
    UIManager.getLookAndFeel().getSupportsWindowDecorations() )
{
    setUndecorated(true);
    getRootPane().setWindowDecorationStyle(JRootPane.PLAIN_DIALOG);
}
~~~

So the dialog is already undecorated.
You also need following to remove the custom window decoration:

~~~java
getRootPane().setWindowDecorationStyle( JRootPane.NONE );
~~~

> With other look and feels we need only dialog.setUndecorated( true ); ...

This depends on whether the Laf supports custom window decorations (on a platform).
Most Lafs do not.
Metal does and behaves the same as FlatLaf

**Comment by basix86** [comment]
ok, thanks. I have solved.
I haven't tested with JRootPane.NONE
