### ISSUE TITLE
Request: Optionally Keep Window Title Centered in Window with Embedded Menu Bar (in Win 10 with Custom Window Decorations Enabled)

### ISSUE THREAD

**Issue by PicoMitchell** [JFormDesigner/FlatLaf#252]
To my eye, it looks weird when the embedded menubar pushes the window title way over to the right since it's getting centered within the space between the end of the menubar items and the window buttons.

If possible, I would like to request adding an option to be able to have FlatLaf simply continue centering the window title within the entire width of the window.

Of course, there should probably be some added logic to never overlap the window title and the menu bar. Maybe something like centering the window title unless that would put it within X number of pixel (maybe this could be a configurable padding with a logical default) to the right of the menubar items, and in that case simply set the window title to that padding from the menubar to always keep it visually far enough away from the menubar items to not overlap or be able to confuse the title with another menubar item.

Thanks so much for your consideration and for FlatLaf!

**Comment by PicoMitchell** [comment]
I've just noticed VS Code handles the title centering with an embedded menubar about perfectly.

It is centers the title to the full window width unless the window gets too small and the left edge of the title gets within about 60px to the right edge of the menubar, then it switches to centering the title between the menubar and window buttons as FlatLaf currently does. Sounds to me like that could be a new default behavior rather than just an option.

**Comment by DevCharly** [comment]
Thx. Sounds like a good idea 👍 

Will try VS Code...

An option to have title left aligned, as in IntelliJ IDEA, would be also useful.

**Comment by DevCharly** [comment]
fixed in main branch
see also PR #268
