### ISSUE TITLE
Windows shadow looks abnormal when minimized and then return to before

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#253]
1.minimized  the window
2.then return to before
3.look what happen 
![image](https://user-images.githubusercontent.com/4653893/106841871-e0c8e580-66dd-11eb-82f8-590e5132f1ed.png)

**Comment by DevCharly** [comment]
Strange, can not reproduce this on my system...

Does this happen always? Or sometimes?
Does it happen in IntelliJ IDEA too?

Looks like a problem in the JetBrains JRE, which provides these (drop shadow) borders...

Does it also happen in newer JetBrains JRE versions (latest is 11.0.10; you're using 11.0.4):
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime

**Comment by rememberber** [comment]
@DevCharly 
1.happen always
2.your guess is right,I tried in IntelliJ IDEA,unbelievable the same!
3.and I tried to update JetBrains JRE version to 11.0.10, behave still the same, Thank you DevCharly, maybe I will give a issue to the JetBrains JRE project

**Comment by rememberber** [comment]
I got the reason finally , because I use the extend displayer
