### ISSUE TITLE
Inconsistent text colours in menu items when using Arc themes

### ISSUE THREAD

**Issue by grimlock81** [JFormDesigner/FlatLaf#259]
Firstly @DevCharly congrats on the 1.0 release, that's an amazing milestone for such a great project. Consider this the first issue for 1.0 😄 

When using these themes:

- Arc
- Arc - Orange

The text colour of a JMenu or JMenuItem is lighter than the text colour of a JRadioButtonMenuItem or a JCheckBoxMenuItem. This is clearest when opening menus in the FlatLaf Demo frame. This gives users a false impression that those items are disabled. This problem also occurs when used in a JPopupMenu.

![Arc](https://i.imgur.com/yrpQCgn.png) ![](https://i.imgur.com/tuoa76p.png) ![](https://i.imgur.com/HS9679A.png)

![Arc Orange](https://i.imgur.com/2AHWdgV.png)

For the equivalent Dark themes:
- Arc Dark (only the `com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme` version, the `com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkIJTheme` version is okay
- Arc Dark - Orange

the problem is reversed although the difference is not as obvious as the light themes. If you look closely the JRadioButtonMenuItem and JCheckBoxMenuItem text is slightly lighter than the JMenu/JMenuItem.

![Arc Dark](https://i.imgur.com/R8NVeT0.png) ![Arc Dark - Orange](https://i.imgur.com/R6F1geW.png)

I have gone through all the other themes, they are not affected by this issue.

**Comment by DevCharly** [comment]
Thx. 😃 
Now fixed in main branch.

The author of the Arc themes simply forgot to set colors for checkbox and radiobutton menuitems because IntelliJ IDEA seems not use them...
