### ISSUE TITLE
Accidentally commiteted System.out.println calls

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#263]
Hey,

I am assuming these were committed by accident and can be removed?

https://github.com/JFormDesigner/FlatLaf/blob/698e33ddf48ca37643ce7884fea5c81f91dd9dd7/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatInspector.java#L257

https://github.com/JFormDesigner/FlatLaf/blob/698e33ddf48ca37643ce7884fea5c81f91dd9dd7/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatInspector.java#L252

Commit:

https://github.com/JFormDesigner/FlatLaf/commit/a9e9fad222ac267d134069b5323744ae989f3775

**Comment by DevCharly** [comment]
Yes, thx.
