### ISSUE TITLE
Initial menu display doesn't show underlined hotkey/shortcut letters, displayed with alt+A 

### ISSUE THREAD

**Issue by mpl1031** [JFormDesigner/FlatLaf#264]
I don't think we're doing anything unusual with our menu.  It works as expected using Metal LAF.  Yes, we've altered the Panel.background color.
<img width="244" alt="2021-03-04 14_16_24-FlatLaf initial display menu" src="https://user-images.githubusercontent.com/80066129/110018501-5764fd00-7cf5-11eb-963d-47e07c83bb1a.png">
<img width="209" alt="2021-03-04 14_17_23-FlatLaf menu after alt-A" src="https://user-images.githubusercontent.com/80066129/110018504-5764fd00-7cf5-11eb-8878-4aa1a5a0514a.png">
<img width="231" alt="2021-03-04 14_20_08-Metal LAF initial menu display" src="https://user-images.githubusercontent.com/80066129/110018505-57fd9380-7cf5-11eb-92bd-b03612a59cf2.png">

**Comment by DevCharly** [comment]
This is a feature.
Mnemonics are hidden by default and shown when the `Alt` key is pressed.
Windows L&F does the same.

To make mnemonics always visible use:
~~~java
UIManager.put( "Component.hideMnemonics", false );
~~~

See https://www.formdev.com/flatlaf/customizing/#show_mnemonics

**Comment by mpl1031** [comment]
Thanks, this works fine.  I must have missed it on your “Customizing” page or it was added since I looked.  Thanks for your quick response.

**Comment by rogerbj** [comment]
@DevCharly is it possible to completely disable mnemonics with the ALT button?

**Comment by DevCharly** [comment]
FlatLaf does only the painting of the mnemonics.

The menu activation is handled by Swing, which registers keystrokes in
`javax.swing.plaf.basic.BasicMenuUI.updateMnemonicBinding()`.
Don't think that it possible to avoid this.

You could avoid setting mnemonic on top-level JMenus. But then other users may be missing this feature...

When I assign `Alt+E` to "File > Open" action (in source code) in FlatLaf Demo, then pressing `Alt+E` always shows the "Edit" menu. Same behavior in Metal, Nimbus and Windows Laf.

When I do the same in DbVisualizer 12.0.3 (in "Tool Properties > Key Bindings"), then pressing `Alt+E` shows the "Open" dialog.
But when I restart DbVisualizer and press `Alt+E`, the "Edit" menu is shown...

Don't know how or where your custom key bindings are registered (to Swing), but it seems that the order of registration makes a difference. Maybe you first register the custom key bindings and then create the menu bar.

I think the trick is to make sure that Swing first looks into your custom key bindings.
