### ISSUE TITLE
flatlaf.uiScale issues

### ISSUE THREAD

**Issue by SchiopuMatei** [JFormDesigner/FlatLaf#266]
Hello, 

we're trying to use FlatLAF to downscale the UI elements in our app, but anything below 100%, like 75%, 50%, etc. doesn't seem to do anything. Upscaling 150%, 200%, 300% works perfectly though. Any ideas? Is minimum element size stopping them from changing?

Thanks, Matthew.

**Comment by DevCharly** [comment]
Following lines prevent down-scaling:

https://github.com/JFormDesigner/FlatLaf/blob/e5a116a0d4ac1a648c3da4c992375b85e5f70fab/flatlaf-core/src/main/java/com/formdev/flatlaf/util/UIScale.java#L326-L327

Removed the two lines and tried the FlatLaf Demo with 75%:

![image](https://user-images.githubusercontent.com/5604048/110622291-91258000-819b-11eb-8a4a-eb7003be1166.png)

And 50%:

![image](https://user-images.githubusercontent.com/5604048/110622321-9d114200-819b-11eb-8dde-de8eee3929a1.png)

While text is still readable at 75%, it is unreadable at 50%.

I wonder what's the use case for down scaling?

**Comment by DevCharly** [comment]
Merged your PR and made some more changes:
- allow scale factors less than 100% for system property `flatlaf.uiScale`
- no longer round scale factor of system property `flatlaf.uiScale` to 1/4
- renamed system property `flatlaf.uiDowncale.enabled` to `flatlaf.uiScale.allowScaleDown`
- round smaller scale factors to 1/10
- absolute minimum user scale factor is now 0.1

Setting system property `flatlaf.uiScale.allowScaleDown` to `true` is only necessary if the scale factor is computed from the font size. E.g. using `UIManager.put( "defaultFont", new Font( "Dialog", Font.PLAIN, 5 ) );`.

If you use `flatlaf.uiScale`, then`flatlaf.uiScale.allowScaleDown` is not necessary.
