### ISSUE TITLE
JPopupMenu lose focus when its bounds outside of window

### ISSUE THREAD

**Issue by weimsh** [JFormDesigner/FlatLaf#273]
Hi author,
  I have a question about JPopupMenu focus, that is when I show it inside of window(or Frame), its children components can request focus in window(in snapshot #1), but when it is showing outside of window(or Frame), its children components cannot request focus any more(in snapshot #2).
  Can you give some suggestions?
  [
![1](https://user-images.githubusercontent.com/8486742/111939129-67a71580-8b06-11eb-9f54-e50b1e9ab24d.png)
](url)
[
![2](https://user-images.githubusercontent.com/8486742/111939150-71c91400-8b06-11eb-9914-6f3e1f7b8a3c.png)
](url)

**Comment by DevCharly** [comment]
Thanks for reporting.

Is it just the missing blue focus border?
Or is it not possible to enter text in the popup?

Tried this with a simple form in a `JPopupMenu`. 
In my case the blue border is missing, but it is possible to enter text.

**Comment by weimsh** [comment]
Yes, only the blue border of texdfield is missing, the table, the table cells are also missing too.

the control of all the components are ok!

**Comment by DevCharly** [comment]
Fixed in main branch.

Please try the latest 1.2-SNAPSHOT and let me know whether it now works:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by weimsh** [comment]
It indeed works, the textfield's focus border, the table's focus border and its row selection are ok now!
Thank you!
[
![1](https://user-images.githubusercontent.com/8486742/112328764-96351400-8cf1-11eb-9ee1-821c6b33703b.png)
](url)
[
![3](https://user-images.githubusercontent.com/8486742/112328803-9d5c2200-8cf1-11eb-9257-f143edaff742.png)
](url)

**Comment by DevCharly** [comment]
Great 😃
