### ISSUE TITLE
Windows with Decorations: Double Titlebar when Re-Opening JFrame Instance

### ISSUE THREAD

**Issue by PicoMitchell** [JFormDesigner/FlatLaf#277]
I have just updated to FlatLaf 1.1 and have noticed an issue with a loading window that I use. It is a JFrame which gets instantiated once and then is disposed and setVisible multiple times throughout running the app.

The first time this loading windows opens, everything looks fine. But, when this window is disposed and then re-opened, it gets 2 titlebars. One appears to be the undecorated titlebar, and the other is the FlatLaf decorated titlebar.

Screenshot attached. Please let me know if there is any other info or testing you need from me. If it turns out to not be easy to reproduce, maybe there is something else weird I am doing that I can try to investigate further.

<img width="330" alt="Screen Shot 2021-03-22 at 11 39 42 AM" src="https://user-images.githubusercontent.com/7358089/112041590-cd45d280-8b03-11eb-87ab-acc204189d85.png">

**Comment by DevCharly** [comment]
Interesting... will try to reproduce.

Do you use `setUndecorated(...)` or `getRootPane().setWindowDecorationStyle(...)` on that window?

**Comment by PicoMitchell** [comment]
Is there anyway to disable Decorations for just this window with the new Decorations setup until this bug has been fixed?

**Comment by PicoMitchell** [comment]
> Interesting... will try to reproduce.
> 
> Do you use `setUndecorated(...)` or `getRootPane().setWindowDecorationStyle(...)` on that window?

Nope, I don't use either of those on this windows.

**Comment by DevCharly** [comment]
> Is there anyway to disable Decorations for just this window...

No, but this is a good idea 👍 

Can reproduce the issue. Working on a fix...

Will release FlatLaf 1.1.1 in a few days.

**Comment by PicoMitchell** [comment]
Great, glad it was easy to reproduce! Thanks so much for your super fast response on this!

**Comment by DevCharly** [comment]
> Great, glad it was easy to reproduce!

Yes, it was easy 😉 
~~~java
window.dispose();
window.setVisible( true );
~~~

Fixed in main branch.

Please try the latest 1.2-SNAPSHOT and let me know whether it now works:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by PicoMitchell** [comment]
> Please try the latest 1.2-SNAPSHOT and let me know whether it now works:
> https://github.com/JFormDesigner/FlatLaf#snapshots

All appears to be working correctly and looking great with Decorated titlebars in Windows with the latest Snapshot (flatlaf-1.2-20210323.141150-4.jar).

Thank you!
