### ISSUE TITLE
Question: customizing JTabbedPane

### ISSUE THREAD

**Issue by j-dimension** [JFormDesigner/FlatLaf#28]
I have a question on customizing JTabbedPane. Can I customize the selectedBackground?

I am using FlatIntelliJLaf and do the following:

```
FlatIntelliJLaf.install();
UIManager.put("TabbedPane.selectedBackground", Color.BLUE);

// UI initialization here
```

This does not seem to have any effect. I see that the property is actually respected: 
https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java

However, no luck. Am I doing something wrong?

**Comment by DevCharly** [comment]
Hi Jens,

I've added `TabbedPane.selectedBackground` a few days ago and it is not in FlatLaf 0.21.
You have to wait for 0.22 (coming the next days) or build it yourself with Gradle.

BTW here is another interesting commit for you: https://github.com/JFormDesigner/FlatLaf/commit/8450e74832b12b5f4880e77d4a8124aa1df309e1 (also coming in 0.22)

**Comment by j-dimension** [comment]
Karl, this is great news! Thank you so much!
I also LOVE the separators feature :-)

**Comment by DevCharly** [comment]
😄 

FlatLaf 0.22 is now available

**Comment by j-dimension** [comment]
Woohoo! Gonna try it tonight!

**Comment by j-dimension** [comment]
Works like a charm, thank you so much!

I sent you an email earlier this week. I know it is not nearly an appropriate appreciation for what you're doing here, but I'd love to give something back. 
(from an Open Source project to another Open Source project)
