### ISSUE TITLE
'@buttonDisabledArrowColor' not found

### ISSUE THREAD

**Issue by tferr** [JFormDesigner/FlatLaf#280]
We are getting this exception on MacOS and ubuntu:
SEVERE: FlatLaf: Failed to initialize look and feel 'com.formdev.flatlaf.FlatLightLaf'.
java.lang.IllegalArgumentException: variable or property '@buttonDisabledArrowColor' not found
	at com.formdev.flatlaf.UIDefaultsLoader.resolveValue(UIDefaultsLoader.java:233)
	at com.formdev.flatlaf.UIDefaultsLoader.loadDefaultsFromProperties(UIDefaultsLoader.java:197)
	at com.formdev.flatlaf.UIDefaultsLoader.loadDefaultsFromProperties(UIDefaultsLoader.java:83)
	at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:391)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at com.formdev.flatlaf.FlatLaf.install(FlatLaf.java:96)
	at com.formdev.flatlaf.FlatLightLaf.install(FlatLightLaf.java:30)

**Comment by DevCharly** [comment]
Hmm, very strange...
Works for me.

> We are getting this exception on MacOS and ubuntu:

And it works on Windows?

`@buttonDisabledArrowColor` is defined here:
https://github.com/JFormDesigner/FlatLaf/blob/14fc652f4bfd939b0e892d2b0c33b43595e941f4/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties#L53

It was introduced in FlatLaf 1.0-rc1.
Do you maintain a copy of that file from an older FlatLaf version?

**Comment by tferr** [comment]
Thanks for the speedy reply and the hint. You are right, it is an old FlatLaf in the classpath that gets picked up. There is another [Fiji](https://fiji.sc/) component that is shipping an outdated FlatLaf jar. Usually our update mechanism replaces outdated dependencies, but somehow that logic fails in this case. I will follow-up on that on our end.

Also, sincere thank you for working on these themes.  Our GUI is entirely swing-based and it has been nightmarish to have a functional GUI in linux that scales reliably on hiDPI screens (at least with Java 8, that remains our default). FlatLaf is working great. And also thanks for mavenizing jide-oss. We were stuck for years with a really outdated version. There are thousands of scientists using Fiji daily, so this has a huge impact!
