### ISSUE TITLE
Broken maximizing the window

### ISSUE THREAD

**Issue by dinix2008** [JFormDesigner/FlatLaf#283]
Hello, @DevCharly.
In version 1.1, the behavior of the code broke
```
frame.setExtendedState (JFrame.MAXIMIZED_BOTH)
```
The error is reproduced in Windows 10, in MacOS and Linux everything is fine. If you set the parameters in Windows 10
```
-Dflatlaf.menuBarEmbedded=false
-Dflatlaf.useWindowDecorations=false
```
then everything is fine too.

**Comment by DevCharly** [comment]
Strange. Does the maximize button the window title bar work?
What Java version do you use?

**Comment by dinix2008** [comment]
@DevCharly
>Does the maximize button the window title bar work

work perfectly

>What Java version do you use

Liberica JDK 

```
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.8+10-LTS, mixed mode)
```

**Comment by DevCharly** [comment]
Thx, will try Liberica JDK...

Strange that your code does not work, but maximize button works because code is nearly identical:
~~~java
frame.setExtendedState( frame.getExtendedState() | Frame.MAXIMIZED_BOTH );
~~~

See:

https://github.com/JFormDesigner/FlatLaf/blob/de6e5bd800e340bfe35163553ec3b0c02039b281/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L566

**Comment by dinix2008** [comment]
in my case i call
```
frame.setExtendedState (JFrame.MAXIMIZED_BOTH)
```
before the call
```
frame.setVisible(true)
```

those window is not visible yet

**Comment by dinix2008** [comment]
@DevCharly, if the code `frame.setVisible(true)` is called when the window is already visible, then everything is ok

```
Utils.invokeWhenShowing(frame, () -> {
     frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
});
```

**Comment by DevCharly** [comment]
Fixed in main branch.

Please try the latest 1.2-SNAPSHOT and let me know whether it now works:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by dinix2008** [comment]
@DevCharly, old behavior restored. Thanx.
