### ISSUE TITLE
Broken window icon change

### ISSUE THREAD

**Issue by dinix2008** [JFormDesigner/FlatLaf#284]
Hello, @DevCharly.
In version 1.1, the behavior of the code broke
```
frame.setIconImage(icon)
```
The window icon does not appear
![image](https://user-images.githubusercontent.com/1597289/112330613-3fb3df80-8cc9-11eb-9e37-6b86de59d499.png)
The error is reproduced in Windows 10 by default. If you set the parameters

```
-Dflatlaf.menuBarEmbedded=false
-Dflatlaf.useWindowDecorations=false
```
then there is no error

**Comment by DevCharly** [comment]
Can't yet reproduce this...

Does this work in FlatLaf 1.0 with `-Dflatlaf.useWindowDecorations=true` ?

**Comment by DevCharly** [comment]
Can now reproduce it. Similar to #283 if `frame.pack()` is not invoked the icon is not shown....

**Comment by DevCharly** [comment]
Unfortunately I can **not** reproduce this.

Could you help and debug a little bit?

A good starting point would be where the image from the frame is converted into a icon:
https://github.com/JFormDesigner/FlatLaf/blob/c24ce7c5bcf6ebb2ffae9139f4cb1323fa54279d/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L346

Or directly in the icon painting method:
https://github.com/JFormDesigner/FlatLaf/blob/c24ce7c5bcf6ebb2ffae9139f4cb1323fa54279d/flatlaf-core/src/main/java/com/formdev/flatlaf/util/ScaledImageIcon.java#L80

**Comment by dinix2008** [comment]
@DevCharly, I'm sorry, the problem with `frame.setIconImage(icon)` was in our code. Therefore, this task can be closed.

But I would like to separately (not within the scope of this task) draw attention to the changed behavior of the following code
```
import com.formdev.flatlaf.FlatLightLaf;
import org.jdesktop.swingx.icon.EmptyIcon;

import javax.swing.*;
import javax.swing.plaf.IconUIResource;

public class NoIconInInternalFrame {
    public static void main(String[] args) {
        SwingUtilities.invokeLater( () -> {
            FlatLightLaf.install();
            
            // !!!!!
            UIManager.put("InternalFrame.icon", new IconUIResource(new EmptyIcon(16, 16)));
            // !!!!!

            JFrame frame = new JFrame( "NoIconInInternalFrame" );
            frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
            frame.setSize(300, 300);
            JDesktopPane desktopPane = new JDesktopPane();
            JInternalFrame internalFrame = new JInternalFrame("test");
            internalFrame.setSize(100, 100);
            internalFrame.setVisible(true);
            desktopPane.add(internalFrame);
            frame.getContentPane().add(desktopPane);
            frame.setVisible( true );
        } );
    }
}
```

FlatLaf 1.0
![image](https://user-images.githubusercontent.com/1597289/112483357-fecfcf80-8d89-11eb-9c47-0022bd6e7efd.png)

FlatLaf 1.1
![image](https://user-images.githubusercontent.com/1597289/112483409-0abb9180-8d8a-11eb-961f-6f4db3463ff9.png)

Is this considered correct behavior now?

**Comment by DevCharly** [comment]
> Is this considered correct behavior now? 

No, this was simply a side effect because FlatLaf custom window decoration used `InternalFrame.icon` also for `JFrame` and `JDialog` window icons. This is the only way to get original Java cup icon.

Anyway found a fix: bf500e46e710b2193f38a7f33d39148073ca7474

Thanks

**Comment by dinix2008** [comment]
@DevCharly, Thanks!

**Comment by dolamasa1** [comment]
is this isue solved yet ?

**Comment by DevCharly** [comment]
@dolamasa1 why are you asking?

**Comment by dolamasa1** [comment]
sorry sir I was using flatlaf and wanted to set an Icon in the application like setting in the frame directly in swing 
but it was my issue to not searching well I fetched out in your last dashboard and I found the solution thank u for your amazing efforts
