### ISSUE TITLE
JInteralFrame minimized icon is not honored (no icon in minimized state)

### ISSUE THREAD

**Issue by sbodmer** [JFormDesigner/FlatLaf#291]
When I minimize a JInternalFrame, the desktop icon is empty (plain gray backgound).
With the default Metal laf the icon is displayed correctly on the bottom left

Flat Laf (light)
![FlatLaf](https://user-images.githubusercontent.com/18146968/112969665-c0e9f700-914d-11eb-80b3-db98fffa55a5.png)

Metal Laf
![MetalLaf](https://user-images.githubusercontent.com/18146968/112969678-c6474180-914d-11eb-9467-fe7a7aaac15a.png)

**Comment by DevCharly** [comment]
Yes, FlatLaf does not display any icon for minimized internal frames.
Instead the content of the internal frame is shown minimized:

![image](https://user-images.githubusercontent.com/5604048/112984467-36aa8e80-915f-11eb-95ea-62fc19f5b18f.png)

Same but not minimized:

![image](https://user-images.githubusercontent.com/5604048/112984458-314d4400-915f-11eb-9dae-d67444529a85.png)

Anyway, the icons should be not completely empty as in your screenshot.

Is there any exception on stdout?
Could you debug into following method?

https://github.com/JFormDesigner/FlatLaf/blob/d13ddeb9446dcbf678042b3f18126317a02975ee/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatDesktopIconUI.java#L239

**Comment by sbodmer** [comment]
Whouhaaa, nicely done for the content snapshot.
Thanks for the pointer, I will debug next week and give you some feedback,

**Comment by sbodmer** [comment]
Found the problem. I have a custom DesktopManager installed, so the FlatLaf one was not used.
I submitted a patch to fix the problem.

**Comment by DevCharly** [comment]
Thanks for the fix. Have merged it.

While working on some improvements for layouting the icons in dock, I had an idea to eliminate the need for `FlatDesktopManager` and `FlatWrapperDesktopManager`, which I've implemented in commits 39bf68a6bdbe804cef12e3a6b4254cfcfe11feed and 2fe5652bc61317d62d1bf3e3b95eb101e29ee5dc. 

So FlatLaf no longer uses a own desktop manager 😄
