### ISSUE TITLE
continuoslayout jplitpane

### ISSUE THREAD

**Issue by dener4321** [JFormDesigner/FlatLaf#301]
Hello

continuouslayout of jsplitpane does not disable when I uncheck the box in the netbeans design.

![Capturar](https://user-images.githubusercontent.com/67351043/113523676-9e0d7780-957f-11eb-8728-b59a4b6570e8.PNG)

As you can see in the image the box is unchecked, in this image I'm testing it with L&F metal and it works, only on the flatlaf that doesn't.

**Comment by DevCharly** [comment]
Thanks, fixed in main branch: https://github.com/JFormDesigner/FlatLaf#snapshots
