### ISSUE TITLE
JComboBox / Spinner controls are very big if component height is higher

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#302]
FlatLaf attempts to keep the height and width of the JComboBox/JSpinner controls in sync. 
The Windows L&F in contrast doesn't do this. In our case, this is a problem since we offer to change the height of specific table rows (it's a tree table and each level can have different sizes, which helps making the table content easier to grasp).

Now there are certain cells where there's for example a datepicker consisting of a date and time component, meaning we have two of these combo-components in one cell. Since they are always keeping their right component parts width and height in sync, this ends up taking a lot of space, meaning the cell isn't usable.

Was this a concious decision or did it just happen to be like this? Personally I prefer the Windows way and would even default to do it that way. While it looks less slightly "clean", it's more useful.

If you need an example, I can do that too, but I hope I explained it good enough :D (Will do it tomorrow then, it's late)

![grafik](https://user-images.githubusercontent.com/19377618/113748564-ed32e400-9708-11eb-890f-bdb041657d71.png)

**Comment by DevCharly** [comment]
Thx. Fixed in main branch.

The width of the arrow button is now the preferred height of the combobox/spinner,
which keeps it square in normal cases.

![image](https://user-images.githubusercontent.com/5604048/113833837-6888aa00-978a-11eb-973a-08c2a20308b7.png)

**Comment by Bios-Marcel** [comment]
Nice, thanks :)
