### ISSUE TITLE
JMenu behavior change in menus, no more default responsive (auto resize) upgrading 0.39 to 0.40

### ISSUE THREAD

**Issue by immobilia** [JFormDesigner/FlatLaf#314]
Hi, I'm trying upgrading from 0.39 to 1.0, 
but I discovered a behavior change with JMenu inside my JMenuBar.

On small screen, with a lot of menus,
- previously (v0.39), JMenu are proportionnaly reduced
- since v0.40,  JMenu aren't more proportionnaly reduced

Screen capture with application large and small width, setted with UIManager.setLookAndFeel(...) :
- SystemLookAndFeelClassName
- FlatLightLaf (version 0.39 and 0.40+)

![image](https://user-images.githubusercontent.com/438549/115628482-fcb54e00-a300-11eb-8202-525a92c7ec22.png)

Compare version 0.39 and 0.40 : https://github.com/JFormDesigner/FlatLaf/compare/0.39...0.40

Is there a way to manualy force the older behavior ?

Setting the minimum size for each menu, the menus are reduced to this size, but no less.
And, if possible, I doesn't want define differents sizes. I want keep 3 size equals (maximumSize, minimumSize, preferredSize), with a auto resize as native behavior.

Thanks in advance for you feed back, and perhaps the solution 🥰 ...

Use case : Java 1.8 on Windows 10

**Comment by DevCharly** [comment]
The reason is that the minimum size of `JMenu` is equal to its preferred size. This is also the case for other Lafs since Java 10.

https://github.com/JFormDesigner/FlatLaf/blob/f58780d36b245fa01b20feb1bffd7cd215e491c2/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuUI.java#L133-L138

> Is there a way to manualy force the older behavior ?

Sure 😉 :

~~~java
for( Component c : menuBar.getComponents() ) {
    if( c instanceof JMenu )
        c.setMinimumSize( new Dimension( 1, 1 ) );
}
~~~

**Comment by immobilia** [comment]
Excellent and complete answer. Thanks Charly.
