### ISSUE TITLE
Double title bar

### ISSUE THREAD

**Issue by Ferdudas97** [JFormDesigner/FlatLaf#315]
When we use  `FlatLaf.setUseNativeWindowDecorations(FlatLaf.supportsNativeWindowDecorations());` , sometimes we got two title bars (one from system and one from FlatLaf).  Also when this error occurs, buttons on title bar don`t work as expected  - no action after click.

The bug occurs in a non-deterministic way, so a test application has been created to reproduce it - [double-title-bar-app.zip](https://github.com/JFormDesigner/FlatLaf/files/6364326/double-title-bar-app.zip)
Gif included from test app
![Animation](https://user-images.githubusercontent.com/26126241/115851919-c8887d00-a427-11eb-9546-82c9275b2b6b.gif)

FlatLaf version: 1.1.2
Java Version: 11
OS:  Windows 10 Pro

```
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;

import javax.swing.*;
import java.awt.*;
import java.lang.reflect.InvocationTargetException;

public class FrameCreator {
   private static int size = 200;

   public static void initLAF() throws UnsupportedLookAndFeelException {
      UIManager.setLookAndFeel(new FlatIntelliJLaf());
      FlatLaf.setUseNativeWindowDecorations(FlatLaf.supportsNativeWindowDecorations());

      UIManager.put("TitlePane.unifiedBackground", true);
   }
   public static void main(String[] args) throws InvocationTargetException, InterruptedException {
      SwingUtilities.invokeAndWait(() -> {
         try {
            initLAF();
         } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
         }
      });
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
      double width = screenSize.getWidth();
      double height = screenSize.getHeight();
         for (int i = 0; i < width / size; i++) {
            for (int j = 0; j < height / size; j++) {
               showFrame(i,j);
            }
      }
   }

   public static void showFrame(int i, int j) {
      SwingUtilities.invokeLater(() -> {
         JFrame frame = new JFrame();
         frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
         frame.setSize(size - 10, size - 10);
         frame.setLocation(i * size + 10, j * size + 10);
         frame.setVisible(true);
      });
   }
}

```

**Comment by DevCharly** [comment]
That's interesting. Never seen this before. Will investigate...

Thanks for the test case. This is a great help 👍 
But could you please replace the animated GIF with a static screenshot? I'm feeling hypnotized :dizzy_face:

**Comment by DevCharly** [comment]
Turns out that subtracting HWNDs in following line is not reliable if key addresses are nearly the same (+/- 2):

https://github.com/JFormDesigner/FlatLaf/blob/8734b062dc1d4c8225e243f43b4a0724b52a6751/flatlaf-natives/flatlaf-natives-windows/src/main/cpp/HWNDMap.cpp#L112

Fixed in commit 9d0823038e20c373aa864a07d383b80af1cbafd6
Please try the latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

CC @ingokegel

**Comment by DevCharly** [comment]
BTW it is not necessary to invoke `FlatLaf.setUseNativeWindowDecorations(FlatLaf.supportsNativeWindowDecorations());` because it is enabled by default.

**Comment by Ferdudas97** [comment]
Thanks for quick fix.

**Comment by ireque** [comment]
@DevCharly 
I confirm that fix works. 
Can you backport it to release version?

**Comment by DevCharly** [comment]
FlatLaf 1.2 is now available. Sorry for the delay...
