### ISSUE TITLE
Component.isBackgroundSet() and similar not respected

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#32]
Hi,

I have a toggle button on which the background and foreground colors are forced, but it paints as if these were not set. It seems the code in Flat*ButtonUI does not get the background from the component even though they were explicitly set.

Am I missing something?

PS: very good work, I am impressed by the quality of FlatLaf!

**Comment by DevCharly** [comment]
Hi Chrriis,

thanks for the complements 😃 

Yes, if the toggle button is selected (or disabled) then the component background and foreground colors are not used. In other states (unselected, hover and pressed) those colors are used.

If you've build FlatLaf locally, you can run [FlatComponentsTest](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatComponentsTest.java) and check the "explicit colors" checkbox try it out:

![image](https://user-images.githubusercontent.com/5604048/72000117-eafe8300-3242-11ea-8582-3a45f1ac3794.png)

So the toggle button should compute reasonable background and foreground colors for the selected state, based on the component colors, right?

Sounds like a good idea 👍

**Comment by Chrriis** [comment]
I wonder what the expected behavior is. I checked with a different look and feel, and unless I am missing something it was ignored there too.

Maybe deriving a reasonable background is not a bad idea. Now, the problem is to define "reasonable" :slightly_smiling_face:

My original problem is that we use toggle buttons in a panel to act as task bar buttons and the difference between selected and not selected was not obvious with FlatLaf, so I tried to force colors. In the original look and feel there is a better contrast by default. While I could change the colors for all buttons of FlatLaf, I only wanted to alter these task bar buttons.

**Comment by DevCharly** [comment]
Implemented in master branch. The selected toggle button background color is now computed at runtime based on the unselected background color.

![image](https://user-images.githubusercontent.com/5604048/79968407-55ed6600-8490-11ea-9d3d-062540b5ce8f.png)

Fixed in FlatLaf 0.32
