### ISSUE TITLE
Best practice for error hints

### ISSUE THREAD

**Issue by SturmB** [JFormDesigner/FlatLaf#320]
This isn't a bug report nor a feature request, it's just a general how-to question.

In the FlatLaf Demo, there are fields that show what an "Error hint" or "Warning hint" looks like. Being still a Java amateur, I have not found any method or such on a JTextField that enables such a border. It looks like I'd have to write a method that manually changes the border of the field, is that correct? Or is there some better way to enable that "error hint" border?

**Comment by Bios-Marcel** [comment]
There are so called `ClientProperties` on each `JComponent`. You can change them via `JComponent#putClientProperty(key, value)`.
The property is called `JComponent.outline` (Flatlaf specific) and can be set to `error`, `warning` or a specific color. Alternatively set it to `null` for the default behaviour.

I found this by looking at the code:

```java
		Object outline = ((JComponent)c).getClientProperty( FlatClientProperties.OUTLINE );
		if( outline instanceof String ) {
			switch( (String) outline ) {
				case FlatClientProperties.OUTLINE_ERROR:
					return isFocused( c ) ? errorFocusedBorderColor : errorBorderColor;

				case FlatClientProperties.OUTLINE_WARNING:
					return isFocused( c ) ? warningFocusedBorderColor : warningBorderColor;
			}
		} else if( outline instanceof Color ) {
			Color color = (Color) outline;
			// use color functions to compute color for unfocused state
			if( !isFocused( c ) && customBorderColor instanceof DerivedColor )
				color = ((DerivedColor)customBorderColor).derive( color );
			return color;
		} else if( outline instanceof Color[] && ((Color[])outline).length >= 2 )
			return ((Color[])outline)[isFocused( c ) ? 0 : 1];
```

@DevCharly I've tried finding it on the website (https://www.formdev.com/flatlaf/customizing/), but couldn't. Maybe this should be documented and if it is, then maybe in a different place ^^

**Comment by gtimbo** [comment]
If you include the "extras" jar, you can use a `FlatTextField` object, which has a `setOutline(Object)` method. 

However, all that method is doing is setting a client property on the component using the `JComponent.putClientProperty(Object, Object)` method. So for any `JTextField` you can simply call `textField.putClientProperty("JComponent.outline", value)`, or better yet, `textField.putClientProperty(FlatClientProperties.OUTLINE, value)` where "value" is a string or Color, or `null`.

Have a look at the documentation for the `FlatClientProperties.OUTLINE` constant for more information on the accepted values.

**Comment by DevCharly** [comment]
Marcel and Tim already explained it in detail. Thanks.

Summary:
~~~java
textField.putClientProperty( "JComponent.outline", "error" );
~~~
or
~~~java
textField.putClientProperty( "JComponent.outline", "warning" );
~~~

Documented here: https://www.formdev.com/flatlaf/client-properties/#JComponent

BTW this works only for FlatLaf. If you also use other look and feels in your app, you need another solution...

**Comment by SturmB** [comment]
You guys are awesome!

I was able to take your suggestions and have come up with the following:

```lang.java
    private boolean fieldValidated(JTextField textField, boolean valid) {
        if (valid) {
            textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE);
            return true;
        }
        textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE_ERROR);
        return false;
    }
```

It's probably not great code, so feel free to correct it to something better.

**Comment by gtimbo** [comment]
> I was able to take your suggestions and have come up with the following:
> 
> ```java
>     private boolean fieldValidated(JTextField textField, boolean valid) {
>         if (valid) {
>             textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE);
>             return true;
>         }
>         textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE_ERROR);
>         return false;
>     }
> ```
> 
> It's probably not great code, so feel free to correct it to something better.

This isn't really a code help forum, but as a quick once-off, here's what I'd do:

```java
private void updateFieldValidity(JTextField textField, boolean valid) {
  textField.putClientProperty(FlatClientProperties.OUTLINE, valid ? null : FlatClientProperties.OUTLINE_ERROR);
}
```

Not sure why you're essentially just returning the `valid` parameter (you already have it calculated to pass it in). Also, passing `FlatClientProperties.OUTLINE` as a value (rather than the key) makes no sense; use `null` to turn off the outline.

**Comment by SturmB** [comment]
Yeah, I'm a Java amateur, sorry. Thank you for the ternary and null suggestions, @gtimbo!
