### ISSUE TITLE
setBackgroundNonSelectionColor in DefaultTreeCellRender not supported

### ISSUE THREAD

**Issue by craigebevil** [JFormDesigner/FlatLaf#322]
We have an existing application that uses setBackgroundNonSelectionColor to highlight various unselected nodes in a JTree. FlatLaf does not appear to be respecting this parameter when set. I attach two screenshots: one showing the behaviour with the Metal LAF and the other with FlatLaf. 

![image](https://user-images.githubusercontent.com/7511780/117952438-14369400-b30d-11eb-948e-dfea9ab14493.png)

![image](https://user-images.githubusercontent.com/7511780/117952510-2284b000-b30d-11eb-9191-05061f3a27d9.png)

**Comment by DevCharly** [comment]
Many thanks for reporting.

Fixed in main branch. Please try the latest snapshot:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by craigebevil** [comment]
Many thanks, Karl - the fix works for me.
