### ISSUE TITLE
JTable: show horizontal Lines not working with JCheckBox CellRenderer

### ISSUE THREAD

**Issue by CodingFuchs** [JFormDesigner/FlatLaf#324]
When launching the FlatLaf Demo 1.1.2 and selecting show horizontal lines for the JTable you can see the lines are not being rendered when the table cell is a checkbox. Is it planned to be fixed in future releases? 
![FlatLafTableCheckBoxBug](https://user-images.githubusercontent.com/84087666/117997927-b83b3200-b343-11eb-8d84-5fe96bdc350d.png)

**Comment by DevCharly** [comment]
> Is it planned to be fixed in future releases?

Yes, already fixed in commit 1c52f1f76ce2444d7529a61c27fea0c3f490df66 for FlatLaf 1.2 (coming soon)

See also #311
