### ISSUE TITLE
Icon location in title bar of maximized window different when using native window decorations

### ISSUE THREAD

**Issue by PikeTec** [JFormDesigner/FlatLaf#326]
When using native window decorations the title bar icon of a maximized window is displayed further to the right than when not using it and the window can't be closed when double clicking in the most top-left pixels. Even with "TitlePane.iconMargins = 0,0,0,0" (which looks horrible in normal size) there is an unclickable area at the top.

FlatLaf 1.1.2 with Amazon Coretto 15.0.2

Disabled
![disabled](https://user-images.githubusercontent.com/13200757/118607966-7a159680-b7b9-11eb-9116-508f7ac64f85.png)

Enabled
![enabled](https://user-images.githubusercontent.com/13200757/118607964-7a159680-b7b9-11eb-9ac1-5d27abf13aec.png)

Enabled with no margin
![margin_000](https://user-images.githubusercontent.com/13200757/118607962-797d0000-b7b9-11eb-94e7-9e96a80f2fea.png)

**Comment by DevCharly** [comment]
Thanks for pointing out this difference. Didn't notice this before.

Commit 35f97368fa51ab81f0ea314b2e0371ea7c15d19f increases the size of the "hit area" for the icon when maximized.
It is now the blue rectangle (in below screenshot) where you can double-click to close the frame:

![image](https://user-images.githubusercontent.com/5604048/118686077-f92fbc80-b803-11eb-8410-11e3726a1cb5.png)

Changing the icon location is not necessary. IMHO it looks better with some space between the left edge and the icon.
