### ISSUE TITLE
Miglayout v11.0: Increasing font size increases component instead of wrapping text on Linux

### ISSUE THREAD

**Issue by stefanoschalkidis** [JFormDesigner/FlatLaf#327]
First of all a big thank you for providing this great library!

In the application I’ve written I’m using Miglayout to pinpoint the dimensions of a component, e.g. panel.add(label, “w 100!, h 24!”). The user can increase the text font size via a parameter in the configuration file. If the user makes the font size too large, the text will wrap with three dots.

### FlatLaf 1.1.2 with Miglayout v5.2
![image_1](https://user-images.githubusercontent.com/9432222/118616225-2d868700-b7ca-11eb-8cfe-7c97f4cb9d35.png)

This behavior seems to have changed when FlatLaf is used with Miglayout v11.0 on Linux (Manjaro), where the components are increased to accommodate the increased font size.

### FlatLaf 1.1.2 with Miglayout v11.0
![image_2](https://user-images.githubusercontent.com/9432222/118616531-75a5a980-b7ca-11eb-9190-fa403d63affe.png)

```
$ java -version 
openjdk 11.0.11 2021-04-20 
OpenJDK Runtime Environment (build 11.0.11+9) 
OpenJDK 64-Bit Server VM (build 11.0.11+9, mixed mode)
```

On Windows 10 the wrapping works using FlatLaf with both Miglayout versions 5.2 and 11.0 respectively. 

```
C:\Users\User>java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

I also tested MetalLookAndFeel and MotifLookAndFeel with Miglayout v11.0 on Linux and the wrapping works, so I suspect the issue may lie with FlatLaf.

Any hint as to what may cause this discrepancy is much appreciated.

Thanks a lot in advance.

**Comment by DevCharly** [comment]
Probably following PR in MigLayout 5.3 and 11.0 causes this:
https://github.com/mikaelgrev/miglayout/pull/76

MigLayout 5.2 used a fixed scale factor of `1`, but since above PR it uses the scale factor that FlatLaf computes based on the font size.
https://github.com/JFormDesigner/FlatLaf/blob/8998371caea610ee8f931f4ad2191fe2913a5fe6/flatlaf-core/src/main/java/com/formdev/flatlaf/FlatLaf.java#L429-L432

To avoid this use:
~~~java
UIManager.put( "laf.scaleFactor", 1 );
~~~

**Comment by stefanoschalkidis** [comment]
Thanks a lot for the clarification. The proposed solution works as intended.
