### ISSUE TITLE
Scroll in FileChooser does not scroll by block

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#33]
In a FileChooser with native look and feel on Windows (my reference), using the scroll bar or the wheel mouse scrolls by block, always with the file names aligned on the left. With FlatLaf, file names can be anywhere which makes it quite hard to find a file in big folders.

**Comment by DevCharly** [comment]
Yes, didn't notice this until now. Thanks.

**Comment by DevCharly** [comment]
fixed in 0.25

(thru commit ef01f2338454b190d92bcded1801c1f4ac558a82; `List.border=0,0,0,0` in `FlatLaf.properties`)
