### ISSUE TITLE
Editable combo box editors do not behave like text fields for mouse clicks

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#330]
Hi all!

I find that editable combo boxes do not feel right compared to text fields. The click on the left or right of the text does not edit the text, as indicated by the cursors:
![TextFieldVsEditableComboBox](https://user-images.githubusercontent.com/1174202/119020858-06cd7980-b99f-11eb-8dc4-f61265e7c71b.png)

I originally noticed this problem in some custom components that recycle the combo box border, but this is also an issue with regular editable combo boxes. When you want to place your caret at the very beginning of the editable text, it is hard and frustrating because it expands the popup instead of editing the text (e.g. try to place your caret before a "I" for example).

Sample code:
```Java
public static void main(String[] args) throws Exception {
	UIManager.setLookAndFeel(new FlatLightLaf());
	JFrame frame = new JFrame();
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	JPanel centerPane = new JPanel(new GridBagLayout());
	centerPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
	centerPane.add(new JTextField("Sample text field", 14), new GridBagConstraints(0, 0, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(0, 0, 0, 0), 0, 0));
	JComboBox<String> combo = new JComboBox<>(new String[] {"Item 1", "Item 2", "Item 3"});
	combo.setEditable(true);
	centerPane.add(combo, new GridBagConstraints(0, 1, 1, 1, 0, 0, GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(10, 0, 0, 0), 0, 0));
	frame.getContentPane().add(centerPane);
	frame.setSize(300, 200);
	frame.setVisible(true);
}
```

**Comment by DevCharly** [comment]
Thanks. I agree with you. That do not feel right.

Is also the case for `JSpinner`.
Will rework it...

**Comment by DevCharly** [comment]
@Chrriis have reworked internals of combo box and spinner UI delegates.
The internal text field now occupies the whole area within the border.
For not editable combo box, the renderer uses the whole area within the border.

Before:
![image](https://user-images.githubusercontent.com/5604048/124507720-b4211300-ddce-11eb-8ca7-940c56b22dc7.png) ![image](https://user-images.githubusercontent.com/5604048/124507730-b71c0380-ddce-11eb-8e93-4df90b0e2cf0.png)

After:
![image](https://user-images.githubusercontent.com/5604048/124507749-c56a1f80-ddce-11eb-85ed-ef1f7307b5d9.png) ![image](https://user-images.githubusercontent.com/5604048/124507758-c7cc7980-ddce-11eb-81ee-336a1f1dfea4.png)

This affects editors with custom borders (#102) and custom renderers.

Before:
![image](https://user-images.githubusercontent.com/5604048/124508461-47a71380-ddd0-11eb-9342-f76e74178d0c.png)

After:
![image](https://user-images.githubusercontent.com/5604048/124508471-4c6bc780-ddd0-11eb-8599-b57fb093a200.png)

**Comment by Chrriis** [comment]
I gave it a try, and everything seems to work as expected, even in some awful compositing cases! Thanks! 👍
