### ISSUE TITLE
Multi-line Tooltip positioning

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#333]
Hi all!

We have multiline tooltips that can be huge.
In our windows L&F implementation, we have a multi-line implementation of BasicToolTipUI and we rely on the Look & Feel to place the tooltip. The tooltip can occupy a certain amount of space, sometimes even appearing under the mouse, but the beginning of the tooltip is always on screen.
When switching to FlatLaf, it seems to always place such huge tooltip above:
![MultiLineTooltips](https://user-images.githubusercontent.com/1174202/120185517-97fbe600-c212-11eb-99da-4b870765b7dc.png)

I think the strategy should be reviewed to always show the beginning of the tooltip (essentially forcing the x and y positions to 0 when they become negative). Having the bottom of the tooltip is useless (main information is generally first in tooltip).

Sample test case:
```Java
public static void main(String[] args) throws Exception {
	UIManager.setLookAndFeel(new FlatLightLaf());
	JFrame frame = new JFrame();
	frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	JPanel centerPane = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
	centerPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
	JLabel label = new JLabel("A label with a tooltip");
	StringBuilder tooltipSB = new StringBuilder();
	for(int i=0; i<100; i++) {
		if(i > 0) {
			tooltipSB.append('\n');
		}
		tooltipSB.append("Tooltip line ").append(i + 1);
	}
	label.setToolTipText(tooltipSB.toString());
	centerPane.add(label);
	frame.getContentPane().add(centerPane);
	frame.setSize(400, 300);
	frame.setLocationByPlatform(true);
	frame.setVisible(true);
}
```

**Comment by DevCharly** [comment]
Yes, that is not optimal...
Will rework it...

BTW I love those short code snippets to reproduce issues.
This makes it much easier to reproduce problems 👍 👍 👍

**Comment by Tyluur** [comment]
> Yes, that is not optimal...
> Will rework it...
> 
> BTW I love those short code snippets to reproduce issues.
> This makes it much easier to reproduce problems 👍 👍 👍

As do I. +1

**Comment by DevCharly** [comment]
fixed in main branch
