### ISSUE TITLE
Suggest using StackWalker in Java 9 rather than getStackTrace() for performance

### ISSUE THREAD

**Issue by gtimbo** [JFormDesigner/FlatLaf#334]
Java 9 includes the `java.lang.StackWalker` API for retrieving information about the stack. It can be much more efficient in walking the stack than the existing `Thread.getStackTrace()` method.

I noticed that you're using the stack to find where a method was invoked from in a few places (`FlatTableUI` and 'FlatPopupFactory`) and thought it might be helpful to switch to the new way when using Java 9.

Here's a decent page with some performance benchmarks: https://www.sitepoint.com/deep-dive-into-java-9s-stack-walking-api/

**Comment by DevCharly** [comment]
Thanks for the suggestion. 
Now implemented in main branch.
Please try latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots
