### ISSUE TITLE
Exposing BasicTableHeaderUI#getRolloverColumn

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#336]
Hey,

When writing a custom renderer, it can be quite useful to know the rollover column in order to paint hover states. Now when making custom renderers, you have three options to achieve this:

1. Use reflection (Won't work soon, due to the reflection access changes in newer java versions)
2. GetMousePosition() + looking up cell at point  (Slow)
3. AddMouseListener on TableHeader and looking up the cell at the last know mouse coordiante (Messy)

However, I think it would be very nice to be able to simply access the TableHeaderUI.
Since the method is protected, FlatLaf could override it and incrase the visibility.

Would you be willing to accept that change?

**Comment by DevCharly** [comment]
Apologies for the late response.
I've added a public method `FlatTableHeaderUI.getRolloverColumn()`.

**Comment by Bios-Marcel** [comment]
No need to say sorry.

Thanks for adding this :)
