### ISSUE TITLE
[Question] Does FlatLaf Support CSS Styling in any way?

### ISSUE THREAD

**Issue by orange451** [JFormDesigner/FlatLaf#340]
I am trying to develop an OpenGL application within Java, and need to pick a UI solution. I spent a lot of time in the past working on my own UI solution that supported some basic CSS styling. I was wondering if FlatLaf supports anything like this? I fear my solution is too slow for large applications, so I want to try other libraries.

**Comment by DevCharly** [comment]
There is some initial work going on in PR #341 to support CSS styling on components (using client properties), but this does not allow using a CSS file.

If you're looking for a way to "style" all components, you can do this in FlatLaf properties files:

- https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties
- https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties
- https://www.formdev.com/flatlaf/properties-files/
- https://www.formdev.com/flatlaf/how-to-customize/
