### ISSUE TITLE
[Question] Is it possible to use Flat Light in a main JFrame and use Flat Dark for auxiliary JFrames

### ISSUE THREAD

**Issue by Fabricio31** [JFormDesigner/FlatLaf#345]
![image](https://user-images.githubusercontent.com/82278710/123343983-7db6de80-d518-11eb-9589-1752329bfa09.png)
![image](https://user-images.githubusercontent.com/82278710/123344058-ad65e680-d518-11eb-983c-7c57f47c07dd.png)

**Comment by DevCharly** [comment]
Actually no, but you could try following:

~~~java
EventQueue.invokeLater( () -> {
    FlatDarkLaf.setup();
    // create frames that should be dark

    FlatLightLaf.setup();
    // create frames that should be light
} );
~~~

No guarantee that this works.
