### ISSUE TITLE
Tree element background in 1.3 version

### ISSUE THREAD

**Issue by psembass** [JFormDesigner/FlatLaf#347]
Background color for tree elements changed in Dark theme in 1.3 version
Version 1.1.2
![image](https://user-images.githubusercontent.com/18038056/124602045-24807080-de71-11eb-9e8a-6e021dc15c16.png)
Version 1.3
![image](https://user-images.githubusercontent.com/18038056/124602110-3235f600-de71-11eb-9aba-a7524f95517f.png)

**Comment by DevCharly** [comment]
There is only one change in `FlatTreeUI` from 1.1.2 to 1.3 to fix #322

You probably invoke `DefaultTreeCellRenderer.setBackgroundNonSelectionColor( Color )`,
which was ignored in 1.1.2, but is used in 1.3.
Either do not invoke this method or pass `null` as parameter.
