### ISSUE TITLE
Derived JPanel components were set to transparent in FlatOptionPaneUI

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#349]
I'm using a JIDE component LabeledTextField in an option pane. It is extended from JPanel. And it was set to transparent when showing up. Is it possible to not change the opaque for those types of components? Thanks.

**Comment by DevCharly** [comment]
Thanks for reporting. Fixed in main branch.

If you want try a snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by tristanzhou** [comment]
Great.
