### ISSUE TITLE
UI artefact at bottom right corner of scrollpane

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#35]
Hi,

I noticed a visual glitch when a component in a scrollpane is focused: the bottom corner at the intersection of the 2 scroll bars has an additional edge. Note that it is more or less visible depending on the theme you are using.

Here is a screenshot:
![BottomRightScrollArtefact](https://user-images.githubusercontent.com/1174202/72068461-6749a280-32e5-11ea-8610-f58ec6dd26e8.png)

**Comment by DevCharly** [comment]
Is this from a HiDPI screen?

**Comment by Chrriis** [comment]
I wish I had a HiDPI screen! 😄

**Comment by Chrriis** [comment]
The artefact is the inner focus that gets painted in the scroll pane (0.5 is the default in the above). It is only visible in the bottom right corner because the other sides get painted over by the view and the 2 scroll bars.

If you try with a bigger inner focus width:
```Java
	public static void main(String[] args) throws Exception {
		UIManager.setLookAndFeel(new FlatLightLaf());
		UIManager.getDefaults().put("Component.innerFocusWidth", 2);
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		JPanel centerPane = new JPanel(new BorderLayout());
		centerPane.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
		JScrollPane scrollPane = new JScrollPane(new JTextArea(50, 80) {
			@Override
			public boolean hasFocus() {
				return true;
			}
		});
		centerPane.add(scrollPane);
		frame.getContentPane().add(centerPane);
		frame.setSize(400, 300);
		frame.setVisible(true);
	}
```

... you then clearly see it:
![ScrollPaneInnerWidthFocus](https://user-images.githubusercontent.com/1174202/72326612-c4f83900-36af-11ea-9620-17ede3bf12b7.png)

I think scroll panes should not paint the inner focus.

**Comment by DevCharly** [comment]
Many thanks.

The fix is now in master branch.

**Comment by Chrriis** [comment]
Thanks a lot, it works as advertised! 🙂
