### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by Abu-Abdullah** [JFormDesigner/FlatLaf#350]
Hi,

i have an issue of having 'JOptionPane.showOptionDialog' RTL when the parentComponent is JInternalFrame/JDesktopPane, it is still displayed LTR. 

just to mentioned it is working correctly using the metal or any internal LnF

**Comment by DevCharly** [comment]
And it works if the parent of another type?

Could you post a screenshot?

I can not reproduce it...

**Comment by Abu-Abdullah** [comment]
please find:
FlatLaf
![Capture](https://user-images.githubusercontent.com/2059463/124803926-c20b9b00-df6a-11eb-8d14-d2d801ef640d.PNG)

Metal
![Capture1](https://user-images.githubusercontent.com/2059463/124803939-c768e580-df6a-11eb-9480-917584b1ab8d.PNG)

JOptionPane seems to work fine when parent is JFrame. I'm still checking the case.

**Comment by Abu-Abdullah** [comment]
sorry, the Text Area inside the JOptionPane has the issue

**Comment by DevCharly** [comment]
The first and last lines are right aligned. So it seems that the dialog/textarea width is too small and the text is wrapped...

**Comment by Abu-Abdullah** [comment]
you are right, but how can we make the wrapped text RTL

**Comment by DevCharly** [comment]
> how can we make the wrapped text RTL

Good question. I don't know...

Can you please give me some details on how you pass the text to the option pane.
Is it a single string? And does it contain line separators?
Or is it a special `JTextArea` or any other custom component?

**Comment by Abu-Abdullah** [comment]
yes, im using in the message System.lineSeparator() to seperate the lines. no special components

**Comment by DevCharly** [comment]
The option pane has the ability to wrap longer lines.
This is disabled in most/all LaFs.
But in FlatLaf it is enabled and wraps at 80 characters per line.
Maybe this causes the problem.

Please try adding following to disable wrapping (after setting FlatLaf):
~~~java
UIManager.put( "OptionPane.maxCharactersPerLine", 0 );
~~~

**Comment by Abu-Abdullah** [comment]
thank you, this solved it

**Comment by DevCharly** [comment]
It turned out that this is a bug in `JOptionPane`. When wrapping longer text the option pane creates a label for each line and puts those labels into a vertical `Box` that uses `BoxLayout.Y_AXIS`. This aligns the labels always to the left. If option pane would use `BoxLayout.PAGE_AXIS`, then the labels would be aligned to the right in RTL or to the left in LTR.

Anyway, I've implemented a fix in FlatLaf.
