### ISSUE TITLE
JFrame cannot be resized narrower than the width required to accommodate its title

### ISSUE THREAD

**Issue by johnmgithub** [JFormDesigner/FlatLaf#351]
A width-resizeable JFrame cannot be resized narrower than the width required to accommodate its title (flatlaf-1.3).

**Comment by DevCharly** [comment]
Hmm, I can make the FlatLaf Demo very small (on Windows 10):

![image](https://user-images.githubusercontent.com/5604048/124929028-760b3580-e000-11eb-84fa-5591c613b2a0.png)

Can you give us more details?
Screenshot?

**Comment by johnmgithub** [comment]
I was just trying it out, here is the narrowest one of my components gets with FlatLAF:

![image](https://user-images.githubusercontent.com/7894110/124930628-676d5000-dff9-11eb-89f3-1fa5afe57c1a.png)

Here is the narrowest it gets when using Nimbus as the underlying LAF:

![image](https://user-images.githubusercontent.com/7894110/124930785-8835a580-dff9-11eb-8204-8079b15bd609.png)

I'm speculating the title is the problem since the width happens to be just right to accommodate the title. The panel within the frame uses TableLayout but the frame uses BorderLayout with the panel added at CENTRE.

**Comment by DevCharly** [comment]
I see! 

So you have some code in your app that prevents resizing window smaller than preferred (or minimum) size of components, right?

And because the window title in FlatLaf is also implemented in Swing, and has some preferred/minimum size, it prevents smaller window width.

**Comment by johnmgithub** [comment]
Sort of. getMinimumSize is overridden for the panel within the frame based on component sizes in the panel, but not for the frame itself. The minimum for the frame is set based on using frame.pack().  I think the problem is that frame.pack() is adjusting the frame's size to accommodate its own title rather than to accommodate the components within it. I'm not sure that really respects the contract for pack(), since I wouldn't have said a frame's title constitutes a subcomponent:

```
    /**
     * Causes this Window to be sized to fit the preferred size
     * and layouts of its subcomponents. The resulting width and
     * height of the window are automatically enlarged if either
     * of dimensions is less than the minimum size as specified
     * by the previous call to the {@code setMinimumSize} method.
     * <p>
     * If the window and/or its owner are not displayable yet,
     * both of them are made displayable before calculating
     * the preferred size. The Window is validated after its
     * size is being calculated.
     *
     * @see Component#isDisplayable
     * @see #setMinimumSize
     */
    public void pack() 

```

**Comment by DevCharly** [comment]
Should be fixed in main branch.
Please try latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by johnmgithub** [comment]
That fixed it, thanks!
