### ISSUE TITLE
JOptionPane title not fully shown with version 1.4

### ISSUE THREAD

**Issue by clausnagel** [JFormDesigner/FlatLaf#354]
After upgrading to FlatLaf 1.4, the title of a JOptionPane is not not fully shown anymore in case it is longer than the actual message. 

![image](https://user-images.githubusercontent.com/5517439/125832232-69d59c3e-ef85-469d-bc62-910a77092b70.png)

When switching back to 1.3, all is fine again. Maybe related to the changes introduced with #351? Is there a setting to influence the behaviour?

**Comment by SunilBohara** [comment]
I think you can write <html> tags for example <br>

**Comment by DevCharly** [comment]
> Maybe related to the changes introduced with #351?

Yes.
It was a bug that the window title did make the dialog wider if FlatLaf native window decorations are used on Windows 10.

On other platforms (macOS, Linux) or on Windows without FlatLaf native window decorations,
a long window title does not make the dialog wider.

> Is there a setting to influence the behaviour?

There is no setting to restore the old behaviour, but you can change the minimum size of the option pane. E.g.

```java
UIManager.put( "OptionPane.minimumSize", new Dimension( 500, 100 ) );
```

Anyway, if the window title text is important and should be not cut off, it is probably better to put it into the dialog..
