### ISSUE TITLE
Enhancement: Buttons for SwingX JXSearchField

### ISSUE THREAD

**Issue by mwithake** [JFormDesigner/FlatLaf#359]
Buttons in SwingX JXSearchField are not compatible especially for the dark themes.

**Comment by DevCharly** [comment]
Thanks for the hint.
Next FlatLaf version has new icons for `JXSearchField`:

![image](https://user-images.githubusercontent.com/5604048/128047309-8d82e31d-2227-4a17-8062-6dc9d636007d.png) ![image](https://user-images.githubusercontent.com/5604048/128047333-619734f5-0176-4eac-9c71-c5efad8253bb.png)
