### ISSUE TITLE
Restrict resizing Inner Frames to the available area

### ISSUE THREAD

**Issue by lukeu** [JFormDesigner/FlatLaf#362]
When resizing an inner frame of a `JDesktopPane`, Metal and Windows L&Fs both restrict the resize operation (whilst dragging) to avoid resizing it out of the available area.

In contrast, FlatLaF allows the inner window to be resized outside of the visible area, potentially making the title and resize controls inaccessible, such that the user cannot bring the inner frame back into full view.

The 3 L&Fs can be tested using this simple example:

    import java.awt.BorderLayout;
    import javax.swing.*;
    import com.formdev.flatlaf.FlatLightLaf;

    public class TestFrames {
    
        public static void main(String[] args) {
            SwingUtilities.invokeLater(() -> new TestFrames().show());
        }
    
        private void show() {
    //        FlatLightLaf.setup();
    
    //        try {
    //            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName().toString());
    //        } catch (Exception e) {
    //            throw new RuntimeException(e);
    //        }
    
            var desktop = new JDesktopPane();
            desktop.setVisible(true);
    
            var frame = new JInternalFrame("frame", true, true, true, true);
            frame.setSize(400,300);
            frame.setVisible(true);
            frame.setResizable(true);
            desktop.add(frame);
    
            var window = new JFrame();
            window.setSize(800, 600);
            window.add(new JToolBar() {{ add(new JMenuItem("Boo")); }}, BorderLayout.NORTH);
            window.add(desktop);
            window.setLocationRelativeTo(null);
            window.setVisible(true);
        }
    }

**Comment by DevCharly** [comment]
Thanks, fixed in main branch.

A snapshot is available here: https://github.com/JFormDesigner/FlatLaf#snapshots
