### ISSUE TITLE
FlatDarkLaf JButton ignores setMargin()

### ISSUE THREAD

**Issue by jjazzboss** [JFormDesigner/FlatLaf#364]
I use FlatDarkLaf on my Netbeans application, thanks for this great L&F, it works very well in general :-)

For some specific dialogs I need "small" OK JButtons. The default left/right margins around the text are too large in this case, and I'd like to change them. 

myButton.setMargin() works when using the system L&F, but is ignored when using FlatDarkLaf.   

I found the FlatLaf properties "Button.margin", I tried setting myButton.putClientProperty("Button.margin", new Insets(...)) but it is ignored as well.

What could I do ? 

Thanks

**Comment by Bios-Marcel** [comment]
`setMargin` isn't being ignored:

![image](https://user-images.githubusercontent.com/19377618/127613898-565cf3c6-dee3-4011-ba0f-7a46f5d46458.png)

But there's two components to the spacing. One is the `margin` and one is the `insets`, which afaik come from the border.

**Comment by DevCharly** [comment]
As Marcel sad, margins are not ignored, but your problem is that buttons in FlatLaf have a minimum width of 72px.
You can disable minimum width for a single button:

~~~java
myButton.putClientProperty( "JComponent.minimumWidth", 0 );
~~~

Or for the whole application:
~~~java
UIManager.put( "Button.minimumWidth", 0 );
~~~

**Comment by DevCharly** [comment]
This question brings me to the idea to not apply minimum button width if button margins are changed...

**Comment by jjazzboss** [comment]
@DevCharly Thanks for the minimumWidth tip!

**Comment by DevCharly** [comment]
Starting with FlatLaf 1.5, if button (or text component) margins are modified (`JButton.setMargin(...)`),
then the minimum width is no longer applied.
