### ISSUE TITLE
Possibility to customise borders of components, for example, just top and bottom

### ISSUE THREAD

**Issue by davidwinter** [JFormDesigner/FlatLaf#365]
Is it possible to customise components, for example, a JTextField to just have its border on the top and bottom of the component?

**Comment by DevCharly** [comment]
Not out-of-the-box, but you can implement and use own borders:

~~~java
public class MyTextBorder
    extends FlatTextBorder
{
    @Override
    public void paintBorder( Component c, Graphics g, int x, int y, int width, int height ) {
        int lineWidth = UIScale.scale( 1 );
        g.setColor( isFocused( c ) ? Color.red : Color.blue );
        g.fillRect( x, y, width, lineWidth );
        g.fillRect( x, y + height - lineWidth, width, lineWidth );
    }
}
~~~

Enable with:
~~~java
UIManager.put( "TextField.border", new MyTextBorder() );
~~~

What's coming in the near future is support for Windows 11 style borders...

**Comment by davidwinter** [comment]
That's great, thanks @DevCharly for the example code. Is there a way to retrieve the colours of the theme as to match the top/bottom border colours? And also, to target specific components only?

**Comment by DevCharly** [comment]
> Is there a way to retrieve the colours of the theme to match the top/bottom border colours?

Yes, all colors are available as protected fields in class `FlatBorder`, which is the superclass of `FlatTextBorder`.

> And also, to target specific components only?

Sure 😉 

~~~java
myTextField.setBorder( new MyTextBorder() );
~~~

**Comment by davidwinter** [comment]
Many thanks!
