### ISSUE TITLE
Want new IntelliJ Icons

### ISSUE THREAD

**Issue by FlatLaf** [JFormDesigner/FlatLaf#366]
![Screenshot (807)](https://user-images.githubusercontent.com/88301399/127821332-42a4f016-0563-4ce5-b530-a8722be1d8ed.png)

Before some days, Jetbrains provided new shining icons for their products. They're looking very well. Can you include them in FlatLaf?

**Comment by DevCharly** [comment]
Why the hell are you using "FlatLaf" as user name 👎 👎 👎

**Comment by j-dimension** [comment]
I was wondering the same thing. What this person is doing is illegal.

https://www.dpma.de/marken/markenschutz/index.html

"Markenschutz entsteht durch die Eintragung einer angemeldeten Marke in das Register des DPMA. Daneben kann Markenschutz auch durch Verkehrsgeltung infolge intensiver Nutzung eines Zeichens im Geschäftsverkehr oder durch allgemeine Bekanntheit entstehen."

**Comment by DevCharly** [comment]
@FlatLaf I would suggest that you rename your account:
1. open https://github.com/settings/admin
2. click "Change username"

**Comment by DevCharly** [comment]
@DSF-Pro many thanks for renaming your account from "FlatLaf" to "DSF-Pro" 👍 

I've now registered the GitHub account "FlatLaf".
Maybe I'll move the FlatLaf project to that account in the future...

**Comment by DevCharly** [comment]
Regarding your initial question:
At the moment I've no plans to change the dialog icons.
They do not fit to the look of FlatLaf.
And it is possible that JetBrains will change them: https://youtrack.jetbrains.com/issue/IDEA-272881

Anyway if like them, you can implement them relative easy. E.g.:
~~~java
public class MyErrorIcon
    extends FlatOptionPaneErrorIcon
{
    @Override
    protected void paintIcon( Component c, Graphics2D g ) {
        g.setPaint( new GradientPaint( 0, 0, Color.magenta, 32, 32, Color.red ) );
        super.paintIcon( c, g );
    }
}
~~~

Replace gradient in above code with gradient used in [errorDialog.svg](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/general/errorDialog.svg?short_path=8b337e2)

Enable the icon for all dialogs:
~~~java
UIManager.put( "OptionPane.errorIcon", new MyErrorIcon() );
~~~

![image](https://user-images.githubusercontent.com/5604048/128153994-4e04bfdd-0f12-4e15-bb43-cc6434d7e171.png)

**Comment by DSF-Pro** [comment]
> Anyway if like them, you can implement them relative easy. E.g.:

Thanks.
