### ISSUE TITLE
JPanel Rounded Corners

### ISSUE THREAD

**Issue by shaydarebuar** [JFormDesigner/FlatLaf#367]
It is great JPanel have rounded property like other components as well...

Thanks for such amazing LAF.

**Comment by DevCharly** [comment]
implemented in main branch for v2

There are several ways to use it.

Set panel background color and arc diameter:
~~~java
panel.setBackground( Color.magenta );
panel.putClientProperty( FlatClientProperties.STYLE, "arc: 8" );
~~~

![image](https://user-images.githubusercontent.com/5604048/146193940-b745a746-f73c-4635-9766-e599512df381.png)

Use `FlatLineBorder`, which also allows specifying insets:

~~~java
panel.setBackground( Color.magenta );
panel.setBorder( new FlatLineBorder( new Insets( 16, 16, 16, 16 ), Color.blue, 1, 8 ) );
~~~

![image](https://user-images.githubusercontent.com/5604048/146193548-727efb52-b48d-4bd7-aeea-207cf61e8d82.png)

Or use styling and let FlatLaf [compute colors](https://www.formdev.com/flatlaf/properties-files/#color_functions):

~~~java
panel.putClientProperty( FlatClientProperties.STYLE,
    "background: tint(@background,50%);" +
    "border: 16,16,16,16,shade(@background,10%),,8" );
~~~

![image](https://user-images.githubusercontent.com/5604048/146194830-a35784fd-19c6-447e-8abf-1e58ec99789b.png)

To support light and dark themes:

~~~java
panel.putClientProperty( FlatClientProperties.STYLE,
    "[light]background: tint(@background,50%);" +
    "[dark]background: shade(@background,15%);" +
    "[light]border: 16,16,16,16,shade(@background,10%),,8;" +
    "[dark]border: 16,16,16,16,tint(@background,10%),,8" );
~~~

![image](https://user-images.githubusercontent.com/5604048/146195606-560568e0-e9fd-4e9b-8225-b62f8338471a.png)

If you have many places to use same panel style, define it once (after `FlatLaf.setup()`):
~~~java
UIManager.put( "[style]Panel.myRoundPanel",
    "[light]background: tint(@background,50%);" +
    "[dark]background: shade(@background,15%);" +
    "[light]border: 16,16,16,16,shade(@background,10%),,8;" +
    "[dark]border: 16,16,16,16,tint(@background,10%),,8" );
~~~

and use it:
~~~java
panel.putClientProperty( FlatClientProperties.STYLE_CLASS, "myRoundPanel" );
~~~

Or use own FlatLaf properties files to define such styles.
See [Application properties files](https://www.formdev.com/flatlaf/how-to-customize/#application_properties).

Create `FlatLightLaf.properties`:
~~~
[style]Panel.myRoundPanel= \
    background: tint(@background,50%); \
    border: 16,16,16,16,shade(@background,10%),,8
~~~

And create `FlatDarkLaf.properties`:
~~~
[style]Panel.myRoundPanel= \
    background: shade(@background,15%); \
    border: 16,16,16,16,tint(@background,10%),,8
~~~

**Comment by Langelot0210** [comment]
How to apply gradient color on a Jpanel with FlatLaf?

**Comment by DevCharly** [comment]
> How to apply gradient color on a Jpanel with FlatLaf?

@Langelot0210 FlatLaf does not support gradient backgrounds. 

You have to implement this yourself.
Simply create a subclass of `JPanel`, override `paintComponent(Graphics)` method and paint the gradient
