### ISSUE TITLE
[Question] FlatTextField set Icon

### ISSUE THREAD

**Issue by Kokecena** [JFormDesigner/FlatLaf#368]
I was wondering if there is any way inside the `properties` to put an icon in a `FlatTextField`, I did not find something about it, but I made my attempt to put icons extending from the `FlatTextField` class and it looks fine even if i change the themes.

![TextFieldIcon](https://user-images.githubusercontent.com/75457600/128613616-d56558e9-ee62-47e8-b7a1-0d36efbbfa96.png)
![TextFieldIcon3](https://user-images.githubusercontent.com/75457600/128613771-06b50ea7-ef1d-4669-a3fc-b2060774adf9.png)

Except when the font size is modified, the icon starts to get closer to the placeholder, but for what I'm going to use it it works relatively well.

![TextFieldIcon2](https://user-images.githubusercontent.com/75457600/128613679-7a95b53d-0694-4b5f-9d79-10d98e248e52.png)

i don't know if there are plans to implement it in the project or if there is any way to do it.

**sorry for my bad english x'D, and thank you very much for the incredible project you have done**

**Comment by DevCharly** [comment]
Thanks for suggestion 👍 
This is now implemented in PR #378
