### ISSUE TITLE
JFrame title bar incorrectly positioned with RootPane Border

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#369]
When doing the following on a `JFrame` `JRootPane`:

```java
getRootPane().setBorder( BorderFactory.createEmptyBorder( 10, 10, 10, 10 ) );
```

the frame will look like this.

![image](https://user-images.githubusercontent.com/19377618/128688668-1e6793bd-3cd9-436c-aef4-b89fdba93445.png)

This seems to be related to the embeded menu bar. Not a big deal, since the setBorder call can just be moved somewhere else. Thought I should report it anyways :)

**Comment by DevCharly** [comment]
When native window decorations are used on Windows 10 (as in the above screenshot),
then the window title bar is implemented in Swing in class `FlatTitlePane`.
`FlatTitlePane` and `JMenuBar` are children of `JLayeredPane`, which is a child of `JRootPane`.
So setting a border on the root pane moves all children.

Can't do much here.
Tried to place the `FlatTitlePane` at [-10,-10] (partly outside of layered pane), but then it is cut off:

![image](https://user-images.githubusercontent.com/5604048/129422184-e929af22-03c5-418d-b338-609a90bb49e8.png)

Better set the border on the content pane or on a child of the content pane.
~~~java
((JComponent)getContentPane()).setBorder( BorderFactory.createEmptyBorder( 10, 10, 10, 10 ) );
~~~
