### ISSUE TITLE
As of FlatLaf 1.3, clicking a JMenuItem(Action) while pressing a modifier key like SHIFT or CTRL has no special effect

### ISSUE THREAD

**Issue by hshafie** [JFormDesigner/FlatLaf#371]
Hello,

As of FlatLaf 1.3, clicking a JMenuItem(Action) while pressing a modifier key like SHIFT or CTRL has no special effect. I mean: ActionEvent.getModifiers() always returns 0.

See attached Test.java. [Test.java.gz](https://github.com/JFormDesigner/FlatLaf/files/6961691/Test.java.gz)

Compile it using:
javac -cp "flatlaf-1.5.jar:." Test.java

Run it using:
java -cp "flatlaf-1.5.jar:." Test

Run it with default LaF using:
java -cp "flatlaf-1.5.jar:." Test -noflatlaf

Additional info:
- I did my tests on my Linux box. I can also test this on Windows if you want.
- There is no such problem with Java 8, only with Java 11 or Java 16.
- There is no such problem with the Metal LaF whatever the version of Java.
- This feature used to work fine with FlatLaf 1.2 whatever the version of Java.

Thank you for your beautiful LAF!

**Comment by DevCharly** [comment]
Can reproduce it. Occurs only with heavy-weight popups (default on Linux and macOS; on Windows only for large popups that do not fit into the window).

This line is responsible:
https://github.com/JFormDesigner/FlatLaf/blob/1df9597bb17c739e034e486681a2146b7b79c390/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatRootPaneUI.java#L161

Added in commit 7b248427f00fdc7a77652e60ace058fe006a4288 for FlatLaf 1.3

But have no idea why adding an hierarchy listener has this effect...

**Comment by DevCharly** [comment]
Fixed in main branch.

https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by hshafie** [comment]
Wow, not an easy fix! Thank you so much!
