### ISSUE TITLE
setMaximumSize dont work on JInternalFrames

### ISSUE THREAD

**Issue by GusBj** [JFormDesigner/FlatLaf#372]
I have seen that the maximum size of the JInternalFrame component does not work using FlatLaf, but it works fine using any native laf such as Nimbus or Metal

https://user-images.githubusercontent.com/80091234/128941750-17ad3e85-1ac1-4c29-be5e-cca8be0ca685.mp4

**Comment by DevCharly** [comment]
This should be already fixed since FlatLaf 1.5.
Please try FlatLaf 1.5.

**Comment by GusBj** [comment]
new release!!! oohh this is great! tanks so much
