### ISSUE TITLE
Will FlatLaf support system menu for JInternalFrame?

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#374]
And double-clicking on the frame icon to close JInternalFrame is very handy for some people. :)

**Comment by DevCharly** [comment]
Have no plans to add system menu to internal frames. This has not much benefit IMHO.

But closing internal frame on icon double-click sounds like a good idea 👍

**Comment by DevCharly** [comment]
Closing internal frame on icon double-click is now implemented in main branch. Thanks for the hint.
