### ISSUE TITLE
How to avoid illegal reflective access warning?

### ISSUE THREAD

**Issue by zrj99** [JFormDesigner/FlatLaf#377]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.formdev.flatlaf.ui.JBRCustomDecorations (file:/C:/Users/foo/.m2/repository/com/formdev/flatlaf/1.5/flatlaf-1.5.jar) to method sun.awt.windows.WWindowPeer.setCustomDecorationTitleBarHeight(int)
WARNING: Please consider reporting this to the maintainers of com.formdev.flatlaf.ui.JBRCustomDecorations
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by DevCharly** [comment]
Well, for using custom window decorations provided by JetBrains Runtime it is necessary to access private methods.
IntelliJ IDEA does exactly the same.

What you can do is disabling JetBrains Runtime custom window decorations by setting system property `flatlaf.useJetBrainsCustomDecorations` to `false`. Then the FlatLaf native window decorations are used.

Either on command line with
~~~
-Dflatlaf.useJetBrainsCustomDecorations=false
~~~
or in Java code with
~~~java
System.setProperty( "flatlaf.useJetBrainsCustomDecorations", "false" );
~~~
(before creating UI).

See also https://www.formdev.com/flatlaf/system-properties/ for a full description of the system property.

**Comment by zrj99** [comment]
Thanks.
