### ISSUE TITLE
How can I remove these?

### ISSUE THREAD

**Issue by KarmaConfigs** [JFormDesigner/FlatLaf#383]
Hi, I was wondering how can I remove these dots?

![image](https://user-images.githubusercontent.com/54160333/132946369-9f21a05c-4a58-498b-8bd5-41f9d6f1298b.png)

**Comment by DevCharly** [comment]
The dots indicate a split pane divider.

You can disable them with (invoke after `FlatDarkLaf.setup()`):
~~~java
UIManager.put( "SplitPaneDivider.style", "plain" );
~~~

Or use less split panes... 😉

**Comment by KarmaConfigs** [comment]
> The dots indicate a split pane divider.
> 
> You can disable them with (invoke after `FlatDarkLaf.setup()`):
> 
> ```java
> UIManager.put( "SplitPaneDivider.style", "plain" );
> ```
> 
> Or use less split panes... 😉

Thanks, it worked
