### ISSUE TITLE
Placeholder in TextArea

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#394]
Hey,

I was wondering whether it was a conscious decision to not offer a placeholder for `JTextArea`. I've seen you are using the default logic from Java via reflection to draw a clipped `String`. I am assuming you didn't implement this because it would require reimplementing the drawing and clipping a bit? Would you be accepting this as a PR if I was to try it with line wrapping AND clipping?

Alternatively a non wrapping version might already be better than nothing.

**Comment by Bios-Marcel** [comment]
Do you want a new property or reuse `JTextField.placeholderText`? Also, the code you suggested to use won't work, since we don't want to split at `\n`, but when the TextArea is out of space AND at `\n`,  so instead I am looping over the placeholder calling `JavaCompatibility.getClippedString` til there is no more String left.

**Comment by DevCharly** [comment]
> Do you want a new property or reuse `JTextField.placeholderText`? 

Reuse `JTextField.placeholderText`.

> ... without copying it's code or manipulating it's properties ...

Since the license of OpenJDK is GPL, it is not allowed to copy code from OpenJDK to FlatLaf (Apache license).

You could create a second `JTextArea` and use that for rendering the placeholder text...
