### ISSUE TITLE
Possible clash: 'TextComponent.selectAllOnFocusPolicy' and enabled 'surrendersFocusOnKeystroke' on JTable?

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#395]
Hi,

The JTextField cell editor normally won't get the focused event if you type directly on a cell (without a mouse click into the cell editor).  So the 'TextComponent.selectAllOnFocusPolicy' won't apply to cell editors. But when you enable the 'surrendersFocusOnKeystroke' on the JTable. The cell editor will get the focus, then the text you typed into the cell directly will be selected (if 'TextComponent.selectAllOnFocusPolicy': once or always). If you set the policy to 'once', it only applies to the first cell editor in the table. It makes people feel strange.

So is it possible to disable this policy for cell editors? Especially when 'surrendersFocusOnKeystroke' is enabled.

Thanks,
Tristan

**Comment by DevCharly** [comment]
Many thanks for reporting this.
I've fixed it in main branch.

**Comment by DevCharly** [comment]
Fixed in [1.6.2](https://github.com/JFormDesigner/FlatLaf/releases/tag/1.6.2).
