### ISSUE TITLE
The new "docking options" in Windows 11 doesn't show

### ISSUE THREAD

**Issue by rogerbj** [JFormDesigner/FlatLaf#397]
Testing FlatLaf 1.6 with Windows 11. The new "docking options" feature activated by right-click on a window's maximize icon doesn't show. Example how it looks from the File Explorer window:

![attachment](https://user-images.githubusercontent.com/11735063/137573665-d969d5e9-cd24-4afd-828d-585a2b82826a.png)

With FlatLaf/Java there are no options listed.

**Comment by DevCharly** [comment]
Don't yet have Windows 11 here, but tried the [fix suggested by Microsoft](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu#why-doesnt-my-app-show-the-snap-layouts-menu).
Unfortunately this breaks the maximize button (on Windows 10). No hover, no maximizing...

So I'll upgrade to Windows 11 in the next weeks to fix this...

BTW do the windows have round corners?

**Comment by rogerbj** [comment]
Hi Karl,

Otherwise it looks fine with round corners:

<img width="1011" alt="2021-10-16_17-28-15" src="https://user-images.githubusercontent.com/11735063/137593270-55d807e5-6943-45de-ae57-7d9c331316f5.png">

**Comment by DevCharly** [comment]
Fixed in main branch (for FlatLaf v2).

BTW you can use keys `Windows+Z` to show the Windows 11 snap menu even with FlatLaf v1 😉 

CC @ingokegel
