### ISSUE TITLE
Can the underlineColor of TabSelection be different based on the focus?

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#398]
Hi,

In IntelliJ, if you split documents into multiple tabbed panes, the tab selection highlighter color is changed to the disabled underline color if the focus is moved away. Can this be supported in FlatLaf?

Cheers,
Tristan

**Comment by DevCharly** [comment]
This is now implemented in main branch.

There is a new UI property `TabbedPane.inactiveUnderlineColor` that is used for the underline if no component within the tabbed pane content is focused. The FlatLaf core themes compute the inactive underline color based on the accent color.

(left is active/focused; right is inactive/not-focused)
![image](https://user-images.githubusercontent.com/5604048/164449057-022acc6c-0ffe-426a-b74f-a8c616817d62.png)
