### ISSUE TITLE
TabbedPane improvements

### ISSUE THREAD

**Issue by smileatom** [JFormDesigner/FlatLaf#40]
I know TabScroller is private on BasicTabPaneUI but is there any hope of possibly getting rid of it?  In your excellent look and feel this is one of the few things that detracts from the moderness and throws us back to old java L&Fs.  I hate it completely.

**Comment by DevCharly** [comment]
Thanks for your feedback. What exactly is the problem? Is it just the cropped line? I don't like that as well. Can't remember the reason for not removing it yet. But will do in next release.

![image](https://user-images.githubusercontent.com/5604048/72247702-bf3e1d00-35f5-11ea-909e-b07b2841a5eb.png)

![image](https://user-images.githubusercontent.com/5604048/72248146-bdc12480-35f6-11ea-87e1-2027760d0b9c.png)

Want also change the arrow colors slightly so that it is easier to see the difference between enabled and disabled arrows.

Any other issues? Is something wrong with the general functionality of TabScroller? Thx.

**Comment by smileatom** [comment]
Yes that cropped line has been an eyesore for years.  Im ok with the buttons but they dont respond as a normal scrollbar would.  It would be nice to be able to literally scroll right to left like you can do in the IJ tab run.  My ideal option would be to be able to replace the buttons with an "overflow" menu like IJ so that hidden tabs can be selected. and to have the tabs scroll using normal scrolling (from trackpad gestures or arrow keys)

**Comment by smileatom** [comment]
I realize thats asking alot, but to get this tab layout into this century that CroppedEdge line simply must go.

**Comment by Chrriis** [comment]
There could be some settings to:
- Have the left scroller on the left of the tabs, and the tab scroll on the right of the tabs.
- The mouse wheel over the tabs could scroll left right.

Note that while I would love having the above to improve the look, I would be afraid that it breaks my hack of the BasicTabbedPaneUI which allows me to have a component on the left and/or a component on the right. See:
![TabsWithButtons](https://user-images.githubusercontent.com/1174202/72259589-25846900-3611-11ea-8b8d-d186c2b0fc80.png)

By-the-way, if I had a simple way to add my left and right components without a hack in FlatLaf, that would be great 😉

**Comment by DevCharly** [comment]
Thanks for your great ideas.

To summarize:

- remove cropped line
- arrow buttons should repeat scrolling as long as pressed
- scroll with mouse wheel or trackpad if mouse is over tabs area
- "overflow" menu like IJ
- left arrow button on left side of tabs area and show left/right buttons only if necessary (hide disabled arrows)
- support adding custom components to left and right sides of tabs area
- optionally shorten long tab text
- close button in tabs (issue #31)

With all that improvements it would also make sense to change the default tab layout policy to scrolling to avoid multi-line tabs.

**Comment by DevCharly** [comment]
Hiding cropped line is now implemented in master branch.

**Comment by smileatom** [comment]
Hiding cropped edge, TY so much!.  Would still like to be able to replace or hide the scroller and have the above described scrolling.

**Comment by Chrriis** [comment]
I am not sure this bug should be closed: the possible improvements mentioned in @DevCharly 's 2nd comment are not implemented and they perfectly match the idea of this bug entry.

**Comment by DevCharly** [comment]
Yep, still like to implement improvements for tabbed panes...

**Comment by DevCharly** [comment]
Wheel scrolling and repeating arrow buttons are not implemented in PR #187

**Comment by DevCharly** [comment]
"Show Hidden Tabs" button (like in IntelliJ IDEA) is now implemented in PR #190

**Comment by DevCharly** [comment]
Support adding custom components to left and right sides of tabs area is now implemented in PR #192

**Comment by DevCharly** [comment]
released in 0.44
