### ISSUE TITLE
Question: How does FlatSVGIcon dark mode recoloring work?

### ISSUE THREAD

**Issue by dvtomas** [JFormDesigner/FlatLaf#402]
When I use a `FlatSVGIcon` with `fill="#6E6E6E"` (copied from the icons in the demo), it changes color depending on whether the theme is dark or light (I like that). When I use `fill="#000000"`, it does not. When I download a raw Material icon that doesn't have a `fill` specified at all, it is always black. How does it work, what is the underlying mechanism, where is it configured? Is there a documentation for that? Is there a common place where such things are documented (maybe the Demo might be a good spot)?

Thank you.

**Comment by DevCharly** [comment]
@howudodat that is a good solution.

> is there a preferred property to use to get the highlight color used by the different themes

No.
IntelliJ themes are converted from JSON files and do not have such a property.
In FlatLaf 2.x core themes there are variables, but they are not accessible via UIManager:

https://github.com/JFormDesigner/FlatLaf/blob/e5956900ea5413fc0e879c0a808272b988cc51c5/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLightLaf.properties#L62-L75
