### ISSUE TITLE
Windows 11 Snap Layouts don't work with FlatLaf

### ISSUE THREAD

**Issue by amberream** [JFormDesigner/FlatLaf#407]
When I create a new JFrame and set the FlatLaf as the look & feel the Windows 11 Snap layouts don't work.
When I hover over the maximize button, a menu with snap layouts should pop up.  With this look & feel set, I don't get that menu.
```
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.formdev.flatlaf.FlatLightLaf;

public class FlatLafTest {
	public static void main(String [] args) throws UnsupportedLookAndFeelException
	{
		// With this line snap layouts don't work.  
		// Comment it out and hover over the maximize button to see the snap layout options.
		UIManager.setLookAndFeel(new FlatLightLaf());
		
		JFrame frame = new JFrame();
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}
}
```

**Comment by DevCharly** [comment]
Thanks for reporting.

This is because FlatLaf paints the window title bar itself to support dark window titles and embedded menu bar.
See PR #267.

Don't yet have Windows 11 here, but will upgrade soon. Then I can fix it...

**Comment by DevCharly** [comment]
BTW is this the same as #397 ?

**Comment by amberream** [comment]
Ah, yes it does look like the same issue as #397. Didn't see if because of terminology!

**Comment by DevCharly** [comment]
Fixed in main branch (for FlatLaf v2).

BTW you can use keys `Windows+Z` to show the Windows 11 snap menu even with FlatLaf v1 😉
