### ISSUE TITLE
JMenuBar background is painted even if the menu bar is not opaque

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#409]
The background of the JMenuBar is always painted, even if the menu bar is not opaque.

Here is an example:

    public static void main(String[] args) throws Exception {
        System.setProperty("flatlaf.useWindowDecorations", "false");
        
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (UnsupportedLookAndFeelException e) {
                e.printStackTrace();
            }

            JFrame frame = new JFrame("JMenuBar Opacity Test");
            frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            frame.setSize(400, 300);
            frame.setVisible(true);
            
            JMenuBar menubar = new JMenuBar();
            menubar.setOpaque(false);
            menubar.setBackground(Color.RED);
            menubar.add(new JMenu("Foo"));
            menubar.add(new JMenu("Bar"));
            
            frame.setJMenuBar(menubar);

        });
    }

![image](https://user-images.githubusercontent.com/54304/139656452-2cfae7ea-7612-452f-82b9-198ed06fdc6e.png)

**Comment by TahirUlusoy** [comment]
Hi @ebourg , I want to work on this issue. Can you assign the issue to me?

**Comment by ebourg** [comment]
Go ahead, no need to assign the issue :)

**Comment by TahirUlusoy** [comment]
Can you give your e-mail address. I will ask a question about the issue.

**Comment by DevCharly** [comment]
fixed in main branch

**Comment by ebourg** [comment]
Thanks!
