### ISSUE TITLE
Tree full row selection

### ISSUE THREAD

**Issue by smileatom** [JFormDesigner/FlatLaf#41]
To do this:
![Screen Shot 2020-01-13 at 6 03 41 AM](https://user-images.githubusercontent.com/22084334/72261884-9bb1ad00-35ca-11ea-9e91-5338a8fee3a6.png)

I am subclassing BasicTreeUI and calling setUI on JTree very simply with no change to the default cell renderer.
(Kotlin)
 ```
override fun paintRow(
        g: Graphics, clipBounds: Rectangle, insets: Insets, bounds: Rectangle,
        path: TreePath, row: Int, isExpanded: Boolean, hasBeenExpanded: Boolean, isLeaf: Boolean
    ) {
        if (tree.isRowSelected(row)) {
            g.color = if (tree.hasFocus()) ColorUtil.hex2Rgb("#2f65ca") else ColorUtil.hex2Rgb("#0d293e")
            g.fillRect(0, row * tree.rowHeight, tree.width, tree.rowHeight)

        }
        super.paintRow(g, clipBounds, insets, bounds, path, row, isExpanded, hasBeenExpanded, isLeaf)
        super.paintExpandControl(g, clipBounds, insets, bounds, path, row, isExpanded, hasBeenExpanded, isLeaf)
    }
```

I see you have a UIDefault "Tree.wideSelection", but its not selecting the entire row for me (maybe I did something wrong) so Im not sure if thats what its intent was.

Is there any way to bake this in to the L&F?  Its a common thing, its not hard to do with subclassing but could save folks some time.

**Comment by DevCharly** [comment]
Wide selection is already implemented in FlatLaf since version [0.23](https://github.com/JFormDesigner/FlatLaf/releases/tag/0.23).

If you need a subclass of `TreeUI` you should extend `FlatTreeUI`. Otherwise FlatLaf wide selection does not work.

**Comment by smileatom** [comment]
When I removed my UI subclass and set Tree.wideSelection to true in UIDefaults it gave me the normal selection rect on MacOS.
![Screen Shot 2020-01-13 at 6 23 57 AM](https://user-images.githubusercontent.com/22084334/72263268-66f32500-35cd-11ea-90bf-c947a390d387.png)

**Comment by smileatom** [comment]
Sorry dude, Im on .22 - my bad
