### ISSUE TITLE
Per component focus border

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#412]
The focus border configured with `Component.focusedBorderColor` is applied to all components. It would be nice to be able to disable it for some components such as the JScrollPanes.

**Comment by DevCharly** [comment]
You can disable focus border for single scroll pane:

~~~java
Component view = myScrollPane.getViewport().getView();
((JComponent)view).putClientProperty(
    FlatClientProperties.COMPONENT_FOCUS_OWNER,
    (Predicate<JComponent>) c -> false );
~~~

**Comment by ebourg** [comment]
Thank you for the tip, I guess making the scroll pane non focusable would work too, but I was looking for something more like a `ScrollPane.focusedBorderColor` property overriding the default `Component.focusedBorderColor`.

**Comment by DevCharly** [comment]
There is actually a simple solution.

Create a own border class that changes the color:
~~~java
public class MyScrollPaneBorder extends FlatBorder {
    public MyScrollPaneBorder() {
        focusedBorderColor = Color.red;
    }
}
~~~

And install it:
~~~java
MyScrollPaneBorder myScrollPaneBorder = new MyScrollPaneBorder();
UIManager.put( "ScrollPane.border", myScrollPaneBorder );
UIManager.put( "Table.scrollPaneBorder", myScrollPaneBorder );
~~~
