### ISSUE TITLE
Is it possible to scale a single component?

### ISSUE THREAD

**Issue by dvtomas** [JFormDesigner/FlatLaf#413]
I'd like to have some elements of my app (in my particular case a few major check-boxes and radio-buttons) bigger (that is, bigger font, bigger check box, check mark, etc). Is it possible to achieve that somehow? [This](https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/size.html) link mentions using `component.putClientProperty("JComponent.sizeVariant", "large")`, but it doesn't seem to do anything with my checkbox.

I need this only for particular instances, that is, *not* for all checkboxes or for all radio buttons.

**Comment by DevCharly** [comment]
There is no general way to scale a single components.
The client property `JComponent.sizeVariant` works only in Aqua and Nimbus L&Fs and is not supported by FlatLaf.

Anyway, for checkboxes and radiobuttons you're in luck. I've implemented zoomable icons last week for the FlatLaf theme editor (code is not yet in git repo):

![image](https://user-images.githubusercontent.com/5604048/140094799-f308464f-5d4c-4b42-8553-cc8ffe267909.png)

~~~java
private static class ZoomCheckBoxIcon
    extends FlatCheckBoxIcon
{
    private final float zoom = 1.3f;

    @Override
    public void paintIcon( Component c, Graphics g, int x, int y ) {
        Graphics2D g2 = (Graphics2D) g.create();
        try {
            g2.translate( x, y );
            g2.scale( zoom, zoom );

            super.paintIcon( c, g2, 0, 0 );
        } finally {
            g2.dispose();
        }
    }

    @Override
    public int getIconWidth() {
        return Math.round( super.getIconWidth() * zoom );
    }

    @Override
    public int getIconHeight() {
        return Math.round( super.getIconHeight() * zoom );
    }
}
~~~

For radiobutton icon, duplicate above class and extend `FlatRadioButtonIcon`.

Usage:

~~~java
checkBox1.setIcon( new ZoomCheckBoxIcon() );
Font font = checkBox1.getFont();
checkBox1.setFont( font.deriveFont( font.getSize() * 1.3f ) );
~~~

![image](https://user-images.githubusercontent.com/5604048/140095550-ffd33376-6c08-4066-ae84-59339064ce44.png)

**Comment by dvtomas** [comment]
Amazing, thank you so much!

**Comment by dvtomas** [comment]
Hmm, there's a problem that such explicitly set icon doesn't respect LaF change. Is there any way around that?

**Comment by DevCharly** [comment]
Sure:

~~~java
class LargeCheckBox extends JCheckBox {
    void updateUI() {
        super.updateUI();

        setIcon( new ZoomCheckBoxIcon() );

        Font font = getFont();
        setFont( new FontUIResource( font.deriveFont( font.getSize() * 1.3f ) ) );
    }
}
~~~

**Comment by dvtomas** [comment]
Works, thank you!
