### ISSUE TITLE
Add constructor to read FlatSVGIcon from a File

### ISSUE THREAD

**Issue by dvtomas** [JFormDesigner/FlatLaf#419]
I need to read user-supplied icons from an ordinary file on the hdd. Is something like that possible at the moment? If not, would it be possible to add that?

**Comment by DevCharly** [comment]
I've added new constructors to `FlatSVGIcon`, which allow loading SVG from `File`, `URL`, `URI` and `InputStream`.

Try the latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by dvtomas** [comment]
Cool, thank you!
