### ISSUE TITLE
Layout loop caused by FlatTitlePane

### ISSUE THREAD

**Issue by ingokegel** [JFormDesigner/FlatLaf#420]
I'm hitting a layout loop that is triggered by `FlatTitlePane::menuBarLayouted` calling `revalidate()`  thereby somehow triggering a layout on the JRootPane. I'm not sure how this can happen, but I see this deterministically in some places in my automated UI tests that use AssertJ Swing as a framework.  The async stack trace chain in IntelliJ looks like this:

![2021-11-10_14-40-12](https://user-images.githubusercontent.com/1199475/141145212-6d520f42-e0de-4ec8-8239-5fa81fdd33c1.png)

and continues like that until IntelliJ truncates it. When this layout loop is triggered for the first time, it continues until the frame is closed. I notice this because the testing framework will become extremely slow in this case. The custom repaint manager in the stack trace is just for me to set a breakpoint, it also happens without it.

Passing the VM parameter `-Dflatlaf.useWindowDecorations` prevents this problem, but this is obviously not desirable.

My workaround is to set 

    UIManager.put("RootPaneUI", CustomFlatRootPaneUI.class.getName());

with 

    public static class CustomFlatRootPaneUI extends FlatRootPaneUI {
        @SuppressWarnings("unused")
        public static ComponentUI createUI(JComponent c ) {
            return new CustomFlatRootPaneUI();
        }

        @Override
        protected FlatTitlePane createTitlePane() {
            return new FlatTitlePane(rootPane) {
                @Override
                protected void menuBarLayouted() {
                    updateNativeTitleBarHeightAndHitTestSpotsLater();
                }
            };
        }
    }

which effectively just removes the `revalidate()` call from `FlatTitlePane::menuBarLayouted`. I don't see any negative effects from that removal.

**Comment by DevCharly** [comment]
Thanks for reporting/debugging this issue.
Have not seen this before, but invoking `revalidate()` from `layout()` was obviously a bad idea...

I've added the call to `revalidate()` in commit 30c7b442a8682ed2fe52e573f7f768c19b071211

It was necessary to update the layout when adding components to the menu bar.

With test app `FlatWindowDecorationsTest` it is possible to test it. When selecting the "right aligned stretching component" checkbox, a glue component and a progress bar are added to the menubar/title bar.

Before:

![image](https://user-images.githubusercontent.com/5604048/141161724-64d8ee65-7daf-4c21-9282-44b950cb7fa0.png)

With `revalidate()` the title label is moved:

![image](https://user-images.githubusercontent.com/5604048/141161774-2fd0a994-0fc9-4349-930f-661797964c82.png)

Without `revalidate()` the title label is missing:

![image](https://user-images.githubusercontent.com/5604048/141161786-d81f451d-bfc7-49c4-811a-4eb01a5d5968.png)

Anyway, need to find a solution without `revalidate()`...

**Comment by DevCharly** [comment]
Replacing `revalidate()` with `doLayout()` works for me and should also fix the layout loop.

Could you please add `doLayout()` to your `CustomFlatRootPaneUI ... menuBarLayouted()` method and check whether the layout loop is gone?

**Comment by ingokegel** [comment]
Just checked with one of my UI tests where the layout loop was always reproducible and calling `doLayout()` instead of `revalidate()` does not trigger the layout loop.

**Comment by DevCharly** [comment]
Fixed in 1.6.2. Thanks.
