### ISSUE TITLE
Regression? Netbeans platform Options ribbon remains white with FlatLaf Dark

### ISSUE THREAD

**Issue by jjazzboss** [JFormDesigner/FlatLaf#424]
Hi,  

I made a new release of my Netbeans platform application (NB 12.5, AdoptOpenJDK11.0.13, FlatLaf Dark) and I noticed that the Options ribbon is now white (see image attached). It was dark when I built the previous release using NB12.3 (and it's also dark in the Options dialog of NB12.5 when using FlatLaf Dark).  I did not change any code around my Options dialog, so I guess something has changed in FlatLaf...

![2021-11-14 20_40_22-Options](https://user-images.githubusercontent.com/54775378/141855342-97dd29c7-3366-4669-bdbe-dc7f49d1a0cb.png)

By the way, the embedded menu bar is super cool, thanks !

**Comment by jjazzboss** [comment]
I think I found the issue by looking at your Netbeans PR code, in 
netbeans/platform/options.api/src/org/netbeans/modules/options/OptionsPanel.java

```
 private Color getTabPanelBackground() {
        Color uiColor = UIManager.getColor("nb.options.categories.tabPanelBackground"); //NOI18N
        if (uiColor != null) {
            return uiColor;
        }

        if( useUIDefaultsColors() ) {
            Color res = UIManager.getColor( "Tree.background" ); //NOI18N
            if( null == res )
                res = Color.white;
            return new Color( res.getRGB() );
        }
        return Color.white;
    }
```

`nb.options.categories.tabPanelBackground` seems to be not defined. If I add in my app UIManager.put("nb.options.categories.tabPanelBackground", Color.ORANGE); the Options ribbon becomes  orange.

**Comment by jjazzboss** [comment]
BY the way what is the property key to reuse the default background ?

**Comment by DevCharly** [comment]
Does IMHO not look like a regression in FlatLaf itself.

`nb.options.categories.tabPanelBackground` is defined in NetBeans module "FlatLaf Look and Feel" here:
https://github.com/apache/netbeans/blob/4658ccfc0a8d53e745358575ca35fd11f757f050/platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java#L59

And the actual color is set here:
https://github.com/apache/netbeans/blob/4658ccfc0a8d53e745358575ca35fd11f757f050/platform/o.n.swing.laf.flatlaf/src/org/netbeans/swing/laf/flatlaf/FlatLFCustoms.java#L127

>  what is the property key to reuse the default background ?

`Panel.background` 😉 

Do you use the NetBeans modules "FlatLaf Look and Feel" and "FlatLaf" (library wrapper) from NetBeans 12.5 platform in your app?

**Comment by jjazzboss** [comment]
Yes, both FlatLaf Look and Feel and FlatLaf modules are enabled in my "platform" configuration. And the FlatLaf module is a dependency on the module that installs the L&F, and also on the module 

I enable the Look & Feel using this:
             ```
    NbPreferences.root().node("laf").put("laf", "com.formdev.flatlaf.FlatDarkLaf");
                 UIManager.installLookAndFeel(new UIManager.LookAndFeelInfo("FlatLaf Dark", FlatDarkLaf.class.getName()));
```
From the NB mailing list, Neil Smith recommended to use only the first line. It's true it's enough to install the L&F, but the white Options ribbon remains...

**Comment by neilcsmith-net** [comment]
> And the FlatLaf module is a dependency on the module that installs the L&F

As said on the NetBeans list, you need to also have a dependency on the FlatLaf Look and Feel module (`org.netbeans.swing.laf.flatlaf`) in your module with ModuleInstall.  Otherwise you'll see this issue and a bunch of other UI issues (just verified with my RCP application).

**Comment by jjazzboss** [comment]
Problem solved by adding the non-API Look and Feel module -it was really not obvious.  Thanks

**Comment by jjazzboss** [comment]
Well, the change solves the issue (and some Windows-specific UI tweaks are now visible, good!) but I lost some branding features: my icons in the upper left corner of the main window and dialogs are back to the Netbeans logo. Same for my splash screen.   

If I remove the FlatLaf Look and Feel module dependency and rebuild, I get my branding back.

**Comment by jjazzboss** [comment]
OK I found the issue: Netbeans ImageUtilities.loadImage() detects that it's a dark mode and expects branding images to be named name_dark.gif...  I think both the dependency to the non-API module and this should be documented in the Netbeans doc for FlatLaf.

**Comment by DevCharly** [comment]
> Netbeans `ImageUtilities.loadImage()` detects that it's a dark mode and expects branding images to be named `name_dark.gif`...

Strange, I think NetBeans should use `name.gif` if `name_dark.gif` is not available...

**Comment by neilcsmith-net** [comment]
> Strange, I think NetBeans should use name.gif if name_dark.gif is not available...

Yes, this one was badly thought out IMO - it searches through all the _dark options before the others, so finds the defaults.

The reason @jjazzboss hasn't seen this before is that the look and feel customs weren't triggered.  If there's any bug here, it's in the FlatLaf NetBeans module - I don't think that should be autoload.
