### ISSUE TITLE
Text appears oversized on Elementary OS Linux distribution

### ISSUE THREAD

**Issue by dprietob** [JFormDesigner/FlatLaf#427]
I dont know if this bug appears on others Linux distributions, but specifically on **Elementary OS 6**, button texts and labels appears oversized:

![oversized](https://user-images.githubusercontent.com/7950452/142282047-8403c469-5228-4296-9e78-0b66117fc994.png)

This issue not occur when Metal or Nimbus LAFs (for example) are configured:

![metal](https://user-images.githubusercontent.com/7950452/142282104-37aeb890-560d-4e9f-b8b2-7f869d033c0f.png)
![nimbus](https://user-images.githubusercontent.com/7950452/142282124-a9a32142-0ce3-4703-840e-5fd5bc2d8921.png)

I thought the error might be because _canberra-gtk_ module was missing on my system (it was the only console error I had while debugging), but I installed it and the result is still the same.

Some idea about what's happening?

**Comment by DevCharly** [comment]
For some reason, the computed font size is too large 😕 

Nimbus and Metal use fixed size fonts (which may result in too small text if screen is scaled).
FlatLaf uses the same approach as `GTKLookAndFeel` to compute a "useful" font size.

Do you have the also too large font when using `GTKLookAndFeel`?
Which Java version do you use?

To better understand the problem, can you please run the following program and post the output?

~~~java
import java.awt.*;
import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;

public class FlatLinuxFontInfo
{
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            System.out.println( "Java version:   " + System.getProperty( "java.version" ) );
            System.out.println( "Java vendor:    " + System.getProperty( "java.vendor" ) );

            System.out.println( "Gtk FontName:   " + Toolkit.getDefaultToolkit().getDesktopProperty( "gnome.Gtk/FontName" ) );
            System.out.println( "Xft DPI:        " + Toolkit.getDefaultToolkit().getDesktopProperty( "gnome.Xft/DPI" ) );
            System.out.println( "Transform:      " + GraphicsEnvironment.getLocalGraphicsEnvironment()
                .getDefaultScreenDevice().getDefaultConfiguration()
                .getNormalizingTransform() );

            FlatLightLaf.setup();
            System.out.println( "Default Font:   " + UIManager.getFont( "defaultFont" ) );
        } );
    }
}
~~~

**Comment by DevCharly** [comment]
Could you please also run [FlatScreenInfo](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatScreenInfo.java) and post the output?
(This is a single-file program that can be compiled/run without any other FlatLaf code or dependencies.
 Since Java 11, you can run this program from source with: `java FlatScreenInfo.java`)

Thanks.

**Comment by dprietob** [comment]
Hi! Thanks to answering so quickly. 

I think this errors its caused by my JRE version. When I opened this issue, I had Oracle's JDK 17 installed on my system and my app looks like this when I forced GTK LAF:

![gtk_oracle](https://user-images.githubusercontent.com/7950452/142382139-fbf0cccf-0bad-4cc3-a154-648a8c40a2f3.png)

Due to some errors trying execute ``FlatScreenInfo`` on terminal, I changed JDK 17 from Oracle to OpenJDK 17, and...

![gtk_openjdk](https://user-images.githubusercontent.com/7950452/142382173-6ab3a4c3-d4ab-4a47-9656-5eaf8d21ccc5.png)

This is how my app looks like now with GTK LAF running with OpenJDK, and this is how looks like with FlatLAF (dark theme):

![flatlaf_openjdk](https://user-images.githubusercontent.com/7950452/142382185-67a40e2c-5643-46e2-b4b9-b758b797ee55.png)

I send you the info shown by ``FlatScreenInfo`` and ``FlatLinuxFontInfo`` running on Oracle's JDK and on OpenJDK if it helps you (both version show the same):


### FlatScreenInfo
```
Scale factors:  100%
Java version:   17.0.1
Java vendor:    Oracle Corporation

ID:      :0.0 (main)
Size:    1920 x 1080 / -1 Bit / 60 Hz
Bounds:  1920 x 1080 / x 0 / y 0
Insets:  left 0 / right 0 / top 30 / bottom 0
Scale:   1.0
```
### FlatLinuxFontInfo
```
Java version:   17.0.1
Java vendor:    Oracle Corporation
Gtk FontName:   Inter 9
Xft DPI:        98304
Transform:      AffineTransform[[1.333333333333333, 0.0, 0.0], [0.0, 1.336842105263158, 0.0]]
Default Font:   javax.swing.plaf.FontUIResource[family=Inter,name=Inter,style=plain,size=12]
```

**Comment by DevCharly** [comment]
Was able to reproduce the issue with Oracle JDK 8 and font "Inter" on Linux.

Seems that Oracle's JDK has problems with this font.
Although the `java.awt.Font` object has size `15`, the `java.awt.FontMetrics` returns a height of `41`...

To avoid this problem in the future, I've added a check that uses a fallback font for this cases.
