### ISSUE TITLE
can't find symbol: Variable TEXT_FIELD_LEADING_ICON

### ISSUE THREAD

**Issue by lwdillon** [JFormDesigner/FlatLaf#428]
1.6.4
java: can't find symbol
  Symbol: Variable TEXT_FIELD_LEADING_ICON
  Location: Interface com.formdev.flatlaf.FlatClientProperties

**Comment by DevCharly** [comment]
`FlatClientProperties.TEXT_FIELD_LEADING_ICON` is not in FlatLaf 1.6.4.
It comes with v2 (not yet released).
See PR #378

Use `2.0-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
