### ISSUE TITLE
JXTable control button icon

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#434]
The JXTable component from SwingX has a button on the top right corner to configure the columns. The default icon is a bitmap and it doesn't scale well. Fortunately it can be managed by the look and feel using the `ColumnControlButton.actionIcon` UI property (defined in org.jdesktop.swingx.table.ColumnControlButton). Maybe FlatLaf could provide a scalable alternative in flatlaf-swingx?

**Comment by ebourg** [comment]
Erratum: the default icon isn't a bitmap, it's painted by org.jdesktop.swingx.icon.ColumnControlIcon. The arrow is painted as 4 horizontal lines (like the arrows in the Metal look and feel), and it looks bad once upscaled.

**Comment by ebourg** [comment]
Here is an alternative icon that scales better:

    import java.awt.Component;
    import java.awt.Graphics;
    import java.awt.Graphics2D;
    import java.awt.RenderingHints;
    import javax.swing.Icon;
    import javax.swing.plaf.UIResource;
    
    import com.formdev.flatlaf.ui.FlatUIUtils;
    
    public class FlatLafColumnControlIcon implements Icon, UIResource {
        
        @Override
        public int getIconWidth() {
            return 10;
        }
    
        @Override
        public int getIconHeight() {
            return 10;
        }
    
        @Override
        public void paintIcon(Component c, Graphics g, int x, int y) {
            g.setColor(c.getForeground());
            
            // draw horizontal lines
            g.drawLine(x, y, x+8, y);
            g.drawLine(x, y+2, x+8, y+2);
            g.drawLine(x, y+8, x+2, y+8);
    
            // draw vertical lines
            g.drawLine(x, y, x, y+8);
            g.drawLine(x+4, y, x+4, y+4);
            g.drawLine(x+8, y, x+8, y+4);
    
            // draw arrow
            double uiScale = ((Graphics2D) g).getTransform().getScaleX();
            if (uiScale != Math.round(uiScale)) {
                // antialiasing at fractional scales to fix the artefacts
                ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            }
            ((Graphics2D) g).fill(FlatUIUtils.createPath(x+3, y+6, x+10, y+6, x+6.5, y+9.5));
        }
    }

There are some artifacts at 125%, 150% and 175%, depending on where the icon is drawn on the canvas the triangle isn't always perfectly pyramidal. The best workaround I've found is to enable the anti-aliasing. At 100% the icon is identical to the original one.

Here is how it looks:
![image](https://user-images.githubusercontent.com/54304/143269801-3c2d29fb-8e28-48e5-968e-f7bf3d67f697.png)

**Comment by DevCharly** [comment]
New "column control" icon at 100%, 150%, 200% and 300%

![image](https://user-images.githubusercontent.com/5604048/145071606-3101b21d-ad14-4ba8-935f-d19c122e4ca4.png)

I've made the "table" one pixel smaller to get a gap between the column separator line (of last column) and the icon.

**Comment by DevCharly** [comment]
Have slightly adjusted the colors:
- in light themes it is now slightly darker (than on above screenshot)
- in dark themes it is brighter than in previous commit

**Comment by ebourg** [comment]
Thank you. With the pixel removed the columns of the icon no longer have the same width, but it still looks ok. I worked around this issue by using a wider scrollbar (12 pixels instead of 10).
