### ISSUE TITLE
Menu items with icons of different sizes are not vertically aligned

### ISSUE THREAD

**Issue by ebourg** [JFormDesigner/FlatLaf#437]
When the items of a JMenu have icons of different width, the text isn't aligned vertically. If the icon is larger than 16 pixels (at scale 100%) the text is pushed to the right. Ideally the maximum icon width should be computed to pad all the texts by the same amount (the other look and feels usually do that).

Here is an example using empty icons of varying sizes:

**FlatLaf**
![image](https://user-images.githubusercontent.com/54304/143899749-1cccd9f2-62c7-464d-8c6a-d2eb2d350fe0.png)

**Metal L&F**
![image](https://user-images.githubusercontent.com/54304/143899078-80fc6859-3ead-4ec3-900b-d84f4bbbb90c.png)

**Windows L&F**
![image](https://user-images.githubusercontent.com/54304/143899312-f66a0e95-2e37-4bc6-b7dd-6cf7836012f7.png)

**Comment by DevCharly** [comment]
Thanks. Now implemented in main branch.
