### ISSUE TITLE
help:not work with   java9 module application

### ISSUE THREAD

**Issue by sosoeo** [JFormDesigner/FlatLaf#441]
I buid a demo application every thing is ok until a module-info.java(every dependency module required) added into src/main/java directory.  when ./gradlew build,  it's said 
the module com.formdev.flatlaf can't find, what wrong with me ?

use java 11

**Comment by DevCharly** [comment]
probably enable `java.modularity.inferModulePath` in gradle build script:

https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular
https://docs.gradle.org/current/userguide/application_plugin.html#sec:application_modular

**Comment by sosoeo** [comment]
thanks very much for your replay, I add that, no lucky. 
I uploaded this simple demo to here:  [flatlaf with java9Demo](https://github.com/sosoeo/moduleTest.git)
can you have a look?
I copy my build.gradle to here:

plugins { id 'application' }
repositories {    jcenter()  }
dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    implementation 'com.google.guava:guava:29.0-jre'
    implementation "com.formdev:flatlaf:1.6.5"
}
application {
    mainModule.set('moduleTest.app.main')
    mainClass.set('moduleTest.App')
}
java.modularity.inferModulePath = true
java {
    modularity.inferModulePath.set(true)
}
tasks.named('test') {
    useJUnitPlatform()
}

**Comment by sosoeo** [comment]
good news, I fixed the "module not found" error,mainly by the plugin :org.javamodularity.module(without java.modularity.inferModulePath) , BUT I DONT KNOW WHY. I have updated my flatlaf demo. I use another plugin org.beryx.jlink to create installer,this plugin will refuse work without module-info.java.

**Comment by DevCharly** [comment]
Sorry, but can't help on building application or installer issues...
