### ISSUE TITLE
JTextPane line wrap issue for RTL text

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#446]
I just discovered something really weird. If I enter a long text in English, proper line breaks are created:

![image](https://user-images.githubusercontent.com/1523778/146578963-e645588f-699b-4c7e-8c6f-44a9d09543be.png)

but when entering a RTL text (Hebrew), there is a _wrong_ line break created (text clipped):

![image](https://user-images.githubusercontent.com/1523778/146579115-543084a7-1d94-4dfa-808e-9c8c36c0b910.png)

the entered text is much longer than the visible part:

```
כאשר עורכת הדין, קולט יוז, נפגשת עם הלקוחה החדשה שלה, אלינור ריזה, אשר מטופלת ביחידה הפסיכיאטרית בבית החולים בסן פרנסיסקו, אין לה מושג שבנוסף לכך היא מקיימת מאבק משפטי גבוה לשיפור הטיפול בחולים הנפשיים בבתי חולים.
```

**Comment by DevCharly** [comment]
This seems to depend on to component orientation of the text component. If you click the "right-to-left" checkbox at the bottom of the FlatLaf Demo, it looks better:

![image](https://user-images.githubusercontent.com/5604048/147278278-7bf5886d-2b35-4edc-821b-395a0a7536ac.png)

BTW same behaviour as in other look and feels.

**Comment by mlaggner** [comment]
Thanks for the response.

Do you have an idea how to solve that for a JTextPane which may hold LTR and RTL text? Is there a helper which can detect whether the text is RTL or LTR?

Otherwise I would need to switch to a JTextArea (which handles this the right way, but has other drawbacks..)

**Comment by DevCharly** [comment]
Tried to figure out why JTextPane and JTextArea behave different in this case.
Both use `javax.swing.text.WrappedPlainView`, but JTextArea uses slightly different classes for the view.
See classes `BasicTextAreaUI.PlainParagraph` and `BasicTextAreaUI.PlainParagraph.LogicalView`.
But don't know what they do...

> Is there a helper which can detect whether the text is RTL or LTR?

Don't know one.

There is a private method `javax.swing.text.AbstractDocument.isLeftToRight()`,
which is used from class `DefaultCaret`.

Or have a look at `DefaultCaret.paint()` where the extra triangle is painted for bidi text:
https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.desktop/share/classes/javax/swing/text/DefaultCaret.java#L692-L696

**Comment by mlaggner** [comment]
thank you very much for your guidance. Since this is no FlatLaf issue, I will close this one (if I find a good solution, I will answer here afterwards)

merry Christmas
Manuel

**Comment by mlaggner** [comment]
Just for your information - I came up with the following solution which seems to work:

1. Subclassed the JTextPane
2. added the following code:

```
  @Override
  public void setText(String t) {
    super.setText(t);

    if (isRTL(t)) {
      setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }
    else {
      setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
    }
  }

  private boolean isRTL(String s) {
    for (int i = 0; i < s.length(); i++) {
      byte d = Character.getDirectionality(s.charAt(i));
      if (d == Character.DIRECTIONALITY_RIGHT_TO_LEFT || d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC
          || d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_EMBEDDING || d == Character.DIRECTIONALITY_RIGHT_TO_LEFT_OVERRIDE) {
        return true;
      }
    }

    return false;
  }
```
