### ISSUE TITLE
Borders around JScrollPane

### ISSUE THREAD

**Issue by Wisser** [JFormDesigner/FlatLaf#447]
A JScrollPane always has a 1-px border. Is it possible to get rid of it if no scrollbar is visible?

![grafik](https://user-images.githubusercontent.com/861721/146648852-b63cdca8-6efe-43be-886c-0ab4fb3de08d.png)

**Comment by Wisser** [comment]
I tried around a bit and was able to remove the border with this:
`UIManager.put("ScrollPane.border", "");`

Is it ok to use an empty string here?

**Comment by DevCharly** [comment]
Better use an empty border:
~~~java
UIManager.put("ScrollPane.border", BorderFactory.createEmptyBorder() );
~~~

Or for single components:
~~~java
scrollPane1.setBorder( BorderFactory.createEmptyBorder() );
~~~
