### ISSUE TITLE
Color of the separators of a TableHeader 

### ISSUE THREAD

**Issue by Wisser** [JFormDesigner/FlatLaf#448]
Is it possible to change the color of the separators of a TableHeader for a specific table?
I only found this to change the color for all tables:
`UIManager.put( "TableHeader.separatorColor", Color.lightGray);`

**Comment by DevCharly** [comment]
> Is it possible to change the color of the separators of a TableHeader for a specific table?

Yes, in FlatLaf 2.x. No in 1.x.

~~~java
tableHeader.putClientProperty( "FlatLaf.style", "separatorColor: #f00; bottomSeparatorColor: #00f" );
~~~

See doc here: https://www.formdev.com/flatlaf/components/tableheader/

**Comment by Wisser** [comment]
Thank, that worked.
Is it also possible to left-align the labels in the table header?

**Comment by DevCharly** [comment]
> Is it also possible to left-align the labels in the table header?

Yes, I think so. `JTableHeader` uses a renderer that you can replace.

**Comment by Wisser** [comment]
Yes, of course. I had totally forgotten about the renderer.
Thanks for the quick help. Now everything works fine.
