### ISSUE TITLE
Question: How to make the title bar take on the color of the system theme?

### ISSUE THREAD

**Issue by rosamarco** [JFormDesigner/FlatLaf#450]
Hi, congratulations on the latest release. I noticed in the demo that the title bar takes on the color of the system theme (on macos). How can I enable this feature? Thank you

**Comment by PicoMitchell** [comment]
I'm also very interested in this! I though this could only be done when using the JetBrain Runtime (or some specific JDK), but the latest FlatLaf demo does indeed change the titlebar to dark mode using the default JDK from https://jdk.java.net

**Comment by PicoMitchell** [comment]
I found the answer hunting through FlatLaf Demo commits: https://github.com/JFormDesigner/FlatLaf/commit/3facbc0900d4330b9aadc44077d3f7fb7e686074#diff-6178310587a0e4e1bf1132df43249c4f95d84e7b7e30d4762918c9d8bcfe1851

Looks like all you need to do is add `System.setProperty("apple.awt.application.appearance", "system");`

**Comment by rosamarco** [comment]
I figured out the problem: you must do this before any AWT classes are loaded.

**Comment by DevCharly** [comment]
FYI the system property `apple.awt.application.appearance` was first implemented for Java 14, and then backported to 11.0.8 and maybe also to Java 8. See: https://bugs.openjdk.java.net/browse/JDK-8231438

**Comment by mvalent23** [comment]
Just in case anyone was wondering, I found a corner case not covered anywhere in the documentation.  If you are using a SplashScreen, then you *must* set the "apple.awt.application.appearance" property in the command line arguments (probably needs to go first too).   Othrewise, even if it's the first line of main(), it still will not result in changing the color of the window decorator bar.
