### ISSUE TITLE
Password reveal button / icon rendering issue when using round edges

### ISSUE THREAD

**Issue by j-dimension** [JFormDesigner/FlatLaf#451]
First of all, thanks for 2.0rc1, what a great piece of work!

When using round edges for a password field, the reveal button overlaps with the components border. Maybe there is a way to have more space to the right of the reveal button. 

Thanks!

![grafik](https://user-images.githubusercontent.com/3729754/146833003-9c24b145-3b6d-48d5-909c-f94ad512f791.png)

**Comment by DevCharly** [comment]
> Maybe there is a way to have more space to the right of the reveal button.

Not at the moment. Have to improve this...

Here is a solution for FlatLaf 2.0-rc1 that makes the reveal button round:
~~~java
if( passwordField1.getComponentCount() > 0 &&
    passwordField1.getComponent( 0 ) instanceof JToggleButton )
{
    JToggleButton revealButton = (JToggleButton) passwordField1.getComponent( 0 );
    revealButton.putClientProperty( "FlatLaf.style", "arc: 999" );
}
~~~

![image](https://user-images.githubusercontent.com/5604048/147775266-38197f3e-b2e6-4885-84b1-98162b289545.png)

You're using a larger font on the password field, right? (the reveal button is not square)
Then it would looks like this: 😕 

![image](https://user-images.githubusercontent.com/5604048/147775451-c6e0c1ad-6e6e-41da-9dd2-6c4047785644.png)

To "fix" this, you can increase the margin of the reveal button. E.g.:
~~~java
revealButton.putClientProperty( "FlatLaf.style", "arc: 999; toolbar.margin: 1,3,1,3" );
~~~

And it looks like this:

![image](https://user-images.githubusercontent.com/5604048/147777688-865df79f-a55a-4518-82cd-5577cfce3390.png)


I think about using the text field arc for buttons in text fields.
Then any text field button would be round if text field is rounded.
But this does not work well if text field font size is changed...

**Comment by j-dimension** [comment]
Thanks @DevCharly , that works well. As I am using this special scenario at only one place (the login dialog), I am fine with your suggestion as a special solution, and you may also close the ticket. 

Thanks!

**Comment by DevCharly** [comment]
I've made some improvements in recent commits.

The buttons now automatically considers the corner arc of the text field. 
No longer necessary to use `arc: 999`.

![image](https://user-images.githubusercontent.com/5604048/148410692-e6a55f8b-057c-4361-a0d7-b997ce20bac0.png)
![image](https://user-images.githubusercontent.com/5604048/148410786-b5f8099d-56c4-40fb-82d4-88fdf543f348.png)


The reveal button now has component name `PasswordField.revealButton` and there is a new utility method `SwingUtils.getComponentByName()` that makes it easy to find a component by name.

This simplifies the code from my previous comment to:
~~~java
JToggleButton revealButton = SwingUtils.getComponentByName( passwordField1, "PasswordField.revealButton" );
if( revealButton != null )
    revealButton.putClientProperty( "FlatLaf.style", "toolbar.margin: 1,3,1,3" );
~~~
