### ISSUE TITLE
Is it possible to run with DLL loading disabled? 

### ISSUE THREAD

**Issue by lrhuff8** [JFormDesigner/FlatLaf#457]
I have an application that typically uses the Windows L&F with an option to use Nimbus (with various tweaks) for dark mode. It would be great to move to FlatLaf as our new standard. By doing that, the UI looks much better, and we would get a consistent component size between these two modes, which we do not get today. My challenge is that our application is running inside a Security Manager and we really do not want to load DLLs due to those associated concerns. The application seems to run fine even after the DLL load failure which I have shown below. Is there a way to run on all platforms (Windows, Linux, OSX) with DLL loading disabled? I have tested with -Dflatlaf.useWindowDecorations=false and that does not seem to eliminate this exception. 

2021-12-22 12:44:20.370 [SEVERE] null (com.formdev.flatlaf.util.LoggingFacadeImpl.logSevere:31)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.C:\Users\X9Ware5\AppData\Local\Temp\flatlaf.temp\flatlaf-windows-x86_64-63392992420000.dll")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.lang.SecurityManager.checkLink(SecurityManager.java:608)
	at java.base/java.lang.Runtime.load0(Runtime.java:762)
	at java.base/java.lang.System.load(System.java:1837)
	at com.formdev.flatlaf.util.NativeLibrary.loadLibraryFromJar(NativeLibrary.java:108)
	at com.formdev.flatlaf.util.NativeLibrary.<init>(NativeLibrary.java:59)
	at com.formdev.flatlaf.ui.FlatWindowsNativeWindowBorder.getInstance(FlatWindowsNativeWindowBorder.java:121)

**Comment by DevCharly** [comment]
VM option `-Dflatlaf.useWindowDecorations=false` is the correct way to disable DLL loading.

Maybe you added this option to field "program arguments" in your IDE?
This does not work. 
Add it to field "VM argument/options". (maybe hidden in IntelliJ IDEA)

Or better add following to your `main()` method (before using FlatLaf):
~~~java
System.setProperty( "flatlaf.useWindowDecorations", "false" );
~~~

**Comment by lrhuff8** [comment]
Karl,                       thank you so much for the quick response and that totally works. I am author and sole employee of X9Ware, with our primary product being X9Assist desktop based on SwingX. These results are pretty amazing, so I want to share them with you so you can see the difference. I totally see this as something that we can do in an upcoming release.

I totally appreciate all of your work. I cannot fathom how much effort it takes to build this, and it is something that is needed to keep Swing as a viable UI alternative. I have been looking at a possible move to Vaadin, but hesitate to do that given the lack of MigLayout support which would make the transition more complex. Our application is based on Java 17 and I have hopes that GraalVM 22.0 will support native image for Windows Swing applications (the added Swing/Linux with their R21.x). That would be a good move from our current use of JLink/JPackage with an embedded JVM. FYI that we were a previous user of Excelsior Jet, but that was dropped a couple of years back when they did an exit and never moved forward from Java 8.

Do you have a timeline for FlatLaf 2.0 final? Please take a look at the below and let me know if you have any questions.

Here is our primary panel using the Windows UI:

***@***.***

And here is that same panel using FlatLaf. Very well done !!  The only immediate difference I see here is the Field Viewer button on the left without the green background color, which we use to indicate which of our panels is currently being shown. This would take some investigation on my part. This is a setBackground() against an opaque JButton, so really no reason for that not to work. The JTable lines are being lost as well, which we set using setShowHorizontalLines() and setShowVerticalLines(). I am extremely impressed with these results.

***@***.***

Lowell Huff
X9Ware LLC
www.x9ware.com<http://www.x9ware.com/>
***@***.******@***.***>
‪(844) 937-1850

We are always interested in your enhancement suggestions, so send them our way. Do you get exceptional value from X9Ware products? If so, please consider referrals to your business partners and colleagues.

**Comment by DevCharly** [comment]
Unfortunately the images in your Email were lost when GitHub converted it into a comment...

> Do you have a timeline for FlatLaf 2.0 final?

early in January
