### ISSUE TITLE
[Help] when change the accent color or laf , the font changes as well, not the before one

### ISSUE THREAD

**Issue by lsldragon** [JFormDesigner/FlatLaf#458]
Firstly, I really thank this remarkable Java Swing Laf, which makes java desktop applications more appealing.
My question is that:

I want to change the accent color of my project, however, every time I change that, the new font is not the previous one, I have checked the flatlaf demo, but I can do nothing. So what can I do? Thanks again.
The code is below:  

```java
 contentComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                int index = contentComboBox.getSelectedIndex();

                if (index == 0) {
                    FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#FA9144"));
                    FlatIntelliJLaf.setup();
                    FlatLaf.updateUI();
                } else if (index == 1) {
                    FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#941939"));
                    FlatIntelliJLaf.setup();
                    FlatLaf.updateUI();
                }
            }
        });
```

**Comment by DevCharly** [comment]
Code looks good. 
Do you change the default font in your app?
Then `FlatIntelliJLaf.setup();` overwrites it.

**Comment by lsldragon** [comment]
Indeed, I change the default font to other font and size, so what can i do to keep the same as before when changing accent color?
Thanks for your reply.

**Comment by DevCharly** [comment]
Change the font again after calling `FlatIntelliJLaf.setup();`

**Comment by DevCharly** [comment]
BTW how you you change the font?

**Comment by lsldragon** [comment]
The Swing UI Designer in IDEA.

P.S.:
before change the accent color, and the font is Microsoft YaHei, PLAIN, 16 pt
![before](https://user-images.githubusercontent.com/31510795/147301860-0b286fc7-b0f2-494d-84aa-0e2e4f06dd78.png)
agter change the accent color, and the font may be:
`Font font = UIManager.getFont("defaultFont");
        System.out.println(font.toString());`
`javax.swing.plaf.FontUIResource[family=Segoe UI,name=Segoe UI,style=plain,size=12]`
![after](https://user-images.githubusercontent.com/31510795/147301949-a17cd389-858e-4058-b430-9f4252e5cf10.png)

Well, this Segoe UI is less readable comparing with Microsoft Ya Hei.

**Comment by lsldragon** [comment]
Thanks for your solution, it works now.
the code like this:
` contentComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                int index = contentComboBox.getSelectedIndex();

                if (index == 0) {
                    FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#FA9144"));
                    FlatIntelliJLaf.setup();
                    FlatLaf.updateUI();
                    final Component[] components = **listPanel**.getComponents();
                    for (Component c : components) {
                        c.setFont(new Font("Microsoft YaHei", Font.PLAIN, 16));
                    }

                } else if (index == 1) {
                    FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#941939"));
                    FlatIntelliJLaf.setup();
                    FlatLaf.updateUI();
                    final Component[] components = **listPanel**.getComponents();
                    for (Component c : components) {
                        c.setFont(new Font("Microsoft YaHei", Font.PLAIN, 16));
                    }
                }
            }
        });`

I have no idea whether there is another effective solution to make it work globally, because there are many Panels....

Anyway, thanks for helping me again.

**Comment by DevCharly** [comment]
Following should work **without** setting font on each component:

~~~java
FlatIntelliJLaf.setup();

Font font = StyleContext.getDefaultStyleContext().getFont( "Microsoft YaHei", Font.PLAIN, 16 );
UIManager.put("defaultFont", font);

FlatLaf.updateUI();
~~~

**Comment by lsldragon** [comment]
Great! Thank you so much!!
