### ISSUE TITLE
method new FlatSVGIcon(String) is not thread safe

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#459]
may cause "FlatSVGIcon: failed to load 'file:/D:/xxx.svg'"
under concurrent case

**Comment by DevCharly** [comment]
Does it fail if loading various icons?
Or do you load the same icon on multiple threads?

**Comment by DevCharly** [comment]
Should be fixed in latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots
