### ISSUE TITLE
MooInfo: New Application using FlatLaf

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#460]
I hava a project could be added to "Applications using FlatLaf"  manifest:
https://github.com/rememberber/MooInfo

**Comment by DevCharly** [comment]
Done.

MooInfo looks very nice 👍 🥇

**Comment by DevCharly** [comment]
tweeted about MooInfo: https://twitter.com/JFormDesigner/status/1479110985868660739
