### ISSUE TITLE
Already created JFileChooser is not repainted

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#464]
I wanted to add a combobox with native, nimbus and FlatLaF Dark/Light LaFs so upon selecting an item in a combobox I call `FlatLaF.updateUI()` this seems to update all components in frames but I have an already created JFileChooser which appear half painted
![Screenshot_20220115_232545](https://user-images.githubusercontent.com/7027319/149639639-4ee905ca-544d-4f1d-b283-c945fd734fa6.png)

**Comment by medmedin2014** [comment]
It seems that `updateUI` iterates only on windows and doesn't include filechoosers. When I apply `SwingUtilities.updateComponentTreeUI( filechooser )` on my filechooser the problem is fixed.

**Comment by DevCharly** [comment]
Yes, `FlatLaF.updateUI()` can update only components that are contained in windows.
It can not access components that are only referenced by variables/fields.

So if you create a component and do not add it to any window, then it is not updated.
It's up to you to update it.

**Comment by medmedin2014** [comment]
@DevCharly Thanks bro :)
