### ISSUE TITLE
Issue with the icon rendering in selected mode

### ISSUE THREAD

**Issue by nroduit** [JFormDesigner/FlatLaf#465]
Following [the Intellij principles for colors](https://jetbrains.design/intellij/principles/icons/), there are sometimes situations for some themes where the rendering of an icon selection (JToggleButton) is not good (very low contrast).
In the example below with Monokai Pro (Material), we see the rendering of the selection of the Draw action:
![image](https://user-images.githubusercontent.com/993975/149652523-eb723130-2aa0-49d9-b1b0-306072e5aacb.png)

To try to improve this, I use the method setSelectedIcon() and FlatSVGIcon.setColorFilter() to make the gray of the icons darker. However the setColorFilter() method applies to an icon but I haven't found a way to derive an existing FlatSVGIcon (like for getDisabledIcon() or scale) without having to completely reload the icon. Is this the right way to do it or am I missing something obvious?

**Comment by DevCharly** [comment]
There is no method to clone a `FlatSVGIcon`. Maybe should add one...

Anyway `FlatSVGIcon` has a cache that avoids loading SVG file if already loaded.
So creating two `FlatSVGIcon` with same name/URL loads the SVG file only once.

BTW the constructor of `FlatSVGIcon` is very lightweight because it does not load anything.
The SVG file is only loaded when needed (when invoking `getIconWidth()`, `getIconHeight()` or `paintIcon()`).

**Comment by nroduit** [comment]
Thank you for the quick and clear answer.

In fact when icons are created in actions or others, it is difficult when retrieving icons of type FlatSVGIcon to be able to create on the fly a derived icon (for selection or rollover) because there is no method to get the URI.

Having a method FlatSVGIcon.derive(ColorFilter colorFilter ) would allow to benefit easily from all the possibilities related to the filters.

**Comment by DevCharly** [comment]
I've added a copy constructor to `FlatSVGIcon`.

See latest `2.0.1-SNAPSHOT` https://github.com/JFormDesigner/FlatLaf#snapshots

Use:
~~~java
FlatSVGIcon selIcon = new FlatSVGIcon( icon );
selIcon.setColorFilter( selColorFilter );
~~~
