### ISSUE TITLE
TitledBorder font color is not updated

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#467]
If I create a JPanel with titled border inside a JDialog then the border font color refuses to be changed when the theme is changed.

`Flatlaf: v2.0`

![Screenshot_20220116_195222](https://user-images.githubusercontent.com/7027319/149674035-33e955d3-8687-44f5-b422-99d1deb57689.png)

**Comment by DevCharly** [comment]
Hmm, this works for me...

Usually the title text color is `null`. Then UI property `TitledBorder.titleColor` is used to paint the text. See:
https://github.com/openjdk/jdk/blob/e20c6bf972a106105733c395877d11d9c894eb28/src/java.desktop/share/classes/javax/swing/border/TitledBorder.java#L481-L483

I think you passed a color to the constructor of the `TitledBorder`, right?
Then it is up to you to update it 😉 
(but better pass `null`)

**Comment by medmedin2014** [comment]
OMG, I feel stupid, sorry for disturbing you. One thing that I wish to tell is thanks really much for this fantastic LaF, this gem will save many Java projects by upgrading their looks :)
