### ISSUE TITLE
Incorrect maximized bounds of decorated windows on macOS for pre-Java 15

### ISSUE THREAD

**Issue by kirill-grouchnikov** [JFormDesigner/FlatLaf#469]
This is for https://github.com/JFormDesigner/FlatLaf/issues/129 and the fix that went into the codebase last year around https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L624

Running a decorated frame with Java 9 on macOS and clicking the maximize button that comes from FlatLaf makes the window too big. If it's a 2x retina screen (on earlier models of MacBook Pro), the window will be 2x as wide and tall as it should be. Perhaps the fix should only apply on Windows?

**Comment by DevCharly** [comment]
You're right, this fix is only for Windows. Thanks.

Currently, this code is not used on macOS,
because custom window decorations are disabled for macOS
(in `FlatLaf.getSupportsWindowDecorations()`).
