### ISSUE TITLE
Memory leak for property change listeners in shared UIs

### ISSUE THREAD

**Issue by ingokegel** [JFormDesigner/FlatLaf#471]
The cached property change listeners in shared UIs strongly reference an instance for which listeners were installed.

![2022-01-24_12-53-56](https://user-images.githubusercontent.com/1199475/150778783-b83acba5-5f82-436a-b889-cca5b4fc4ec1.png)

Should this listener maybe be stored in a client property of the component instead of in a field in the shared UI so that the component can be garbage collected?

**Comment by DevCharly** [comment]
Should be fixed in latest `2.0.1-SNAPSHOT` https://github.com/JFormDesigner/FlatLaf#snapshots

Please give it a try

**Comment by ingokegel** [comment]
Thank you, now it looks good in my tests!
