### ISSUE TITLE
Window paint incomplete

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#472]
When I set a new L&F at runtime, some windows paint is incomplete and needs to be opened and closed two times to be fully painted with the new theme.

![Screenshot_20220124_231934](https://user-images.githubusercontent.com/7027319/150875008-4c9d622e-9afb-4dc8-aa6b-0cb2749b1224.png)

**Comment by DevCharly** [comment]
Does it work without `FlatAnimatedLafChange` ?
What is `disabledLayer`?

**Comment by medmedin2014** [comment]
With `FlatAnimatedLafChange` and `disabledLayer` lines removed it still doesn't work.
`disabledLayer` is a simple `JComponent` that will be set as GlassPane on top of the frame to block all mouse and keyboard events until all UI elements are updated with new theme.

**Comment by DevCharly** [comment]
The "JSignPdf" window looks OK on your screenshot.
It the problem only in the "TSA ..." dialog?

**Comment by medmedin2014** [comment]
Yes, the problem appears on frames and dialogs that were not visible, but if I open and close each of them two or three times then they get fixed and show correct theme.

**Comment by DevCharly** [comment]
You should know that only those components are updated that are in windows.
See `for(Window w : Window.getWindows())`.

Components that are created, but not added to a window, are not updated.
If you later show such components, the have the wrong look.

**Comment by medmedin2014** [comment]
It's an instance of `JDialog` and is member of a class of type `JFrame`.

![text4189-2](https://user-images.githubusercontent.com/7027319/150884913-c08b42eb-f2e3-4537-bceb-895982e05d53.png)

**Comment by DevCharly** [comment]
Very strange... 😕 

When the TSA dialog is shown wrong, does it always look like in the first screenshot? Or random?

Is the TSA dialog repainted correctly if you resize the dialog?

**Comment by medmedin2014** [comment]
It's random, and if I resize the window just a little then the theme is applied instantly to it. I tested it on OpenJDK 8, 11 and 17 and got same result.

**Comment by medmedin2014** [comment]
It seems to occur only on Linux, in my case Manjaro KDE, but on Windows 10 with both OpenJDK 15 and 17 the problem doesn't exist.
