### ISSUE TITLE
ExtendViewIntoTitleBar window property

### ISSUE THREAD

**Issue by WesleiRamos** [JFormDesigner/FlatLaf#478]
There's a way to set [ExtendViewIntoTitleBar](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplicationviewtitlebar.extendviewintotitlebar?view=winrt-22000) property?

![image](https://user-images.githubusercontent.com/7925807/153783532-f0713562-500a-40af-8952-9cace602584d.png)

**Comment by DevCharly** [comment]
No, there is no such property in FlatLaf at the moment. Maybe in the future...

**Comment by WesleiRamos** [comment]
Ok, thanks!
