### ISSUE TITLE
Question: Is the  Demo and Editor jar open-sourced?

### ISSUE THREAD

**Issue by 2catycm** [JFormDesigner/FlatLaf#479]
Hi, there!
I am a student currently learning Java and Swing, and I'm not skilled at using swing components so elegantly and comprehensively like your demo in the README.md do. Would you be so kind to tell me whether the source code for the demo jar  is available?
If yes, I would be really grateful because I can learn swing better.

**Comment by Uguisu32J** [comment]
It's here.
https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-demo

**Comment by 2catycm** [comment]
Awesome！ Thanks for your guidance.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 16, 2022 17:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JFormDesigner/FlatLaf] Question: Is the  Demo and Editor jaropen-sourced? (Issue #479)




 
It's here.
 https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-demo
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
