### ISSUE TITLE
JSplitPane no divider arrow Buttons

### ISSUE THREAD

**Issue by Conversage** [JFormDesigner/FlatLaf#48]
default i dont have any JSplitPane arrow buttons on my divider.

Is there extra customization i have to do or am i missing something?

regards

Nils G.

**Comment by DevCharly** [comment]
You have to enable this feature with:
~~~java
splitPane.setOneTouchExpandable(true);
~~~

See: https://docs.oracle.com/javase/8/docs/api/javax/swing/JSplitPane.html#setOneTouchExpandable-boolean-

**Comment by Conversage** [comment]
well mb for not researching correctly! 
Thank you very mutch.
