### ISSUE TITLE
Repaint doesn't work properly on putClientProperty 

### ISSUE THREAD

**Issue by rooVV** [JFormDesigner/FlatLaf#480]
Hi,
I had a case in an app I code on where an action on a button changed whether or not a combobox was valid. I trimmed everything down to a very minimalistic case :
```
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import com.formdev.flatlaf.FlatLightLaf;

class ComboBoxExample extends JFrame implements ItemListener {

	static JFrame frame;
	static JComboBox combobox;
	static JButton button;

	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel(new FlatLightLaf());
		} catch (UnsupportedLookAndFeelException e) {
			//couldn't load flaf
		}

		frame = new JFrame("frame");

		ComboBoxExample obj = new ComboBoxExample();

		frame.setLayout(new FlowLayout());

		String s1[] = { "yay", "nay" };

		combobox = new JComboBox(s1);
		combobox.setSelectedItem(null);
		combobox.addItemListener(obj);

		button = new JButton("reset");
		button.addActionListener(e -> {
			combobox.setEditable(true);
			combobox.setSelectedItem(null);
			controlCombo();
		});

		JPanel p = new JPanel();

		p.add(combobox);
		p.add(button);

		frame.add(p);
		frame.setSize(400, 200);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
	}

	@Override
	public void itemStateChanged(ItemEvent e) {
		if (e.getSource() == combobox) {
			controlCombo();
		}
	}

	private static void controlCombo() {
		if (String.valueOf(combobox.getEditor().getItem()).isBlank()) {
			combobox.putClientProperty("JComponent.outline", "warning");
		} else {
			combobox.putClientProperty("JComponent.outline", null);
		}
	}
}
```
In this example, the combobox is considered at fault when empty, I don't run a check at first.
![InitialState](https://user-images.githubusercontent.com/55491636/154034575-cd4e435a-21b2-47f7-8116-e899e0af775f.png)
The steps to reproduce my issue is to click the "reset" button right away. Doing so will call the controller of the combobox and find it to be faulty, thus calling ```combobox.putClientProperty("JComponent.outline", "warning");```. However, the outline is not painted properly.
![IncompleteOutline](https://user-images.githubusercontent.com/55491636/154034574-dbdfec7f-340e-435b-bdc0-c980ce71eef6.png)
When I hover over the arrow, the outline is completed, but the colour isn't quite the right one. 
![WrongColourTooLight](https://user-images.githubusercontent.com/55491636/154034576-ed7decc2-0fb3-46af-a077-40016dc36128.png)
When I get the focus the outline is fixed.
![Expectedoutline](https://user-images.githubusercontent.com/55491636/154034573-1b71103d-1750-4179-b7c9-977276a002bb.png)
Two workarounds I found are : forcing the repaint after calling the controller from the button or requesting the focus on the combobox after calling the controller from the button. Forcing the focus changes the expected behaviour so I'm avoiding that method.
Could that be an issue on FlatLaf's side?

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

Yes, it would be better if FlatLaf would redraw the component automatically. I will have a look...

At the moment you have to do:
~~~java
combobox.putClientProperty("JComponent.outline", "warning");
combobox.repaint();
~~~

**Comment by DevCharly** [comment]
Fixed in main branch.
