### ISSUE TITLE
NPE when painting icon on OS X top menu bar

### ISSUE THREAD

**Issue by nroduit** [JFormDesigner/FlatLaf#483]
Painting on the native menu bar triggers a NPE because [the icon is painted with a null component](https://github.com/openjdk/jdk/blob/d7f31d0d53bfec627edc83ceb75fc6202891e186/src/java.desktop/macosx/classes/com/apple/laf/AquaIcon.java#L68).

**Comment by DevCharly** [comment]
Thanks for reporting.

What kind of icon do you use? (SVG, image, ...)
Do you have a stack trace?

**Comment by nroduit** [comment]
This is the class FlatHelpButtonIcon

**Comment by nroduit** [comment]
I made a PR to allow painting icons like FlatHelpButtonIcon, FlatMenuArrowIcon...
