### ISSUE TITLE
TitledBorder doesn't scale using flatlaf.uiScale

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#487]
With 2.0.2 version, the title of border isn't affect by setting system property `flatlaf.uiScale`

![Screenshot_20220227_003530](https://user-images.githubusercontent.com/7027319/155862413-3c8bc6eb-822d-4d83-bfd1-ea5fb145e5e9.png)

**Comment by DevCharly** [comment]
Hmm, this works for me...

Do you pass a font to the constructor of `TitledBorder`?

**Comment by DevCharly** [comment]
Better use following to set title border text color for all titled borders.
Then you can remove title border color in NetBeans GUI builder.

~~~java
UIManager.put( "TitledBorder.titleColor", Color.red );
~~~

**Comment by medmedin2014** [comment]
Thanks :) , In fact I try to avoid global properties because I had bad experience with them because any external L&F theme can ignore it.
