### ISSUE TITLE
How do you get the menu's on the titlebar in the example pic?

### ISSUE THREAD

**Issue by Shadowblitz16** [JFormDesigner/FlatLaf#488]
How do you get the menu's on the titlebar in the example pic?
https://www.formdev.com/flatlaf/screenshots/flat_dark2.png

I can't even get the menubar to be the right color
![image](https://user-images.githubusercontent.com/2453707/155918441-30fe3fa9-5f99-4451-b7c7-8855243d4465.png)

**Comment by Kokecena** [comment]
the menu embedded in the title only works on Windows 10/11

**Comment by DevCharly** [comment]
This will be available for Linux too in FlatLaf **2.1** (see #482)

Please try the latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

To enable it use:
~~~java
if( SystemInfo.isLinux ) {
    // enable custom window decorations
    JFrame.setDefaultLookAndFeelDecorated( true );
    JDialog.setDefaultLookAndFeelDecorated( true );
}
~~~

**Comment by Kokecena** [comment]
Wow that was too fast!

**Comment by Shadowblitz16** [comment]
@DevCharly does this titlebar / menubar work with internal frames also?

**Comment by DevCharly** [comment]
> does this titlebar / menubar theme work with internal frames also?

Yes, internal frames use same/similar look for title bars.
But embedding menu bar into internal frame title bar does not work.

Anyway, internal frames can have menu bars:

![image](https://user-images.githubusercontent.com/5604048/156740199-fee33b94-5a83-481a-a671-85082af92850.png)
