### ISSUE TITLE
How do I change a specific component style individually

### ISSUE THREAD

**Issue by xcfdszzr** [JFormDesigner/FlatLaf#489]
![image](https://user-images.githubusercontent.com/10494040/155936999-93c5e12a-e32c-4eae-8c5e-08941351a94b.png)
           

How to modify the various borders of the button, click color, press color.

So button1 I'm going to click down and it's red,button2 I'm going to click down and it's green, button3 I'm going to click down and  it's yellow.

**Comment by DevCharly** [comment]
> ...click down and it's red...

It is not exactly clear what you mean by that...

If want change the color when the button is in pressed state, use:
~~~java
button1.putClientProperty( "FlatLaf.style", "pressedBackground: #f00" );
button2.putClientProperty( "FlatLaf.style", "pressedBackground: #0f0" );
~~~

Or simple change button background color in a listener:
~~~java
button1.setBackground( Color.red );
~~~

If you want that the user can toggle the state of the button, better use `JToggleButton` and set `selectedBackground`:

~~~java
togglebutton1.putClientProperty( "FlatLaf.style", "selectedBackground: #f00" );
togglebutton2.putClientProperty( "FlatLaf.style", "selectedBackground: #0f0" );
~~~

See also PR #341

**Comment by xcfdszzr** [comment]
Thank you very much to the authors, and it would be a very good thing if you added custom components to the demo.
