### ISSUE TITLE
JXStatusBar does not support FlatLAF on Windows

### ISSUE THREAD

**Issue by ijabz** [JFormDesigner/FlatLaf#492]
I see you have a Swingx add on, but JXStatusBar is not included and this does not look good on Windows please see
see https://stackoverflow.com/questions/71350234/replacement-layoutmanager-for-jxstatusbar-constraints-or-way-to-use-with-jpanel
for more details and example screenshots.

**Comment by DevCharly** [comment]
Add [flatlaf-swingx](https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-swingx) library to your project, then it works fine:

![image](https://user-images.githubusercontent.com/5604048/156919853-7fec721e-cd95-4bbc-9dc0-a992508c42b5.png)
![image](https://user-images.githubusercontent.com/5604048/156919857-baeb7c56-48b9-4f00-a497-d27b83438b58.png)

Without the `flatlaf-swingx` library, it looks indeed wrong:

![image](https://user-images.githubusercontent.com/5604048/156919858-a776fffd-bb94-41c8-8ddc-13bcee3c4cb1.png)
![image](https://user-images.githubusercontent.com/5604048/156919862-a1cb8ef1-9730-4e67-b2d3-74869e0eba61.png)
