### ISSUE TITLE
Scrollbar up and down buttons issues

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#493]
There are 3 issues with scrollbar up and down buttons in FlatLaf v2.0.2:

1. The scrollbar up and down buttons are not well centered with the track 
![Screenshot_20220305_235038](https://user-images.githubusercontent.com/7027319/156902327-dc33cb97-cb49-4b3c-b9d0-97d805f62732.png)
3. The scrollbar up and down buttons doesn't scale with scrollbar width 
![Screenshot_20220305_235225](https://user-images.githubusercontent.com/7027319/156902356-530bc0e0-677a-4f42-acae-fb77a9ef12a3.png)
4. the scrollbar up and down buttons default size is too small and difficult to grab them by mouse
 ![Screenshot_20220305_235410](https://user-images.githubusercontent.com/7027319/156902402-1d032e43-1568-4d91-bf46-c31f161d14b6.png)

**Comment by DevCharly** [comment]
1 and 2 are fixed in main branch

regarding 3: there is now a new UI property `ScrollBar.minimumButtonSize`. Default is `12,12`.

See also:
- https://www.formdev.com/flatlaf/components/scrollbar/
- https://www.formdev.com/flatlaf/customizing/#scrollbar

**Comment by medmedin2014** [comment]
They really look much better 

![Screenshot_20220318_003535](https://user-images.githubusercontent.com/7027319/158914401-203806e0-eb73-4ae8-a7ff-1b196308f2e8.png)
