### ISSUE TITLE
Selected RevealButton icon not visible with most IJ dark themes

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#494]
With most IJ dark themes, reveal button icon in password field becomes hard to see when it's selected.

![Screenshot_20220306_111945](https://user-images.githubusercontent.com/7027319/156919148-40db3920-903c-4dc4-9f9b-75ea328ec6c1.png)
![Screenshot_20220306_112010](https://user-images.githubusercontent.com/7027319/156919151-2f070a6e-afa5-45b8-bcb5-ccd14948572e.png)
![Screenshot_20220306_112024](https://user-images.githubusercontent.com/7027319/156919153-19429615-9af9-4d0f-893c-dd81dfebe88a.png)
![Screenshot_20220306_112039](https://user-images.githubusercontent.com/7027319/156919155-260abb07-9bb2-40b0-b61e-cc1b283f7c61.png)
![Screenshot_20220306_112129](https://user-images.githubusercontent.com/7027319/156919156-e5e929ef-ddf1-4479-acb3-7a7d1074d868.png)
![Screenshot_20220306_112142](https://user-images.githubusercontent.com/7027319/156919157-3e6fdf26-282b-4fa7-bd98-4ffb7eacd288.png)
![Screenshot_20220306_112236](https://user-images.githubusercontent.com/7027319/156919160-191de0d0-5d8d-46bc-bb90-a3569f772d80.png)
![Screenshot_20220306_112253](https://user-images.githubusercontent.com/7027319/156919164-dda172dc-a8f4-46bb-8183-a0950b109eb1.png)
![Screenshot_20220306_112310](https://user-images.githubusercontent.com/7027319/156919165-54445196-ca62-4234-bb9a-320469a7560d.png)
![Screenshot_20220306_112323](https://user-images.githubusercontent.com/7027319/156919166-07e8810b-a018-4dba-bf36-8bfa4314caca.png)
![Screenshot_20220306_112335](https://user-images.githubusercontent.com/7027319/156919167-e2579378-2d33-4059-86de-78badfad1978.png)
![Screenshot_20220306_112347](https://user-images.githubusercontent.com/7027319/156919169-4cd46c95-61bc-4f4d-b8b3-497ff4b13a59.png)
![Screenshot_20220306_112402](https://user-images.githubusercontent.com/7027319/156919171-21987e74-9f8a-4b78-a70d-b8ff02076b7e.png)
![Screenshot_20220306_112413](https://user-images.githubusercontent.com/7027319/156919172-46348a73-1692-45fb-a282-d2b7fb3de2a1.png)
![Screenshot_20220306_112424](https://user-images.githubusercontent.com/7027319/156919175-84eb8aa2-84ad-4975-af43-6a213aff256d.png)
![Screenshot_20220306_112448](https://user-images.githubusercontent.com/7027319/156919176-d07a3806-9347-41b0-b550-00bb38d69b55.png)
![Screenshot_20220306_112500](https://user-images.githubusercontent.com/7027319/156919178-a4bcde8a-422a-454e-8d6f-f38e53df5b28.png)
![Screenshot_20220306_112512](https://user-images.githubusercontent.com/7027319/156919180-b57745b9-f5cb-41ab-bd09-f3da7cf6cbb8.png)
![Screenshot_20220306_112529](https://user-images.githubusercontent.com/7027319/156919181-3662de80-d62b-4467-9525-a7939410400c.png)
![Screenshot_20220306_112549](https://user-images.githubusercontent.com/7027319/156919182-14803bb8-6a63-4c61-88b3-6067f5fee718.png)

**Comment by DevCharly** [comment]
Thanks for reporting. Fixed in main branch.
