### ISSUE TITLE
[Question] is com.formdev.flatlaf.intellijthemes.FlatAllIJThemes.FlatAllIJThemes.INFOS stable and safe

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#495]
Does the method com.formdev.flatlaf.intellijthemes.FlatAllIJThemes.INFOS is safe to be used in future to load list of all supported FlatLaf themes, because I see in class doc that it's automatically generated

![Screenshot_20220306_113118](https://user-images.githubusercontent.com/7027319/156919340-78291a68-381f-47fa-9fff-10331f2775bb.png)

**Comment by DevCharly** [comment]
Yes, it is safe to use. Content may change when themes are added or removed. But API does not change.

**Comment by medmedin2014** [comment]
Thanks :)
