### ISSUE TITLE
Editable combobox loses clear icon after changing theme

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#496]
I tried to set clear icon to a combobox using:
```
((JTextField)((BasicComboBoxEditor)cbAlias.getEditor()).getEditorComponent()).
                putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
```
But after changing the theme at runtime, textfields keep their clear icons but the editable combobox loses it.

**Comment by DevCharly** [comment]
This is because a new `JTextField` component is created when the theme changes.

To fix this, set the client property in `updateUI()`:

~~~java
class ClearComboBox<E> extends JComboBox<E> {
    @Override
    public void updateUI() {
        super.updateUI();
        ((JTextField)((BasicComboBoxEditor)getEditor()).getEditorComponent()).
            putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
    }
}
~~~

**Comment by medmedin2014** [comment]
@DevCharly I didn't know that all UI components are recreated after changing theme. Your fix worked perfectly.

**Comment by DevCharly** [comment]
> I didn't know that all UI components are recreated ...

Usually only **internal** used components are recreated. E.g. arrow buttons in combobox or spinner.
