### ISSUE TITLE
FlatDark is not best match for MacOS Dark mode

### ISSUE THREAD

**Issue by ijabz** [JFormDesigner/FlatLaf#497]
I naively assumed that FlatDark laf would mimic the dark mode on MacOS, but actually it seems a lot lighter. Im no expert on MacOS but I do know that Mac users are very particular about how applications look and therefore would it not be a good idea to use MacOS dark mode as the basis for the FlatDark laf. 

If not I did try out the demo and it seems that maybe GitDark was the best match, why not add a theme called MacOS Dark to give developers  such as myself with no expertise in this the confidence to know what is the best laf to use to best match MacOS native apps.

**Comment by DevCharly** [comment]
There are plans to provide macOS (and Windows) specific light and dark themes, that are closer to the OS look, in the future...

In the meantime you can use following:

Create a file `com/myapp/themes/FlatDarkLaf.properties` (used for dark themes) in your application resources:
```
[mac]@background = #1e1e1e
[mac]@foreground = #e0e0e0
[mac]@accentColor = #107aff
[mac]@accentFocusColor = #176896

[mac]Component.arrowType = chevron

[mac]CheckBox.icon.style = filled
[mac]CheckBox.icon[filled].selectedBorderColor = @accentColor
[mac]CheckBox.icon[filled].selectedBackground = @accentColor
[mac]CheckBox.icon[filled].checkmarkColor = @foreground

[mac]RadioButton.icon.style = filled
[mac]RadioButton.icon[filled].centerDiameter = 6
```

In your `main()` method use:
```java
FlatLaf.registerCustomDefaultsSource( "com.myapp.themes" );
FlatDarkLaf.setup();
```

Then it looks like this on macOS:

![image](https://user-images.githubusercontent.com/5604048/158082131-7295c820-4d30-45c5-88ab-94261a392cc0.png)

Default look for comparison:

![image](https://user-images.githubusercontent.com/5604048/158082167-38e4ec34-45f8-4fd7-b7f4-4f553e17f1c4.png)

**Comment by ijabz** [comment]
Thanks, that looks great.

However,  can I do it i code ?

The reason being introducing config files for different platforms not so easy

**Comment by DevCharly** [comment]
> The reason being introducing config files for different platforms not so easy

The file `FlatDarkLaf.properties` needs to be in your application JAR and
works for all platforms because each line is prefixed with `[mac]` 😉 

To do it in code, have a look at `FlatLaf.setGlobalExtraDefaults()`:
https://www.javadoc.io/static/com.formdev/flatlaf/2.0.2/com/formdev/flatlaf/FlatLaf.html#setGlobalExtraDefaults(java.util.Map)

**Comment by ijabz** [comment]
ok, thanks that works for me

This is my code if they select Dark Mode
```
public static  void install() throws Exception
    {
        Map<String, String> darkModeAdjustments = new HashMap();
        if(Platform.isOSX())
        {
            darkModeAdjustments.put("@background", "#1e1e1e");
            darkModeAdjustments.put("@foreground", "#e0e0e0");
            darkModeAdjustments.put("@accentColor", "#107aff");
            darkModeAdjustments.put("@accentFocusColor", "#176896");
            darkModeAdjustments.put("Component.arrowType", "chevron");
            darkModeAdjustments.put("CheckBox.icon.style", "filled");
            darkModeAdjustments.put("CheckBox.icon[filled].selectedBorderColor", " @accentColor");
            darkModeAdjustments.put("CheckBox.icon[filled].selectedBackground", "@accentColor");
            darkModeAdjustments.put("CheckBox.icon[filled].checkmarkColor", "@foreground");
            darkModeAdjustments.put("RadioButton.icon.style", "filled");
            darkModeAdjustments.put("RadioButton.icon[filled].centerDiameter", "6");
        }
        FlatLaf.setGlobalExtraDefaults(darkModeAdjustments);

        UIManager.put("Table.alternateRowColor", DarkMode.veryDarkGray);

        UIManager.setLookAndFeel(FlatDarkLaf.class.getName());
    }
```
Also found if they set light mode i need to clear out that mapping

```
public static void install() throws Exception
    {
        Map<String, String> macosLightMode = new HashMap();
        FlatLaf.setGlobalExtraDefaults(macosLightMode);

        UIManager.setLookAndFeel(FlatLightLaf.class.getName());

        UIManager.put("Table.alternateRowColor", aquaBlue);
    }
```

**Comment by DevCharly** [comment]
macOS specific themes are coming in FlatLaf 3: see PR #533

**Comment by DevCharly** [comment]
PR #533 merged
