### ISSUE TITLE
Frame default button has inconsistent background color

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#499]
The icon of default button (set by `JFrame.setDefaultButton()`) is hard to see due to inconsistent background color.

**FlatLaf IntelliJ**
![Screenshot_20220309_204915](https://user-images.githubusercontent.com/7027319/157523671-090f33e1-18ba-4cab-9573-acd9c76f9355.png)

The same behaviour is visible with some IntelliJ themes: e.g

**Arc**
![Screenshot_20220309_204945](https://user-images.githubusercontent.com/7027319/157523829-c45927a1-3bd3-4e57-928e-e0a10fd9876c.png)

**Cobalt 2**
![Screenshot_20220309_205947](https://user-images.githubusercontent.com/7027319/157524013-dff31519-edcd-4d63-ba12-173a811f70b6.png)

**Comment by DevCharly** [comment]
The solution is very simple: remove the (useless) icon from the button.

**Comment by DevCharly** [comment]
Most FlatLaf themes use colored default buttons, some do not.

macOS uses blue colored default buttons.
Other operating systems use light gray default buttons (e.g. Windows).

So there are always differences...

**Comment by medmedin2014** [comment]
I agree with removing icons from default frame's button as temporary solution, but sometimes removing them contradicts requirements (they can be mandatory). In fact using normal `Icon` (not `FlatSVGIcon`) can solve the problem but makes whole app looking not okay due to difference in icons look.

**Comment by DevCharly** [comment]
You could implement a custom icon that chooses different colors for the checkmark depending on the button color.

`Icon.paintIcon()` gets the button. You can check whether it is the default button,
then use `UIManager.getColor("Button.default.background")` to get the default button background color.
Then use `ColorFunctions.luma(Color)` to get the "brightness" and either use a light or dark color to paint the checkmark.
