### ISSUE TITLE
LineBorder thickness ignored by scaling

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#500]
I use this code to set all TitledBorder instances thickness

![Screenshot_20220310_013309](https://user-images.githubusercontent.com/7027319/157563754-6c9e8f0e-5d2d-4230-b7f9-1a66e24a66e5.png)

But scaling is applied to Separators and not TitledBorders

![Screenshot_20220310_013058-1](https://user-images.githubusercontent.com/7027319/157564090-b82abd11-94c0-4f08-81bc-c5c8ae4d1bff.png)

![Screenshot_20220310_012850-1](https://user-images.githubusercontent.com/7027319/157564119-03130b9c-8468-4219-8909-44ee4b8ae547.png)

**Comment by DevCharly** [comment]
That's because `javax.swing.border.LineBorder` is a core Swing class and does not know FlatLaf scaling 😉 

Better use `FlatLineBorder` in this case. E.g.
~~~java
new FlatLineBorder( new Insets( 1, 1, 1, 1 ), GuiUtils.darkBlue )
~~~

**Comment by medmedin2014** [comment]
Great :) , this LaF is really fantastic and elegant, what I found confusing is how some Swing components are automatically painted and scaled while others like this case of `LineBorder` are not taken care of and should be swapped by completely new components from FlatLaF library such as `FlatLineBorder`. Is there any documentation that helps newbies users to make right changes.
