### ISSUE TITLE
Reveal icon is clickable even if JPasswordField is disabled

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#501]
Even if `JPasswordField` is disabled, it's possible to click on reveal icon and show/hide typed password.

`FlatLaF v2.0.2`

![Peek 2022-03-15 13-12](https://user-images.githubusercontent.com/7027319/158375468-4c509ae6-f1e4-4fd4-8bde-6e43dcef48b1.gif)

**Comment by DevCharly** [comment]
And why is this a problem?
You still cannot modify the password.

**Comment by sysoutch** [comment]
yeah seems kinda weird being able to click it when disabled

**Comment by Plyha** [comment]
Hello, I also faced the same problem. For example, an application that can store multiple accounts, it would be nice if the user could not see the password if field is disabled.

**Comment by DevCharly** [comment]
Thanks for all your feedback.

I've changed it in latest `2.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Now the reveal button is hidden if the password field is disabled.

**Comment by Plyha** [comment]
Thank you!
