### ISSUE TITLE
IconImage to JButton not set with the correct distance when using setDefaultButton()

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#506]
Dear FlatLaf developers,

I use the FlatLaf libraries in four little Java Swing applications which I have coded.

On most of the look and feels, except the FlatLaf main default look and feel, when using a JButton which is set to default Button with getRootPane().setDefaultButton(),
![flatlaf-setdefaultbutton-iconimage-does-not-align-correctly](https://user-images.githubusercontent.com/102819800/161301178-bb8b31b2-d96a-4066-831a-a344285b3721.png)
 the IconImage of that JButton has not enough distance to the the buttons text.

This issue is there since I use the FlatLaf libriaries (version 1.6.1) and still exists in the new version, version 2.1, which I already use in my Java Swing programs.

I will attach a screenshot of the issue attached to this message.

Thank you very much for this great Java Swing look and feel library.

Sincerely,

Adrian Kiess

**Comment by DevCharly** [comment]
That's probably because the text is painted using bold font, but layout computing is done with regular font. I'll have a look...

**Comment by adriankiess** [comment]
Thank you very much for your answer. The FlatLaf Light/Dark look and feel does not have this issue, but it appears most of the other look and feels. I use all of the FlatLaf look and feels, including the flatlaf-intellij-themes in my applications, the user can choose which look and feel to use.
Many greetings from Germany,
Adrian Kiess

**Comment by DevCharly** [comment]
Fixed in main branch. Thanks.

**Comment by adriankiess** [comment]
Thank you very much! 
Sincerely,
Adrian Kiess
