### ISSUE TITLE
Window Decorations: How to remove the dark border?

### ISSUE THREAD

**Issue by tempaccforissue** [JFormDesigner/FlatLaf#511]
![277455331_675303207040471_112080137139385088_n](https://user-images.githubusercontent.com/102426645/162559908-7611a1f7-194b-48be-a544-b26675cf591d.png)

Any way to remove the dark border around the window?

**Comment by DevCharly** [comment]
For frames:
~~~java
frame.setUndecorated( true );
frame.getRootPane().setWindowDecorationStyle( JRootPane.FRAME );
~~~

For dialogs:
~~~java
dialog.setUndecorated( true );
dialog.getRootPane().setWindowDecorationStyle( JRootPane.PLAIN_DIALOG );
~~~

**Comment by tempaccforissue** [comment]
@DevCharly that did not work.

![Screenshot_2022-04-10_12-09-35](https://user-images.githubusercontent.com/102426645/162604966-6234d5a5-5f78-4d67-b8d1-00c8a3095d7a.png)

Here is my code:
```package com.yasinahmed.notepad;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

public class NotepadApp {
    private JMenuItem createFileMenuItem;
    private JMenuItem openFileMenuItem;
    private JMenuItem saveFileMenuItem;
    private JMenuItem saveAsFileMenuItem;
    private JMenuItem closeFileMenuItem;
    private JMenuItem exitFileMenuItem;
    private JMenu fileMenu;
    
    private JMenuItem undoEditMenuItem;
    private JMenuItem redoEditMenuItem;
    private JMenuItem copyEditMenuItem;
    private JMenuItem cutEditMenuItem;
    private JMenuItem pasteEditMenuItem;
    private JMenuItem selectAllEditMenuItem;
    private JMenuItem findEditMenuItem;
    private JMenu editMenu;
    
    private JMenuItem usageHelpMenuItem;
    private JMenuItem aboutHelpMenuItem;
    private JMenu helpMenu;
    
    private JMenuBar menuBar;
    
    private JMenuItem copyPopupMenuItem;
    private JMenuItem cutPopupMenuItem;
    private JMenuItem pastePopupMenuItem;
    private JMenuItem selectAllPopupMenuItem;
    private JPopupMenu popupMenu;
    
    private JTextArea textArea;
    private JScrollPane scrollPane;
    private JFrame frame;
    
    private void launch(String... args) {
        FlatLightLaf.setup();
        JFrame.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        
        createFileMenuItem = new JMenuItem("Create");
        openFileMenuItem = new JMenuItem("Open");
        saveFileMenuItem = new JMenuItem("Save");
        saveAsFileMenuItem = new JMenuItem("Save As");
        closeFileMenuItem = new JMenuItem("Close");
        exitFileMenuItem = new JMenuItem("Exit");
        
        fileMenu = new JMenu("File");
        fileMenu.add(createFileMenuItem);
        fileMenu.add(openFileMenuItem);
        fileMenu.add(saveFileMenuItem);
        fileMenu.add(saveAsFileMenuItem);
        fileMenu.add(closeFileMenuItem);
        fileMenu.addSeparator();
        fileMenu.add(exitFileMenuItem);
        
        undoEditMenuItem = new JMenuItem("Undo");
        redoEditMenuItem = new JMenuItem("Redo");
        copyEditMenuItem = new JMenuItem("Copy");
        cutEditMenuItem = new JMenuItem("Cut");
        pasteEditMenuItem = new JMenuItem("Paste");
        selectAllEditMenuItem = new JMenuItem("Select All");
        findEditMenuItem = new JMenuItem("Find");
        
        editMenu = new JMenu("Edit");
        editMenu.add(undoEditMenuItem);
        editMenu.add(redoEditMenuItem);
        editMenu.addSeparator();
        editMenu.add(copyEditMenuItem);
        editMenu.add(cutEditMenuItem);
        editMenu.add(pasteEditMenuItem);
        editMenu.add(selectAllEditMenuItem);
        editMenu.addSeparator();
        editMenu.add(findEditMenuItem);
        
        usageHelpMenuItem = new JMenuItem("Usage");
        aboutHelpMenuItem = new JMenuItem("About");
        
        helpMenu = new JMenu("Help");
        helpMenu.add(usageHelpMenuItem);
        helpMenu.add(aboutHelpMenuItem);
        
        menuBar = new JMenuBar();
        menuBar.add(fileMenu);
        menuBar.add(editMenu);
        menuBar.add(helpMenu);
        
        copyPopupMenuItem = new JMenuItem("Copy");
        cutPopupMenuItem = new JMenuItem("Cut");
        pastePopupMenuItem = new JMenuItem("Paste");
        selectAllPopupMenuItem = new JMenuItem("Select All");
        
        popupMenu = new JPopupMenu();
        popupMenu.add(copyPopupMenuItem);
        popupMenu.add(cutPopupMenuItem);
        popupMenu.add(pastePopupMenuItem);
        popupMenu.add(selectAllPopupMenuItem);
        
        textArea = new JTextArea();
        textArea.setComponentPopupMenu(popupMenu);
        
        scrollPane = new JScrollPane(textArea);
        scrollPane.setBorder(null);
        
        frame = new JFrame("Notepad");
        frame.setUndecorated(true);
        frame.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setJMenuBar(menuBar);
        frame.setContentPane(scrollPane);
        frame.setMinimumSize(new Dimension(400, 250));
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
    
    public static void main(String... args) {
        SwingUtilities.invokeLater(() -> {
            new NotepadApp().launch(args);
        });
    }
}```

**Comment by DevCharly** [comment]
Strange, here it works:

![grafik](https://user-images.githubusercontent.com/5604048/162611437-522607a1-1d97-4c95-9fcd-ec129f660b92.png)

Please set a breakpoint at following line and post the stack trace:
https://github.com/JFormDesigner/FlatLaf/blob/f21261914b65c8f3073a22a6c15a3c9e644dd4af/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeWindowBorder.java#L130

**Comment by tempaccforissue** [comment]
> Strange, here it works:
> 
> ![grafik](https://user-images.githubusercontent.com/5604048/162611437-522607a1-1d97-4c95-9fcd-ec129f660b92.png)

Oh, I see. Is that a OS native feature? Actually I am developing on my mobile phone in Ubuntu using [Termux](https://github.com/termux/termux-app) app. The native libraries are incompatible with my mobile's architecture. May be that is why the native feature is not working?

**Comment by tempaccforissue** [comment]
> Strange, here it works:
> 
> ![grafik](https://user-images.githubusercontent.com/5604048/162611437-522607a1-1d97-4c95-9fcd-ec129f660b92.png)

Oh, I see. Is that a OS native feature? Actually I am developing and running the app in my mobile phone using [Termux](https://github.com/termux/termux-app). The native libraries provided by FlatLaf should be incompatible with my mobile's architecture. May be that is why the native feature is not working?

**Comment by DevCharly** [comment]
> Oh, I see. Is that a OS native feature?

`setUndecorated(true)` is a AWT/Swing feature that removes the whole window border including window title bar. This works with all L&Fs on all platforms.

> Actually I am developing and running the app in my mobile phone using [Termux](https://github.com/termux/termux-app).

Does this mean that you're running Swing applications on a Android SmartPhone?

> May be that is why the native feature is not working?

I'm confused. The two screenshots you posted previously show that the FlatLaf native library works on your system.

**Comment by tempaccforissue** [comment]
> Does this mean that you're running Swing applications on a Android SmartPhone?

Yes, I'm running it on a non-root Android device, by installing the XFCE4 (a desktop GUI environment) in Termux's environment.

> I'm confused. The two screenshots you posted previously show that the FlatLaf native library works on your system.

Because the Termux environment provides most of the shared libraries needed to develop and run these softwares.

BTW, I'll try to diagnose the problem, then I'll send report the issues here.

**Comment by DevCharly** [comment]
I'll close this for now.

**Comment by DJ-Raven** [comment]
> For frames:
> 
> ```java
> frame.setUndecorated( true );
> frame.getRootPane().setWindowDecorationStyle( JRootPane.FRAME );
> ```
> 
> For dialogs:
> 
> ```java
> dialog.setUndecorated( true );
> dialog.getRootPane().setWindowDecorationStyle( JRootPane.PLAIN_DIALOG );
> ```

Hello, When I use your code here It's work but The no shadow. How can I keep the shadow ? Thank you.

**Comment by DevCharly** [comment]
> How can I keep the shadow ?

Do not use that code!
