### ISSUE TITLE
With FlatLightLaf and setShowGrid enabled the grid lines are so faint not clear if they are there or not

### ISSUE THREAD

**Issue by ijabz** [JFormDesigner/FlatLaf#514]
With FlatLightLaf and setShowGrid enabled the grid lines are so faint not clear if they are there or not, when I first enabled setShowGrid() I didnt think it was working. I think grid lines should be a little darker so clear they are there (maybe the same as TableHeader.bottomSeparator)

In

Table.gridColor:javax.swing.plaf.ColorUIResource[r=242,g=242,b=242]
Table.backgroung:javax.swing.plaf.ColorUIResource[r=255,g=255,b=255]
TableHeader.separatorColor:javax.swing.plaf.ColorUIResource[r=230,g=230,b=230]
TableHeader.bottomSeparatorColor:javax.swing.plaf.ColorUIResource[r=230,g=230,b=230]
TableHeader.background:javax.swing.plaf.ColorUIResource[r=255,g=255,b=255]

In Contrast using FlatDarkLaf the grid lines can clearly be seen, 

Table.gridColor:javax.swing.plaf.ColorUIResource[r=82,g=86,b=88]
Table.background:javax.swing.plaf.ColorUIResource[r=70,g=73,b=75]
TableHeader.separatorColor:javax.swing.plaf.ColorUIResource[r=95,g=99,b=101]
TableHeader.bottomSeparatorColor:javax.swing.plaf.ColorUIResource[r=95,g=99,b=101]
TableHeader.background:javax.swing.plaf.ColorUIResource[r=70,g=73,b=75]

I see in both dark and light cases the difference in each color component between background and grid is only 13 but for me the difference is only visible for dark, this might be my eyes but thought it was worth pointing out.

**Comment by DevCharly** [comment]
Thanks for your feedback. The grid lines were indeed hard to recognize. I've changed the colors.
