### ISSUE TITLE
JTable horizontal/vertical gridlines missing when using Swingx alternate row highlighting 

### ISSUE THREAD

**Issue by lrhuff8** [JFormDesigner/FlatLaf#517]
Our application uses Swingx JTable alternate row highlighting with horizontal/vertical gridlines. Quite honestly, this implementation is overkill since we really do not need both; one or the other would suffice. However, shouldn't this work? I have included screenshots below that show the issue. You will also see issue #516 here, where the right side "Field Viewer" button does not have a green background, which is set for the active view being displayed. FYI that the FlatLaf UI looks substantially better. 

Here is the application the way it looks with FlatLaf:

![image](https://user-images.githubusercontent.com/5575589/163622940-987d47eb-9caf-4775-9690-6dc4bdb8c417.png)

And here is the same panel using the Windows L&F: 

![image](https://user-images.githubusercontent.com/5575589/163622586-96f8c876-403f-4ed6-b1de-cba2fe81cf3e.png)

**Comment by DevCharly** [comment]
The reason for the missing grid lines is that FlatLaf set the intercell spacing to zero.
This is necessary to have gapless row/column selection.

To fix this use:
~~~java
UIManager.put( "Table.intercellSpacing", new Dimension( 1, 1 ) );
~~~

**Comment by lrhuff8** [comment]
Thanks for the very quick response on this. Your direction that this was related to intercell spacing pointed me in the right direction. I had a bug that was calculating cell preferred width that was not taking intercell spacing into consideration. The Windows L&F did not allow me to encroach on gridline pixels, so I was unaware of the bug. I have this fixed and now the gridlines are showing. I do agree with  issue#514 that the lite gridlines could be a bit darker.
