### ISSUE TITLE
[Question] Is there a way to install custom themes?

### ISSUE THREAD

**Issue by Kokecena** [JFormDesigner/FlatLaf#518]
I am making a player and I included all the themes that flatlaf has, including those of IntelliJ (Using the demo code as a reference in the themes section), after a while I decided to make it possible to place themes separately as it says in the documentation, previously my program saved the name of the theme class and that worked very well well with those that exist in the library, the problem was when I wanted to do the same with the downloaded ones, the problem is that they did not have a class name as such to identify it, so I had to change the way of saving said class, only saving the name of the theme,my question is if there is any way to install other themes so that they come out with their respective class name when I call `UIManager.getLookAndFeel();` or is it impossible?

![image](https://user-images.githubusercontent.com/75457600/163649637-aaeef272-5e3a-4808-adf4-adb64b77513c.png)

This is the way I do it, I'm very new to Java so maybe it's not the best way to do it haha

![image](https://user-images.githubusercontent.com/75457600/163649462-01454801-f2c9-4435-ac08-eb7d2ddfc275.png)

**Comment by DevCharly** [comment]
Well, there are no classes for downloaded IntelliJ themes (`.json` files)...

I would suggest to use the class name for themes provided by FlatLaf,
and use the file name for downloaded IntelliJ themes (`.json` files).

Use a prefix to distinguish them. E.g. `file:myTheme.json`
