### ISSUE TITLE
[BUG] Swing Application FlatLafDark bug.

### ISSUE THREAD

**Issue by TwoThreeTwo** [JFormDesigner/FlatLaf#519]
Issue: So, when I went onto your website for more information on how to set it up. I saw that I could use a try -> catch statement to help implement this as FlatLafLight.setup(); did not work, so I did, and then when I assembled the jar and then launched it, it showed a white background on the main-Screen, but when I clicked to go to the other screen, it showed that it had been using FlatLafDark, I am using the try-catch statement for FlatLafDark on both, but it seems that it is only showing up for 1. I do not know if this is a bug, but if you need me to provide my source code I will provide it to you guys so you can take a look for further help.

**Comment by TwoThreeTwo** [comment]
Well, I am using a JButton being pressed to open up a new page, should I just switch to using file paths? As in, a little section on the top where users can click so they can easilly switch between tabs, I might do that and then try this again. I got to rewrite the entire System if this works.

**Comment by DevCharly** [comment]
I've read your description 3 times and still do not understand what you did, what goes wrong or where you see a bug.

You need to invoke `FlatLightLaf.setup();` only once.
And before you create any Swing components.

Please also check whether your app works with the default look and feel (without FlatLaf and without invoking `UIManager.setLookAndFeel()`.
