### ISSUE TITLE
Combo box pop up highlight color settings?

### ISSUE THREAD

**Issue by Mmerendi22** [JFormDesigner/FlatLaf#520]
Is there a way to change the highlight color in a combo box pop up? I have tried many existing properties but have not found one to do it yet. 

Thanks! Great Product!

**Comment by DevCharly** [comment]
Use `ComboBox.selectionBackground` and `ComboBox.selectionForeground`.

Those properties were indeed missing in the docs:
https://www.formdev.com/flatlaf/components/combobox/
