### ISSUE TITLE
FlatLaf: Some themes miss different color for enabled JFields

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#528]
Dear developers,

some of the themes, in this example, the Gradianto Dark Fuchsia look and feel, miss a highlighted color for enabled JPasswordFields (JFields) using field.setEnabled(true). It is implemented correctly in some themes, for example in the FlatLaf Light look and feel, everything is done the right way.

I am using FlatLaf version 2.2.

I will attach a screenshot to highlight the issue.
![jexercise-flatlaf-some-themes-miss-different-color-for-enabled-jfields](https://user-images.githubusercontent.com/102819800/167112040-b368e58e-7d16-4b03-b013-85cced3c316f.png)

Sincerely,

Adrian Kiess

**Comment by adriankiess** [comment]
Actually, what I mean in the example above, is: field.setEditable(true). Sorry, I confused it with field.setEnabled(), :-)

With many greetings,

Adrian Kiess

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
