### ISSUE TITLE
ComboBox renderer cant center items over expanded list

### ISSUE THREAD

**Issue by smileatom** [JFormDesigner/FlatLaf#53]
Hi,

When rendering a list under the combo box of items and HorizontalAlignment is set to center on both the list and the combobox renderer when it appears, the selected value in the combo box editor is offset by the size of the ComboBox drop down button.  (Cant be centered over the list)

![Screen Shot 2020-01-31 at 11 43 50 PM](https://user-images.githubusercontent.com/22084334/73588945-4a3b6600-4484-11ea-81cc-cb5f5fc31bf4.png)

Is there a way that the centering logic can eliminate the width of the ComboBox open button when centering the editor so the value is centered exactly the same as the list?

**Comment by DevCharly** [comment]
That's tricky...
The arrow buttons is square. 
So the arrow button width is combobox height minus top and bottom insets.

**Comment by smileatom** [comment]
So i was able to do this, but due to the extra space required to offset the size of the drop down button, it seems like the best solution (in the case of images) would be a more custom combobox that did not draw the drop down button at all.
