### ISSUE TITLE
DemoApp mentions formdev macos webpage but it doesn't exist

### ISSUE THREAD

**Issue by ebayedq** [JFormDesigner/FlatLaf#531]
The "DemoFrame" class in den demo project mentions a page

https://www.formdev.com/flatlaf/macos/

but it doesn't seem to exist. Is there a typo in there somewhere?

**Comment by DevCharly** [comment]
The url is correct, but that page is not yet ready and not published... coming soon

**Comment by ebayedq** [comment]
OK, thanks for the info. I'll be sure to check it out!

Also: Thanks for making this awesome LAF available!

**Comment by DevCharly** [comment]
https://www.formdev.com/flatlaf/macos/ is now online 😄

**Comment by ebayedq** [comment]
Thanks, I'll have a look!
