### ISSUE TITLE
Button.hoverForeground??? Can it be added>

### ISSUE THREAD

**Issue by Mmerendi22** [JFormDesigner/FlatLaf#535]
I have a case where my button is a light color background with black text. I use a dark color background on hover to make it "light up", however it is hard to read the black text on the dark color background. Would be nice if I could change the foreground to light so the text is easier to read.

Thanks

**Comment by DevCharly** [comment]
Thanks for the suggestion. The missing foreground colors are now implemented in FlatLaf 2.3
