### ISSUE TITLE
Switching LAF is changing JPanels custom background color

### ISSUE THREAD

**Issue by jokarmus** [JFormDesigner/FlatLaf#539]
Hello,
I have prepared small app with 2 JPanels with 2 background Colors:

```
uiManagerColorPanel.setBackground(UIManager.getColor("Actions.Green"));
constantBasicColorPanel.setBackground(Color.RED);
```

When we are changing LAF  uiManagerColorPanel background color is changing to background of default JPanel color. constantBasicColorPanel stays RED:

![Animation](https://user-images.githubusercontent.com/37440709/169029148-ff985754-f019-4fdb-bffa-3113394a65fe.gif)

Is it intentional? I wanted to set Color taken from UIManager to ensure that it will change to darker/lighter after LAF change, but now color is changing to default. In that case I have to set uiManagerColorPanel background color once again by myself after LAF change which is not very convinient.

[ColorTestFrame.zip](https://github.com/JFormDesigner/FlatLaf/files/8715850/ColorTestFrame.zip)

**Comment by DevCharly** [comment]
This is normal behavior.

If a color is an instance of `javax.swing.plaf.UIResource` (e.g. `ColorUIResource`), then it is replaced when switching Laf.
This is normal Swing behavior. All Swing Lafs work this way.
Colors returned by `UIManager.getColor()` are usually instances of `ColorUIResource`.

To avoid that a color is replaced, you could create a new non-UIResource instance (not recommended in this case). E.g.:

~~~java
uiManagerColorPanel.setBackground(new Color(UIManager.getColor("Actions.Green").getRGB(), true));
~~~

> I wanted to set Color taken from UIManager to ensure that it will change to darker/lighter after LAF change, 

This can not work. `UIManager.getColor("Actions.Green")` returns different colors depending on active Laf.
It is necessary to update color when switching Laf.
This is best done in `updateUI()`:

~~~java
JPanel uiManagerColorPanel = new JPanel() {
    @Override
    public void updateUI() {
        super.updateUI();
        setBackground(UIManager.getColor("Actions.Green"));
    }
};
~~~
