### ISSUE TITLE
MenuItem iconTextGap appears to be affecting margins

### ISSUE THREAD

**Issue by smileatom** [JFormDesigner/FlatLaf#54]
Hi,

iconTextGap is supposed to govern the space between the icon<->text in a label component.
In JMenuItem this appears to be making the entire menu much larger when set.

Here is an example of iconTextGap 4: (Notice that the menu appears to be in general too wide)
![Screen Shot 2020-02-01 at 11 32 07 AM](https://user-images.githubusercontent.com/22084334/73597960-f31aad00-44e6-11ea-9afc-c5cf0aec0b6f.png)

The same menu with iconTextGap of 10:

![Screen Shot 2020-02-01 at 11 32 41 AM](https://user-images.githubusercontent.com/22084334/73597969-062d7d00-44e7-11ea-83be-9d29667bafe4.png)

With an increase in iconTextGap the menu gets wider and wider for no reason.  Its also likely too wide at smaller values due to this issue (this is on MacOS).

On my non-retina display increasing iconTextGap from 4 to 10 increased the menu width by 17 pixels.

**Comment by DevCharly** [comment]
Looks like that iconTextGap is also used for the gap left to the icon, for the gap between text and accelerator, and gap right to accelerarator.

Here is popup menu with two equal menu items, but the second has a large iconTextGap:
![image](https://user-images.githubusercontent.com/5604048/73695331-2a9d7b00-46da-11ea-900a-08ba1bef6149.png)

Same happens in Metal Laf. On Nimbus and Windows Laf it is similar.

FlatLaf currently uses the default menu item layout that is implemented in `sun.swing.MenuItemLayoutHelper`, which uses iconTextGap for all gaps.

I plan to change this for issue #3. Then I can also fix this issue.

**Comment by smileatom** [comment]
Interesting, I guess I assumed it was just the JLabel property for the menu item.  Maybe since theres accelerator and hotkeys that can be displayed in the margins it was overloaded

**Comment by DevCharly** [comment]
fixed in master branch
