### ISSUE TITLE
JOptionPane showconfirmdialog button cutting after upgrade from 1.0 to 2.2

### ISSUE THREAD

**Issue by pmg1991** [JFormDesigner/FlatLaf#540]
Incorrect Black Box on top and buttons are cut as shown in image
![image](https://user-images.githubusercontent.com/34839986/169274107-56769be0-c07f-481e-a9cb-d4cb3656b0c4.png)

**Comment by DevCharly** [comment]
Strange... never seen this.

What Java version is used to run the application?

**Comment by DevCharly** [comment]
Does this occur always? Or only sometimes?

**Comment by pmg1991** [comment]
It happens always.

Although after setting 	UIManager.put( "TitlePane.useWindowDecorations", false); dialog is shown correctly but with white border.  
![image](https://user-images.githubusercontent.com/34839986/170258419-f3b69a3c-6b1d-4a14-a488-34c5a12931c5.png)

**Comment by DevCharly** [comment]
Thanks for the info.

What Java version is used to run the application?

**Comment by pmg1991** [comment]
I have tried with 3 different JDK same partial dialog. 

OpenJDK8U-jdk_x64_windows_hotspot_8u312b07
JBR-17.0.1.12-164.8-jcef
zulu8.54.0.21-ca-jdk8.0.292-win_x64

**Comment by DevCharly** [comment]
Tried to reproduce this on several machines without success.

Does this also happen for own dialogs (class `JDialog`)?

Can you reproduce the problem with following simple app?

~~~java
import javax.swing.*;
import com.formdev.flatlaf.FlatIntelliJLaf;

public class OptionPaneTest
{
	public static void main( String[] args ) {
		SwingUtilities.invokeLater( () -> {
			FlatIntelliJLaf.setup();
			JOptionPane.showConfirmDialog( null, "Do you want to exit the application?" );
		});
	}
}
~~~

**Comment by pmg1991** [comment]
System.setProperty("sun.java2d.opengl", "true"); This line is the culprit.

**Comment by DevCharly** [comment]
@pmg1991 many thanks for the update.
I can now reproduce it. Interestingly only on Windows 10, but not on Windows 11 (using same Java version)...

**Comment by DevCharly** [comment]
FlatLaf window decorations are no longer used if system property `sun.java2d.opengl` is `true` on Windows 10.
