### ISSUE TITLE
JTabbedPane look and feel

### ISSUE THREAD

**Issue by meeeee12** [JFormDesigner/FlatLaf#541]
I am trying to create a JTabbedPane with a similar look to google chrome. like so:

![image](https://user-images.githubusercontent.com/22572797/169636220-a06e9d56-334a-4bbb-ad11-6092dafcdc2a.png)

I can get close by using `tabbedPane.putClientProperty( "JTabbedPane.tabType", "card" );`

![image](https://user-images.githubusercontent.com/22572797/169636578-8ee911a7-d716-4bd5-ba12-fade6191b81c.png)

I would also like to be able to round off the corners and remove the blue select bar. Is either option possible with flatlaf?

**Comment by DevCharly** [comment]
You can remove the blue selection bar with:
~~~java
UIManager.put( "TabbedPane.cardTabSelectionHeight", 0 );
~~~

**Comment by meeeee12** [comment]
Thanks for your help, but my selected tab background is not the same color as the tab area and I can see the square corners protruding from the round corners.

![image](https://user-images.githubusercontent.com/22572797/170268831-578ef776-ec9d-46db-a26a-66e739109ed4.png)

**Comment by DevCharly** [comment]
Override `paintTabBackground()`:
https://github.com/JFormDesigner/FlatLaf/blob/58dbccec2d5264cd2ce0317e49f83c766bd562b7/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTabbedPaneUI.java#L1089-L1096

**Comment by meeeee12** [comment]
That did it. Thank you.
