### ISSUE TITLE
Disabled buttons background

### ISSUE THREAD

**Issue by Ejdzyn** [JFormDesigner/FlatLaf#542]
Hi, I want to change background color of disabled button but its always static color, white by default.

Tried to remove Button.disabledBackground from UIManager but didnt work.

I want some disabled buttons to have orange background and some to have red color f.e.
It can be changed without look and feel

**Comment by DevCharly** [comment]
Use styling:
~~~java
button.putClientProperty( "FlatLaf.style", "disabledBackground: #ff0000" );
~~~

**Comment by Ejdzyn** [comment]
Wow it works

Thanks a lot!
