### ISSUE TITLE
FYI: HashGarten uses FlatLaf

### ISSUE THREAD

**Issue by jonelo** [JFormDesigner/FlatLaf#549]
Thank you very much for FlatLaf.  IMHO it is an excellent Look and Feel which improves the UX/UI for Swing based Java desktop apps.

I am pleased to announce that [HashGarten](https://github.com/jonelo/HashGarten) uses FlatLaf 👍 

[HashGarten](https://github.com/jonelo/HashGarten) is a GUI for [Jacksum](https://jacksum.net) to compute and verify message digests, CRCs, and checksums.

Feel free to add it to the list of application that use FlatLaf if you like.

**Comment by DevCharly** [comment]
I've now added HashGarten to [Applications using FlatLaf](https://github.com/JFormDesigner/FlatLaf#applications-using-flatlaf). Thx.
