### ISSUE TITLE
TextField leading/traling icons and components are always enabled

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#550]
I have noticed that the icons and components inside a text Field ignore the text field enabled status.

Here you can see the user icon (I have added the attribute style="fill:#12739e" to add the blu color in the icon user.SVG) and the components.
![immagine](https://user-images.githubusercontent.com/17149962/172548004-f09ea982-c5b2-43fc-ab68-a62361fc43df.png)

The buttons are enabled and the icon is not grayed

![immagine](https://user-images.githubusercontent.com/17149962/172548082-a278fc3e-507b-43de-ac27-0e763f2b91e7.png)

**Comment by DevCharly** [comment]
Yes, FlatLaf does not disable/enable leading/trailing components added to text fields.
And IMHO it should not do that.

Those components are shown in a text field, but they belong to the application and the application should manage them. You can add any type of component to a text field. FlatLaf can not know what components should be disabled/enabled and which not.

Typically you would create a subclass of `JTextField`, add leading/trailing components in constructor, and override `setEnabled()` to disable/enable leading/trailing components where necessary.

**Comment by basix86** [comment]
Ok, thanks
