### ISSUE TITLE
Apply the light theme only to the JPanel and its children

### ISSUE THREAD

**Issue by tsjung75** [JFormDesigner/FlatLaf#553]
Hello,

I am developing a data analysis application that needs to capture analysis results.
When I choose the dark theme, at the same time I need to use the light theme to capture the analysis panels.

Is there any way to apply the light theme only to the certain JPanel and its children?

**Comment by DevCharly** [comment]
Yes, this is possible. Here is an example

![image](https://user-images.githubusercontent.com/5604048/133428357-f479513f-c9b7-4c80-8501-755dd0f7c476.png)

See https://github.com/JFormDesigner/FlatLaf/issues/363#issuecomment-919953134
