### ISSUE TITLE
Top border is truncated in dark themes on Windows

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#554]
The top border is not visible with all dark themes on Windows 10, while on Linux it looks fine.

```
FlatLaf v2.3
OpenJDK 18
```

![Capture1](https://user-images.githubusercontent.com/7027319/173332976-cf269897-3653-4c67-93e5-2f1755c2fbef.PNG)

**Comment by DevCharly** [comment]
This occurs only on Windows 10 (and not on Windows 11) if window drop shadows are disabled in "System Properties > Performance Options" (see https://www.howtogeek.com/197866/how-to-disable-the-drop-shadows-in-windows-10/)
Then Windows paints only left, right and bottom borders. But not the top border.

Usually this is no problem when windows have drop shadows:

![Capture](https://user-images.githubusercontent.com/5604048/176976814-a6fb9200-7ceb-4b75-9514-d3b3328d4570.PNG)

Anyway, have added a top border.
