### ISSUE TITLE
Exception Access Violation causing crash

### ISSUE THREAD

**Issue by OsenCrow** [JFormDesigner/FlatLaf#556]
Relates to #357 I imagine

Any idea why a Java application using Flatlaf v2.0.1 is terminating unexpectedly? Here is the Windows Event.

![image](https://user-images.githubusercontent.com/107437252/173439248-41ca28a6-86b8-445e-b52f-fed4cafd9f21.png)

It seems potentially related to Windows Decorations. Hard to replicate since it is spontaneous, but it seems to happen when launching new windows within the app.

**Comment by DevCharly** [comment]
Do you have a `hs_err_pid12345.log` file?
Should be in the current directory of the application.
Could you send that file to support@formdev.com (or post it here)?

**Comment by OsenCrow** [comment]
> Do you have a `hs_err_pid12345.log` file? Should be in the current directory of the application. Could you send that file to [support@formdev.com](mailto:support@formdev.com) (or post it here)?

Unfortunately, I cannot find any such error logs in the application directory. I also looked through temp folders. 
We upgraded to version 2.3 and so far it seems stable. I can provide another update soon.
