### ISSUE TITLE
Remove button enabled default color

### ISSUE THREAD

**Issue by Ejdzyn** [JFormDesigner/FlatLaf#560]
Hi again, 
I once asked how to repaint disabled button, but it turns out that was not the way I needed.

I want to remove the trigger that is changing background color ("FlatLaf.style", "disabledBackground: ...").
Disabling the button should leave background color as it was before disabling,  without using putClientProperty().

**Comment by DevCharly** [comment]
Sorry, but I don't understand the problem...

#542

**Comment by Ejdzyn** [comment]
By default, disabling a button does not change its background color, but flatlaf does. I want to turn it off

![default](https://user-images.githubusercontent.com/60040883/176705832-ba4ddcc2-8aa4-4edc-b365-7edbea37c61a.png)
![flatlaf](https://user-images.githubusercontent.com/60040883/176705837-441598e3-22df-498b-a7d3-f1f9c6fe8405.png)

**Comment by DevCharly** [comment]
Ok, I think I understand it now:
you set the background color of a button and want that this color is used for enabled and disabled states.

There is no special option in FlatLaf to do this.
You have to set background and disabledBackground.
