### ISSUE TITLE
macOS unified title bar affordance is too narrow

### ISSUE THREAD

**Issue by ctipper** [JFormDesigner/FlatLaf#562]
I suspect this is to do with JDK implementation of `apple.awt.fullWindowContent` but the affordance using FlatLaf at top of the frame is smaller than other native apps. I am putting this here in the hope that the issue gains some traction. I show a screenshot of my own private app and macOS Safari (macOS 12). When a user attempts to drag using the title bar the target is very narrow, though not insurmountable.

![Screenshot 2022-07-02 at 15.41.50.png](https://www.e-conomist.me.uk/images/Screenshot%202022-07-02%20at%2015.41.50.png)
![Screenshot 2022-07-02 at 15.42.34.png](https://www.e-conomist.me.uk/images/Screenshot%202022-07-02%20at%2015.42.34.png)

> openjdk version "11.0.15" 2022-04-19
> OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
> OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
> macOS 12 (Monterey) iMac 4K Core i7 16GB 512GB

**Comment by ctipper** [comment]
So I've found a workaround with a `javax.swing.border.EmptyBorder` I guess that will get me most of the way there, but achieving the native padding effect seems impossible using existing Java APIs.

**Comment by ctipper** [comment]
I think you have confirmed what I thought and really it would be too much to expect native controls in Java. The property to set a transparent title bar means that the title bar is still available, I only confirmed that after I posted this issue. So I will close this issue.

**Comment by DevCharly** [comment]
Thanks for the info. That's very interesting 👍
