### ISSUE TITLE
Inconsistent selection behavior in table between light and dark themes

### ISSUE THREAD

**Issue by kingthorin** [JFormDesigner/FlatLaf#564]
Version: 2.3

We have an add-on for ZAP that allows setting a color to items in a table, this functionality leverages AbstractHighlighter. In Light mode when a highlighted row is selected the font color changes to white (so you can tell which rows are selected), in dark mode there's no change at all (so you can't tell what's selected).

Here's an animated gif that demonstrates the difference (note when in dark mode and there's a black border briefly I was using ctrl+click to select things). [In use: Flat Light and Flat Dark]
![highlight_example](https://user-images.githubusercontent.com/7570458/178269622-8745688d-12e0-45fa-91a5-7142d5c3869a.gif)

**Comment by DevCharly** [comment]
The reason that in light themes the text color of selected rows is changed to white is that black text is not readable on blue selection background. On the other hand, in dark themes, light gray text on blue selection background is readable.

And if the table is not focused, text is also black in light themes:

![image](https://user-images.githubusercontent.com/5604048/178280519-793998f2-d9a1-4535-86b3-1373cb460fa4.png)

Those selection colors are statically defined in UI properties `Table.selectionForeground` and `Table.selectionInactiveForeground`. There is no magic that automatically changes text color based on (selection) background color.

You should not rely on text color to indicate selection.
Users probably do not understand that "4 Proxy" is selected in below screenshot:

![image](https://user-images.githubusercontent.com/5604048/178280719-298f49b5-9616-4ea4-bc56-e2194e723346.png)

Maybe you could apply red color only to some columns for selected rows. E.g.:

![image](https://user-images.githubusercontent.com/5604048/178287641-c82399ab-f28b-4fae-a641-43a690a435de.png)

or

![image](https://user-images.githubusercontent.com/5604048/178287683-001a8aaf-a9cd-4235-b0ef-99e3f1a1ca28.png)

**Comment by kingthorin** [comment]
Thanks @DevCharly thanks for clarifying the difference I was seeing.

I agree with your point about not depending on text to indicate selection. I’ll see what we can do differently.

Given your explanation I agree this isn’t a Flatlaf issue.
