### ISSUE TITLE
Specify italic font style

### ISSUE THREAD

**Issue by medmedin2014** [JFormDesigner/FlatLaf#567]
There is no way to specify italic style to a component using style class like how we do it for bold `component.putClientProperty( "FlatLaf.styleClass", "h4" )`, the only available alternative is to use `component.putClientProperty( "FlatLaf.style", "font: italic $defaultFont" )` which from [Typography](https://www.formdev.com/flatlaf/typography/#set_style) is used to derive whole new font, but in this case I just want to specify italic style to the default font loaded by the app without deriving any new font.

**Comment by DevCharly** [comment]
Not sure whether I understand the problem.
You want that the whole application uses italic style?

**Comment by medmedin2014** [comment]
@DevCharly I want to set italic style for only some toggle buttons.

**Comment by DevCharly** [comment]
There are several possibilities:

~~~java
toggleButton.setFont( toggleButton.getFont().deriveFont( Font.ITALIC ) );
~~~

or

~~~java
toggleButton.putClientProperty( "FlatLaf.style", "font: italic" );
~~~

or

~~~java
// do this once (after setting look and feel)
UIManager.put( "[style].italic", "font: italic" );

toggleButton.putClientProperty( "FlatLaf.styleClass", "italic" );
~~~

**Comment by medmedin2014** [comment]
@DevCharly Thanks for the detailed response, I think what I'm looking for is the third choice in your given answer.
I opened this issue because I was confused about difference between the two properties : "FlatLaf.styleClass" and "FlatLaf.style" usage, so using only "FlatLaf.styleClass" there is no way to apply italic because the given style classes given in [this table](https://www.formdev.com/flatlaf/typography/#available) include only possibility to change size and width with no italic option. The second properties "FlatLaf.style" allows specifying italic style but from its [description](https://www.formdev.com/flatlaf/typography/#how_to_use) it's used only to create whole new derived font from the default ones.
