### ISSUE TITLE
TitlePane does not respond to full-width events

### ISSUE THREAD

**Issue by insengrim** [JFormDesigner/FlatLaf#569]
This is our title pane with embedded menu bar. Menu bar contains JLabel with additional informations and button with user name (show popup). Application title is on left side (Glue in JMenuBar), support from FlatLaf 2.4. 
![image](https://user-images.githubusercontent.com/109586319/179713116-2a50a555-6522-4642-a979-0ea5c9a6b0ba.png)
Left side with titleLabel react on every events (maximize, minimize and window move). But righ side doesn't. From jmenubar (without menu) right side (additional information) all events are consumed (maximize, minimize and window move).

![image](https://user-images.githubusercontent.com/109586319/179714480-267cf339-8cd3-43e8-b764-5cdf056f7103.png)
Are we doing something wrong? Or is it a bug?
We used window decorations. System.setProperty("flatlaf.useWindowDecorations", Boolean.TRUE.toString());
JMenuBar code (adding components):

```
		description = new JLabel();
		user = new FlatTitlePaneButton();
		add(Box.createGlue() `);'
		add(description);
               add(user);
```
Setting JMenu bar:
```
        JMenuBar mb= new FlatLafMenuBar();  
        WindowManager.getDefault().getMainWindow().setJMenuBar(mb);
```

**Comment by DevCharly** [comment]
This is normal behavior. Only the title label (the glue) allows moving the window (`WM_NCHITTEST` returns `HTCAPTION`). The components left and right to the glue are assumed to be components that need mouse events (e.g. menus or buttons; `WM_NCHITTEST` returns `HTCLIENT`).

ATM there is no way to change this.

Maybe I can extend this a little bit and check children of `JMenuBar` for a special client property (e.g. `FlatLaf.isTitleBarCaption`)...

**Comment by insengrim** [comment]
That's a very good idea and we would use the feature right away.

**Comment by DevCharly** [comment]
This is now implemented in latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

Set following client property:
~~~java
description.putClientProperty( FlatClientProperties.COMPONENT_TITLE_BAR_CAPTION, true );
~~~

**Comment by insengrim** [comment]
We tried this property in snapshot and it's great. Thank You.
