### ISSUE TITLE
Possible to set up a vertical JTabbedPane to have icons 'fixed' to one side while text floats?

### ISSUE THREAD

**Issue by paul-griffith** [JFormDesigner/FlatLaf#571]
I've played around some with the client properties in FlatTabbedPane and wasn't able to accomplish this, but I may just be missing something. I'm trying to achieve the same result described in this SO post: https://stackoverflow.com/questions/26308859/jtabbedpane-tab-placement-set-to-left-but-icons-are-not-aligned

Was hoping the (excellent) FlatLaF might already have this covered :)

**Comment by DevCharly** [comment]
You can do that with:

```java
tabbedPane.putClientProperty( "JTabbedPane.tabAlignment", "leading" );
```
(see https://www.formdev.com/flatlaf/client-properties/#JTabbedPane)

![image](https://user-images.githubusercontent.com/5604048/182543398-32360b6d-b2e8-4480-bfe2-5d503695ae53.png)
