### ISSUE TITLE
Disable tab row rotation

### ISSUE THREAD

**Issue by tduva** [JFormDesigner/FlatLaf#574]
When there are several tab runs/rows they switch around so that the active tab is always in the bottom row. This means that the location of tabs constantly changes as tabs in different rows are selected, which can be irritating.

It's possible to turn this of by overwriting a method of the `BasicTabbedPaneUI`, for example when manually setting the UI in a JTabbedPane:

```
setUI(new FlatTabbedPaneUI() {
            
        @Override
        protected boolean shouldRotateTabRuns(int tabPlacement) {
                return false;
        }

});
```
However a property to disable this globally for all tab panes would be nice. Maybe something like `TabbedPane.rotateTabRuns = false`?

**Comment by DevCharly** [comment]
thanks, implemented in latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
Screenshot with `TabbedPane.rotateTabRuns = false`:

![grafik](https://user-images.githubusercontent.com/5604048/184370312-1a98b602-39bc-478d-bc3b-a94b7c656354.png)

**Comment by tduva** [comment]
Awesome, thanks. 👍
