### ISSUE TITLE
FlatUIUtils.resetRenderingHints should check for null values

### ISSUE THREAD

**Issue by mchmaj** [JFormDesigner/FlatLaf#575]
Hi,
I noticed that some component UIs in FlatLaF save the graphics object rendering hints for antialiasing and stroke control, update them and then re-set the original values after painting is done. However, if the graphics object did not have those hints set in the first place, trying to reset them to original (which is null in that case) can cause an exception to be thrown. This happens for instance in SVGGraphics2D from the jfreesvg library. Adding a check for null in the FlatUIUtils.resetRenderingHints would solve this, it seems.

**Comment by DevCharly** [comment]
many thanks for reporting 👍 
fixed in latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
@mchmaj
Do you use [JFreeSVG](https://github.com/jfree/jfreesvg) to create "screenshots" in SVG format?
I wonder how well this works?

**Comment by mchmaj** [comment]
We have a screenshot functionality in our system wit a few formats available, among them svg using JFreeSVG. It works quite well.
