### ISSUE TITLE
please add breadcrumb component！

### ISSUE THREAD

**Issue by morecup** [JFormDesigner/FlatLaf#578]
such as:
![图片](https://user-images.githubusercontent.com/103871318/185751517-42f3312c-e778-4b71-aa00-47d6b05e1dcb.png)
in IntelliJ
or like
![图片](https://user-images.githubusercontent.com/103871318/185751688-602e9328-8b7d-4755-b317-afc95d143dec.png)
in github
breadcrumb is a usual component。please add it！

**Comment by DevCharly** [comment]
Sorry, but at the moment I've no plans to implement or add a breadcrumb component to FlatLaf.

If you're interested in the IntelliJ breadcrumb, this seems to be the code:
https://github.com/JetBrains/intellij-community/tree/master/platform/platform-api/src/com/intellij/ui/components/breadcrumbs
