### ISSUE TITLE
AbstractButton's ContentAreaFilled=false not honored when parent is a CellRendererPane

### ISSUE THREAD

**Issue by hshafie** [JFormDesigner/FlatLaf#58]
When the ContentAreaFilled property of an RadioButton or CheckBox is set to false and this kind of AbstractButton is painted by a CellRendererPane, its background color is still rendered. This behavior differs from what do the Windows, Metal, GTK+, Nimbus, etc, LAFs.

This behavior is implemented here in FlatLaf 0.26, com/formdev/flatlaf/ui/FlatRadioButtonUI.java:
---
	@Override
	public void paint( Graphics g, JComponent c ) {
		// fill background even if opaque if
		// - used as cell renderer (because of selection background)
		// - if background was explicitly set to a non-UIResource color
		if( !c.isOpaque() &&
			(c.getParent() instanceof CellRendererPane || !(c.getBackground() instanceof UIResource)) )
		{
			g.setColor( c.getBackground() );
			g.fillRect( 0, 0, c.getWidth(), c.getHeight() );
		}
---

---
PS: This is a very minor bug. Other than this, FlatLaf is fast, works great and looks gorgeous in my large, complex, Swing application. Thank you **_very much_**  for your work!

**Comment by smileatom** [comment]
PR submitted https://github.com/JFormDesigner/FlatLaf/pull/63

**Comment by DevCharly** [comment]
@hshafie thanks for reporting.

This is now fixed in master branch.
To try it out you can use the latest snapshot (https://github.com/JFormDesigner/FlatLaf#snapshots).
A new release will be available in a few days.

**Comment by hshafie** [comment]
> To try it out you can use the latest snapshot (https://github.com/JFormDesigner/FlatLaf#snapshots).

No need to try the snapshot. I read your code and found that I made exactly the same modification 

    if( !c.isOpaque() && ((AbstractButton)c).isContentAreaFilled() &&... 

in my copy of FlatLaf 0.26 and I confirm that this change fixes the problem.

I will download and use FlatLaf 0.27 as soon as it will be available.

Many thanks!

**Comment by DevCharly** [comment]
released in 0.27
