### ISSUE TITLE
Bug: setUndecorated() on JFrame or JDialog has no visual effect on Linux

### ISSUE THREAD

**Issue by eduhoribe** [JFormDesigner/FlatLaf#586]
## Sample code:
```java
import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;

class Scratch {
	public static void main(String[] args) {

		JFrame.setDefaultLookAndFeelDecorated(true);

		FlatLightLaf.setup();

		JFrame frame = new JFrame();
		frame.setUndecorated(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(100, 100);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
	}
}
```
### Expected result:
A JFrame/JDialog without the window decoration
![image](https://user-images.githubusercontent.com/40374938/188500914-33bc9950-5659-4b71-a695-29285f763ab0.png)

### Actual result:
A JFrame/JDialog with the window decoration
![image](https://user-images.githubusercontent.com/40374938/188499870-eb4234bb-e8c4-4dab-9156-10be38538110.png)

## Workaround:
```java
frame.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
```

**Comment by DevCharly** [comment]
This is not a bug.
This is normal behavior for look and feels that support window decorations,
where `LookAndFeel.getSupportsWindowDecorations()` returns `true`.

Same happens for Metal L&F:

![grafik](https://user-images.githubusercontent.com/5604048/188514298-99771476-ad2e-41d0-8d5c-0b61697d6bc8.png)

For L&Fs that do not support window decorations (GTK, Windows, Nimbus, etc), you indeed get an empty window.

The reason for this behavior is in `JFrame.frameInit()`: https://github.com/openjdk/jdk/blob/ef20ffe4d222d48f0bdba81a0b864d9fb455e9a6/src/java.desktop/share/classes/javax/swing/JFrame.java#L261-L268

**Comment by eduhoribe** [comment]
I see... Thank you, I'm closing the issue then.
