### ISSUE TITLE
Submenu styling separate from top level menus

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#587]
When customizing menu colors, you can change the selection color for a menu via `Menu.selectionBackground` and for a menu item via `MenuItem.selectionBackground`. However, it appears that `Menu.selectionBackground` applies to both the top level menu (e.g. JMenu in the menu bar) and any submenus (e.g. JMenu > JMenu in the drop down menu) as shown below.

<img width="325" alt="Menu Colors" src="https://user-images.githubusercontent.com/46196614/189447853-7b06986a-8fe1-4bed-abb2-aa57e9cea273.png">

Is it possible to have a different color for top level menus and submenus? Or is there a way to have submenus use the menu item colors?

**Comment by DevCharly** [comment]
Yes, it is possible in latest `2.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

There are two new UI properties `MenuBar.selectionBackground` and `MenuBar.selectionForeground` that are used for top level menus (`JMenu` components in `JMenuBar`). See also https://www.formdev.com/flatlaf/components/menubar/

Usage (for all menu bars):

~~~java
UIManager.put( "MenuBar.selectionBackground", Color.green );
UIManager.put( "MenuBar.selectionForeground", Color.red );
~~~

Styling is also supported (for single menu bar):

~~~java
menuBar.putClientProperty( "FlatLaf.style", "selectionBackground: #0f0; selectionForeground: #f00" );
~~~
