### ISSUE TITLE
Customizing title font and icons

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#589]
The title pane is quite configurable which is great, but I can't see how to achieve the following (at least not via a properties file for a custom theme):

1. Show the application icon in the title bar for regular windows but hide it for dialogs. I see that the icon is not visible when you use `JOptionPane`, but if you create a `Dialog` manually it will display the icon if `TitlePane.showIcon` is set to `true`.
2. Change the font style for the title and menu bar if embedded. I don't see any setting for the for the title other than the base font. `Menu.font` will change the font, but for all instances including submenus. `MenuBar.font` is [noted as "unused"](https://www.formdev.com/flatlaf/components/menubar/) and indeed does not seem to have any effect. Ideally, the menu bar font could match the title font if it is embedded and use its own settings when displayed separately.

**Comment by DevCharly** [comment]
1. For option pane there is another flag `OptionPane.showIcon`, which is `false` by default. 
   There is a client property `JRootPane.titleBarShowIcon` (see https://www.formdev.com/flatlaf/client-properties/#JRootPane) that can be used to hide the icon for dialogs, but this needs to be set on each dialog. There is ATM no option to hide icon for all dialogs.
2. yes, this needs some improvements...

**Comment by DevCharly** [comment]
This is now implemented in main branch.

There are two new UI properties:
- `TitlePane.showIconInDialogs` (boolean; default is true)
- `TitlePane.font` is used for window title

Also `MenuBar.font` is now used for top-level menus (instead of `Menu.font`)
