### ISSUE TITLE
Elements and layout doesn't show up when launching the jar build

### ISSUE THREAD

**Issue by electrogu** [JFormDesigner/FlatLaf#592]
After building the project and launching the JAR file, nothing shows up until the cursor goes over or clicks to a specific element. But there is no problem when running without setting LookAndFeel as FlatLaf with UIManager or while running the project inside the NetBeans.
What should I do?

Editor: Apache Netbeans 12.0
JDK: 11
FlatLaf: 2.4

![flatlaf problem](https://user-images.githubusercontent.com/30390865/191498886-45122fbd-c9c3-41b1-b8c0-34a81d433bbb.gif)

**Comment by DevCharly** [comment]
Strange, could be related to window decorations.

Does it work when you add following to the beginning of `main()`?

~~~java
System.setProperty( "flatlaf.useWindowDecorations", "false" );
~~~

**Comment by DevCharly** [comment]
By default, FlatLaf replaces Windows 10/11 window title bar with own title bar, which allows embedding menu bar into title and styling (e.g. dark title bar):

![image](https://user-images.githubusercontent.com/5604048/191514140-43618ae4-ec6f-4246-9ad3-c705857a75a4.png)

This is with disabled FlatLaf window decorations. The white title bar is painted by Windows 10/11. Menu bar is below title.

![image](https://user-images.githubusercontent.com/5604048/191514089-dcc7c729-58a8-4edb-aa16-a4ddffb997d4.png)

So it seems that there is a FlatLaf window decoration related issue on your machine.
I can not reproduce the issue here.
I'll have a look at the code...

**Comment by DevCharly** [comment]
> ...  saw that still some features like dialogue boxes, text fields and pictures are missing. If this is related to the code or not, is there any way I can fix this problem? 

Hmm, hard to say without details 🤔 
Does it work correctly without FlatLaf? Or with Windows L&F?

> Also, my program doesn't change the color theme from light to dark, is it because of the code you sent to disable window decorations?

Sorry, I'm not sure what you mean 😕

**Comment by electrogu** [comment]
> > ...  saw that still some features like dialogue boxes, text fields and pictures are missing. If this is related to the code or not, is there any way I can fix this problem?
> 
> Hmm, hard to say without details 🤔 Does it work correctly without FlatLaf? Or with Windows L&F?


I checked both without FlafLaf and with Windows L&F. And they are not working for those features either. Sorry for misinterpretation. I am not sure what's causing it.


> So it seems that there is a FlatLaf window decoration related issue on your machine. I can not reproduce the issue here. I'll have a look at the code...

Despite the problem I am having right now, about the first problem -none of the elements showing up properly:
Do you mean that the first problem is caused of something inside the FlafLaf code?

**Comment by DevCharly** [comment]
Yes, the blank windows problem is probably a FlatLaf bug.

Unfortunately I can not reproduce it here.
So I hope you can help me a little bit and test some special JARs.
Maybe next week when your project is finished?

BTW are you sure that double-clicking the JAR uses the same JDK/JRE as the project in your IDE?
To find out, you could add a tooltip to the first menu bar item that shows some info:

~~~java
menuBar1.getMenu( 0 ).setToolTipText(
    System.getProperty( "java.version" ) + "\n"
    + System.getProperty( "java.vendor" ) + "\n"
    + System.getProperty( "java.home" ) );
~~~

![image](https://user-images.githubusercontent.com/5604048/191846144-01e7f8cd-a27e-489b-afc3-7adad84cc6f1.png)

**Comment by electrogu** [comment]
> Yes, the blank windows problem is probably a FlatLaf bug.
> 
> Unfortunately I can not reproduce it here. So I hope you can help me a little bit and test some special JARs. Maybe next week when your project is finished?
> 
> BTW are you sure that double-clicking the JAR uses the same JDK/JRE as the project in your IDE? To find out, you could add a tooltip to the first menu bar item that shows some info:
> 
> ```java
> menuBar1.getMenu( 0 ).setToolTipText(
>     System.getProperty( "java.version" ) + "\n"
>     + System.getProperty( "java.vendor" ) + "\n"
>     + System.getProperty( "java.home" ) );
> ```


Oh. They are not the same, what should I do?

**Comment by DevCharly** [comment]
What it the exact version and vendor of your JDK 16?

**Comment by electrogu** [comment]
> What it the exact version and vendor of your JDK 16?

This is the JAR File
![image](https://user-images.githubusercontent.com/30390865/191940317-99aaa9fc-96a0-4f2d-9fdc-f812dcb9cb02.png)

This is from NetBeans run
![image](https://user-images.githubusercontent.com/30390865/191940546-f40a5b7e-e314-4f0d-9123-29e9be7d9014.png)

**Comment by DevCharly** [comment]
Hmm, tried Oracle JDK 16.0.2 on Windows 11 and on Windows 10. Works fine on both systems.

Could you please download the build artifacts ZIP from this build: https://github.com/JFormDesigner/FlatLaf/actions/runs/3108162250
and test `flatlaf-core/build/libs/flatlaf-2.5-SNAPSHOT.jar` (contained in artifacts ZIP) with you app with enabled window decorations. (remove system property `flatlaf.useWindowDecorations`)

Don't expect that this build fixes the issue, but would be interested whether the blank window is filled gray or green.
Thanks.

**Comment by electrogu** [comment]
> Hmm, tried Oracle JDK 16.0.2 on Windows 11 and on Windows 10. Works fine on both systems.
> 
> Could you please download the build artifacts ZIP from this build: https://github.com/JFormDesigner/FlatLaf/actions/runs/3108162250 and test `flatlaf-core/build/libs/flatlaf-2.5-SNAPSHOT.jar` (contained in artifacts ZIP) with you app with enabled window decorations. (remove system property `flatlaf.useWindowDecorations`)
> 
> Don't expect that this build fixes the issue, but would be interested whether the blank window is filled gray or green. Thanks.

Netbeans run showed green background at first but switched to normal gray layout within just some milliseconds.

In contrast, JAR worked like this:
![image](https://user-images.githubusercontent.com/30390865/191975177-acf18845-e3db-48b1-b7b1-51c547f4264f.png)

**Comment by DevCharly** [comment]
Ok, that either means that FlatLaf `WM_ERASEBKGND` handling paints over Swing components.
Or Swing components are not painted to window.

Here is a new FlatLaf build with disabled `WM_ERASEBKGND` handling:
https://github.com/JFormDesigner/FlatLaf/actions/runs/3113310323

Could you please try this build. Many thanks.

**Comment by electrogu** [comment]
> Ok, that either means that FlatLaf `WM_ERASEBKGND` handling paints over Swing components. Or Swing components are not painted to window.
> 
> Here is a new FlatLaf build with disabled `WM_ERASEBKGND` handling: https://github.com/JFormDesigner/FlatLaf/actions/runs/3113310323
> 
> Could you please try this build. Many thanks.

It's back to the same problem.
![image](https://user-images.githubusercontent.com/30390865/191982674-e3124e1a-d9db-4348-b6d9-62ca98db4bc3.png)

**Comment by DevCharly** [comment]
Ok, for some reason Swing does not initially paint the window...
Have no idea...

Could you please try following build:
https://github.com/JFormDesigner/FlatLaf/actions/runs/3114493008

It uses green in `WM_ERASEBKGND` and does not remove the top title bar from Windows.
So the window should have two title bars.
The question is whether the window content is painted?

**Comment by electrogu** [comment]
The one below has the layout problem but the upper one doesn't have

![image](https://user-images.githubusercontent.com/30390865/192027198-50be0645-6ab2-4c7b-a9db-1c440c0e2394.png)

**Comment by DevCharly** [comment]
Interesting, I think we're coming closer.
Next build: https://github.com/JFormDesigner/FlatLaf/actions/runs/3115378903

**Comment by DevCharly** [comment]
Hmm, didn't expect that 😕 

Have created another build where nearly all message handling is disabled.
https://github.com/JFormDesigner/FlatLaf/actions/runs/3115921068

Also disabled a NULL check.
So this build may crash.
If it crashes, please start the app from command line.
It should output a single line with info about the message and its params.
~~~
"C:\Program Files\Java\jdk-16.0.2\bin\java" -jar yourjar.jar
~~~

BTW can you please run following on command line and post the output?
~~~
"C:\Program Files\Java\jdk-16.0.2\bin\java" -version
~~~

**Comment by electrogu** [comment]
> Hmm, didn't expect that 😕
> 
> Have created another build where nearly all message handling is disabled. https://github.com/JFormDesigner/FlatLaf/actions/runs/3115921068
> 
> Also disabled a NULL check. So this build may crash. If it crashes, please start the app from command line. It should output a single line with info about the message and its params.

Umm, it didn't give crash and it is the same result.
![image](https://user-images.githubusercontent.com/30390865/192064920-27b114ef-fd32-4d22-8346-5d99d871fd6a.png)

> 
> ```
> "C:\Program Files\Java\jdk-16.0.2\bin\java" -jar yourjar.jar
> ```
> 
> BTW can you please run following on command line and post the output?
> 
> ```
> "C:\Program Files\Java\jdk-16.0.2\bin\java" -version
> ```

The output:
![image](https://user-images.githubusercontent.com/30390865/192065009-4685b7d7-11a8-4925-ba73-1da219348830.png)

**Comment by DevCharly** [comment]
Very, very strange 😕 

I have exactly the same Java version here.

Last build for today, which does not invoke any native methods:
https://github.com/JFormDesigner/FlatLaf/actions/runs/3116114883

**Comment by electrogu** [comment]
> Very, very strange 😕
> 
> I have exactly the same Java version here.
> 
> Last build for today, which does not invoke any native methods: https://github.com/JFormDesigner/FlatLaf/actions/runs/3116114883

the problem continues... 😕

![image](https://user-images.githubusercontent.com/30390865/192067828-8cde48d9-79a0-4d27-b533-1f680ea8aef7.png)

**Comment by DevCharly** [comment]
Ok, then the problem seems to be not in the native code.

Maybe a simple `repaint()` is missing:
https://github.com/JFormDesigner/FlatLaf/actions/runs/3116219993

**Comment by electrogu** [comment]
> Ok, then the problem seems to be not in the native code.
> 
> Maybe a simple `repaint()` is missing: https://github.com/JFormDesigner/FlatLaf/actions/runs/3116219993

:(
![image](https://user-images.githubusercontent.com/30390865/192084779-fecf14c8-798d-47ed-9e83-5c688a7d0949.png)

**Comment by DevCharly** [comment]
Very mysterious 🤔 

At the end of your video (in initial post) there is a window with menu bar and tabbed pane.
Does the tabbed pane repaint if you select another tab?
Are menus displayed correctly if they pop down?

Is the whole window painted if you resize it?
If yes, does it afterwards work correctly?

Because disabling code seems to have no effect, I think it is best to try above with following build (original code with green background):
https://github.com/JFormDesigner/FlatLaf/actions/runs/3108162250

**Comment by electrogu** [comment]
Sorry for bad quality, had to reduce the quality to upload here.
I tried to show all the things you asked.
But couldn't understand "pop down".

https://user-images.githubusercontent.com/30390865/192095390-3b93b806-bb3f-4706-90eb-2a78f69d69ea.mp4

In default, I disabled the resize option. To test, I enabled and the result:

https://user-images.githubusercontent.com/30390865/192095765-a1d00b58-1940-43e4-848a-6e5105cc6524.mp4

**Comment by electrogu** [comment]
> Ok, then the problem seems to be not in the native code.
> 
> Maybe a simple `repaint()` is missing: https://github.com/JFormDesigner/FlatLaf/actions/runs/3116219993

I sent the result in the previous comment, is there anything else?

**Comment by electrogu** [comment]
> Very mysterious 🤔
> 
> At the end of your video (in initial post) there is a window with menu bar and tabbed pane. Does the tabbed pane repaint if you select another tab? Are menus displayed correctly if they pop down?
> 
> Is the whole window painted if you resize it? If yes, does it afterwards work correctly?
> 
> Because disabling code seems to have no effect, I think it is best to try above with following build (original code with green background): https://github.com/JFormDesigner/FlatLaf/actions/runs/3108162250

I sent the result in the previous comment, is there anything else?

**Comment by electrogu** [comment]
> Very mysterious 🤔
> 
> At the end of your video (in initial post) there is a window with menu bar and tabbed pane. Does the tabbed pane repaint if you select another tab? Are menus displayed correctly if they pop down?
> 
> Is the whole window painted if you resize it? If yes, does it afterwards work correctly?
> 
> Because disabling code seems to have no effect, I think it is best to try above with following build (original code with green background): https://github.com/JFormDesigner/FlatLaf/actions/runs/3108162250

Hey, I was waiting for your reply but still you didn't. When would you be replying my comment which I sent the videos?

**Comment by DevCharly** [comment]
Thanks for all the information.
I still have no idea whats going on 😕 
I actually expected that window resizing paints its content 😕 

Have you ever tried the FlatLaf Demo on your machine?
https://github.com/JFormDesigner/FlatLaf#demo

If it has the same problem, does it work if you deselect "Options > Window decorations" in menu of demo?

**Comment by electrogu** [comment]
> Thanks for all the information. I still have no idea whats going on 😕 I actually expected that window resizing paints its content 😕
> 
> Have you ever tried the FlatLaf Demo on your machine? https://github.com/JFormDesigner/FlatLaf#demo
> 
> If it has the same problem, does it work if you deselect "Options > Window decorations" in menu of demo?

The demo works properly with both window decorations on and off.

**Comment by DevCharly** [comment]
> The demo works properly with both window decorations on and off.

Oh, then it may be cause by something special in your app...

Do you have a custom repaint manager (class `javax.swing.RepaintManager`) in your app?
Set a method breakpoint at `RepaintManager.setCurrentManager(RepaintManager)` to find out.

**Comment by electrogu** [comment]
> > The demo works properly with both window decorations on and off.
> 
> Oh, then it may be caused by something special in your app...
> 
> Do you have a custom repaint manager (class `javax.swing.RepaintManager`) in your app? Set a method breakpoint at `RepaintManager.setCurrentManager(RepaintManager)` to find out.

I did it and an error showed up. I imported the location of the class RepaintManager.
![image](https://user-images.githubusercontent.com/30390865/193411556-6f4c7d74-b085-41f9-868a-b62f08dfbfc3.png)

**Comment by DevCharly** [comment]
You misunderstood me. You should not add that code.

`javax.swing.RepaintManager` is a class in the JDK and
has a `setCurrentManager()` method to replace the implementation.

**Comment by electrogu** [comment]
> Do you have a custom repaint manager (class `javax.swing.RepaintManager`) in your app?

I don't know.

> You misunderstood me. You should not add that code.
> 
> `javax.swing.RepaintManager` is a class in the JDK and has a `setCurrentManager()` method to replace the implementation.

What should I do then?

**Comment by DevCharly** [comment]
Open that class, set an breakpoint at the method and start you app in the debugger.
If it stops at that method, you can see in the stack trace where it comes from.

**Comment by electrogu** [comment]
> Open that class, set an breakpoint at the method and start you app in the debugger. If it stops at that method, you can see in the stack trace where it comes from.

Umm... 
![image](https://user-images.githubusercontent.com/30390865/193413526-05a72887-9a95-40dc-bcfc-e4783305d961.png)
![image](https://user-images.githubusercontent.com/30390865/193413560-04d5aa6f-c64c-4757-a908-2a764b9ca4ed.png)

**Comment by DevCharly** [comment]
You set an breakpoint at loading class `javax.swing.RepaintManager`.

Please set an breakpoint at method `javax.swing.RepaintManager.setCurrentManager()`

**Comment by electrogu** [comment]
Oh sorry.

The result:
![image](https://user-images.githubusercontent.com/30390865/193414085-d691caaa-2a75-4f4a-8f7f-51686bf2d989.png)

**Comment by DevCharly** [comment]
Ok, seems that it is not invoked.

I think we're not making any progress this way...
Is there a chance that you send me your application jar by email to `support at formdev dot com` ?
Or could you create a stripped-down version of your app that shows only the initial dialog and send that to me?

**Comment by electrogu** [comment]
> Ok, seems that it is not invoked.
> 
> I think we're not making any progress this way... Is there a chance that you send me your application jar by email to `support at formdev dot com` ? Or could you create a stripped-down version of your app that shows only the initial dialog and send that to me?

I sent the email. Did you get it?

**Comment by electrogu** [comment]
> > Ok, seems that it is not invoked.
> > I think we're not making any progress this way... Is there a chance that you send me your application jar by email to `support at formdev dot com` ? Or could you create a stripped-down version of your app that shows only the initial dialog and send that to me?
> 
> I sent the email. Did you get it?

BTW the username and the password are both "admin". You can use it to check whether the dialog boxes are working.

**Comment by DevCharly** [comment]
Thanks. Got it. Will try...

BTW are there exceptions if you start your app on command line?
~~~
"C:\Program Files\Java\jdk-16.0.2\bin\java" -jar yourjar.jar
~~~

**Comment by DevCharly** [comment]
The source code uses JavaFX.

My guess is that your Zulu Java 11 contains JavaFX, but your Oracle Java 16 does not...

~~~
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/util/Pair
	at database.LoginDatabase.checkConnection(LoginDatabase.java:59)
	at views.LoginScreen.formComponentShown(LoginScreen.java:189)
	at views.LoginScreen$1.componentShown(LoginScreen.java:37)
	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6449)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
	at java.desktop/java.awt.Window.processEvent(Window.java:2050)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 30 more
~~~

**Comment by electrogu** [comment]
> The source code uses JavaFX.
> 
> My guess is that your Zulu Java 11 contains JavaFX, but your Oracle Java 16 does not...
> 
> ```
> Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/util/Pair
> 	at database.LoginDatabase.checkConnection(LoginDatabase.java:59)
> 	at views.LoginScreen.formComponentShown(LoginScreen.java:189)
> 	at views.LoginScreen$1.componentShown(LoginScreen.java:37)
> 	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
> 	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
> 	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6449)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
> 	at java.desktop/java.awt.Window.processEvent(Window.java:2050)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
> 	... 30 more
> ```

Oh.
Before using FlatLaf, I was trying to work with JavaFX but as I faced many errors and bugs, I started to continue with Swing but with FlatLaf.
I guess because of the JavaFX, I started to use Zulu JDK.

**Comment by electrogu** [comment]
> The source code uses JavaFX.
> 
> My guess is that your Zulu Java 11 contains JavaFX, but your Oracle Java 16 does not...
> 
> ```
> Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/util/Pair
> 	at database.LoginDatabase.checkConnection(LoginDatabase.java:59)
> 	at views.LoginScreen.formComponentShown(LoginScreen.java:189)
> 	at views.LoginScreen$1.componentShown(LoginScreen.java:37)
> 	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
> 	at java.desktop/java.awt.AWTEventMulticaster.componentShown(AWTEventMulticaster.java:187)
> 	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6449)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2264)
> 	at java.desktop/java.awt.Window.processEvent(Window.java:2050)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
> 	... 30 more
> ```

What should I do?

**Comment by DevCharly** [comment]
> > The source code uses JavaFX.
> > My guess is that your Zulu Java 11 contains JavaFX, but your Oracle Java 16 does not...
> 
> What should I do?

Either remove usage of JavaFX classes from your app, or ship it with Zulu Java 11.

**Comment by electrogu** [comment]
> > > The source code uses JavaFX.
> > > My guess is that your Zulu Java 11 contains JavaFX, but your Oracle Java 16 does not...
> > 
> > 
> > What should I do?
> 
> Either remove usage of JavaFX classes from your app, or ship it with Zulu Java 11.

After getting errors and bugs, I created a new project and continued from that. Hence, I think there are not any classes that uses JavaFX.

**Comment by DevCharly** [comment]
> Hence, I think there are not any classes that uses JavaFX.

Search for "javafx" in your source code 😉 

The code you sent me uses `javafx.util.Pair`

**Comment by electrogu** [comment]
> > Hence, I think there are not any classes that uses JavaFX.
> 
> Search for "javafx" in your source code 😉
> 
> The code you sent me uses `javafx.util.Pair`

Oh yeah. I just remembered. Thanks.
Otherwise, how can I ship it with Zulu?

**Comment by DevCharly** [comment]
Pair is a very small class. Implement your own an get rid of the JavaFX dependency 😉

**Comment by electrogu** [comment]
Thank you for the solution. But still, because of a reason the problem continues.
I changed the JDK to Oracle's JDK 11.
I got the following exception when I ran the JAR from command line:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
        at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
        at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
        at com.formdev.flatlaf.util.ScaledImageIcon.image2bufferedImage(ScaledImageIcon.java:175)
        at com.formdev.flatlaf.util.ScaledImageIcon.paintIcon(ScaledImageIcon.java:121)
        at java.desktop/javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:191)
        at com.formdev.flatlaf.ui.FlatLabelUI.paint(FlatLabelUI.java:248)
        at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:797)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5271)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1707)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1616)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
        at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
        at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
        at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
        at java.desktop/java.awt.Container.paint(Container.java:2003)
        at java.desktop/java.awt.Window.paint(Window.java:3949)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1884)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DevCharly** [comment]
Yes, I've seen this as well.
This is because the image you pass to `JFrame.setIconImages()` does not exist.

**Comment by electrogu** [comment]
> Yes, I've seen this as well. This is because the image you pass to `JFrame.setIconImages()` does not exist.
Oh. But this one?
![image](https://user-images.githubusercontent.com/30390865/193422354-e0e660a2-1084-4028-91a4-f5b71338955d.png)

**Comment by DevCharly** [comment]
`icon.png` does not exist.
See `LoginScreen`:

~~~java
Image icon =  Toolkit.getDefaultToolkit().getImage("icon.png");
this.setIconImage(icon);
~~~

**Comment by electrogu** [comment]
> `icon.png` does not exist. See `LoginScreen`:
> 
> ```java
> Image icon =  Toolkit.getDefaultToolkit().getImage("icon.png");
> this.setIconImage(icon);
> ```

I did it. Finally. I just copied the images to dist folder.

**Comment by electrogu** [comment]
Thank you very much for the support :)
