### ISSUE TITLE
TableCellRenderer with JTextArea is painted over grid line

### ISSUE THREAD

**Issue by flandreas** [JFormDesigner/FlatLaf#596]
I''m using a TableCellRenderer with a JTextArea to render multiline text in a JTable. It seems like the background of the JTextArea is slightly too high, covering the JTable grid line below the row with name "Description".

<img width="355" alt="without-height-correction" src="https://user-images.githubusercontent.com/24633141/192353686-fbfae984-c69f-4438-a418-fb20d74e3a88.png">

When I artificially make the JTextArea slightly less high, the rendering seems correct.

```
textComponent = object : JTextArea() {
	override fun setBounds(x: Int, y: Int, width: Int, height: Int) {
		super.setBounds(x, y, width, height - 1)
	}
}
```

<img width="355" alt="with-size-correction" src="https://user-images.githubusercontent.com/24633141/192354143-1936bdf1-850b-4593-80df-19ced09e5765.png">

However, when selecting the row after applying the above change, the selection over the JTextArea is 1 pixel less high, which is the obvious outcome of the change.

<img width="355" alt="selection-with-size-correction" src="https://user-images.githubusercontent.com/24633141/192354417-d5802e9a-47e6-4bea-81c5-6ad83efcf4e5.png">

When setting up the JTable to adjust the individual row heights, the row with the JTextArea is set to height 60, and that's the same height the JTextArea received when used as a TableCellRenderer.

The only explanation I have is that FlatLaf adds an y offset when drawing the JTextArea's background, or the background is rendered with too much height. Or do I miss something?

**Comment by DevCharly** [comment]
Hi, the problem is probably that FlatLaf sets the intercell spacing to zero (and hides the grid lines).
If you enable grid lines, it may be also necessary to set intercell spacing to `1, 1`.
See this comment for details: https://github.com/JFormDesigner/FlatLaf/issues/348#issuecomment-875044763

**Comment by flandreas** [comment]
That works, thank you very much!
