### ISSUE TITLE
FlatClientProperties.OUTLINE - Small proposal

### ISSUE THREAD

**Issue by Richard-Tang** [JFormDesigner/FlatLaf#602]
I want to do parameter validation in JTextField

FlatLaf already provides the effect of ERROR

```java
textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE_ERROR);
```

<img width="392" alt="image" src="https://user-images.githubusercontent.com/30547741/196020603-ede4a652-e97f-4bbe-b2c2-be86b2734c7c.png">

I hope the OUTLINE can be restored after the parameter input is correct

Below is my way

```java
Color color = UIManager.getColor("JComponent.outline");
textField.putClientProperty("JComponent.outline", color);
```

<img width="400" alt="image" src="https://user-images.githubusercontent.com/30547741/196020826-157c8127-aa6f-46db-a34c-558be5ae128b.png">

Perhaps FlatLaf can increase `FlatClientProperties OUTLINE_NORMAL`，Restore the initial OUTLINE?

```java
textField.putClientProperty(FlatClientProperties.OUTLINE, FlatClientProperties.OUTLINE_NORMAL);
```

This is a small suggestion of functionality :p

**Comment by DevCharly** [comment]
Simply set the client property to `null` to remove the error outline: 😉 

~~~java
textField.putClientProperty( FlatClientProperties.OUTLINE, null );
~~~

**Comment by Richard-Tang** [comment]
> Simply set the client property to `null` to remove the error outline: wink
> 
> ```java
> textField.putClientProperty( FlatClientProperties.OUTLINE, null );
> ```

666666 , so that's it！！！

It worked, thank you! 😄
