### ISSUE TITLE
Regression (w/ fix): JFileChooser has irregular margins

### ISSUE THREAD

**Issue by LoadingByte** [JFormDesigner/FlatLaf#604]
Consider the following minimal example, which draws a `JFileChooser`:

```java
public class Main {
    public static void main(String[] args) {
        FlatLightLaf.setup();
        var frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(new JFileChooser());
        frame.pack();
        frame.setVisible(true);
    }
}
```

In FlatLaf 2.2, this works as expected: the component's margins are precisely dictated by the `new EmptyBorder(12, 12, 11, 11)` set up by `MetalFileChooserUI`. You can measure pixels to convince yourself:

![JFileChooser in FlatLaf 2.2](https://user-images.githubusercontent.com/2351649/196759684-e9784c54-8a4b-4da5-880c-7d8b4bdaa138.png)

Starting with FlatLaf 2.3 however, there are 8 superfluous pixels of margin on the right:

![JFileChooser in FlatLaf 2.3](https://user-images.githubusercontent.com/2351649/196760117-595e0971-ce6a-4d0a-99da-e36155aaa87d.png)

I'm pretty sure that the culprit is [this section of code](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatFileChooserUI.java#L238-L255), which repackages the `topPanel`, `filePane`, and `bottomPanel` in a wrapper `JPanel`, but forgets about the `getAccessoryPanel()` (AP). In addition, it increases the hgap of `JFileChooser`'s `BorderLayout` from 0 to 8 in preparation for FlatLaf's shortcuts panel. Now, seeing that the empty AP is not repackaged but remains subject to `JFileChooser`'s top-level `BorderLayout` with the constraint `LINE_END`, it becomes clear why there are exactly 8 additional pixels on the right.

I think the most straightforward solution is to simply not forget the AP, i.e.:

```diff
			Component north = borderLayout.getLayoutComponent( BorderLayout.NORTH );
+			Component lineEnd = borderLayout.getLayoutComponent( BorderLayout.LINE_END );
			Component center = borderLayout.getLayoutComponent( BorderLayout.CENTER );
			Component south = borderLayout.getLayoutComponent( BorderLayout.SOUTH );
-			if( north != null && center != null && south != null ) {
+			if( north != null && lineEnd != null && center != null && south != null ) {
				JPanel p = new JPanel( new BorderLayout( 0, 11 ) );
				p.add( north, BorderLayout.NORTH );
+				p.add( lineEnd, BorderLayout.LINE_END );
				p.add( center, BorderLayout.CENTER );
				p.add( south, BorderLayout.SOUTH );
				fc.add( p, BorderLayout.CENTER );
			}
```

I've not tested this change myself, but I'm pretty certain it will resolve the issue.

Best,
Felix

**Comment by DevCharly** [comment]
Many thanks for the detailed report and the fix 👍 

You're right, I forgot the (optional) accessory component.

This is the wrong layout of the accessory component in FlatLaf 2.3 - 2.5:

![image](https://user-images.githubusercontent.com/5604048/197186613-6d986871-a12b-494e-aa28-aed2acba6641.png)

Fixed layout (same layout as in other Lafs and in FlatLaf 2.2 and older):

![image](https://user-images.githubusercontent.com/5604048/197186711-de66b75b-ff53-4369-b14c-d19c38cff7ef.png)
