### ISSUE TITLE
JXTreeTable first character within cell has vertical pixels drawn with alternative color 

### ISSUE THREAD

**Issue by x9ware-llc** [JFormDesigner/FlatLaf#606]
I have what appears to be an issue with a JXTreeTable where the first character of a string within a cell can have a vertical pixel line overwritten with an alternate color. I saw this on earlier FlatLaf releases and it still happens with FlatLaf 2.6. The below example of "123456780" is most interesting, where the "1" retains the top and bottom pixel while losing a small vertical pixel line between those two endpoint pixels. Based on my testing, this displays properly using the Windows LAF. When using FlatLaf is also fails with all SwingX row highlighters removed. Any help would be greatly appreciated. Thank you, 

This shows the issue occurring: 

![2022-10-30 08_52_38-Xml Editor](https://user-images.githubusercontent.com/106101653/198882733-b79cbd71-f932-46c4-936e-838fc9177960.png)

This shows the table cell opened for editing, where the string is painted correctly: 

![2022-10-30 09_02_39-Xml Editor](https://user-images.githubusercontent.com/106101653/198884458-688ad5a1-9ff8-418d-8f9d-1ef01c3f0373.png)

And this is an example of it working with Windows LAF:

![2022-10-30 09_15_25-Xml Editor](https://user-images.githubusercontent.com/106101653/198883867-1a5eda52-471c-4244-8f9a-1a86ca3be6b2.png)

**Comment by DevCharly** [comment]
Hmm, works fine here:

![image](https://user-images.githubusercontent.com/5604048/198886118-21dd90de-85b6-4c59-9ab5-7097b474ac52.png)

Looks like you're using a monospaced font in the "Text Value" column, right?
What font is this?

Does the problem also occur if you do not change the font for that column?

**Comment by x9ware-llc** [comment]
I agree all very strange. I have tested and see it fail using SansSerif, Tahoma, and Arial. But I also see it work with Consolas.

**Comment by DevCharly** [comment]
Could you create a minimal test case that demonstrates the issue?
A simple main method, creating a JFrame with a JXTreeTable.
See issue #581 for an example test case.

BTW what Java version do you use?

**Comment by x9ware-llc** [comment]
Based on more testing and isolation, I can now definitely see that it is my problem, so I apologize for bringing this to you. I am using Java 17.
