### ISSUE TITLE
JTextField.placeholderText on MacOs

### ISSUE THREAD

**Issue by Plyha** [JFormDesigner/FlatLaf#617]
Hi, for some reason the text on macOS is not showing up. On Windows and Linux, the text is displayed correctly. We use Flatlaf 2.6 
```
        tfDomain.putClientProperty("JTextField.placeholderText", Res.getString("hint.login.domain"));
        tfPassword.putClientProperty("JTextField.placeholderText", Res.getString("hint.login.password"));
        tfUsername.putClientProperty("JTextField.placeholderText", Res.getString("hint.login.username"));
```

Mac OS:
![image](https://user-images.githubusercontent.com/71222850/204106137-d82e48ff-8b23-4eed-8159-8704e530cb52.png)

Windows and Linux Ubuntu 
![2022-09-04_19-12-42](https://user-images.githubusercontent.com/71222850/204106188-769d4513-28db-498c-941b-b44cf8a9d506.png)
![image](https://user-images.githubusercontent.com/71222850/204106279-233a54d2-0677-4a4f-a1e1-5eb834903b56.png)

**Comment by DevCharly** [comment]
I think the macOS screenshot does not show FlatLaf.
It looks like Aqua (Mac OS X) look and feel, which does not support placeholder text.

**Comment by Plyha** [comment]
Thanks!
