### ISSUE TITLE
Black top border

### ISSUE THREAD

**Issue by mimoguz** [JFormDesigner/FlatLaf#618]
I have a weird bug. On my app, on the right side of the frame there is a button that opens a popup menu that shows a grid view of items. The popup menu can go outside of the frame. Like this:
![Screenshot 1](https://user-images.githubusercontent.com/7283047/204158517-329c78ce-30b4-4bcb-9923-120c285c3c0f.png)

Here is the problem: when I move the mouse cursor out of the button, top border of the frame becomes black (this is a phone photo, because the issue goes away when I try to take a screenshot): 
![Screenshot 2](https://user-images.githubusercontent.com/7283047/204158595-d0a97d23-f1e3-4077-95e6-86dd97c8f51a.jpg)

Weirder, if the popup is so big and overflows from the both sides of the frame, it's just OK, no black border:
![Screenshot 3](https://user-images.githubusercontent.com/7283047/204158690-eb8e6e33-9949-431d-9b08-b2a21667bf8f.jpg)

It's pretty inconsequential, but annoying still 🙂. Maybe a video driver issue?

**Comment by DevCharly** [comment]
Hmm, there is some top-border painting for Windows 10 in FlatLaf, but this is not painted for Windows 11 (since FlatLaf 2.4)

Can you set a breakpoint at following method an check whether it is invoked:

https://github.com/JFormDesigner/FlatLaf/blob/04f1f5921d8af3182e733aa5910742033375c16c/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/JBRCustomDecorations.java#L288

You're using Windows 11, right?
There is no border shown in your screenshots. On my system there is always a 1px border.
I wonder why? Is there some Windows setting to hide the 1px border?

BTW What (exact) Java version do you use?

**Comment by mimoguz** [comment]
> Can you set a breakpoint at following method an check whether it is invoked:

It's not invoked.

>You're using Windows 11, right?
There is no border shown in your screenshots. On my system there is always a 1px border.
I wonder why? Is there some Windows setting to hide the 1px border?

Windows 11 22H2 build 22621.819 with Windows Feature Experience Pack 1000.22636.1000.0. There are borders, just very translucent:

![Light theme](https://user-images.githubusercontent.com/7283047/204189366-8c5d056b-a82d-4694-b537-6021cec543d9.png)

![Dark theme](https://user-images.githubusercontent.com/7283047/204189761-75283e8c-f275-4c89-af51-e253e8dbc905.png)

> BTW What (exact) Java version do you use?

OpenJDK 19.0.1

**Comment by mimoguz** [comment]
I just tested it on my work notebook. It also happens on internal display/Intel UHD graphics, but not on external display/NVidia card. My own computer has an AMD card. So, video driver issue?

**Comment by DevCharly** [comment]
Don't know whether this is a video driver issue.
Will try your app later...

BTW is the black top border also there if you disable FlatLaf window decorations?
https://www.formdev.com/flatlaf/window-decorations/#enable_disable_windows

**Comment by mimoguz** [comment]
> BTW is the black top border also there if you disable FlatLaf window decorations?

With native title bar? No, it's not.

**Comment by mimoguz** [comment]
> Will try your app later...

I'll be thankful.  [Project link.](https://github.com/mimoguz/pixelj) There are a couple of example projects in the examples folder.

**Comment by DevCharly** [comment]
Don't have the effect here...

![image](https://user-images.githubusercontent.com/5604048/205465460-c3d56891-64e5-4351-ae05-f9404fae4401.png)

I'm on Windows 11 21H2 build 22000.1219 Windows Feature Experience Pack 1000.22000.1219.0
Could be also a problem in Windows 11 22H2 😕 

Let's keep this issue open. Perhaps someone else is also experiences this effect...

**Comment by mimoguz** [comment]
Here is something weirder: would you please try it while “Basic Latin” selected? Because I just noticed the black border won’t appear otherwise on my system either. 😕
