### ISSUE TITLE
How to use FlatSVGIcon

### ISSUE THREAD

**Issue by nuth-vireak** [JFormDesigner/FlatLaf#620]
Hello I just started use FlatLaf. Can you give a simple code to display SVG icon in JButton.

**Comment by MXandresMX** [comment]
`button.setIcon(new FlatSVGIcon("resource/icon.svg", 48, 48));`

**Comment by nuth-vireak** [comment]
![image](https://user-images.githubusercontent.com/66857698/204623759-8830e54a-1b5d-448b-898b-2c8e7a71aee8.png)

Why FlatSVGIcon is not shown?

**Comment by MXandresMX** [comment]
The resource path is wrong. Should be "resources/back.svg"

**Comment by nuth-vireak** [comment]
![image](https://user-images.githubusercontent.com/66857698/205091887-b79be778-93ab-4e55-b64a-ac9b7697a4ee.png)

it still the same

**Comment by MXandresMX** [comment]
The problem is how you put the resources in your project.

**Comment by DevCharly** [comment]
Try `new FlatSVGIcon("back.svg")`

I would recommend to put icons into a subfolder/package.
E.g. `src/main/resources/com/myapp/icons` and then use `new FlatSVGIcon("com/myapp/icons/back.svg")`.

Here is how FlatLaf Demo uses FlatSVGIcon:

https://github.com/JFormDesigner/FlatLaf/blob/bb32c727b6d93ac73df9c277285d83857ed524b6/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/BasicComponentsPanel.java#L68-L70

**Comment by Abneco** [comment]
the icon must follow the structure of your project

example

store in `src/main/resources/com/yourpackage/nameapp/icons`

`new JLabel(new FlatSVGIcon("com/yourpackage/nameapp/icons/icon.svg", 22, 22));`

there is a difference for the program icon paths `public class MainFrame extends JFrame`

````java
private void setFrameUp() {
setIconImages(FlatSVGUtils.createWindowIconImages("/com/yourpackage/nameapp/icons/icon.svg"));
}
````
