### ISSUE TITLE
FlatLaf theme editor while using NetBeans

### ISSUE THREAD

**Issue by freedom764** [JFormDesigner/FlatLaf#622]
I am not sure if it is my problem or not. I was using FlatLaf theme editor in Eclipse and it worked perfectly but now I am working in NetBeans and the themes that are created have no effect there. I am using themes to change the accent color but even after  `Theme.setup()` accent color does not change. I would appreciate any help.

**Comment by DevCharly** [comment]
Maybe you need to build the NetBeans project so that the changed properties files are copied to output folder, where the application tries to load them from.

Eclipse does some kind of automatic build every time you save a file (or refresh).

**Comment by freedom764** [comment]
I tried but it does not seem to work. It is most likely a problem on my end so I will not bother you any further. I changed the accent color myself with the code that you provided about a year ago `FlatLaf.setGlobalExtraDefaults( Collections.singletonMap( "@accentColor", "#f00" ) );
FlatIntelliJLaf.setup();`
Thank you so much for your work!
