### ISSUE TITLE
virustotal.com MaxSecure reports "Trojan.Malware.300983.susgen"

### ISSUE THREAD

**Issue by flaphoschi** [JFormDesigner/FlatLaf#623]
Hello!  
I've noticed during a routine check that "MaxSecure" on [virustotal](https://www.virustotal.com/gui/file/6a897cac19c4f48b22884a21a7ddcbfa47c7fda266dba69804a6f847ab9e97c8/detection) (owned by Google) believes FlatLaf contains malicious code named "Trojan.Malware.300983.susgen". I assume this is false positive. Especially because the other 64 scanners doesn't share this opinion.
Occours with `2.1`, `2.4`, `2.6` and nightly `3.0` JAR files.

There is no reason to believe antivirus software in general. Anyway, maybe this could be sorted out?  
Thanks

**Comment by DevCharly** [comment]
Hi, also think this is a false positive. There are more reports on google regarding MaxSecure and .Trojan.Malware.300983.susgen..

I've just signed the DLLs that are in the JAR.

This seems to "fix" the MaxSecure detection, but now Cylance reports "Unsafe" 😕 

https://www.virustotal.com/gui/file/a77bd409876540a7006d8b248e305b5dd6aeb03cd63d4a90f6953fcb0550bcd9?nocache=1

**Comment by DevCharly** [comment]
`flatlaf-3.0.jar` is now fine on VirusTotal:
https://www.virustotal.com/gui/file/969b27aa612c70ecb85664e55d8c5f7678a6188f9db7c5142a81f6e475e19867/detection

**Comment by flaphoschi** [comment]
Thanks for your extra effort. Especially because it is not within a technical scope of the project itself.

**Comment by PhysShell** [comment]
> `flatlaf-3.0.jar` is now fine on VirusTotal: https://www.virustotal.com/gui/file/969b27aa612c70ecb85664e55d8c5f7678a6188f9db7c5142a81f6e475e19867/detection

Hi! How did you manage to get rid of this MaxSecure?

**Comment by DevCharly** [comment]
> Hi! How did you manage to get rid of this MaxSecure? @DevCharly

I digitally signed the DLL, which is within the JAR. See https://github.com/JFormDesigner/FlatLaf/issues/623#issuecomment-1351758817
