### ISSUE TITLE
Add support for TabbedPane foreground color on hover

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#627]
TabbedPane currently only has the ability to set the hover background (via "TabbedPane.hoverColor"). It would be nice to have the option to also set the background, perhaps via "TabbledPane.hoverForeground".

**Comment by DevCharly** [comment]
Implemented in latest `3.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

![grafik](https://user-images.githubusercontent.com/5604048/216815100-b6317082-f8ce-496e-9ee3-cc43561e87c2.png)

There are 2 new (optional) UI properties:
~~~
TabbedPane.hoverForeground
TabbedPane.focusForeground
~~~

This allows e.g. following style:
- normal text color for selected tab
- dimmed text for non-selected tabs
- normal text color if mouse is over tab
- special text color for focused tab
- no tab background for hover and focused tab

![grafik](https://user-images.githubusercontent.com/5604048/216815867-31519396-4b28-4d56-a204-27ae55c1fec0.png)

~~~
TabbedPane.foreground = tint(@foreground,50%)
TabbedPane.selectedForeground = @foreground
TabbedPane.hoverForeground = @foreground
TabbedPane.focusForeground = @accentLinkColor
TabbedPane.hoverColor = null
TabbedPane.focusColor = null
~~~
