### ISSUE TITLE
FlatLaf 2.6: Wrong button hover effect in the FlatLaf IntelliJ Solarized Light look and feel

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#628]
Dear Maintainer,

a small bug in the FlatLaf 2.6 IntelliJ Solarized Light look and feel: The hover effect of JButton's with .setDefaultButton(true) is wrong:

Here, a screenshot:

![jexercise-flatlaf-solarized-light-look-and-feel-wrong-button-hover-effect](https://user-images.githubusercontent.com/102819800/207787769-84799ea9-6b84-4466-8bbb-5b4f0fb7e79b.png)

Thank you for your kind attention.

Sincerely,

Adrian Kieß

**Comment by DevCharly** [comment]
Thanks for reporting.

Fixed in latest `3.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by adriankiess** [comment]
The issue is fixed in 3.1.1. Thank you very much!
