### ISSUE TITLE
Icons in JMenuItems are left aligned

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#631]
When using some icons with different widths in JMenuItems, they appear left aligned (see the play icon and the cross at the bottom) :

<img width="49" alt="image" src="https://user-images.githubusercontent.com/1523778/210100234-0eba870d-32a1-48b6-a0fa-962ee50cfe87.png">

imho they should be centered to make it look more consistent: 

<img width="43" alt="image" src="https://user-images.githubusercontent.com/1523778/210099958-d02b6add-1ea1-4209-9e0f-5b576913f058.png">

I found the place where you render the icons: https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatMenuItemRenderer.java#L454

you already center the icons vertically:

```
		// center because the real icon may be smaller than dimension in iconRect
		int y = iconRect.y + centerOffset( iconRect.height, icon.getIconHeight() );

		// paint
		icon.paintIcon( menuItem, g, iconRect.x, y );
```

but I think you should also center dem horizontally:

```
		// center because the real icon may be smaller than dimension in iconRect
	        int x = iconRect.x + centerOffset( iconRect.width, icon.getIconWidth() );
	        int y = iconRect.y + centerOffset( iconRect.height, icon.getIconHeight() );

		// paint
		icon.paintIcon( menuItem, g, x, y );
```

this is what I did for the second screenshot

**Comment by DevCharly** [comment]
Thanks for pointing out this issue and for the fix.

Fixed in latest `3.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
