### ISSUE TITLE
Vertical buttons?

### ISSUE THREAD

**Issue by DrDaleks** [JFormDesigner/FlatLaf#633]
First off thanks a million for this awesome library 👏. 

I'm currently using tabbed panes with side (left or right) tab placement, but in order to save screen space I'd like to have these buttons vertical (typically the way IDEA does it for side views)

I might have missed it but I don't see a way to get vertical (read +/- 90deg rotated) buttons from client properties. Is that a thing?

I've ended up doing things "manually" by creating a RotatedJButton class and using a JToolbar to handle the tab selection "old-school". 

Thanks in advance for your advice. 

P.S.: now that I write this, would it make sense to just build a "regular" (horizontal) JToolbar and just rotate the whole thing via UI to make it vertical? If so, would that hack apply to tabbed panes as well?

**Comment by DevCharly** [comment]
See PR #758

**Comment by DevCharly** [comment]
implemented in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
