### ISSUE TITLE
How to get icons

### ISSUE THREAD

**Issue by Plyha** [JFormDesigner/FlatLaf#634]
How can I get these icons from the library?
I would like to use them in the application
![image](https://user-images.githubusercontent.com/71222850/211098768-b42a88cf-2f94-4459-be94-d5ed683b08a3.png)

**Comment by DevCharly** [comment]
Those icons shown in the above screenshot are actually SVG icons (see [here](https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-demo/src/main/resources/com/formdev/flatlaf/demo/extras/svg)),
but there are also Swing icons that are used in `JOptionPane`:

![image](https://user-images.githubusercontent.com/5604048/212084888-5b2b23ac-a099-45f9-8956-ba6759661eb5.png)

~~~java
panel.add( new JLabel( new FlatOptionPaneErrorIcon() ) );
panel.add( new JLabel( new FlatOptionPaneInformationIcon() ) );
panel.add( new JLabel( new FlatOptionPaneWarningIcon() ) );
panel.add( new JLabel( new FlatOptionPaneQuestionIcon() ) );
~~~
