### ISSUE TITLE
Tree refresh causes content to be truncated, v3.0

### ISSUE THREAD

**Issue by Corionis** [JFormDesigner/FlatLaf#640]
When a JTree control is refreshed the content is truncated with trailing ellipses (...).  The tree is in a JSplitPane that is significantly wider.

The previous version 2.4 worked correctly. Nothing else has changed.

![Screenshot from 2023-01-12 16-33-10](https://user-images.githubusercontent.com/21012251/212203491-7757a59a-321c-490f-8e7a-8304a957398a.png)

FlatLaf 3.0 on Linux Mint latest running Java 8.

**Comment by DevCharly** [comment]
Hmm, don't have this effect here.
Could be related to commit b736502c274d74c7ddde1861b07519338d3dd7ac, which hides default node icons (closed and opened folders).

Did you set `Tree.showDefaultIcons` to `true` to show them after the update to FlatLaf 3.0?
Or is it a custom tree renderer?

Does it work if you add following?

~~~java
UIManager.put( "Tree.showDefaultIcons", true );
~~~

**Comment by Corionis** [comment]
No, I had not set Tree.showDefaultIcons to true.
No, not a custom tree renderer, but a custom tree cell renderer.

Yes, it works after adding that line! Thank you!! (Gee, that was easy).

**Comment by DevCharly** [comment]
Still trying to understand why this happens...

> No, not a custom tree renderer, but a custom tree cell renderer.

In which method do you set the icon in your renderer?

**Comment by Corionis** [comment]
It's done in:

`public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus)`

after calling `super.getTreeCellRendererComponent(...)`

**Comment by Corionis** [comment]
You can see the code add: [GrokeSoft/ELS Version 4.0.0](https://github.com/GrokSoft/ELS/tree/Version-4.0.0) [ELS/src/com/groksoft/els/gui/browser/NavTreeCellRenderer.java](https://github.com/GrokSoft/ELS/blob/Version-4.0.0/src/com/groksoft/els/gui/browser/NavTreeCellRenderer.java)

**Comment by DevCharly** [comment]
Found the reason for this behavior. It is because you [disable the tree](https://github.com/GrokSoft/ELS/blob/439330203922fe06d293f7a6771e300d0d77cd41/src/com/groksoft/els/gui/browser/Browser.java#L1743-L1760) while updating the table model (which is fine), but the custom tree cell renderer does not have a icon for disabled state. This results in too small nodes, which were not updated when re-enabling tree.

Fixed in latest `3.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
