### ISSUE TITLE
Text antialiasing issue

### ISSUE THREAD

**Issue by ShadelessFox** [JFormDesigner/FlatLaf#641]
On Windows 10 (can't claim about other OSes), in the apps that use FlatLaf, including FlatLaf Demo, I recently started experiencing weird antialiasing caused by the `rt` combination of letters (notice that the letter `r` is cut off on the right):

![image](https://user-images.githubusercontent.com/35821147/212666878-c2b9ca5d-f2fe-425a-89c7-aa0acffaadb7.png)

I'm trying to figure out what's causing it, and it's only reproducible against one of my PCs.

Maybe someone has thoughts on this?

**Comment by ShadelessFox** [comment]
Thanks for the investigation. Should I close the issue, then?

**Comment by DevCharly** [comment]
Yes.

(we can reopen in case someone has some ideas)
