### ISSUE TITLE
Invalid custom theme

### ISSUE THREAD

**Issue by Epresin** [JFormDesigner/FlatLaf#642]
![image](https://user-images.githubusercontent.com/67505848/212853888-a4688a9f-660a-48c5-83b6-fca5dd252535.png)
![image](https://user-images.githubusercontent.com/67505848/212854096-80c62b72-7deb-427c-b267-127b83391d2c.png)
I create a custom theme according to the docs.
![image](https://user-images.githubusercontent.com/67505848/212854317-dd3819dc-e418-4653-a014-e9cb2a95f26c.png)
And used it in the main method, but it only shows the FlatLightLaf theme instead of the one I defined.
My flatlaf version is 3.0.
Is there something wrong with my custom steps?
[MyAppTheme.zip](https://github.com/JFormDesigner/FlatLaf/files/10433183/MyAppTheme.zip)

**Comment by Epresin** [comment]
My flatlaf version is 3.0

**Comment by DevCharly** [comment]
Your theme works fine here.

Maybe it is simply a "build issue" in IntelliJ IDEA.

Please check whether IDEA has copied `MyAppTheme.properties` file to the build output folder `out`.
Maybe you need to move `MyAppTheme.properties` to `main/resources/...`

**Comment by Epresin** [comment]
![image](https://user-images.githubusercontent.com/67505848/213339264-e1d01ebe-01bc-4ae8-b33c-19b7428852b4.png)
I solved this problem by adding one more line to the gradle script, thanks a lot.
