### ISSUE TITLE
Tree not using custom icons in v3.0

### ISSUE THREAD

**Issue by ebayedq** [JFormDesigner/FlatLaf#644]
I'm using my own icons for the tree nodes which I set using

```
Tree.leafIcon=packagename.MyTreeIcon
Tree.closedIcon=packagename.MyTreeIcon
Tree.openIcon=packagename.MyTreeIcon
```

in my own Flatlaf.properties (which extend FlatSVGIcon). This worked up until 3.0 but with 3.0 the tree now shows the default icons (right and downward facing arrows). Is that a bug or do I just have to configure this differently now?

**Comment by DevCharly** [comment]
This is a new feature in FlatLaf 3. See PR #609.

Add following to your properties file to show tree icons:
~~~
Tree.showDefaultIcons = true
~~~

**Comment by ebayedq** [comment]
Thanks, I must've missed that! With that it works, of course!
