### ISSUE TITLE
Add noIconLeftGap to FlatClientProperties

### ISSUE THREAD

**Issue by ArthurKwasny** [JFormDesigner/FlatLaf#645]
It would be great if there was a way to set the noIconLeftGap property for each root panel separately via putClientProperty / FlatClientProperties.

I am trying to achieve having no gap on the left in my primary window while using the default gap in every other windows. Easiest way would be to just set noIconLeftGap for the primary window, but there is no client property for this.

Or is there another approach to this?

**Comment by DevCharly** [comment]
This is a very specific use case. Don't want to add another client property. There are already too many...

Here is a trick to do what you want 😉 

~~~java
UIManager.put( "TitlePane.noIconLeftGap", 0 );
JFrame frame = new JFrame();
// ... create frame content
frame.setVisible( true );
UIManager.put( "TitlePane.noIconLeftGap", null );
~~~
