### ISSUE TITLE
HiDPIUtils.paintAtScale1x() paints at wrong location under special conditions

### ISSUE THREAD

**Issue by DevCharly** [JFormDesigner/FlatLaf#646]
`HiDPIUtils.paintAtScale1x()` paints at wrong location if:

- graphics is rotated and
- graphics is scaled and
- `x` or `y` parameters are not zero

Didn't notice this bug when fixing issue #557, because the used test application always passed `0, 0` for `x, y`... 😒 

The bug does not affect FlatLaf L&F itself because rotation is not used with `HiDPIUtils.paintAtScale1x()` in FlatLaf.
Noticed the bug when using rotated `ScaledImageIcon`, which internally uses `HiDPIUtils.paintAtScale1x()`, in custom application.

Here is a video that demonstrates the issue.
Red rectangle is correct.
Green rectangle is painted using `HiDPIUtils.paintAtScale1x()` at wrong location.

![hdpiutils-bug](https://user-images.githubusercontent.com/5604048/216828752-5f788fbd-2466-493a-82e0-68aaba61c52d.gif)

Fixed:

![hdpiutils-fix](https://user-images.githubusercontent.com/5604048/216828987-ab44c942-c613-4d42-8ce1-de02cb262de8.gif)

CC @kirill-grouchnikov

**Comment by kirill-grouchnikov** [comment]
Nice, I'll take a look if it has any regression in Radiance usage

**Comment by DevCharly** [comment]
Great. The fix is in commit f5f6850172da77cdb553b3c5970d4b47b6f8700c

**Comment by kirill-grouchnikov** [comment]
Something's broken for Radiance's drawing of rotated tabs in LEFT / RIGHT tab placement.

[In here](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/internal/ui/RadianceTabbedPaneUI.java#L1038) I rotate the graphics context for such tabs (90 degrees + translation). Then I call `super.paintTab` on that graphics context to have everything drawn on it, which is `paintTabBackground` + `paintText` + `paintIcon`.

The text and the icon are drawn correctly, but the background isn't visible at all. The background (which is the fill + the border) is drawn by [this function](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/internal/ui/RadianceTabbedPaneUI.java#L657) which is called [from here](https://github.com/kirill-grouchnikov/radiance/blob/sunshine/theming/src/main/java/org/pushingpixels/radiance/theming/internal/ui/RadianceTabbedPaneUI.java#L713).

I don't do any extra translations or rotations in that except for the bottom placement - that continues working correctly. It's only left and right placement that don't show the background.

**Comment by DevCharly** [comment]
Have a strange effect when running Radiance Demo with Java 11 (or 10). This is with latest commit in Radiance repo without any local changes (without HiDPIUtils changes).

![image](https://user-images.githubusercontent.com/5604048/217097147-20dab97c-ac6c-4eed-90e6-b419d52c5082.png) &nbsp; ![image](https://user-images.githubusercontent.com/5604048/217099998-d7d624a5-6766-4f85-81e0-bd6e61e2d991.png)

The strange thing is that this occurs only for Java 10 and 11. It works fine for Java 9, 12, 17, 18 and 19. (have not tried Java 13 - 16)

Occurs also when running pre-compiled https://github.com/kirill-grouchnikov/radiance/blob/sunshine/drop/6.5.0/demo/radiance-theming-demo-6.5.0.jar

**Comment by DevCharly** [comment]
Forgot to mention that this is on Windows 11 without scaling.

**Comment by kirill-grouchnikov** [comment]
Thanks, I'll look into that
