### ISSUE TITLE
Tiling window to the left or right incorrectly shows restore button (linux only)

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#647]
*Reproduction Steps*
1. Launch the demo app (or any app using FlatLaf) in normal windowed mode (i.e. not maximized)
2. Drag the window by the title bar to the left or right edge of the screen
3. When you get the cue that it will maximize it vertically, let go

The window correctly repositions itself to be the full height and use the left or right half of the screen. On Linux, the restore button is now visible and does nothing when clicked. It should instead continue to maximize button as it does on Windows.

The issue appears to be in [`FlatTitlePane.frameStateChanged`](https://github.com/JFormDesigner/FlatLaf/blob/7e91d78633befee769bb0e4a554ba4fdd6d5fdd5/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L363) where it calculates the `maximized` variable. The value of `frame.getExtendedState()` is `Frame.MAXIMIZED_VERT` in this case. The check then comes back as true.

The resolution would be to change the check to `== Frame.MAXIMIZED_BOTH` instead of `!= 0`.

It looks like Windows does not fire a frame state changed event in this case which is why it works as expected.

**Comment by DevCharly** [comment]
Thanks for reporting and for the details. 👍 

Fixed in latest `3.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
