### ISSUE TITLE
Tree.showDefaultIcons=false also hides the custom leaf/open/closed icons of a custom DefaultTreeCellRenderer

### ISSUE THREAD

**Issue by hshafie** [JFormDesigner/FlatLaf#653]
Tree.showDefaultIcons=true or false works great when no custom DefaultTreeCellRenderer has been installed in a JTree.

Tree.showDefaultIcons=true works as expected when a custom DefaultTreeCellRenderer having custom leaf/open/closed icons  has been installed in a JTree. Screenshot Custom_Icons_ShowDefaultIcons_True.png 

Tree.showDefaultIcons=false (the default) does _not_ work as expected when a custom DefaultTreeCellRenderer having custom leaf/open/closed icons  has been installed in a JTree. This setting has the effect of removing the leaf/open/closed icons from the custom DefaultTreeCellRenderer (com/formdev/flatlaf/ui/FlatTreeUI.java, updateRenderer()). Screenshot Custom_Icons_ShowDefaultIcons_False.png

I don't think Tree.showDefaultIcons=false should have an effect on the custom icons of a custom DefaultTreeCellRenderer. That is, my dialog box should look like Screenshot Custom_Icons_ShowDefaultIcons_True.png no matter the value of Tree.showDefaultIcons.

Many thanks for you help. Many thanks for giving us FlatLaf (which IMHO totally saved Java/Swing from being cheesy).

![Custom_Icons_ShowDefaultIcons_True](https://user-images.githubusercontent.com/41793491/222413440-164415e4-90a0-4943-9b1e-ef8242907478.png)

![Custom_Icons_ShowDefaultIcons_False](https://user-images.githubusercontent.com/41793491/222413518-bafd8cb1-1895-4f94-a8e4-ec1a8ada653b.png)

**Comment by DevCharly** [comment]
You're right. Forgot to handle that case. Sorry.

Fixed in latest snapshot.
The icons are now removed only if all three have default icons.

**Comment by hshafie** [comment]
Thank you so much!
