### ISSUE TITLE
Non responsive UI related to big JTable vs selection

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#654]
We have a complex component that is a table with a tree structure and some frozen columns. We now need to display lots of data. With FlatLaf, the UI is unresponsive when there is an active selection. This does not happen with the system look and feel.

Try it with this test case, click to select a cell and use page up/down to navigate:
[BigSelectableTableTest.zip](https://github.com/JFormDesigner/FlatLaf/files/10982549/BigSelectableTableTest.zip)

The reason is that in our complex component, there is cell remapping taking place between tree nodes and on screen rows. It is not a free operation. I found that this line triggers remapping for each row:
https://github.com/JFormDesigner/FlatLaf/blob/875083a92464de5672b8a49516244b5db92b96f1/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTableCellBorder.java#L138

I guess one first optimization would be to not run the second part of the algorithm if the first part returned false and both row and column selections are turned on. Still, I wonder if this can be improved altogether... Imagine the above sample with millions of rows! 😉 

Let me know what you think and do let me know if I can be of any help...
And keep up the good work! 😃

**Comment by Chrriis** [comment]
I took another look at the cell border logic, and I don't understand the intent...

Here is a modified test case with full row selection and 2 editable cells (this test case is NOT to show the original problem):
[BigSelectableTablePartiallyEditableTest.zip](https://github.com/JFormDesigner/FlatLaf/files/11010644/BigSelectableTablePartiallyEditableTest.zip)

Here is what I get when I change selection. Orange point shows which cell has the focus, red outline in image 8 shows the 2 cells that are editable:
![FlatLafTableSelectionLogic](https://user-images.githubusercontent.com/1174202/226168485-0de8eea7-f0a2-474c-a537-9a764cdde37f.png)

Questions:
- Why is cell 1_1 not outlined in image 1 and cell 2_1 outlined in image 2, although they are both not editable?
- Why is cell 4_1 outlined in image 7 but not in image 6?

More generally, what is the cell border class trying to achieve by checking the editable cells in selection?

**Comment by Chrriis** [comment]
Thanks, the performance issue is solved!

As for the logic of cell focus, I am still confused. In the test case `BigSelectableTablePartiallyEditableTest`, uncomment the line `table.setCellSelectionEnabled(true);`. The editable cells are (1;1) and (2;2), but the focus is only shown for the last column whatever is selected...

As a workaround, we activated `defaults.put("Table.showCellFocusIndicator", Boolean.TRUE);`

Perhaps the behavior of cell selection mode should be different from row or column selection mode. In cell selection mode, focus should be shown only when there is more that one cell that is selected (which internally means >= 2 rows, or >= 2 columns).

**Comment by DevCharly** [comment]
> Perhaps the behavior of cell selection mode should be different from row or column selection mode. In cell selection mode, focus should be shown only when there is more that one cell that is selected (which internally means >= 2 rows, or >= 2 columns).

That's what the current implementation does (but only for rows).

In the meantime I think that it would be better to **never show focus** in **cell selection mode**.
If the user uses the arrow keys to navigate to an editable cell, then there is always only one cell selected (in cell selection mode).
If the user presses Shift+Arrow to select multiple cells, he probably does not want edit a cell. He maybe wants copy cell content or do another action.

In **row selection mode** it is different because always all cells of a row are selected. Here it makes sense to show focus if there is an editable cell in that row.

**Comment by DevCharly** [comment]
Have reworked the code again in commit d530624362080dd3dc9d913f7c811b21d14c6f25 (hopefully the last time).

The cell focus is now shown under following conditions:

- always if enabled via UI property `Table.showCellFocusIndicator=true`
- for row selection mode if exactly one row is selected and at least one cell in that row is editable
- for column selection mode if exactly one column is selected and at least one cell in that column is editable
- never for cell selection mode

To avoid possible performance issues, checking for editable cells is limited to 50. If there are more cells to check, the focus indicator is always shown.

**Comment by Chrriis** [comment]
This is perfect! Great job ! 😉
