### ISSUE TITLE
ToggleButton: Allow overriding selectedColor per-instance

### ISSUE THREAD

**Issue by kunstmusik** [JFormDesigner/FlatLaf#657]
I have not been able to find a way yet to override the selected color for a JToggleButton on a per-instance basis.  It seems to me that the only overrides available were for tab style buttons, but I would need this with a regular JToggleButton. Is there a way to achieve this now? If not, could there be support added for this via client properties on the JToggleButton?

**Comment by DevCharly** [comment]
You can do this with the `"FlatLaf.style"` client property. E.g.:

~~~java
myToggleButton.putClientProperty( FlatClientProperties.STYLE, "selectedBackground: #f00" );
~~~

The available properties are documented here:
https://www.formdev.com/flatlaf/components/button/
(see "Style key" column)

See also PR #341

**Comment by kunstmusik** [comment]
Fantastic, that worked very well. Many thanks for the assistance @DevCharly!
