### ISSUE TITLE
Support toolbox-style "small" title bars on Window/Linux, like on MacOS (feature request)

### ISSUE THREAD

**Issue by eirikbakke** [JFormDesigner/FlatLaf#659]
On MacOS, one can do `JRootPane.putClientProperty("Window.style", "small")` on a JFrame or JDialog to have the OS draw a more compact title bar, as seen in the "Fields" JDialog in the following screenshot (from [Ultorg](https://www.ultorg.com/) running with FlatLAF Light):

<img width="563" alt="smalltitle" src="https://user-images.githubusercontent.com/886243/229172024-398b43c9-c465-4574-bfae-4cca456ea4f6.png">

Apple's original documentation for the "Window.style" client property can be found [here](https://developer.apple.com/library/archive/technotes/tn2007/tn2196.html).

It would be nice if FlatLAF could make this kind of title bar style work on Windows and Linux as well, for use with toolbox windows and such.

(As an alternative to a client property, there is also `Windows.setType(Window.Type.UTILITY)`, which was probably meant to be used as a hint for this kind of LAF-specific adjustment in window appearance.)

**Comment by DevCharly** [comment]
Good idea 👍

**Comment by DevCharly** [comment]
@eirikbakke I've now implemented this feature in PR #702

If you want to try it out, pre-built JARs are available in the artifacts of this build:
https://github.com/JFormDesigner/FlatLaf/actions/runs/5706662697

**Comment by eirikbakke** [comment]
Oh, that's brilliant, thanks for implementing that! Will test...

**Comment by eirikbakke** [comment]
Works great in a stand-alone Java app. I tried with JDialog and JFrame, with a non-empty title set, and with both putClientProperty and Windows.setType. Thanks again!

**Comment by DevCharly** [comment]
Merged PR #702

**Comment by eirikbakke** [comment]
I see that FlatLAF 3.2 is now released; would you like me to make the "Upgrade FlatLaf from 3.1 to 3.2" PR for NetBeans, following the pattern in https://github.com/apache/netbeans/pull/5818 ?

**Comment by DevCharly** [comment]
@eirikbakke that would be great. Thank you. 👍 

There is a new DLL in FlatLaf 3.2 for Windows on ARM64. If NB supports this platform, it would be good to also extract this DLL from flatlaf.jar similar to the other DLLs.

**Comment by eirikbakke** [comment]
I had a chance to the Small Title Bar feature on Windows from within my NetBeans Platform app now; it works very nicely:

<img width="490" alt="smalltitle" src="https://github.com/JFormDesigner/FlatLaf/assets/886243/5c493c53-3e9f-4af0-9796-f2ec463ec131">

Tested dragging-to-resize, close button etc. All works well.

Thanks again! Next up, will post the NetBeans PR for upgrading the FlatLaf version...

**Comment by eirikbakke** [comment]
I prepared the version bump pull request for NetBeans at https://github.com/apache/netbeans/pull/6362
