### ISSUE TITLE
Custom Window Decorations on MACOS How to Disable Movement 

### ISSUE THREAD

**Issue by Link-Kou** [JFormDesigner/FlatLaf#660]
Look at the GIF picture

![2023-04-05_21-52-57 (1)](https://user-images.githubusercontent.com/22113151/230102313-77af56c9-768b-4d1d-9d75-552c2d1e57ea.gif)

When I click the button or the Label, it still triggers the window move event, so I want to click the button or the Label and the window doesn't move.

**Comment by DevCharly** [comment]
You are using client property `apple.awt.fullWindowContent`, right?
https://www.formdev.com/flatlaf/macos/#full_window_content

This is a feature of the JDK.
Can't do anything to change this behavior 😞 

But is is not a big problem.
Usually people to not click-and-drag on a button.
Simple click works as expected.

**Comment by Link-Kou** [comment]
@DevCharly  
yes
```xml
apple.awt.fullWindowContent
```


But so far there are obvious problems. The reason is simple: most Windows implement a user on a button that is unable to trigger a move.

**Comment by Link-Kou** [comment]
@DevCharly  
Whether to disable the movement, to implement separately

**Comment by Link-Kou** [comment]
@DevCharly  Or if you can make the area that you can move smaller

**Comment by DevCharly** [comment]
> But so far there are obvious problems. The reason is simple: most Windows implement a user on a button that is unable to trigger a move.

Can you click the button? Press-and-release mouse button (without moving).

**Comment by Link-Kou** [comment]
@DevCharly 
How do you do that?

My goal is to make window movement impossible right on the button

**Comment by Link-Kou** [comment]
@DevCharly 

IDEA ，new UI  It solved the problem I described.

![image](https://user-images.githubusercontent.com/22113151/230816441-35accee8-9636-4796-acc5-639139f1e3e3.png)
