### ISSUE TITLE
Null border persistence through FlatLaf.updateUI() call

### ISSUE THREAD

**Issue by iclkevin** [JFormDesigner/FlatLaf#663]
There are a few JComponents in my interface with borders set to null. When using the FlatLaf.updateUI() function, borders are returned to these components. Is there a more appropriate way to use FlatLaf to remove borders on components so they do not reappear when calling FlatLaf.updateUI()?

**Comment by DevCharly** [comment]
Yes, this is common problem with Swing L&F switching: if a border is null (or an instanceof UIResource), it is replaced with the default border of the new L&F. See installBorder():

https://github.com/openjdk/jdk/blob/9e20382311c58bd172abc98bc0a6757c3a64dda1/src/java.desktop/share/classes/javax/swing/LookAndFeel.java#L230-L235

To avoid this, use an empty border instead:

~~~java
c.setBorder( BorderFactory.createEmptyBorder() );
~~~

**Comment by iclkevin** [comment]
This worked. Thank you. I see this is a Swing concern, not a FlatLaf concern.
