### ISSUE TITLE
Possibly better support for SVG icons

### ISSUE THREAD

**Issue by weisJ** [JFormDesigner/FlatLaf#664]
As I understand it currently SVG icons are rendered using the svgSalamander library. Sadly it isn't under active development anymore and won't return to it anytime soon. I have been developing an alternative to it (https://github.com/weisJ/jsvg) and in the meantime it has become almost on par feature-wise with svgSalamander in some areas and exceeds it in some others. In particular the only missing features I am aware of are animations and element picking by position which aren't exposed through `FlatSVGIcon` anyway.

Note: The Jetbrains team recently switched from rendering their UI icons with Batik to JSVG, so the library seems to work well for them:
https://github.com/JetBrains/intellij-community/commit/93a8fe3d8376a1ee4b4bcf4cf85d991afc01013d

I was wondering whether replacing svgSalamander with JSVG would be something to consider here? If yes I would be happy to prepare a PR :)

**Comment by weisJ** [comment]
I have released version 1.0.0 and submitted a PR. There were some outstanding performance and correctness issues with commonly used filters which I wanted to get fixed first hence the wait.

**Comment by DevCharly** [comment]
JSVG is coming to FlatLaf 3.2 😄
