### ISSUE TITLE
Possibility to opt-out of rounded-popups?

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#665]
We just upgraded from 2.0.1 to 3.1.

I think the rounded popups and tooltips on Windows 11 is an improvement. Unfortunately it causes problems in a place where we use popups to reveal hidden data (aka data tips). For example, an object is in a tree, but it is only partially visible in the scroll pane.

Here is before/after:
![FlatLafWindow11Popups](https://user-images.githubusercontent.com/1174202/231827247-fb35299c-4207-4107-8912-c5f4883dbea3.png)

The problem is not exactly the fact that now the popup is round and has a shadow, but the fact that if we double click on it the object underneath does not open in 3.1. It does not receive the double click. I suspect that 2.0.1 is using a lightweight popup and 3.1 forced it to heavyweight.

So: is there a way to have the old popup behavior for certain elements of the UI?

**Comment by Chrriis** [comment]
Thanks for your help!

I don't want to deactivate the feature for all popups in these components so I had to modify the data tip library itself (and another similar pattern) with such code:
```Java
String borderCornerRadiusPropertyKey = "Popup.borderCornerRadius";
Object oldBorderCornerRadiusPropertyValue = parentComponent.getClientProperty(borderCornerRadiusPropertyKey);
try {
  parentComponent.putClientProperty(borderCornerRadiusPropertyKey, 0);
  popup = popupFactory.getPopup(parentComponent, dataTipComponent, tipPosition.x, tipPosition.y);
} finally {
  parentComponent.putClientProperty(borderCornerRadiusPropertyKey, oldBorderCornerRadiusPropertyValue);
}
popup.show();
```

The above seems to work. Do you think this is the right approach?
Without thinking too much about it, wouldn't it be better to have a way to activate Windows 11 rounded feature only for JPopupMenu and JToolTip?

**Comment by DevCharly** [comment]
> The above seems to work. Do you think this is the right approach?

LGTM

> Without thinking too much about it, wouldn't it be better to have a way to activate Windows 11 rounded feature only for JPopupMenu and JToolTip?

This is already available. There are 4 UI properties for configuration:

~~~
PopupMenu.borderCornerRadius
ComboBox.borderCornerRadius
ToolTip.borderCornerRadius
Popup.borderCornerRadius
~~~

The first three are used for JPopupMenu, JComboBox and JToolTip.
The last one is used for other components show as popup via PopupFactory.getPopup().
