### ISSUE TITLE
JFrame is not maximized correctly

### ISSUE THREAD

**Issue by samic2020** [JFormDesigner/FlatLaf#666]
I´m Brazilian programmer.

I was using PlatLaf  version 2.4 with Java8 and the command was not working correctly:
                       setExtendedState(Frame.MAXIMIZED_BOTH);
I switched to version 3.1 and the problem continues.

Any sugetions,

Souza, Wellington

**Comment by DevCharly** [comment]
Hmm, works fine for me.

Does is work if you use Metal L&F (or any other L&F)?

**Comment by samic2020** [comment]
Hi!
Only the FlatLaf LookAndFeel.
I´m using the FlatLightLaf() and FlatDarkLaf().

Example:
try { UIManager.setLookAndFeel(new FlatLightLaf() ); } catch (UnsupportedLookAndFeelException ex) { ex.printStackTrace(); }

**Comment by DevCharly** [comment]
Please try whether following test case works for you:

~~~java
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLightLaf;

public class MaximizeTest {
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            FlatLightLaf.setup();

            JFrame frame = new JFrame( "MaximizeTest" );
            frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
            frame.setBounds( 50, 50, 400, 200 );
            frame.setExtendedState( JFrame.MAXIMIZED_BOTH );
            frame.setVisible( true );
        } );
    }
}
~~~

**Comment by samic2020** [comment]
Worked, thank you.
