### ISSUE TITLE
Material themes have large spaces in the menus

### ISSUE THREAD

**Issue by nroduit** [JFormDesigner/FlatLaf#667]
Since version 3.1, the material themes have much larger spaces in the menus. Is it intentional? It doesn't seem very coherent to me compared to the other lists which are compact.
| Version 3.1 | Previous versions or non-material |
|--------|--------|
|![image](https://user-images.githubusercontent.com/993975/232237665-a0eeafaa-7051-4da5-893e-e44ad71feccb.png) | ![image](https://user-images.githubusercontent.com/993975/232237671-02521e28-3dc8-40b0-88aa-b92814068cfa.png) |

**Comment by DevCharly** [comment]
No, this is not intentional.

In 3.1, I've updated the 3rd party themes to the latest versions. Unfortunately some properties have changed to "bad" values.
Besides too large menu item padding, the table row height is also too large.

**Comment by DevCharly** [comment]
fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by DevCharly** [comment]
FlatLaf 3.1.1 is now available
