### ISSUE TITLE
flatlaf-windows-x86_64.dll very infrequently not found 

### ISSUE THREAD

**Issue by x9ware-llc** [JFormDesigner/FlatLaf#674]
BTW, sincerely thank you for a great product. I have upgraded from 2.6 to 3.1.1 in the last couple of days and have gotten the message that flatlaf-windows-x86_64.dll is not found (message is below). This is correct, because I have the DLL removed from the JAR. However, the class that sets the look and feel has a static initializer that worked with 2.6, but seems to be slightly sporadic with 3.1.1, where it throws this error maybe once every 20 launches. I assume it must be some type of timing issue. I see the error thrown 5-6 seconds after startup, and it does not take any human UI interaction to generate the error. Any thoughts? 

Here is my static initializer:  

	static {
		System.setProperty("flatlaf.useWindowDecorations", "false");
	}

And the message that I am getting: 

2023-05-01 12:22:06.399 [SEVERE] Library 'com/formdev/flatlaf/natives/flatlaf-windows-x86_64.dll' not found (com.formdev.flatlaf.util.LoggingFacadeImpl.logSevere)

**Comment by DevCharly** [comment]
> This is correct, because I have the DLL removed from the JAR

Why?

`flatlaf.useWindowDecorations` does not disable usage of the DLL.

The DLL is also used for rounded popup borders (on Win 11) and in class `SystemInfo` to determine Windows 11.
There is no way to disable usage of the DLL.

You maybe get the message as soon as a popup is shown (tooltip, combobox list, menu, ...).
You can find out easy by setting a breakpoint 😉

**Comment by DevCharly** [comment]
I've added another system property to disable usage of FlatLaf native library:

~~~java
System.setProperty( "flatlaf.useNativeLibrary", "false" );
~~~

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
