### ISSUE TITLE
FYI on this: java.lang.IllegalArgumentException: Comparison method violates its general contract! #1628

### ISSUE THREAD

**Issue by x9ware-llc** [JFormDesigner/FlatLaf#675]
This is not a FlatLaf issue but I wanted to provide the information so you can be aware. Please close this issue as soon as you read. 

The problem is associated with JFileChooser in Windows, and specifically the left-side column that contains buttons for Home, Recent, Desktop, Documents, This PC, and Network. When there are top-level folders that exist in two of these button choices, you can get the above IllegalArgumentException when you switch from one to the other. This is evidently an issue that has existed since at least 2015, but evidently has only gotten recent identification. I have experienced it on JDK 17. In my case, it happened when I had duplicate folder names in Recent Items, which obviously would be expected. I am not sure of when it gets fixed, but a JDK bug report has been opened within the last month or so. Here is some research on the issue: 

https://github.com/skylot/jadx/issues/1628 

https://forum.vassalengine.org/t/cannot-open-window-for-load-save-or-beginlogs/76730/27  

https://github.com/vassalengine/vassal/pull/12152

**Comment by conker-rsc** [comment]
Just commenting 1.5 years down the line to thank @x9ware-llc for posting this, helped me track down an issue
