### ISSUE TITLE
IntelliJ cannot find new fonts package after updating, even after doing a clean install of library

### ISSUE THREAD

**Issue by Hedreon** [JFormDesigner/FlatLaf#676]
Title says it most. It's very irritating. I want to use the new Inter font, but I can't, because it can't find the new `fonts` package. What do I do? (I may add more details to this tomorrow)

What I mean by, "even after doing a clean install of library" is deleting the entire library in the `.m2/repository` folder, and then running `mvn -U clean install` into the terminal.

**Comment by DevCharly** [comment]
Add following to your maven POM:

~~~xml
<dependency>
  <groupId>com.formdev</groupId>
  <artifactId>flatlaf-fonts-inter</artifactId>
  <version>3.19</version>
</dependency>
~~~

See: https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-fonts/flatlaf-fonts-inter
