### ISSUE TITLE
Properties file not working with a "Java with Maven" application

### ISSUE THREAD

**Issue by edison369** [JFormDesigner/FlatLaf#685]
Hello everyone!!
I would like some help please because I don't know what I am doing wrong...
I am developing an app using Flatlaf and wanted to customize the UI defaults using an Application properties file. I read the [guide](https://www.formdev.com/flatlaf/how-to-customize/) on how to do it and it didn't work. So I started testing and did the following:
1. I created a "Java with Maven" application and a "Java with Ant" application in Netbeans.
2. I created a JFrame Form "NewJFrame" in each application and placed a single button in the middle of the JFrame.
3. I created a package "style" with a "FlatIntelliJLaf.properties" file inside the package, in each application.
4. I added the line `@accentColor=#1eb980` in the properties file, in each application
5. I added the lines `FlatIntelliJLaf.registerCustomDefaultsSource("style"); FlatIntelliJLaf.setup();` in the main() method for each application.
After running both applications, the change in the accent color just works in the "Java with Ant" application. 

Image of the "Java with Ant" application:
![image](https://github.com/JFormDesigner/FlatLaf/assets/58643543/24cf10cb-a682-4a34-ab5a-f269c4e5a453)

Image of the "Java with Maven" application:
![image](https://github.com/JFormDesigner/FlatLaf/assets/58643543/d802fd37-1ee0-4924-9ce3-f1e031ec173c)

**Comment by DJ-Raven** [comment]
Put your properties file in resources folder
Ex :
`
src/main/resources/style/FlatIntelliJLaf.properties
`

**Comment by edison369** [comment]
Thank you @DJ-Raven, that worked!!
