### ISSUE TITLE
FlatLaf Gradianto Midnight Blue scrollbar button not visible (same color as background)

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#686]
Dear Maintainer,

the FlatLaf Gradianto Midnight Blue look and feel scrollbar button is not visible (same color as background) in the current 3.1.1 release!

![juliaset-screenshot-flatlaf-gradianto-midnight-blue-bug-scrollbar-button-not-visible](https://github.com/JFormDesigner/FlatLaf/assets/102819800/d98cb9a1-8c04-4716-8d2c-a97cbe236274)

(Look on the right JList in the application)

Thank you in advance.

Sincerely,

Adrian Kieß

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
