### ISSUE TITLE
FlatLaf Light Owl menu items text color in the menu bar are very hard to read

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#687]
Dear Maintainer,

the menu items in the menu bar using the FlatLaf Light Owl look and feel have white text and this is very hard to read, even using my HP Z24i monitor. Maybe the text color in the menu items should be black instead of white.

![juliaset-screenshot-flatlaf-light-owl-bug-menu-item-text-hard-readable](https://github.com/JFormDesigner/FlatLaf/assets/102819800/ef1abaa7-8d9b-4580-b031-405bec9e78fe)

(Look in the unfolded menu bar at the left top)

Thank you in advance.

Sincerely,

Adrian Kieß

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
