### ISSUE TITLE
JFileChooser, warning message.

### ISSUE THREAD

**Issue by wemersontga** [JFormDesigner/FlatLaf#694]
when running the project with a JFileChooser, the message is displayed in the console.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.formdev.flatlaf.ui.FlatFileChooserUI$FlatShortcutsPanel (file:/C:/Users/virtual_pc/eclipse-workspace/cheat_pcsx2/lib/flatlaf-3.1.1.jar) to method sun.awt.shell.ShellFolder.get(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.formdev.flatlaf.ui.FlatFileChooserUI$FlatShortcutsPanel
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

I am reporting what appears in eclipse, but the program itself works normally.

**Comment by SenorEsel** [comment]
Me too, the error message pops up only running
openjdk version "11.0.10" 2021-01-19

when running openjdk version "17.0.6" 2023-01-17, no warning pop ups anymore and I assume, the method mentioned isn't allowed to start anymore (silently), but has no significant effect to the JFileChooser

**Comment by DevCharly** [comment]
This is expected behavior for Java 9 to 16, because FlatLaf uses private Java API for those Java versions to get shortcut folders and large icons. There is no public API available in those Java versions.

Since Java 17, public API is available and used.
