### ISSUE TITLE
FlatLaf look and feel Material design dark: Very hard to read selected Tab title text in JTabbedPane

### ISSUE THREAD

**Issue by adriankiess** [JFormDesigner/FlatLaf#697]
Dear Maintainer,

the text in selected Tab title text in a JTabbedPane is very hard to read in the FlatLaf look and feel 'Material design dark'.

Below a screenshot, which highlights the problem:

![jexercise-flatlaf-look-and-feel-material-design-dark-hard-readable](https://github.com/JFormDesigner/FlatLaf/assets/102819800/ef7d3a11-97e7-4af9-a125-946ac1a1a57e)

Thank you very much in advance.

Sincerely,

Adrian Kieß

**Comment by DevCharly** [comment]
Thanks for reporting 👍 

fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
