### ISSUE TITLE
Title background of JOptionPane.showConfirmDialog

### ISSUE THREAD

**Issue by c4rth** [JFormDesigner/FlatLaf#699]
Hi,

How to change the background color of the title of a JOptionPane ?

With this sample, the title foreground color is changed but not the background.
```java
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import java.awt.*;

public class FlatLafTitle
{
	public static void main( String[] args ) {

		FlatLightLaf.setup();

		UIManager.put( "TitlePane.foreground", Color.blue );
		UIManager.put( "TitlePane.background", Color.red );

		JOptionPane.showConfirmDialog( null, "Do you want to continue?", "Confirm", JOptionPane.YES_NO_OPTION,
			JOptionPane.QUESTION_MESSAGE );
	}
}
```

<img width="198" alt="Screenshot" src="https://github.com/JFormDesigner/FlatLaf/assets/8505625/3025fac9-4951-491b-83c6-2f15875958ee">

**Comment by DevCharly** [comment]
You need to disable "unified background":

~~~java
UIManager.put( "TitlePane.unifiedBackground", false);
~~~

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/63dede80-9b54-40cb-845f-6c42befa7e67)

**Comment by c4rth** [comment]
It works as expected.
Many thanks for your answer and your great library !
