### ISSUE TITLE
Improve disabled button rendering

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#70]
The look and feel render the disabled button with a grayscale.

FlatLaf inherit getDisabledIcon method from "BasicLaF".
It has hight performance (https://stackoverflow.com/a/9131751) but I think that we can choose a better graphic solution.

"BasicLaF" internally use a GrayFilter with a 50% value filter.
I have tested many values to have a lighter solution. The best values are near 70 and 80.
The problem with these high value filter is that we lose a color contrast.

I have seen that "MetalLaF" override the basic method and I think that the graphical result is better.

See here an example:
 - on top the actual Flat and "Basic" solution
- in the bottom the "Metal" solution

![disabledButton](https://user-images.githubusercontent.com/17149962/75368606-4acbee80-58c2-11ea-9ac1-d85dc1d037f1.jpg)

If you accept my idea, I can prepare a merge request with a solution inspired from "MetalLaF"(MetalUtils.getOceanDisabledButtonIcon).

With this solution we can also add to the UIManager the key "Button.disabledGrayRange" = [180,215]

**Comment by DevCharly** [comment]
Yes, this looks better 👍 
A PR would be great.

Will this work for the dark themes too?
With different gray range?

BTW the FlatLaf .properties files do not support arrays. So it is probably easier to use two integer UI values. E.g. `Button.disabledGrayRangeMin` and `Button.disabledGrayRangeMax`.
With [FlatUIUtils.getUIInt( String key, int defaultValue )](https://github.com/JFormDesigner/FlatLaf/blob/master/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatUIUtils.java#L109) its easy to get integers and pass defaults.

**Comment by basix86** [comment]
I have created the PR here:
https://github.com/JFormDesigner/FlatLaf/pull/72

I have tested with various themes, ad it work well.
With dark theme we suggest to change the value of grays from [180-215] to a lower values, for example [1-100].

This solution is very pretty with gray themes but with colored theme should be possible to replace a gray scale with a single color scale

**Comment by DevCharly** [comment]
@basix86 I've merged PR #72 into new branch 'disabled-icons'.

For testing with some real world icons I've created a little app `com.formdev.flatlaf.testing.FlatDisabledIconsTest`

The disabled icons look good. Maybe a little bit to light.
But they are hard to see on selected disabled toggle buttons.

![image](https://user-images.githubusercontent.com/5604048/79203418-4c824f00-7e3b-11ea-850d-a51f216d7bc1.png)

So I looked around what other LaFs and IDEs use and extended `FlatDisabledIconsTest` to compare the solutions:

![image](https://user-images.githubusercontent.com/5604048/79222660-3c2c9d00-7e58-11ea-91db-e16dcd5bfab1.png)

This app uses toolbars with toggle buttons. The sliders on the right side allow controlling the filters.

Here a screenshot with selected toggle buttons:

![image](https://user-images.githubusercontent.com/5604048/79222724-5b2b2f00-7e58-11ea-9255-66f45a8a50f6.png)

In dark:

![image](https://user-images.githubusercontent.com/5604048/79222751-68481e00-7e58-11ea-95ce-1eaf3e7bc551.png)
![image](https://user-images.githubusercontent.com/5604048/79222764-6b430e80-7e58-11ea-8f2f-4493304177b4.png)

Now playing around with all the the sliders to find optimal values for FlatLaf and decide whether stay with the Metal filter or switch to another filter. The IntelliJ filter seems to be more flexible. The NetBeans filter preserves some color but is not configurable.

**Comment by basix86** [comment]
Nice Job.
I think that a configurable filter is a good option, because we should support many themes (dark and light version).
Personally I don't know what is the best.

**Comment by DevCharly** [comment]
The code is now in master branch. I've replaced the Metal gray filter with the IntelliJ filter, but with different values for brightness and contrast. Also support for multi-resolution images (e.g. @2x.png on macOS) is now implemented for Java 9+

And here is the result (row "current LaF"):

![image](https://user-images.githubusercontent.com/5604048/80232274-f55b5600-8654-11ea-852c-4bbef196bdc8.png)

![image](https://user-images.githubusercontent.com/5604048/80232324-02784500-8655-11ea-8ad1-e1761e22cd76.png)

**Comment by martin-jamszolik** [comment]
@DevCharly Thank you for adding the support for multi-resolution images.  This is really awesome!
I also started to look at your `FlatSVGIcon.java` utility to help with scaling in 4k and while it's good for default sizes,  I found the `com.kitfox.svg.app.beans.SVGIcon` to be useful when scaling to different sizes. Just FYI.  Great Job guys!

**Comment by DevCharly** [comment]
implemented in 0.33
