### ISSUE TITLE
Context menu items not selectable when over the GNOME task bar

### ISSUE THREAD

**Issue by rkeen-siemens** [JFormDesigner/FlatLaf#701]
On Linux (at least AlmaLinux 8.8) with GNOME in classic mode showing the taskbar, if a context menu appears that overlaps the taskbar the menu items that overlap the task bar are not selectable. To reproduce:
1. Run FlatLaf Demo
2. Select the Data Components tab
3. Resize the window so that the top row of JLists are fully visible
4. Move the window so the bottom is just above the task bar
5. Invoke the context menu for the bottom item in one of the lists
6. Attempt to select the Noop Action

You'll see that the action is not highlighted when the mouse hovers over it as expected. The image below shows this scenario, although it didn't capture the mouse position which was over the last "Noop Action" menu item.

<img width="654" alt="Context menu over task bar" src="https://github.com/JFormDesigner/FlatLaf/assets/46196614/8a78e942-e0c4-410c-8ac4-878ab1fae482">

Ideally, it would be possible to select menu items overlapping the task bar. Other applications (e.g. Chrome) seem to adjust the position of their context menus to avoid overlapping the task bar. Main menus in FlatLaf seem to do the same thing, so perhaps context menus should have the same handling if it's not possible to allow selection when overlapping the task bar.

**Comment by DevCharly** [comment]
Seems to be a general Swing problem on Linux.
Metal, Nimbus and GTK+ Lafs have the same problem...

Not sure whether it is possible to fix this in FlatLaf...

So I've implemented popup position adjusting to avoid overlapping the task bar.

**Comment by LinuxBeaver** [comment]
This update solved a problem I was having with a Java application called Pixelitor on the Cinnamon desktop. Thanks @DevCharly

**Comment by eirikbakke** [comment]
I tested this on Windows 11 with both FlatLAF 3.1 and FlatLAF 3.2; either policy works there (including in FlatLAF 3.1 when the popup menu overlaps the taskbar). Chrome, Notepad, and Excel all seem to avoid overlapping the taskbar when opening popup menus, so FlatLAF's new approach is consistent with those apps. Thank you!

**Comment by mbien** [comment]
awesome! I already trained myself to select the last item with the arrow keys :)
