### ISSUE TITLE
Obfuscating with proguard 

### ISSUE THREAD

**Issue by Andy-DG** [JFormDesigner/FlatLaf#706]
Obfuscating with proguard gives me the following warnings;
Warning: com.formdev.flatlaf.FlatLaf: can't find referenced method 'java.lang.Object invoke(javax.swing.JComponent)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.ui.FlatPopupFactory: can't find referenced method 'javax.swing.Popup invoke(com.formdev.flatlaf.ui.FlatPopupFactory,java.awt.Component,java.awt.Component,int,int,boolean)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.ui.FlatPopupFactory: can't find referenced method 'javax.swing.Popup invoke(com.formdev.flatlaf.ui.FlatPopupFactory,java.awt.Component,java.awt.Component,int,int,int)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.ui.FlatStylingSupport: can't find referenced method 'java.lang.Object invoke(java.lang.Object)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.ui.FlatStylingSupport: can't find referenced method 'void invoke(java.lang.Object,java.lang.Object)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.util.JavaCompatibility: can't find referenced method 'void invoke(javax.swing.JComponent,java.awt.Graphics2D,java.lang.String,int,float,float)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.util.JavaCompatibility: can't find referenced method 'void invoke(javax.swing.JComponent,java.awt.Graphics,java.lang.String,int,int,int)' in library class java.lang.invoke.MethodHandle
Warning: com.formdev.flatlaf.util.JavaCompatibility: can't find referenced method 'java.lang.String invoke(javax.swing.JComponent,java.awt.FontMetrics,java.lang.String,int)' in library class java.lang.invoke.MethodHandle

And I don't know how to get rid of them. Not sure where the problem lies

**Comment by DevCharly** [comment]
Don't know what the problem is. Better ask the ProGuard guys.

Anyway, obfuscated FlatLaf will not work! There is some reflection used in Swing and FlatLaf.

See https://github.com/JFormDesigner/FlatLaf/issues/648#issuecomment-1441547550

Better exclude FlatLaf from obfuscation.
