### ISSUE TITLE
Share Java Codestyle

### ISSUE THREAD

**Issue by basix86** [JFormDesigner/FlatLaf#71]
Hi,
@DevCharly can you share your java code-style file to align all developers commits?

**Comment by DevCharly** [comment]
Sure, what IDE do you use?

**Comment by basix86** [comment]
IntelliJ IDEA

**Comment by DevCharly** [comment]
@basix86 I've just added code style for IntelliJ IDEA to `.editorconfig`. This should be automatically used by IDEA in the FlatLaf project.

Requires IDEA EditorConfig plugin, which is bundled with IDEA (since some versions) and enabled by default.

**Comment by DevCharly** [comment]
Also added formatter profile for Eclipse.
