### ISSUE TITLE
Rounded corners in JMenuBar

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#710]
Hi, I want to have rounded corners in my menu items just like tool bar buttons. I've tried with setting a style arc of 8 but it doesn't work as expected... I was wondering if I'm missing a "proper" way of doing this or if it's just a matter of finding the right hacky solution?

**Comment by DevCharly** [comment]
See PR #536

Also take a look at the both FlatLaf macOS themes, which use rounded menu selection.

**Comment by DevCharly** [comment]
Did it work? If yes, please close the issue.
