### ISSUE TITLE
Long text in JTextComponent becomes garbled on Linux

### ISSUE THREAD

**Issue by bjorndarri** [JFormDesigner/FlatLaf#711]
FlatLaf v3.1.1.

Reproducable on Linux (Fedora 38), doesn't seem to be an issue on Windows.

When long (thousands of characters) text is added to a JTextField (or JTextArea) it becomes garbled, after reaching a certain length.

Below is a program for reproducing the error, run it, move the caret to either end of the field and add one or more characters and voila, it becomes garbled.

![non_garbled_text](https://github.com/JFormDesigner/FlatLaf/assets/2327926/c1571061-658d-408b-a17f-21a8e1ac8f8b)

...after adding a few A's at the end:

![garbled_text](https://github.com/JFormDesigner/FlatLaf/assets/2327926/69707bef-3829-4f96-aadc-542cd1517955)

```
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import java.util.stream.IntStream;

import static java.util.stream.Collectors.joining;

public class GarbledTextFieldDemo {
  public static void main(String[] args) throws Exception {
    UIManager.setLookAndFeel("com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMonokaiProContrastIJTheme");
    String string = IntStream.range(0, 7_282)
            .mapToObj(i -> "X")
            .collect(joining());
    JTextField textField = new JTextField(15);
    textField.setText(string);
    JOptionPane.showMessageDialog(null, textField);
  }
}
```
Thank you for this excellent library, by the way.

**Comment by DevCharly** [comment]
This is probably a general Java/Swing text rendering issue on Linux.
Occurs also with Metal, Nimbus and GTK+ Lafs with longer texts.

If I change text to `"Xa"` and count to `17_282` in your example, it shows following with Nimbus Laf:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/0db541df-a1c5-48e3-a995-dcd7f685b518)

And with FlatLaf.

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/41204627-134b-41a2-8141-93a1de11521b)

Tried to search for that bug on https://bugs.openjdk.org/, but did not yet find one... 😕

**Comment by bjorndarri** [comment]
Yeah, sorry about that, I thought I had tested this with Metal L&F, but it looks like I didn't use quite enough characters.

Feel free to close this issue.
