### ISSUE TITLE
JPopup menu sometime lose focus.

### ISSUE THREAD

**Issue by kamilkrzywanski** [JFormDesigner/FlatLaf#712]
Hello! I have a problem with focus on some OS/Arch 
On my laptop i7/12700k or PC i7/12700k everything works fine and focus is on jPopup:
![image](https://github.com/JFormDesigner/FlatLaf/assets/61804231/dc23b56c-55e9-497c-acc9-ec0ca46b6784)
But on some pc`s i7/7700 for example is happeinig something like that: 
![image](https://github.com/JFormDesigner/FlatLaf/assets/61804231/4e0df998-d165-49db-b2d6-ad48873ee2e3)
When I disable flatlaf everything is fine everywhere. 
When I tried to localize focus with:
KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner()
focus owner is RootPane. 
Can you check it?
Tried with flatlaf 2.6, 3.1 and 3.1.1
Tried with java 8 and 11 (different version) 
I suppouse problem with some native library.

**Comment by DevCharly** [comment]
Is the first screenshot from Windows 11 and the second from Windows 10?

> Can you check it?

Could you provide a minimal test case? (see other issues for examples)

> I suppouse problem with some native library.

Then please try with disabled native library.
Use FlatLaf 3.2 and pass `-Dflatlaf.useNativeLibrary=false` at command line.

**Comment by kamilkrzywanski** [comment]
It's right, second screen is from windows 10, problem is maybe on windows 10, Unfortunately the next week I have vacation and will create you test case on 21 August.

**Comment by kamilkrzywanski** [comment]
@DevCharly I tried with 3.2 and property -Dflatlaf.useNativeLibrary=false
And still happens the same. You're right that this happens only on windows 10(I tried very old long time non updated version and current)

**Comment by kamilkrzywanski** [comment]
Another problem is situation when I press "Alt" on textfield on this popup it also disappear the.

**Comment by DevCharly** [comment]
And the popup stays visible in other L&Fs when you press the Alt key?

**Comment by kamilkrzywanski** [comment]
On MetalLaf is fine, on WindowsLookAndFeel is the same problem :(

**Comment by DevCharly** [comment]
> On MetalLaf is fine,

Really, for me the popup is hidden when releasing the `Alt` key 😕 

JPopupMenu is designed to be used for menus, not for forms 😉 
There is some extra work necessary...

To move the focus into the popup try: 

~~~java
popup.addPopupMenuListener( new PopupMenuListener() {
    @Override
    public void popupMenuWillBecomeVisible( PopupMenuEvent e ) {
        EventQueue.invokeLater( () -> {
            // focus first component in popup
            popup.transferFocus();
        } );
    }
    @Override public void popupMenuWillBecomeInvisible( PopupMenuEvent e ) {}
    @Override public void popupMenuCanceled( PopupMenuEvent e ) {}
} );
~~~

Also make sure that pressing `Tab` key does not move focus out of popup:

~~~java
popup.setFocusCycleRoot( true );
~~~

To "block" `Alt` key, use:

~~~java
JPopupMenu popup = new JPopupMenu() {
    @Override
    protected boolean processKeyBinding( KeyStroke ks, KeyEvent e, int condition, boolean pressed ) {
        if( e.getID() == KeyEvent.KEY_PRESSED && e.getKeyCode() == KeyEvent.VK_ALT )
            return true;
        return super.processKeyBinding( ks, e, condition, pressed );
    }
};
~~~
