### ISSUE TITLE
How can I change JButton FlatSVGIcon color?

### ISSUE THREAD

**Issue by AkashFulari** [JFormDesigner/FlatLaf#714]
How to change a specific JButton FlatSVGIcon color.
![image](https://github.com/JFormDesigner/FlatLaf/assets/90330629/6ad01273-02b0-4759-8545-01c894cd23ed)
I want to change different colors on each button svg icon dynamicaly. 

Please help me. Thank you in advance.

**Comment by nroduit** [comment]
Try with
``` java
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;

FlatSVGIcon flatSVGIcon = ...
ColorFilter colorFilter = new ColorFilter();
// Convert a the original color into another one
colorFilter.add(new Color(0x6E6E6E), UIManager.getColor(FlatIconColors.ACTIONS_RED.key));
FlatSVGIcon icon = new FlatSVGIcon(flatSVGIcon);
icon.setColorFilter(filter);
```

**Comment by AkashFulari** [comment]
@nroduit I tried same, but its not working. here is the my code:
```
....
public void setIconColor(Color c) {
      if (c != null && this.icon != null) {
          FlatSVGIcon.ColorFilter colorFilter = new FlatSVGIcon.ColorFilter();
          colorFilter.add(c, UIManager.getColor(FlatIconColors.ACTIONS_RED.key));
          this.icon.setColorFilter(colorFilter);
     }
}
.......
```

**Comment by DevCharly** [comment]
@AkashFulari make sure that the color that you pass as first argument to `colorFilter.add()` is the same as used in the SVG file.
E.g. if the SVG contains `<path fill="#6E6E6E" ...` then pass `new Color( 0x6E6E6E )`.

If you want replace any color, which should work with the one-colored icons shown in your screenshot, you can use following:

~~~java
icon.setColorFilter( new FlatSVGIcon.ColorFilter( color -> Color.red ) );
~~~
