### ISSUE TITLE
How can i get a list of Available Themes at run-time?

### ISSUE THREAD

**Issue by amiga-500** [JFormDesigner/FlatLaf#716]
So i can check for the existence of FlatLaf library and theme jar files in java at runtime..that's easy, but i would like to get a list of available themes that exist in the "flatlaf-intellij-themes-<version>.jar" so i can them add them to my menu for the user to select from.

How do i do that?

**Comment by matt-pan** [comment]
You're looking for FlatAllIJThemes.INFOS - which is an array of all existing FlatIJLookAndFeelInfo definitions

**Comment by amiga-500** [comment]
Thank you.
