### ISSUE TITLE
TabbedPane rounded card tabs and transparent background

### ISSUE THREAD

**Issue by j-dimension** [JFormDesigner/FlatLaf#717]
Hi, I love the new rounded corners for card-style tabs, thanks a lot!

I have a tabbed pane on a JPanel, and the JPanel has a background image. Is there a way to make the card tabs unused space (the "negative" of the rounded corner card) render the background image of its parent instead of a default color?

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/3729754/5c3b91fd-187a-4097-b298-f553b91056ee)

FlatLaf 3.2
Linux with KDE
Java 11

**Comment by j-dimension** [comment]
related to https://github.com/JFormDesigner/FlatLaf/pull/703

**Comment by DevCharly** [comment]
> Is there a way to make the card tabs unused space (the "negative" of the rounded corner card) render the background image of its parent instead of a default color?

No, not at the moment. Will investigate... Thanks for reporting.

**Comment by DevCharly** [comment]
fixed in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

The tab area background is now painted with a rounded rectangle:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/89fa1d47-fa66-4d11-83f0-f1f8bfbf0f66)

**Comment by j-dimension** [comment]
Looks fantastic! Thank you so much @DevCharly! Really looking forward to the 3.3 release.

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/3729754/a8420146-ff7b-4edc-9ff0-0e306b451774)

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/3729754/b54e0355-e5f4-4d75-80b2-69f00a6206fa)

**Comment by DevCharly** [comment]
FlatLaf 3.3 is now available 😉

**Comment by j-dimension** [comment]
Awesome, thank you so much @DevCharly !
