### ISSUE TITLE
Alert or tips wanted

### ISSUE THREAD

**Issue by rememberber** [JFormDesigner/FlatLaf#725]
A global alert like this wanted, Thanks a lot
![image](https://github.com/JFormDesigner/FlatLaf/assets/4653893/ede74758-c992-431b-8ebe-16ce46715191)

**Comment by matt-pan** [comment]
Hi,
I don't have any affiliations with this project - but I guess as a "Look and Feel" I don't think the goal is to introduce new UI features to Java Swing.
But: just search for "Java Swing Toast" or "Java Swing Snackbar" on any search engine and you'll find plenty of easy to follow tutorials to achieve something similar with minimal lines of code, independent of the "Look and Feel" of your project.

**Comment by DevCharly** [comment]
Sorry, but this is out of scope of this project.

> May be included as flatlaf-extras

Well, we could add a lot of stuff to flatlaf-extras: date/month controls, docking, dashbord, alerts/notifications, tree-table component, etc.

But first you need someone that implements this stuff, then you need to review and test it.
And once it is first released, you need to implement feature requests, provide support, fix bugs, etc.

This should be done in own projects.
