### ISSUE TITLE
Inconsistent behavior with the JPopup when switch the theme.

### ISSUE THREAD

**Issue by CRY-D** [JFormDesigner/FlatLaf#727]
### Issue Description
When attempting to switch the theme color, I observed inconsistent behavior with the JPopup component. Specifically, when I use `pop.show(...)`, the JPopup's theme color doesn't update to reflect the changes made to the theme. However, when I use `setComponentPopupMenu(pop)`, the JPopup's color correctly reflects the updated theme color.

i have no idea why The JPopup theme remains unchanged and does not update to match the theme color when using `pop.show(...)`.?

Note that using `comp.setComponentPopupMenu(pop)` triggers the JPopup with the right mouse button, while `pop.show(...)` triggers it with the action. 

#### Additional Information
- Java version: java-11-openjdk
- FlatLaf version: 3.1.1
- Operating System: Linux
 
#### Here i'm using `pop.show()`

![Screenshot from 2023-09-02 03-15-53](https://github.com/JFormDesigner/FlatLaf/assets/16564491/51acb156-3db1-49ba-a7db-3098475ddfb0)
![Screenshot from 2023-09-02 03-15-59](https://github.com/JFormDesigner/FlatLaf/assets/16564491/db0bdf68-fc86-4c49-8ab4-2e2629caee3f)

#### Actual Behavior after change the theme for  `pop.show()`
![Screenshot from 2023-09-02 03-16-52](https://github.com/JFormDesigner/FlatLaf/assets/16564491/983360e9-92e2-47e0-99e3-8e30c87a69ac)

![Screenshot from 2023-09-02 03-16-46](https://github.com/JFormDesigner/FlatLaf/assets/16564491/70cfada8-d3b9-4a61-91d8-d94463f900b5)

#### Here i'm using `.setComponentPopupMenu(pop)`
![Screenshot from 2023-09-02 03-16-20](https://github.com/JFormDesigner/FlatLaf/assets/16564491/6dc3cc9e-70e5-4250-8bc0-6bbfc5225468)

#### Actual Behavior after change the theme for  `setComponentPopupMenu(pop)`
![Screenshot from 2023-09-02 03-17-18](https://github.com/JFormDesigner/FlatLaf/assets/16564491/32627d9f-2093-421c-a382-6b21296d2e3e)

![Screenshot from 2023-09-02 03-17-03](https://github.com/JFormDesigner/FlatLaf/assets/16564491/293c25fc-119d-4df4-9441-f864d6f46c51)

**Comment by DevCharly** [comment]
The reason is probably that you create the popup once and reused it. So you're having a reference to the popup somewhere, but it is not added to the component hierarchy. Therefore it is not updated when switching theme.

To fix this, either recreate the popup each time before you show it, or update it when switching theme by invoking `popup.updateUI()`. You can override `JComponent.updateUI()` on the component that stores the reference to the popup. E.g.

~~~java
class JSearchField extends JTextField {
    JPopupMenu popup;

    @Override
    public void updateUI() {
        super.updateUI();
        if( popup != null )
            popup.updateUI();
    }
}
~~~

**Comment by CRY-D** [comment]
You mentioned that the issue might be related to reusing the popup without adding it to the component hierarchy, and you suggested two potential solutions: recreating the popup each time before showing it or invoking `popup.updateUI()` when switching themes.

I attempted to follow your advice by overriding `updateUI()` on the component storing the reference to the popup.

However, it appears that this approach did not resolve the issue in my specific case. 
and also I am working within a certain logic flow that restricts me from recreating the popup before showing it. 
Therefore, I explored an alternative solution to address the issue.

I have implemented an alternative solution that specifically addresses the left mouse button trigger requirement and ensures that the JPopup reflects the updated theme color correctly. Here's the code snippet of the solution:
it's to override the trigger button `setComponentPopupMenu` method
```java
class ButtonLeftClickPopup extends FlatButton {
    private JPopupMenu popupMenu;

    @Override
    public void setComponentPopupMenu(JPopupMenu popup) {
        this.popup  = popup;

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getButton() == MouseEvent.BUTTON1) {
                    popup.show(e.getComponent(), e.getX()+5, e.getY()+5);
                }
            }
        });
    }

    @Override
    public JPopupMenu getComponentPopupMenu() {
        return this.popup;
    }
}
```

This solution effectively addresses the issue and allows me to achieve the desired behavior of triggering the JPopup with the left mouse button.

Thank you again for your insights and suggestions. I hope this information helps, and I look forward to any further guidance or recommendations you may have.

**Best regards**

**Comment by DevCharly** [comment]
Sorry, my code was wrong.

You need to invoke `SwingUtilities.updateComponentTreeUI()` on the popup.
Adding following to `ButtonLeftClickPopup` should work:

~~~java
    @Override
    public void updateUI() {
        super.updateUI();
        if( popup != null )
            SwingUtilities.updateComponentTreeUI( popup );
    }
~~~

**Comment by CRY-D** [comment]
Yes it works, thanks for your time
