### ISSUE TITLE
FileChooser hangs indefinitely on Windows loading the system icons

### ISSUE THREAD

**Issue by ustieber** [JFormDesigner/FlatLaf#728]
FlatLaf 3.2
Windows 10
Java 17.0.8

When creating the JFileChooser instance, the application hang up indefinitely trying to load the system icons on Windows 10 and Java 17. 

park:-1, Unsafe (jdk.internal.misc)
park:211, LockSupport (java.util.concurrent.locks)
awaitDone:447, FutureTask (java.util.concurrent)
get:190, FutureTask (java.util.concurrent)
invoke:641, Win32ShellFolderManager2$ComInvoker (sun.awt.shell)
invoke:537, ShellFolder (sun.awt.shell)
invoke:523, ShellFolder (sun.awt.shell)
getIcon:1060, Win32ShellFolder2 (sun.awt.shell)
**getSystemIcon:250, FileSystemView (javax.swing.filechooser)
getIcon:372, FlatFileChooserUI$FlatFileView (com.formdev.flatlaf.ui)
getIcon:1611, JFileChooser (javax.swing)**
getListCellRendererComponent:951, MetalFileChooserUI$DirectoryComboBoxRenderer (javax.swing.plaf.metal)
getListCellRendererComponent:1047, FlatComboBoxUI$FlatComboPopup$PopupListCellRenderer (com.formdev.flatlaf.ui)
updateLayoutState:1444, BasicListUI (javax.swing.plaf.basic)
maybeUpdateLayoutState:1394, BasicListUI (javax.swing.plaf.basic)
valueChanged:2815, BasicListUI$Handler (javax.swing.plaf.basic)
lambda$createListSelectionListener$2:195, FlatListUI (com.formdev.flatlaf.ui)
valueChanged:-1, FlatListUI$$Lambda$361/0x000001d8e84bf988 (com.formdev.flatlaf.ui)
fireValueChanged:224, DefaultListSelectionModel (javax.swing)
fireValueChanged:204, DefaultListSelectionModel (javax.swing)
fireValueChanged:251, DefaultListSelectionModel (javax.swing)
changeSelection:448, DefaultListSelectionModel (javax.swing)
changeSelection:458, DefaultListSelectionModel (javax.swing)
setSelectionInterval:502, DefaultListSelectionModel (javax.swing)
setSelectedIndex:2232, JList (javax.swing)
setListSelection:1273, BasicComboPopup (javax.swing.plaf.basic)
itemStateChanged:1097, BasicComboPopup$Handler (javax.swing.plaf.basic)
fireItemStateChanged:1257, JComboBox (javax.swing)
selectedItemChanged:1318, JComboBox (javax.swing)
contentsChanged:1365, JComboBox (javax.swing)
fireContentsChanged:127, AbstractListModel (javax.swing)
setSelectedItem:1106, MetalFileChooserUI$DirectoryComboBoxModel (javax.swing.plaf.metal)
addItem:1071, MetalFileChooserUI$DirectoryComboBoxModel (javax.swing.plaf.metal)
doDirectoryChanged:721, MetalFileChooserUI (javax.swing.plaf.metal)
propertyChange:810, MetalFileChooserUI$5 (javax.swing.plaf.metal)
fire:343, PropertyChangeSupport (java.beans)
firePropertyChange:335, PropertyChangeSupport (java.beans)
firePropertyChange:268, PropertyChangeSupport (java.beans)
firePropertyChange:8722, Component (java.awt)
setCurrentDirectory:609, JFileChooser (javax.swing)
<init>:363, JFileChooser (javax.swing)
<init>:309, JFileChooser (javax.swing)
createJFileChooser:1283, UIFactory (de.sep.swing.factory)
...

Switching to Java 11 shows the same behavior. When temporarily disabling FlatLaf, the JFileChooser dialog opens without issue.

**Comment by DevCharly** [comment]
Hmm, for me it works without problems on Windows 10 (and 11) 😕 

Does it work with Windows L&F ?

**Comment by ustieber** [comment]
Indeed, it does not. Stuck at the same frame ...

park:-1, Unsafe (jdk.internal.misc)
park:211, LockSupport (java.util.concurrent.locks)
awaitDone:447, FutureTask (java.util.concurrent)
get:190, FutureTask (java.util.concurrent)
invoke:641, Win32ShellFolderManager2$ComInvoker (sun.awt.shell)
invoke:537, ShellFolder (sun.awt.shell)
invoke:523, ShellFolder (sun.awt.shell)
getIcon:1060, Win32ShellFolder2 (sun.awt.shell)
getSystemIcon:250, FileSystemView (javax.swing.filechooser)
getIcon:1351, WindowsFileChooserUI$WindowsFileView (com.sun.java.swing.plaf.windows)
getIcon:1611, JFileChooser (javax.swing)
...

So it appears to be an JDK issue than. Sorry for the noise.

**Comment by DevCharly** [comment]
Have you checked on which file it hangs?
Selecting one of the get icon methods in debugger should show the filename in variables view.

BTW Do you create the file chooser on the AWT thread?

**Comment by ustieber** [comment]
>Have you checked on which file it hangs?

Has to do with network shares apparently. It tries to get the mounted network drive icon for one of our default network shares. 

>BTW Do you create the file chooser on the AWT thread?

Yes, I do. Found suggestions to (pre-)load the JFileChooser instance in a separate thread. Will look into this too.
