### ISSUE TITLE
Novice: Failing to Add FlatLaf to my Java Swing project on Eclipse 

### ISSUE THREAD

**Issue by greatkalu** [JFormDesigner/FlatLaf#73]
Good day,

I''m a novice developer keen to improve the UI of a Java Swing app I've been developing. I'm quite keen on FlatLaf but am currently failing to add it to my project on Eclipse IDE For Java Developers, Version: 2019-06 (4.12.0).

I added flatlaf-0.27.jar to Libraries of my project (Java Build Path -> Libraries Tab) and tried both of the options indicated in the documentation:
![image](https://user-images.githubusercontent.com/61576288/75518775-5de9d600-5a0a-11ea-97b9-5348dbcf1712.png)

`public class FpsMain {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		FlatLightLaf.install();
		new LoginGuiContol();
	}

}`

And ...

`public class LoginGui extends JFrame {

	private JPanel contentPane;
	private JTextField textFieldUsername;
	private JPasswordField passwordField;
	private JButton btnLogin;
	private JButton btnCancel;
	private JLabel lblwrongPassword;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					LoginGui frame = new LoginGui();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public LoginGui() {
		super("User Login");
		try {
		    UIManager.setLookAndFeel( new FlatLightLaf() );
		} catch( Exception ex ) {
		    System.err.println( "Failed to initialize LaF" );
		}
		
		
		// Get the size of the screen
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();`

Unfortunately I'm getting the same below error from both and am stumped at the first hurdle ... :(

`Exception in thread "main" java.lang.NoClassDefFoundError: com/formdev/flatlaf/FlatLightLaf
	at zm.co.freight.control.FpsMain.main(FpsMain.java:12)
Caused by: java.lang.ClassNotFoundException: com.formdev.flatlaf.FlatLightLaf
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more`

`Exception in thread "main" java.lang.NoClassDefFoundError: com/formdev/flatlaf/FlatLightLaf
	at zm.co.freight.control.LoginGuiContol.<init>(LoginGuiContol.java:31)
	at zm.co.freight.control.FpsMain.main(FpsMain.java:13)
Caused by: java.lang.ClassNotFoundException: com.formdev.flatlaf.FlatLightLaf
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more`

Please will greatly appreciate an assistance to resolve this.

Warm Regards.

**Comment by DevCharly** [comment]
The problem is probably that `flatlaf.jar` is on the (Java 9) modulepath, but it is not in the `module-info.java`. There should be a `module-info.java` file in your project. Add `requires com.formdev.flatlaf;` to it. E.g.
~~~java
module MyApp {
    requires com.formdev.flatlaf;
}
~~~
Maybe it is possible to do this on the "Module dependencies" tab in "Project properties > Java Build Path". I'm not sure.

**Comment by greatkalu** [comment]
Hi DevCharly,

Many thanks, I'm now on FlatLaf!

What tools would you recommend to build FlatLaf UIs? I've added JFormDesigner to Eclipse and am going to try to use it, but I've mainly been building UIs using code.
