### ISSUE TITLE
Nullpointer Exception - FlatPanelUI

### ISSUE THREAD

**Issue by SakthiRJ** [JFormDesigner/FlatLaf#731]
I am getting null pointer exception during flatpanelui installation.  I don't any open tickets here. Please help me.

~~~
stack trace: java.lang.NullPointerException
	at util.cmAbstractDisplay.addPropertyChangeListener(cmAbstractDisplay.java:919)
	at com.formdev.flatlaf.ui.FlatPanelUI.installUI(FlatPanelUI.java:72)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at util.csAbstractDisplay.<init>(cmAbstractDisplay.java:148)
	at util.cmAbstractDisplayField.<init>(cmAbstractDisplayField.java:61)
	at util.cmDisplayField.<init>(cmDisplayField.java:63)
~~~

**Comment by DevCharly** [comment]
Please take a look at `cmAbstractDisplay.java` line 919

**Comment by SakthiRJ** [comment]
I have checked it and it looks fine. The issue happens after I upgrade flatlaf from 1.6.5 to 2.0.0
`/**
     * Adds a PropertyChangeListener to the listener list.
     *
     * @param l The listener to add.
     *
     */
    @Override
    public void addPropertyChangeListener(java.beans.PropertyChangeListener l) {
        propertyChangeSupport.addPropertyChangeListener(l);
    }`

**Comment by DevCharly** [comment]
Set a breakpoint at that line and check whether `propertyChangeSupport` is `null`

**Comment by SakthiRJ** [comment]
> addPropertyChangeListener

No its not null. I have checked it. I am confused now.
![image](https://github.com/JFormDesigner/FlatLaf/assets/104691007/4c755342-2141-4d3b-8a1a-5d99cac88d88)

**Comment by DevCharly** [comment]
The screenshot shows value of parameter `l`.
I asked for field `propertyChangeSupport`.

**Comment by SakthiRJ** [comment]
After upgrading to the latest version of FlatLaf, I've encountered an issue where the propertyChangeSupport variable is null. Previously, I had declared it at the end of the code block, following the implementation of the above method. Interestingly, moving its definition above the method did not resolve the issue; it only functions as expected when placed within the actual method block. This behavior was not present in version 1.6.5

`private java.beans.PropertyChangeSupport propertyChangeSupport = new java.beans.PropertyChangeSupport(this);`

**Comment by DevCharly** [comment]
Aha, ok, I see the problem. 😄 

Method `FlatPanelUI.installUI()` (see stack in first post) is invoked from `JPanel` constructor, which is before fields in class `cmAbstractDisplay` are initialized.

You could fix this with:

~~~java
public abstract class csAbstractDisplay extends javax.swing.JPanel implements util.csDisplayInterface, java.awt.event.MouseListener {
    private java.beans.PropertyChangeSupport propertyChangeSupport;

    @Override
    public void addPropertyChangeListener(java.beans.PropertyChangeListener l) {
        if( propertyChangeSupport == null )
            propertyChangeSupport = new java.beans.PropertyChangeSupport(this);
        propertyChangeSupport.addPropertyChangeListener(l);
    }

    //TODO add `null` checks to all places where `propertyChangeSupport` is used
}
~~~

But I would **recommend** to remove field `propertyChangeSupport` and all related add/remove/fire methods from your class `csAbstractDisplay`.

The superclasses of `JPanel` already have those methods.
It is not necessary to re-implement them.

**Comment by SakthiRJ** [comment]
I have removed the code from cmAbstractDisplay and everything works fine now. But now the properties file changes are not proerly reflecting back. 

TitlePane.background = #4B4F6M
TitlePane.foreground = #ffffff

Entire title pane is now shows white background. I am using custom properties. Other details are properly pickedup

**Comment by DevCharly** [comment]
> Entire title pane is now shows white background

Since FlatLaf 2.0, the general background color is also used for the title bar.
You can disable this with:

~~~
TitlePane.unifiedBackground = false
~~~

**Comment by SakthiRJ** [comment]
Hi DevCharly,

I have problem with  component alignments and all components overrides each other in the panel. Is it possible to avoid this issue. I am using FlatLafLight. Please help me out.

![image (1)](https://github.com/JFormDesigner/FlatLaf/assets/104691007/8c130f69-e07f-4319-a5f8-56cb61ea2221)
