### ISSUE TITLE
Issue with LAF/Theme switch using JXTable and custom setCellRenderer

### ISSUE THREAD

**Issue by cmadsen** [JFormDesigner/FlatLaf#735]
When switching LAF the background color of a custom table cell renderer installed in a JXTable is not updated. When using a plain JTable there is no issue. 

Using flatlaf-swingx:3.2.1 and swingx-all:1.6.5-1.

![image](https://github.com/JFormDesigner/FlatLaf/assets/550040/dbb72bde-9373-4df6-9040-4c60f30cf37f)

Is JXTable not supported by FlatLaf?

```java
public class TableExample extends JFrame {

	public TableExample() {
		String[] columns = new String[] { "Id", "Name", "Hourly Rate",
				"Part Time" };
		Object[][] data = new Object[][] { { 1, "John", 40.0, false },
				{ 2, "Rambo", 70.0, false }, { 3, "Zorro", 60.0, true }, };
		JTable table = new JXTable(data, columns);
		// JTable table = new JTable(data, columns); // this works?
		if (true) {
			table.getColumnModel().getColumn(1)
					.setCellRenderer(new DefaultTableCellRenderer() {
						@Override
						public Component getTableCellRendererComponent(
								JTable table, Object value, boolean isSelected,
								boolean hasFocus, int row, int column) {
							return super.getTableCellRendererComponent(table,
									value, isSelected, hasFocus, row, column);
						}
					});
		}
		JPanel p = new JPanel(new BorderLayout());
		p.add(new JScrollPane(table), BorderLayout.SOUTH);
		JButton b1 = new JButton("Light Laf");
		b1.addActionListener(l -> changeLaf(FlatLightLaf.class.getName()));
		JButton b2 = new JButton("Dark Laf");
		b2.addActionListener(l -> changeLaf(FlatDarkLaf.class.getName()));
		p.add(b1, BorderLayout.EAST);
		p.add(b2, BorderLayout.WEST);
		getContentPane().add(p);
		setTitle("Flat Laf Cell Rendering Issue");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		pack();
		setVisible(true);
	}

	static private void changeLaf(String lafName) {
		try {
			UIManager.setLookAndFeel(lafName);
		} catch (Exception ex) {
			ex.printStackTrace();
		}
		FlatLaf.updateUI();
	}

	public static void main(String[] args) {
		invokeLater(() -> {
			changeLaf(FlatLightLaf.class.getName());
			new TableExample();
			Timer t = new Timer(1000,
					e -> changeLaf(FlatDarkLaf.class.getName()));
			t.setRepeats(false);
			t.start();
		});
	}
}```

**Comment by cmadsen** [comment]
Not sure why but adding `table.putClientProperty(JXTable.USE_DTCR_COLORMEMORY_HACK, Boolean.FALSE);` fixes the problem.

**Comment by DevCharly** [comment]
Seems to be a bug in SwingX related to L&F switching.

If `JXTable.USE_DTCR_COLORMEMORY_HACK` is `true` (the default),
and renderer is instance of `DefaultTableCellRenderer`
then SwingX stores background and foreground colors in a client property of the renderer.
See [ResetDTCRColorHighlighter.applyBackground()](https://github.com/ebourg/swingx/blob/820656cece5d727e85c32f335a3363bc852d07d8/swingx-core/src/main/java/org/jdesktop/swingx/decorator/ResetDTCRColorHighlighter.java#L82-L87) and [ResetDTCRColorHighlighter.applyForeground()](https://github.com/ebourg/swingx/blob/820656cece5d727e85c32f335a3363bc852d07d8/swingx-core/src/main/java/org/jdesktop/swingx/decorator/ResetDTCRColorHighlighter.java#L94-L99).

So after switching from light to dark theme, those client properties still contain light colors.

To fix this, it would be necessary to clear those client properties when switching L&F.
E.g. by overriding renderers `updateUI()` method:

~~~java
.setCellRenderer(new DefaultTableCellRenderer() {
	@Override
	public Component getTableCellRendererComponent(
			JTable table, Object value, boolean isSelected,
			boolean hasFocus, int row, int column) {
		return super.getTableCellRendererComponent(table,
				value, isSelected, hasFocus, row, column);
	}

	@Override
	public void updateUI() {
		super.updateUI();
		putClientProperty("rendererColorMemory.background", null);
		putClientProperty("rendererColorMemory.foreground", null);
	}
});
~~~

This works fine, even if using some cell or rollover highlighters.

If `JXTable.USE_DTCR_COLORMEMORY_HACK` is set to `false` and a rollover highlighter is used, then the cell background is not reset correctly after moving mouse over rows:

~~~java
table.setHighlighters( new ColorHighlighter( HighlightPredicate.ROLLOVER_ROW, Color.cyan, null ) );
~~~

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/0470656d-7006-4bf4-b540-2c8569856491)
