### ISSUE TITLE
FlatSVGIcon and File.separator

### ISSUE THREAD

**Issue by tjosinga** [JFormDesigner/FlatLaf#736]
When working with files it is a best practice to use File.separator. However, this does not work for the file reference for a FlatSVGIcon. As I work on Mac I didn't run into the issue, and only found out after testing my application on a Windows machine. 

The Javadoc of the constructor of FlatSVGIcon shows perfectly that one should always use '/' separated string. It indeed does not mention File.separator. So I can and will update my code not to use File.separator. Easy fix.

Just out of curiosity: what is the reason to force this on '/' instead of (or also) File.separator?

**Comment by weisJ** [comment]
Paths to resources in Java archives aren't OS paths. See https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResource-java.lang.String-

**Comment by tjosinga** [comment]
Aaa, that explains it. Didn't know that. Thanks!
