### ISSUE TITLE
JTable header reappears after LnF change and cannot be removed

### ISSUE THREAD

**Issue by Corionis** [JFormDesigner/FlatLaf#739]
Using a JTable with a null header, like this:

```
        table.getTableHeader().setUI(null);
        table.setTableHeader(null);
```
But after the user switches the Look 'n Feel the header reappears with an "A" column title.

Cannot find any technique to remove the header again, including an "invokeLater" thread. Also, table.getTableHeader() returns null after the LnF change..

Odd that it cannot be removed using the same technique.

Suggestions or is this a bug/?

**Comment by DevCharly** [comment]
Can not reproduce this issue.

Using `table.setTableHeader(null)` permanently removes the table header for me.

Are you using plain `JTable`? Or some extended table? e.g. from JIDE or SwingX

**Comment by Corionis** [comment]
Using a plain JTable. 

Changing the LaF this way:
```
    try
    {
        UIManager.setLookAndFeel(new FlatLightLaf());
        FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#" + preferences.getAccentColor()));
        Class<? extends LookAndFeel> lafClass = UIManager.getLookAndFeel().getClass();
        FlatLaf.setup(lafClass.newInstance());
        FlatLaf.updateUI();
    }
    catch (Exception e)
    {
        logger.error(Utils.getStackTrace(e));
    }
```

Once that is done the JTable header is shown with an "A" but ```table.getTableHeader()``` returns null.

Is the LaF change approach correct, going from dark to light?

Thank you for your time and this great software. 
btw - Was as born in Augsburg, but grew-up on an Iowa farm.

**Comment by DevCharly** [comment]
`UIManager.setLookAndFeel()` is actually the same as `FlatLaf.setup()`. So you're setting the L&F twice in your example.

Still can not reproduce the problem.

Here is a complete test case:

~~~java
import java.awt.*;
import java.util.Collections;
import javax.swing.*;
import com.formdev.flatlaf.*;

public class NoTableHeaderTest
	extends JFrame
{
	public static void main( String[] args ) {
		SwingUtilities.invokeLater( () -> {
			FlatLaf.setGlobalExtraDefaults( Collections.singletonMap( "@accentColor", "#f00" ) );
			FlatLightLaf.setup();
			new NoTableHeaderTest();
		} );
	}

	public NoTableHeaderTest() {
		setTitle( "NoTableHeaderTest" );
		setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );

		Object[][] data = { { "row 0", "0000" }, { "row 1", "1111" }, };
		Object[] columnNames =  { "Col 1", "Col 2" };

		JTable table = new JTable( data, columnNames );
		table.setTableHeader( null );

		JButton lightLafButton = new JButton( "Light Laf" );
		JButton darkLafButton = new JButton( "Dark Laf" );

		lightLafButton.addActionListener( l -> {
			FlatLightLaf.setup();
			FlatLaf.updateUI();
		} );
		darkLafButton.addActionListener( l -> {
			FlatDarkLaf.setup();
			FlatLaf.updateUI();
		} );

		add( lightLafButton, BorderLayout.WEST );
		add( darkLafButton, BorderLayout.EAST );
		add( new JScrollPane( table ), BorderLayout.SOUTH );

		pack();
		setVisible( true );
	}
}
~~~

After start:

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/5b8e46ea-af74-4502-9b51-87391d7b60af)

After pressing "Dark Laf" button:

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/7edbc906-fc00-4e9e-8934-00dfa054567a)

No table header shown...

**Comment by Corionis** [comment]
Have spent 2 days on this. Rearranged the initialization and LaF change to be exactly as your example. It's in a "Settings" non-modal dialog.

However table headers still reappear after the ```FlatLaf.updateUI();``` call. Subsequent ```table.getTableHeader();``` calls return null, although the head is shown. Refresh and repaint have no effect.

Assumed it was something in my code but sure can't find it. Need to move forward with other work and am going to let this go for now.

I'll leave closing this Issue to you.  Thanks for your time.

**Comment by DevCharly** [comment]
Sorry to hear that...

Have you tried to set some breakpoints to find out where it comes from?
E.g. on `JTableHeader` constructors or on `JScrollPane.setColumnHeaderView()`.

**Comment by Corionis** [comment]
Outstanding! 

It turned-out to be the JScrollPane adding it back. Setting ```scrollpane.setColumnHeaderView(null);``` after ```FlatLaf.updateUI();``` solved the problem.

Thank you very much for the intelligent tip! _That is the solution._

**Comment by DevCharly** [comment]
But were does the header come from when switching L&F?

**Comment by DevCharly** [comment]
Who calls `scrollpane.setColumnHeaderView()` with **not** `null` parameter, when switching L&F?

**Comment by Corionis** [comment]
Commented-out my solution and setup a direct test case.

Have breakpoints on:
  - ```table.setTableHeader()```
  - ```scrollPane.setColumnHeader()```
  - ```scrollPane.setColumnHeaderView()```

It never stops.

The solution of setting ```scrollPane.setColumnHeaderView(null)``` works but why is a mystery.  I do have a custom table model that extends ```DefaultTableModel``` and does not override ```getColumnName(int columnIndex)```. Any override makes the header appear. Do not see anything else in the those classes that appears to have anything to do with it. 

So two of the several in the application look like this:
![Screenshot from 2023-09-30 13-32-19](https://github.com/JFormDesigner/FlatLaf/assets/21012251/4ac35be5-3b61-4b5e-82e6-16d8874cefef)

Is there any other way it can be changed, or ideas on where to debug? A default model perhaps? Something is doing it - and it's not "real" in that the 'gets' return null.

---
The current code:
```
    if (isInitial) // not sure if this matters
    {
        UIManager.put("Tree.showDefaultIcons", true);
        UIManager.put("ScrollBar.showButtons", true); // show scrollbar up/down buttons
        UIManager.put("Component.hideMnemonics", false); // show/hide mnemonic letters
        UIManager.put("TabbedPane.showTabSeparators", true); // separators between tabs

        // set accent color for current LaF
        if (getAccentColor() == null || getAccentColor().length() < 1)
        {
            setAccentColor(DEFAULT_ACCENT_COLOR);
        }
        String accent = getAccentColor();
        FlatLaf.setGlobalExtraDefaults(Collections.singletonMap("@accentColor", "#" + accent));
    }

    switch (getLookAndFeel())
    {
        // Built-in themes
        case 0:
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            break;
        // FlatLaf themes
        case 1:
            FlatLightLaf.setup();
            break;
        case 2:
            FlatDarkLaf.setup();
            break;
        case 3:
            FlatIntelliJLaf.setup();
            break;
        case 4:
        default:
            setLookAndFeel(4);
            FlatDarculaLaf.setup();
            break;
        case 5:
            FlatMacLightLaf.setup();
            break;
        case 6:
            FlatMacDarkLaf.setup();
            break;
    }

    FlatLaf.updateUI();
```

**Comment by DevCharly** [comment]
Please also try breakpoints at `JTableHeader` constructors and at `JViewport.setView()`.

Don't think that L&F initialization has something to do with the issue.

Do you use a custom scroll pane?

**Comment by Corionis** [comment]
Did that. It still never stops..

However I was wrong. After ```FlatLaf.updateUI();``` a call to ```scrollPane.getColumnHeader()``` does in fact have that header.  The **table** header is null.

Not using a custom JScrollPane. And should mention this is OpenJDK 8. That make be a difference.

**Comment by DevCharly** [comment]
😕 

And the example from https://github.com/JFormDesigner/FlatLaf/issues/739#issuecomment-1739280959 works for you, right?

**Comment by Corionis** [comment]
Actually had not tried until now. Just followed your example.

In any case yes, your example works as expected. That removes OpenJDK 8 as a variable.

I've been cutting code professionally since 1976 and this one has me stumped, so far. This is the Version-4.0.0 branch of a GitHub project called [ELS](https://github.com/Corionis/ELS/tree/Version-4.0.0). Let me know if you want to take a look. There are a couple of steps to set it up. Built with IntelliJ of course.

**Comment by Corionis** [comment]
If interested I can provide a test script and breakpoint locations. The code involved is isolated.

Willing to help if you want to chase this.

**Comment by DevCharly** [comment]
Mystery solved 😄 

It has nothing to do with FlatLaf. Also occurs e.g. when starting with Window L&F and switching to Nimbus.

The problem is that you "try to remove" the table header **too late**. After it has been **made visible**.
That's why `table.setTableHeader(null)` did not work for you and you added  `table.getTableHeader().setUI(null)`.

The table header is created by JTable and applied to `JScrollPane.setColumnHeaderView()` when the frame is **made visible** (see `JTable.configureEnclosingScrollPane()`).`

Invoking `table.setTableHeader(null)` on a displayed table simply clears JTable field `tableHeader`, but does remove the table header from the JScrollPane.

`table.getTableHeader().setUI(null)` removes the UI delegate from the table header (size becomes 0,0), but it does not remove the table header. `FlatLaf.updateUI()` recreates UI delegates for all components, which now shows the table header.

Solution: invoke `table.setTableHeader(null)` before showing the main window 😉

**Comment by Corionis** [comment]
:100: Above & beyond! Thanks a lot for debugging my code. A nuance I was not aware of, obviously. Have one on me mate! :beer:
