### ISSUE TITLE
Can't figure out how to change font size using heading name in Theme Editor.

### ISSUE THREAD

**Issue by ForceConstant** [JFormDesigner/FlatLaf#740]
So I created a new theme with "@baseTheme = darcula", and then 
`Button.font = H2`
And nothing happens. Interestingly I don't see any examples of something like this in the docs, but it seems that it would be a common option.  What am I missing?

**Comment by DevCharly** [comment]
Use
~~~
Button.font = $h1.font
~~~

The fonts are defined here:
https://github.com/JFormDesigner/FlatLaf/blob/67b0faa9aeefba3ad9d6219d829437db411d050d/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties#L32-L37

See also https://www.formdev.com/flatlaf/typography/
