### ISSUE TITLE
ScrollPane border paint problem at large scalings

### ISSUE THREAD

**Issue by tristanzhou** [JFormDesigner/FlatLaf#743]
I've seen the four sides of a ScrollPane border painted with different thicknesses at large scalings: 125% ~ 175%. 
Any idea that we can work around this?

![scrollpane borders](https://github.com/JFormDesigner/FlatLaf/assets/5662534/1a17b40b-ed89-42aa-89ab-cad2a356c3ea)

**Comment by DevCharly** [comment]
> I've seen the four sides of a ScrollPane border painted with different thicknesses at large scalings: 125% ~ 175%.

This is because Swing scales the 1px border either to one or to two screen pixels.

> Any idea that we can work around this?

Not really...

**Comment by DevCharly** [comment]
Fixed in latest `3.5-SNAPSHOT`: https://github.com/JFormDesigner/

The scrollpane border now has same thickness on all 4 sides.
