### ISSUE TITLE
FlatMenuItem icon won't act accordingly to the hover effect

### ISSUE THREAD

**Issue by MomoTheDev** [JFormDesigner/FlatLaf#748]
When the cursors hovers above a FlatMenuItem, the hover effect changes it's appearance and turn it's foreground color from #000000 to #FFFFFF but the icon will stay the same. This ends up in a very low contrast sometimes.

Here are my screenshots:
- Hovered
![image](https://github.com/JFormDesigner/FlatLaf/assets/82108477/d4cefafe-a64d-46a7-929f-de11b577357f)

- Unhovered
![image](https://github.com/JFormDesigner/FlatLaf/assets/82108477/68b2c006-147c-4536-8d3f-fce250ce60ed)

**Comment by DevCharly** [comment]
It's up to you to provide a special icon for selected state (if needed).

If using bitmap icons, you probably need to create another bitmap icon and assign it with:

~~~java
menuItem.setSelectedIcon(...);
~~~

If you're using a vector icon, you can check armed/selected state in `Icon.paintIcon()` and use special colors to paint the icon.

Here is a subclass of `FlatSVGIcon` that changes all colors to `MenuItem.selectionForeground` when icon is used in `JMenuItem` and menu item is armed or selected:

~~~java
private static class MyFlatSVGIcon
    extends FlatSVGIcon
{
    private static final ColorFilter SELECTED_FILTER = new ColorFilter(
        color -> UIManager.getColor( "MenuItem.selectionForeground" ) );

    public MyFlatSVGIcon( String name ) {
        super( name );
    }

    @Override
    public void paintIcon( Component c, Graphics g, int x, int y ) {
        boolean selected =
            (c instanceof JMenuItem && ((JMenuItem)c).isArmed()) ||
            (c instanceof JMenu && ((JMenu)c).isSelected());
        setColorFilter( selected ? SELECTED_FILTER : null );

        super.paintIcon( c, g, x, y );
    }
}
~~~

**Comment by MomoTheDev** [comment]
Thank you for the clarification. I was able to achieve my desired look by implementing your implementation of the extended FlatSVGIcon class. If someone else wants to use this class, I would really suggest to rename it to `AdaptiveSVGIcon` or `DynamicSVGIcon` for the better understand of its usage.
