### ISSUE TITLE
TextArea with a border has focus color painting issues

### ISSUE THREAD

**Issue by BaGuLus** [JFormDesigner/FlatLaf#749]
**_Description:_**
Hello,

I have found a issue, that I think is a problem in FlatLaf, not just an application I work on, because I could replicate it on MRE too. It's related to a focus color of a JTextArea, which has a Flat border set. If I click on the JTextArea, the border is not repainted with the focus color until I resize the component. Then if I give focus to other component, the border stays painted with the focus color.  Sometimes not the whole border stays colored _(Image Not Whole Border Colored)_.

**_Temporary(?) solution:_**
If I add a FocusListener to the JTextArea, where I call repaint() in both focusGained() and focusLost(), then it works normally.

**_STR:_**
1. Have a JTextArea with a border set (I have tried FlatBorder, FlatRoundBorder, FlatTextBorder), which is put into a JSplitPane (with any other component).
2. Have any other component that has the border with focus color (for example JTextField). 
3. Click on the JTextArea or have a text inside the JTextArea and highlight it - its border does not get focus (or it doesn't have the focus border color).
4. Resize the JTextArea (move the JSplitPane divider or resize the whole app window) - the JTextArea's border gets the focus color.
5. Click on other component (the JTextField) - it gets the focus border color, but this color also stays on the JTextArea. _(Image Step 5)_
6. Resize the JTextArea again - the JTextArea loses the focus border color.

_Image Not Whole Border Colored:_
![image](https://github.com/JFormDesigner/FlatLaf/assets/120109389/f88f3b6d-962c-4535-90fd-0cd024a53c41)

_Image Step 5:_
![image](https://github.com/JFormDesigner/FlatLaf/assets/120109389/654cbd7c-2ca7-4a34-8f7e-5ed04d7e0b96)

**_Environment:_**
- Java version: 17.0.6
- FlatLaf version: 3.2.2
- Operating system: Windows 10 22H2

**_MRE:_**
```java
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.ui.FlatBorder;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;

public class FlatLafTextAreaTestApp {
    private FlatLafTextAreaTestApp() {}

    public static void main(String[] args) {
        FlatLafTextAreaTestApp.run();
    }

    public static void run() {
        SwingUtilities.invokeLater(FlatLafTextAreaTestApp::init);
    }

    private static void init() {
        FlatLightLaf.setup();
        // make the border more visible
        UIManager.put("Component.borderWidth", 3);

        JFrame jFrame = new JFrame("FlatLaf TextArea Test App");
        jFrame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        jFrame.setSize(600, 300);

        Container contentPane = jFrame.getContentPane();

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.PAGE_AXIS));

        JTextArea textAreaWithoutBorder = new JTextArea("JTextArea without a border");

        JTextArea textAreaWithBorder = new JTextArea("JTextArea with a FlatBorder");
        textAreaWithBorder.setBorder(new FlatBorder());

        JSplitPane splitPane = new JSplitPane();
        splitPane.setLeftComponent(textAreaWithoutBorder);
        splitPane.setRightComponent(textAreaWithBorder);
        splitPane.setDividerLocation(275);

        mainPanel.add(splitPane);
        mainPanel.add(Box.createRigidArea(new Dimension(0, 5)));

        contentPane.add(mainPanel, BorderLayout.CENTER);
        contentPane.add(new JTextField("Click me to steal the focus"), BorderLayout.PAGE_END);

        jFrame.setVisible(true);
    }
}

```

**Comment by MomoTheDev** [comment]
This may help (a property for the child component): 
```java
textArea.putClientProperty("JComponent.focusOwner", (Predicate<JComponent>) component -> {
	return false;
});
```

**Comment by DevCharly** [comment]
This is actual normal behavior.

`JTextArea` does not have any border by default.
If you add a border, you're responsible for updating on focus changes.

But usually you should put the `JTextArea` into a `JScrollPane`, which provides the border and listens to focus changes to update the border.

**Comment by BaGuLus** [comment]
> This may help (a property for the child component):
> 
> ```java
> textArea.putClientProperty("JComponent.focusOwner", (Predicate<JComponent>) component -> {
> 	return false;
> });
> ```

Thank you very much, this indeed works.

**Comment by BaGuLus** [comment]
> This is actual normal behavior.
> 
> `JTextArea` does not have any border by default. If you add a border, you're responsible for updating on focus changes.
> 
> But usually you should put the `JTextArea` into a `JScrollPane`, which provides the border and listens to focus changes to update the border.

Thank you very much for the explanation, describes perfectly what I wanted to know. Closing the issue.
