### ISSUE TITLE
problem with setting properties

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#751]
Hi,
I have a JButton where I'm trying to remove the border outline and increment the border arc, but all the below examples didn't work...
I'm most probably doing something wrong, but I tried looking at the documentation and the examples but I can't figure this one out...!

`action` is the `JButton` object.

```
    action.putClientProperty( "Button.borderWidth", 0 );
    action.putClientProperty( "Component.focusWidth", 0 );
    action.putClientProperty( "Component.arc", 12 );
```

```
    action.putClientProperty( "JButton.borderWidth", 0 );
    action.putClientProperty( "JButton.focusWidth", 0 );
    action.putClientProperty( "JButton.arc", 12 );
```

```
    action.putClientProperty( "borderWidth", 0 );
    action.putClientProperty( "focusWidth", 0 );
    action.putClientProperty( "arc", 12 );
```

then I tried to see if setting it globally would do something.... which doesn't

```
    UIManager.put( "Button.borderWidth", 0 );
    UIManager.put( "Component.focusWidth", 0 );
    UIManager.put( "Component.arc", 12 );
```

**Comment by MomoTheDev** [comment]
You can remove the border by using 
```java
JButton.setBorder(null);
```

**Comment by MomoTheDev** [comment]
Oh, now I understand. You could add the `FlatLaf-Extras` library and use the `FlatButton` class (instead of `JButton`). The `FlatButton` class provides you with extra features, including the custom button type feature.
```java
flatButton.setButtonType(ButtonType.toolBarButton);
```
It will give you the same look and feel that you're looking for.

**Comment by Frank-99** [comment]
Oh I didn't know I could do this, amazing!
Thank you very much, this does exactly what I want ahah
I'll have to look more into the FlatLaf-Extras!
