### ISSUE TITLE
textarea rounded corners

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#757]
Hi, is there a way to achieve something similar to this?
![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/05a64582-7495-4ab0-8ca4-0fa0d0c6013d)

I can't find a way to round the corners on a scrollview... it comes out squared while all the other components are rounded. 
![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/a134f257-f1c9-4443-95ce-2f09a61db73c)

I've found some hacky solutions but are not perfect... is there a built in way to do this or do I just need to make my own "FlatScrollPaneBorder" implementation, which sounds like a bit of a pain?
I've tried in vain to use this code below
```
	FlatTextBorder border = new FlatTextBorder();
	border.applyStyleProperty("arc", 12);
	
	//test 1
	noteScrollPane.putClientProperty("ScrollPane.viewportBorder", border);
	
	//test 2
	noteScrollPane.putClientProperty("ScrollPane.border", border);
	
	//test 3
	noteScrollPane.setBorder(border);
```
But at best it comes out like this
![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/81ea156b-58e8-4fb6-9dc1-b03d5f396766)

**Comment by DevCharly** [comment]
See PR #713

**Comment by Frank-99** [comment]
Ah yes, this is what I was looking for!
And sorry, I'll have to look better in the closed issues next time...
