### ISSUE TITLE
weird inital popup menu position scaling issue when moving between different monitors

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#759]
I have 2 monitors, Monitor 1 has 125% scale and monitor 2 has 100% scale. 

![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/4fb91fbd-d192-4905-b37d-d5cf3ec78677)

If I move the app to monitor 1, then move it back to monitor 2, then the first time I open the menu popup it displays to the 1.25 scaled position (screenshot 1), then if I close it and reopen it, it willl display correctly to the 100% scale position (screenshot 2)

![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/02ebf43b-a51c-46ee-8e54-e3e692c911fd)

![image](https://github.com/JFormDesigner/FlatLaf/assets/49396838/5c00af5d-bdd3-4a9d-a10d-684a6193da19)

If I disable the FlatLaf this issue is not presenting....
Using Win11 and Java 17

**Comment by Frank-99** [comment]
After a few more tests this is what I found:

If the app launches to the screen 1 the JFrame has the correct size.
If the app launches to the screen 2 the JFrame has the size scaled by 125%.

All JPopupMenus that open for the first time on screen 2 have an initial position scaled by 125% that then gets corrected when they get shon for a second time

**Comment by DevCharly** [comment]
Hmm, can not reproduce this issue 😕 

Is this a standard menu bar in the screenshots?
Does the FlatLaf Demo have the same problem?
What is the full version of your Java 17?

**Comment by Frank-99** [comment]
Example

```
	public static void main(String[] args) {
		SwingUtilities.invokeLater(() -> {
			FlatLightLaf.setup();
			
			JFrame frame = new JFrame();
			frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			
			frame.setPreferredSize(new Dimension(400, 200));
			
			JMenuBar menuBar = new JMenuBar();
			frame.setJMenuBar(menuBar);
			
			JMenu menu_edit = new JMenu();
			menu_edit.setText("Modifica");

			JMenuItem item_edit_resurces = new JMenuItem();
			item_edit_resurces.setText("Risorse");
			item_edit_resurces.addActionListener((e) -> {
				
			});
			menu_edit.add(item_edit_resurces);

			JMenuItem item_edit_categories = new JMenuItem();
			item_edit_categories.setText("Categorie");
			item_edit_categories.addActionListener((e) -> {
				
			});
			menu_edit.add(item_edit_categories);

			menuBar.add(menu_edit);
			
			frame.pack();
			frame.setVisible(true);
		});
	}
```

using FlatLaf 3.2.5
compiling for java 9 but running it with java 17

**Comment by Frank-99** [comment]
Aha, when I was writing the reply it dawned on me...
technically if I compile with Java 9 it happens only using FlatLaf and not with normal LAF. but if I try to compile for java 11 the issue doesn't happen... is it safe to assume it's a java < 11 problem then?

**Comment by DevCharly** [comment]
Compiling with Java 9 or with 11 should actually not make any difference if you run both in same Java 17. 😕 

What is the full version of your Java 17?
There may be HiDPI fixes/changes in Java 17 patch versions and I'd like to try it with exact the same version that you use.

**Comment by Frank-99** [comment]
Java 17.0.8 compiled with Netbeans 19 and using gradle...
Tell me if you need other details...

**Comment by DevCharly** [comment]
Sorry, but can not reproduce this issue. Whatever I try, it is always shown at the correct location.

> ...  but if I try to compile for java 11 the issue doesn't happen ...

I recommend to build your project using Java 11 (or later).
Java 9 (and 10) already have reached end-of-life and should no longer used.
So it makes no sense to compile for Java 9 or use Java 9 as minimum requirement for an application.
Always use a LTS versions 😉
