### ISSUE TITLE
Displaying project folders in Netbeans 11.3 under Gnome (Linux) with errors

### ISSUE THREAD

**Issue by chris576** [JFormDesigner/FlatLaf#76]
Hi, 
I have installed Netbeans 11.3 to benefit from the flat light laf. But under Gnome the project folders are unreadable. Is there anything I can do? 

![flatLightLAFProject](https://user-images.githubusercontent.com/59051160/76087845-3e791d00-5fb7-11ea-954d-b6a45c2cb7ab.png)

**Comment by DevCharly** [comment]
Thanks for reporting.

Seems that the problem is that FlatLaf scales the font, but the tree item height is not scaled.

Do you use a HiDPI screen and have scaling enabled in Gnome settings panel?
"Settings > Devices > Displays > Scale (100% or 200%)" or
"Settings > Universal access > Large Text"?

**Comment by NerdyChris** [comment]
Thanks for responding.

"Settings > Devices > Displays > Scale (100% or 200%)" : This adjustment is not available on my device. 
"Settings > Universal access > Large Text"; This adjustment has no effect referred to the  problem.

I do not use a HiDPI screen. I do use Linux under VM Player. Anything is working under KDE.

**Comment by DevCharly** [comment]
@NerdyChris I'm not yet able to reproduce this problem.

Could you please give me some details about the Linux system?
- Linux distribution name and version
- Java version used to run NetBeans

Is this problem limited to the project folders as shown in the screenshot above?
Or is text painted everywhere at wrong position?

Could you please post a screenshot of the NB Options dialog

**Comment by martin-jamszolik** [comment]
This is likely an issue with your JDK font rendering. I recommend you start Netbeans using the following JDK where font rendering is fixed. This JDK is maintained by Jetbrains.  
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime

Just change the path in your `etc/netbeans.conf`

It's boggles my mind why upstream OpenJDK does not have these fixes.
Needless to say, I am running Netbeans 11.3 on Linux (fedora 31) in Native 4K
with ubuntu font and it looks beautiful.
![Screenshot from 2020-04-09 09-03-40](https://user-images.githubusercontent.com/1155998/78898054-29bdf800-7a41-11ea-843c-3fec110dc929.png)

**Comment by NerdyChris** [comment]
Thank you, that worked! :)
