### ISSUE TITLE
Increase insets of combos when inside a toolbar

### ISSUE THREAD

**Issue by ShadelessFox** [JFormDesigner/FlatLaf#760]
Currently, if you have several combos, one next to another, in a toolbar, it will look like this:

![image](https://github.com/JFormDesigner/FlatLaf/assets/35821147/11c51277-c70c-4c48-9a8e-4e5cd3316186)

I wish it would look something like this instead:

![image](https://github.com/JFormDesigner/FlatLaf/assets/35821147/91b12828-1ccc-4792-a468-043e3f7722df)

As a workaround, I have to insert `Box.createHorizontalStrut(4)` between every combo.

**Comment by DevCharly** [comment]
And what's wrong with the horizontal strut?

Here is an alternative solution: https://github.com/JFormDesigner/FlatLaf/issues/56#issuecomment-586297814

**Comment by ShadelessFox** [comment]
Because it looked hacky to me. Looking at the proposed solution, I think my solution is acceptable, too 🙂

Thanks for the response. I'll close the issue
