### ISSUE TITLE
Suggestion: Allow "ScrollBar.width" to be set for a single component

### ISSUE THREAD

**Issue by electriq** [JFormDesigner/FlatLaf#763]
Some style properties can be set either globally, for example:
`UIManager.put( "ScrollBar.showButtons", true );`
or for a single component:
`myScrollPane.putClientProperty( "JScrollBar.showButtons", true );`

But there are properties that are only global, like `"ScrollBar.width"`. It would be nice to have a possibility to override `"ScrollBar.width"` for a single component. Maybe this is only ours need, but I suppose that someone may need some other properties to be set for a single component. Thank you!

**Comment by DJ-Raven** [comment]
Use this :
``` java
myScrollPane.getVerticalScrollBar().putClientProperty(FlatClientProperties.STYLE, "width:5");
```
