### ISSUE TITLE
Unsharp Text rendering with Inter Font

### ISSUE THREAD

**Issue by Aerobraking** [JFormDesigner/FlatLaf#764]
Hello,

I have noticed that texts with the Inter font are not displayed sharply. Attached is a comparison between Segoe UI which I usually use and the Inter Font. 

The situation is the same when I use the Flatlaf demo.

Is the rendering correct? After all, Inter is designed to always be sharp on screens and I am not used to this blurred rendering from other apps that use Inter. 

The Code I use is this:

            FlatInterFont.installLazy();

            FontUtils.loadFontFamily(FlatInterFont.FAMILY);
            FontUtils.loadFontFamily(FlatInterFont.FAMILY_LIGHT);
            FontUtils.loadFontFamily(FlatInterFont.FAMILY_SEMIBOLD);

            FlatLaf.setPreferredFontFamily(FlatInterFont.FAMILY);
            FlatLaf.setPreferredLightFontFamily(FlatInterFont.FAMILY_LIGHT);
            FlatLaf.setPreferredSemiboldFontFamily(FlatInterFont.FAMILY_LIGHT);

            IntelliJTheme.setup(MainClass.class.getResourceAsStream("/ui/UIHelper/arc-theme-orange.theme.json"));

I also tried this, without any change in rendering:
 
            System.setProperty("awt.useSystemAAFontSettings", "on");
            System.setProperty("swing.aatext", "true");

Screenshots:
Inter:
![test_inter](https://github.com/JFormDesigner/FlatLaf/assets/4540741/3f954e29-e83b-44a8-a7a2-95a7c50fae2a)
Segoe UI:
![test_segoe](https://github.com/JFormDesigner/FlatLaf/assets/4540741/a4d5f321-8462-40ff-938f-4fa5076655fe)

And here zoomed in
Inter:
![test_inter_zoom](https://github.com/JFormDesigner/FlatLaf/assets/4540741/2481e853-e2f8-46eb-90d6-9e17d664c9c7)
Segoe UI:
![test_segoe_zoom](https://github.com/JFormDesigner/FlatLaf/assets/4540741/8fb4d72b-4aab-44f5-a880-e4cd5027b5af)

**Comment by DevCharly** [comment]
Is this on Linux?
What Java version do you use to run this app?

**Comment by Aerobraking** [comment]
Hey, 

Windows 10 64 bit, openJDK 15. I think I tried also newer Java version, but I will fact check this again!

**Comment by Aerobraking** [comment]
It' the same Issuer with Windows 10 64 bit, JDK 18.0.1.1 on my other PC.

**Comment by DevCharly** [comment]
Please try Inter v4.0: https://github.com/JFormDesigner/FlatLaf/releases/tag/fonts%2Finter-4.0

Looks better to me:

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/5604048/3e0d4cc6-c4b1-4953-9102-4ae2f7ba3b8b)

(left is Inter v3.19, right is Inter v4.0)

You could also try the Inter `.ttf` fonts, which should have Windows specific rendering hints.
Maybe they look better than the Inter `.otf` fonts that FlatLaf integrates.
The `.ttf` fonts are in `Inter-4.0.zip` that you can download here: https://github.com/rsms/inter/releases/tag/v4.0


FlatLaf only provides a simple way to integrate those fonts into applications.
The rendering is done by Swing.
FlatLaf has no influence on the font rendering quality.
