### ISSUE TITLE
Components alignment failure - overriding each other

### ISSUE THREAD

**Issue by SakthiRJ** [JFormDesigner/FlatLaf#765]
I am encountering an issue with component alignments where all components are overlapping in the panel. Is there a way to prevent this problem? I am currently using FlatLightLaf. Your assistance in resolving this matter is appreciated. I've highlighted the issue using a blue line for reference.

![image (1)](https://github.com/JFormDesigner/FlatLaf/assets/104691007/8c130f69-e07f-4319-a5f8-56cb61ea2221)

The text within fields is only partially visible, extending beyond visibility limits, and the text field sizes are inconsistent. In this instance, both text field components have the same length, yet they display different sizes when executed. Additionally, there is no gap between the fields. What might I be overlooking? What should I define in the properties file to address this issue?

![image (2)](https://github.com/JFormDesigner/FlatLaf/assets/104691007/31976e44-6b5e-47ee-8587-cb55920b2a9b)

I am using 1.6.5 version
JDK - 11

Thanks in advance!

**Comment by DevCharly** [comment]
This are layout issues.
What layout manager do you use?

**Comment by DevCharly** [comment]
And do the components also overlap in the GUI builder?

**Comment by SakthiRJ** [comment]
Everything appears good in the GUI builder, and it also looks fine in the preview panel. 

builder preview
<img width="472" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/104691007/50863ff3-72e6-4f7c-b176-49ca6e92e4a6">

Why this data load is also looks like this?
![image (2)](https://github.com/JFormDesigner/FlatLaf/assets/104691007/31976e44-6b5e-47ee-8587-cb55920b2a9b)

**Comment by SakthiRJ** [comment]
This issue happens in my entire panel in run time. GUI builder shows it perfectly with default layout

**Comment by DevCharly** [comment]
> This issue happens in my entire panel in run time. GUI builder shows it perfectly with default layout

Maybe the width of the panel is larger in the GUI builder than in the running application?

> Why this data load is also looks like this?
> ![image (2)](https://github.com/JFormDesigner/FlatLaf/assets/104691007/31976e44-6b5e-47ee-8587-cb55920b2a9b)

Don't know. Seems that the field is too small...

NetBeans supports using FlatLaf as application look and feel.
I recommend to change the NetBeans L&F to FlatLaf (Menu: Tools > Options > Appearance > Look and Feel).
Then the NB GUI builder uses also FlatLaf.
Maybe this helps...

Some rules to use GridBagLayout:
- use "insets" (in **Customize Layout** dialog) to define gaps between components
- or better enable **uniform gaps** (in **Customize Layout** dialog) 
- use `JTextField.columns` property to give text fields a minimum width if necessary
- do not change component minimum/preferred/maximum size in GUI builder

**Comment by SakthiRJ** [comment]
The alignment of fields becomes problematic when a JPanel is nested within another JPanel. While the components in the first JPanel align correctly using GridBagLayout, the components in the inner JPanel encounter alignment issues. The Inner Jpanel is also using the GridBagLayout. They tend to override each other, leading to alignment problems that occur in various instances.

<img width="472" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/104691007/50863ff3-72e6-4f7c-b176-49ca6e92e4a6">
