### ISSUE TITLE
Support Radiance as additional module

### ISSUE THREAD

**Issue by tlf30** [JFormDesigner/FlatLaf#768]
Hello,
OK, I know this is a long shot, but I was wondering if you would consider supporting Radiance, probably as an additional module.
I asked about FlatLaf support in the Radiance repo, but it sounds like it would be something that would have to be implemented on the laf side, not the radiance side.  https://github.com/kirill-grouchnikov/radiance/issues/455

Thoughts? 

Thank you,
Trevor

**Comment by DevCharly** [comment]
I've no plans to implement support for Radiance components in FlatLaf.

This could be done in an independent project. 
You just need someone that does the work... 😉 

Had a look at the documentation of the Radiance Ribbon component.
Seems to be a very powerful component with a lot of code.
Could take some time to support FlatLaf...

I spent about 1 month on SwingX support for FlatLaf,
and more than 2 months for JIDE (thankfully partly sponsored by DbVis Software).
