### ISSUE TITLE
Move traffic lights on MacOS

### ISSUE THREAD

**Issue by remcopoelstra** [JFormDesigner/FlatLaf#769]
This has been discussed before (I mentioned a possible solution myself in #562), I am once again at a point where I would like to give my apps a more modern look on MacOS but the biggest problem is always the positioning of the traffic lights (window control buttons). The jetbrains runtime can do this but I just tested the ```"apple.awt.windowTransparentTitleBarHeight"``` property doesn't seem to be working anymore in the latest jetbrains runtime release, and I would also prefer to be able to run my app on other jdk distributions.

It would be great if FlatLaf supported this feature, I think this would probably mean creating a native library similar to decorations on windows. Depending on how much work this is I might consider sponsoring this feature.

**Comment by remcopoelstra** [comment]
I decided to give this a try myself and I think I just got this to work, I had a look at the Jetbrains implementation and put together a small native library that i'm calling through jna, if you want I can direct message you my xcode project with a demo application if your interested.

My app is now looking like this:
<img width="1663" alt="Screenshot 2023-11-27 at 19 18 28" src="https://github.com/JFormDesigner/FlatLaf/assets/16516303/f5897a17-a088-4e1f-bdd7-179ababc7da6">

**Comment by DevCharly** [comment]
That looks great 👍 💯 

Yes, I'm interested in that code and consider adding this feature to FlatLaf.
Can you please send it to support@formdev.com ?

**Comment by remcopoelstra** [comment]
I will send you the code as soon as possible, I have been experimenting a little more so I need to do some cleaning up. I will send you a minimal project with just the code needed to move the control buttons, and another project with all my experimental code, for example I just managed to get a vibrant background working with another app:

<img width="1580" alt="Screenshot 2023-12-02 at 14 18 13" src="https://github.com/JFormDesigner/FlatLaf/assets/16516303/5628b435-632b-4a7f-96d8-86db6f81fb14">

I'm not yet really sure though if this experimental stuff is suitable for releasing :wink:

**Comment by duhiqc** [comment]
> I will send you the code as soon as possible, I have been experimenting a little more so I need to do some cleaning up. I will send you a minimal project with just the code needed to move the control buttons, and another project with all my experimental code, for example I just managed to get a vibrant background working with another app:
> 
> <img alt="Screenshot 2023-12-02 at 14 18 13" width="1580" src="https://private-user-images.githubusercontent.com/16516303/287450524-5628b435-632b-4a7f-96d8-86db6f81fb14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjc0NDIsIm5iZiI6MTcwMjEyNzE0MiwicGF0aCI6Ii8xNjUxNjMwMy8yODc0NTA1MjQtNTYyOGI0MzUtNjMyYi00YTdmLTk2ZDgtODZkYjZmODFmYjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEzMDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjI3MDE3MmUxNDIxOGJlZDljOWYyYzJmNmM3YjhlYmUwNzNhODQxZGU1NDVmM2JiNWNjZTQ2MDQ4OWM3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5EFL0Ju5BPj_Obze_cIzcUeJNlc9vJRUD3Euf4xhe9g">
> I'm not yet really sure though if this experimental stuff is suitable for releasing 😉

Can you share this code

**Comment by basix86** [comment]
> I decided to give this a try myself and I think I just got this to work, I had a look at the Jetbrains implementation and put together a small native library that i'm calling through jna, if you want I can direct message you my xcode project with a demo application if your interested.
> 
> My app is now looking like this: <img alt="Screenshot 2023-11-27 at 19 18 28" width="1663" src="https://private-user-images.githubusercontent.com/16516303/285971573-f5897a17-a088-4e1f-bdd7-179ababc7da6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTYzNjksIm5iZiI6MTcwMjI5NjA2OSwicGF0aCI6Ii8xNjUxNjMwMy8yODU5NzE1NzMtZjU4OTdhMTctYTA4OC00ZTFmLWJkZDctMTc5YWJhYmM3ZGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OThmMDk5M2ExMGE4YWI0ZjQ4MmVlMTY2MGVhZjA1MjcwMzM1ZGNhMzM1NmI2NjRhZTcxOTdmNWNiZGVhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tKUbRUaSnNTDO-WeXmS4_s_fNrDwrTGVk0UDG4n9n_g">

Just a curiosity. 
How you have generated the graph of occurrences? Is it a plugin?

**Comment by remcopoelstra** [comment]
> Can you share this code

For now I prefer to wait and see if FlatLaf will support this at some point (I don't want to interfere with this), if it doesn't get supported I might consider releasing something myself, but at this moment I don't think the quality of my code is good enough.

> Just a curiosity. How you have generated the graph of occurrences? Is it a plugin?

If you are referring to the curved lines that are painted from the text area in the center to the table on the right, that's actually quite simple, I added a GlassPane in which I paint GeneralPaths between the calculated locations of the occurence-string and the table cell. The text area is a RSyntaxTextArea and I am able to get a view-rect for a offset in the text, it did take me some time to get this working correctly in combination with code folding.

To get the string occurrences from the source file I created a parser that also understands eclipse style //$NON-NLS-1$ comments and annotations, this was also a little bit harder.

**Comment by DevCharly** [comment]
See PR #779

**Comment by remcopoelstra** [comment]
This is great! I will give my feedback in the PR.

**Comment by duhiqc** [comment]
![e80a84f4f2bae6ce10fd48940c6e1b9c](https://github.com/JFormDesigner/FlatLaf/assets/153368625/dad19708-c0cc-4794-8e2e-9f87e148ed8e)
How do you avoid the swing component being blocked?

**Comment by remcopoelstra** [comment]
> How do you avoid the swing component being blocked?

It looks like you managed to add a NSVisualEffectView to your NSWindow, there is 1 very big problem to get this working with a java application because java adds a NSView as the contentView of the NSWindow, it needs this to draw the swing components. In a normal mac app you would normally first add the NSVisualEffectView as the contentView and then add your own child views, but with a java app this is not possible, this is why you see NSVisualEffectView being painted over your swing components.

First I tried to rearrange the views but my app crashed because java tries to access the contentView and finds an unexpected view.

I managed to get the swing components painted on top of the NSVisualEffectView by rearranging the CALayers of the views in the NSWindow, I am not sure if it is ok to do this, I feel like this could easily break after an jdk/macos update.

Also another challenge is to make (part of) your swing container transparent to let the NSWindow show through, I did this by setting ```frame.getRootPane().putClientProperty("apple.awt.brushMetalLook", true);``` and ```frame.getRootPane().setBackground(new Color(0, 0, 0, 0));``` and you have to make sure to call ```setOpaque(false);``` on any swing component/panel etc. that needs to be transparent.

This was all very experimental because I was curious if I could get this working, but I would not advise you to use this in your app because there are too many hacks involved to get this working.
