### ISSUE TITLE
JCheckBox opaque = false ignored

### ISSUE THREAD

**Issue by coreequip** [JFormDesigner/FlatLaf#77]
Hi JFormDesigner-Team (hallo Karl),

first thanks for the great FlatLaf - its awesome!

I just switched from Darcula to FlatLaf and now I had to realize that there is a problem with the "opaque-ness" of the `JCheckBox` component. In my case I use a `JScrollPane` with a custom `JViewport` to draw a background image behind the list elements. As a `ListCellRenderer` I use `JCheckBox`es with `opaque = false`. It worked well with all other LAFs but FlatLaf shows a solid (opaque) background color. The expected behavior is a transparent background of the `JCheckBox`' text label.

```groovy

class TrackListCellRenderer implements ListCellRenderer<TrackListBean> {

    private JCheckBox checkBox
    TrackListCellRenderer() {
        checkBox = new JCheckBox()
    }

    @Override
    Component getListCellRendererComponent(JList<? extends TrackListBean> list, TrackListBean value,
                                           int index, boolean isSelected, boolean cellHasFocus) {

        // make sure to have it opaque when selected
        checkBox.opaque = isSelected

        // ...
}
```
(this is groovy code)

Thanks a lot.

**Comment by Chrriis** [comment]
In dark mode, I noticed a table where one column does not respect the background color: it actually has a checkbox renderer. I would need to investigate when time allows, but it might well be linked to this issue.

**Comment by Chrriis** [comment]
Using this one-class test case (warning, nasty look and feel stuff to paint cell background):
[TableTest.zip](https://github.com/JFormDesigner/FlatLaf/files/4586886/TableTest.zip)

We get on Windows:
![TableBackground1](https://user-images.githubusercontent.com/1174202/81180364-36376100-8fab-11ea-9a27-feee8bba461f.png)

and with FlatLaf:
![TableBackground2](https://user-images.githubusercontent.com/1174202/81180377-3b94ab80-8fab-11ea-82f5-ff2e7e53f763.png)

**Comment by DevCharly** [comment]
Sorry for the late response. This should be fixed in master branch now. Hope it works 😉

**Comment by Chrriis** [comment]
Works fine! Thanks!
