### ISSUE TITLE
Add menu item(s) to macOS application menu?

### ISSUE THREAD

**Issue by Corionis** [JFormDesigner/FlatLaf#770]
Is there a way to add menu items to the macOS application menu?

In particular, my application has both "_Quit_" - and "_Quit and Stop Remotes_" options under the File menu if it is connected to a remote instance.

Not a Mac person and not sure what the best, or most-accepted, approach would be?

**Comment by DevCharly** [comment]
> Is there a way to add menu items to the macOS application menu?

Maybe when using native Objective-C API, but not using Java API (as far as I know).

> In particular, my application has both "Quit" - and "Quit and Stop Remotes" options under the File menu if it is connected to a remote instance.

You could show a small dialog (e.g. `JOptionDialog`) when user selects "Quit" from application menu and ask user whether remotes should also stopped.

See `java.desktop.Desktop.setQuitHandler()` (requires Java 9+).
For Java 8, use [com.formdev.flatlaf.extras.FlatDesktop.setQuitHandler()](https://github.com/JFormDesigner/FlatLaf/blob/417f0f5f1c0ef3aff74fb521f14b8214f9b1ae6f/flatlaf-extras/src/main/java/com/formdev/flatlaf/extras/FlatDesktop.java#L146)

**Comment by Corionis** [comment]
Thank you for your time.
