### ISSUE TITLE
Unable to use intellijthemes on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by Hellf0rg0d** [JFormDesigner/FlatLaf#773]
Hey, i'm unable to use these themes but i'm able to use non intellijthemes like macdark, maclight,  i was able to use all of these themes on windows.
--- 
![image](https://github.com/JFormDesigner/FlatLaf/assets/93775719/c6cf0b8c-2fbe-4682-a894-fb9a879e0236)

**Comment by DevCharly** [comment]
Those themes are not in core `flatlaf.jar`.
You also need `flatlaf-intellij-themes.jar`.
See https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-intellij-themes
