### ISSUE TITLE
File chooser should handle Enter key properly

### ISSUE THREAD

**Issue by teohhanhui** [JFormDesigner/FlatLaf#774]
### Steps to reproduce
1. Open the file chooser.
2. Select a file or directory.
3. Press the `Enter` key.

### Expected result
The `Open` button should be triggered, or the selected directory should be entered.

### Actual result
Nothing happens. This works properly with `MetalLookAndFeel`.

**Comment by DevCharly** [comment]
This works for me 😕 
Tested on Windows 11 with Java 8 and 21.

What operating system and Java version do you use?

**Comment by teohhanhui** [comment]
OpenJDK 21 from Flathub, on Fedora Linux 39, KDE Plasma desktop.

**Comment by DevCharly** [comment]
Tries on several Linux distros with several Java versions, but can not reproduce it. The `Enter` key works fine.

Can you reproduce the problem with this test case?

~~~java
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatLightLaf;

public class FileChooserTest
{
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            FlatLightLaf.setup();

            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog( null );
        } );
    }
}
~~~

**Comment by teohhanhui** [comment]
Just tried it. I'm able to reproduce the same issue with your code. Double-clicking a file works. `Enter` with a file selected does nothing.

```
flatpak run \
    --command=/usr/lib/sdk/openjdk21/bin/java \
    --share=network \
    --socket=x11 \
    --filesystem="$PWD":ro \
    org.freedesktop.Sdk//23.08 \
    -cp flatlaf-3.2.5.jar \
    Main.java
```

(The correct SDK extension: https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk21)

Could you please reopen?

**Comment by DevCharly** [comment]
Well, spent already several hours trying to reproduce the issue. Without success so far...

But I'm not using flatpak. 
Have you tried without flatpak?

Does clicking the `Open` button work as expected? (e.g. enter selected directory)

Could you debug it yourself?
The `Enter` key in the file chooser dialog is handled by the dialog's default button, which is the `Open` button.

Following method is (or should be) invoked if you press `Enter` key or click `Open` button:
https://github.com/openjdk/jdk/blob/ca9635df3357bf70b41645f619237b6d2068afb7/src/java.desktop/share/classes/javax/swing/plaf/basic/BasicFileChooserUI.java#L1082

You could also set a breakpoint at `JRootPane.setDefaultButton()` to verify that the `Open` button is registered as default button:
https://github.com/openjdk/jdk/blob/61ebe3b0c4afb6bfdadbf54d0e8a20347bea1975/src/java.desktop/share/classes/javax/swing/JRootPane.java#L752
