### ISSUE TITLE
Customize amount of round corner radius on the component in UI

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#777]
I have added flatlaf look and feel to the application. I am directly inheriting round corners from windows 11 UI into our application. We want to reduce the radius of the corner arc, is there a way to do that.

**Comment by SakthiRJ** [comment]
Hi,

Did you tried following properties? It will allow you to control the rounded corners.

Component.arc = 8
TextComponent.arc = 8
Button.arc = 7

**Comment by VKaddala** [comment]
I want to control the rounded corners for jdialog and joptionpane and so i tried Component.arc but no use.

**Comment by DevCharly** [comment]
> I want to control the rounded corners for jdialog and joptionpane

Why would you do that? All windows on Windows 11 use the same rounded corners.

If you really want to do that, you could use internal FlatLaf class [FlatNativeWindowsLibrary](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeWindowsLibrary.java):

~~~java
if( SystemInfo.isWindows_11_orLater && FlatNativeWindowsLibrary.isLoaded() ) {
    long hwnd = FlatNativeWindowsLibrary.getHWND( frame );
    FlatNativeWindowsLibrary.setWindowCornerPreference( hwnd, FlatNativeWindowsLibrary.DWMWCP_DONOTROUND );
}
~~~

Note this comment regarding `getHWND()`:

https://github.com/JFormDesigner/FlatLaf/blob/c25d857e78f3597f1a72f12d09e6e11e7d394ed0/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatNativeWindowsLibrary.java#L64-L78

For rounded corners of popups see PR #643

**Comment by VKaddala** [comment]
I want to get a corner round with 2px radius and that too at centralized location, so all component in the application will automatically apply, mainly JDialog.

**Comment by DevCharly** [comment]
> ...so all component in the application...

I'm confused...
In your last post you asked to change corners of JDialog window, now you're talking about components...

Maybe this helps: https://www.formdev.com/flatlaf/customizing/#corners

**Comment by VKaddala** [comment]
Yeah, this helps a lot. I need to change corners for JDialog as well as components.  I have one more question to ask, I have seen the [PR](https://github.com/JFormDesigner/FlatLaf/pull/643) where I can use window procedure to change the dialog corner to small radius. But this change is dialog specific right. Suppose say I have 100 dialogs in my application, I need to modify at 100 locations. Is there any way, so that I can change the corner of JDialog itself, since every dialog is extending from it?
