### ISSUE TITLE
Spacing between components and size of components

### ISSUE THREAD

**Issue by SakthiRJ** [JFormDesigner/FlatLaf#778]
I am utilizing the latest version of Flatlaf, and as illustrated below, there is no default spacing between components. I attempted to use Component.focusWidth, but it resulted in a reduction of the component size. My objective is to uniformly increase the size of components throughout the entire application, maintaining a minimum gap of 0.5 to 1 between them. Despite trying various approaches, I have been unable to achieve this globally.

![image](https://github.com/JFormDesigner/FlatLaf/assets/104691007/ca8fc904-0a9e-433c-8b77-51e933bbda35)

Additionally, the combo data is not fully visible, as it is partially obscured. 

<img width="437" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/104691007/60eac01b-158d-4664-9d1d-64bd28a840c8">

**Comment by DevCharly** [comment]
> I attempted to use Component.focusWidth, but it resulted in a reduction of the component size.

This happens if you use a fixed height for that component.
Do not use `comp.setSize()` or `comp.setBounds()`.
Instead use a layout manager that uses the preferred size/height of the component (e.g. MigLayout, GridBagLayout or GroupLayout).

Regarding the table: seems that you've set the row height using `table.setRowHeight()`. This is not necessary and should be avoided.

**Comment by SakthiRJ** [comment]
I have numerous panels already designed, all utilizing GridBagLayout. In the previous look and feel, there was spacing between the components, but it is no longer visible now after changing to FlatLaf. I noticed that there are size and bounds controls in some components, but not in every component used in it. Is there a way to achieve this globally by handling it in FlatLaf classes?

**Comment by DevCharly** [comment]
> In the previous look and feel, there was spacing between the components, but it is no longer visible now after changing to FlatLaf.

Maybe because other L&F use smaller fonts or smaller margins, which results in smaller components...

> I noticed that there are size and bounds controls in some components, but not in every component used in it. 

Don't know that mean 😕 

> it. Is there a way to achieve this globally by handling it in FlatLaf classes?

No.

What you seem to have is a layout problem.
The L&F is not responsible for the gap between the components.

**Comment by DevCharly** [comment]
If you can not find the problem, please post code that demonstrates the problem.
