### ISSUE TITLE
New textfield feature 

### ISSUE THREAD

**Issue by Poivin** [JFormDesigner/FlatLaf#78]
Hello everybody,

do you think it could be interesting to give a new feature to textfields : the "clear on click". It is a common behavior in nowadays textfields. 
A cross icon appears when the mouse is over the textfield : 
![image](https://user-images.githubusercontent.com/61098745/76713443-f6799900-6720-11ea-9985-42eabc7b6b10.png)

It is a quick way to clear a field and put the focus in it. 

And sorry i have a question. Does anyone know the easier way to set a dedicated font in all the components? Is there a global variable "Font" that dispatch the font to all components?

**Comment by vincenzopalazzo** [comment]
Sorry for the intromission, but I'm interested in this issue.

>do you think it could be interesting to give a new feature to textfields : the "clear on click". It is a common behavior in nowadays textfields.
A cross icon appears when the mouse is over the textfield :

I think this change introduces a little problem inside the java community. The l&f is a method to change the style inside the Framework Java Swing.
The component that you describe should be a different component, like 
```class PersonalTextFieled extend JtextField{}````
P.S: This is only my opinion.

>Does anyone know the easier way to set a dedicated font in all the components? Is there a global variable "Font" that dispatch the font to all components?

All components have the ComponentName.font like propriety.

For example ```UIManager.put("Label.font", YourFont)````

Advice, the font should be a FontUIResource instance.
there are system around github that simplify the method to change the font, but the idea is this.

**Comment by Poivin** [comment]
Ok thanks for your message, you are probably right. It is the applications' job to create a specific class to handle that.
For the font, i have noticed that flatLAF (since 0.29 version) bring us the possibility to use a global property ("defaultFont") in order to set a font for all textual components and it works. OS font changes in profile configuration has no impacts when using this property.

**Comment by vincenzopalazzo** [comment]
Hi @Poivin,

this is not correlated to FlatL&f but I want only to conclude the talk.

If you are founding an example of the custom text field, I'm implementing a personal component, you can found it [here](https://github.com/vincenzopalazzo/JTextFieldPlaceholder)
If you want to improve this component all PR are welcome.
