### ISSUE TITLE
FlatLaf not rendering borders correctly on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by RickIvo** [JFormDesigner/FlatLaf#781]
FlatLaf look and feel is not rendering correctly several items borders (buttons, textboxes, etc) under Ubuntu 22.04.3 LTS

For example, the FlatLaf-demo.jar look like this:

![flatlaf_demo_screenshot](https://github.com/JFormDesigner/FlatLaf/assets/154336597/3b258002-1ef0-4b24-b04e-d997bfce9f8a)

**Comment by DevCharly** [comment]
Are you sure that this has nothing to do with the "Private Build" (see bottom line in screenshot) of your Java 21 build?

Please try with some other "official" OpenJDK distro.

**Comment by RickIvo** [comment]
Thank you for your reply. 

The first screen shot was using:

_openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-Ubuntu-222.04)
OpenJDK 64-Bit Server VM (build 21.0.1+12-Ubuntu-222.04, mixed mode, sharing)_

Here is a screenshot using the jdk17 downloaded from oracle website:

_java version "17.0.9" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)_

![screenshot_jdk17_ubuntu](https://github.com/JFormDesigner/FlatLaf/assets/154336597/2ec9643e-e941-4828-a29d-7ee6f2ac814c)

And here using openjdk21 downloaded from the https://jdk.java.net/21/:

_openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment (build 21.0.1+12-29)
OpenJDK 64-Bit Server VM (build 21.0.1+12-29, mixed mode, sharing)_

![screenshot_openjdk21_ubuntu](https://github.com/JFormDesigner/FlatLaf/assets/154336597/9c75939c-1b30-44ad-8756-fcc6e7790761)

**Comment by DevCharly** [comment]
Strange 😕 
Just tried in Ubuntu 22.04 (in VirtualBox) and it looks normal here...

What does it look like when you switch to Metal or Nimbus L&F using combobox in bottom-left corner?

Do other Swing applications work on your machine?

**Comment by RickIvo** [comment]
I am also using Ubuntu under a Virtual Machine (VMware Workstation 16 player) and I just realized that if I disable "Accelarete 3D graphics" on the virtual machine settings, the issue disappears and everything is perfectly rendered in flatlaf-demo under all L&Fs.

**Comment by DevCharly** [comment]
Maybe you need to install some special VMware graphics card driver within the Ubuntu VM for 3D acceleration?
