### ISSUE TITLE
Keep the border arc when the component is a cell editor

### ISSUE THREAD

**Issue by dar-dev** [JFormDesigner/FlatLaf#786]
Is there a way to keep the border arc even if the component is a cell editor? 

I need this feature as I want to use the cell editor component as table cell renderer. In this case, the border of cell renderer component is drawn with the arc and the cell editor without it.

Here's a sample video:

https://github.com/JFormDesigner/FlatLaf/assets/55930104/b59dd4b4-e37b-45d4-914b-04ed921436e3

Cheers,

Dar

--

**Comment by DevCharly** [comment]
thx for reporting

fixed in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
