### ISSUE TITLE
SwingX support for JXTable

### ISSUE THREAD

**Issue by martin-jamszolik** [JFormDesigner/FlatLaf#79]
Hi Team,
You already have `FlatTableUI` configured and setting `showHorizontalLines` and `showVerticalLines`.
However, JXTable in SwingX needs additional properties to be set for it to work, specifically

```
jxTable.setShowGrid( true );
jxTable.setShowGrid( true, true );
```
Without the above, JXTables do not have any vertical or horizontal lines.

Cheers.

**Comment by DevCharly** [comment]
Just tried `JXLoginPane` in my SwingX test application and it works without any change.

Do you have the **flatlaf-swingx** addon in your project?
https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-swingx

**Comment by martin-jamszolik** [comment]
Ohh, wow you are right. I reverted back to the original library version and it does appear to work now.
My mistake.  I wished I saved the NullPointerException I was getting before. I can't seem to reproduce this anymore.  In any case, glad that `JXLoginPane` is working out of the box.  Amending this issue only to JXTable.

**Comment by DevCharly** [comment]
For JXTable grid lines you also have to set `Table.intercellSpacing`.

E.g. for horizontal lines:
~~~java
UIManager.put( "Table.showHorizontalLines", true );
UIManager.put( "Table.intercellSpacing", new Dimension( 0, 1 ) );
~~~

Maybe the JXTable cell renderers are opaque.

Setting `Table.intercellSpacing` may be also necessary for `JTable` when using custom renderers or other column data types. E.g. when using a column with booleans (a checkbox).
