### ISSUE TITLE
Added components on menu row display wrong background

### ISSUE THREAD

**Issue by Corionis** [JFormDesigner/FlatLaf#791]
Have added a JPanel to the right of a JMenuBar for notification icons.

In JFormDesigner Test Form it displays correctly (using IntelliJ).  When compiled and executed the added components takes-on the background color of a JTabbedPane and similar. The background color of the JPanel and two JLabels is the same as the JMenuBar.

![Screenshot from 2024-01-10 19-39-36](https://github.com/JFormDesigner/FlatLaf/assets/21012251/1bd088ae-8ae8-45c2-9337-415e182e312e)

(Thanks for the great tool !)

**Comment by DevCharly** [comment]
JMenuBar uses a different color than JPanel.

Make panel non-opaque to fix it:

~~~java
panel.setOpaque( false );
~~~

**Comment by Corionis** [comment]
:vulcan_salute: ... duh. A checkbox in JFormDesigner.
