### ISSUE TITLE
Text in the buttons are getting ellipses added.

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#793]
I have 3 buttons with the text and with no icon. I tried to get the maximum size of the buttons using getPreferredSize() method and manually setting that size on three buttons to make them look similar. Now the size of bigger button that returned from getPreferredSize() method is no sufficient and making the text inside the button adding ellipse. If I add +1 to the size getting from getPreferredsize() i ended up with correct button render. Can I know the reason why I need to add 1 .

Here is the buttons looks:
![MicrosoftTeams-image (1)](https://github.com/JFormDesigner/FlatLaf/assets/55906470/6da8a007-fed8-45e4-83c7-64d10ec06b5f)

**Comment by DevCharly** [comment]
> I tried to get the maximum size of the buttons using getPreferredSize() method and manually setting that size on three buttons to make them look similar.

You know that Swing has layout managers that exactly do that for you 😉 
E.g. use a grid-based layout manager (e.g. MigLayout or `GridBagLayout`), 
place all three buttons into a column and tell the layout manager
that those components should fill the whole column width.

> Can I know the reason why I need to add 1

Don't know. Maybe some rounding/scaling issue...

What Java version do you use?
What scaling does your screen use?
