### ISSUE TITLE
GetMonitorInfo() call does not initialize cbSize 

### ISSUE THREAD

**Issue by Adam-** [JFormDesigner/FlatLaf#798]
I noticed the call to GetMonitorInfo here https://github.com/JFormDesigner/FlatLaf/blame/main/flatlaf-natives/flatlaf-natives-windows/src/main/cpp/FlatWndProc.cpp#L380C6-L380C20 does not initialize `monitorInfo.cbSize` despite the docs saying it is required https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa. Despite this, the code does still appear to work okay.

**Comment by DevCharly** [comment]
Good catch 👍 

> Despite this, the code does still appear to work okay.

Yes, at least if only one display is connected...
