### ISSUE TITLE
FlatSVGIcon consuming notable CPU

### ISSUE THREAD

**Issue by garthhenning** [JFormDesigner/FlatLaf#799]
In an area of our app where there are multiple repaints underway, the Netbeans profiler identifies notable CPU usage by the FlatSVGIcon when such an icon is attached to a JButton in the repainted area.

<img width="1037" alt="Screenshot 2024-01-23 at 5 11 35 PM" src="https://github.com/JFormDesigner/FlatLaf/assets/69611648/cf960c85-79db-47b4-80e4-fb35b5c8fbbc">

**Comment by DevCharly** [comment]
Is there no information about the "number of invocations/calls" for the methods in the stack?

Is the CPU usage high because `SVGDocument.render()` is invoked very often?
Or does it use much CPU for a single/few invocations?

Does the SVG contains some kind of animation or is it very large?
Can you post the SVG?

**Comment by garthhenning** [comment]
There does seem to be an endless repaint. So, the high CPU is a combination of the high frequency of calls and the cost of the SVG layout. The SVG's are very small icons, with no animation. The repaint *seems* to be affecting other components, but those are being repainted with only a fraction of the CPU time. I see a FlatSlider being repainted a large number of times as well, but it is not consuming anywhere near as much CPU as the FlatSVGIcons.

I should also note that this is FlatLaf 3.2.5, not 3.3.0 since I don't yet see 3.3.0 at Maven Central. This seems very similar to the bug fixed with 3.3.0 that referenced endless repaint looping on tabbed panes, though these buttons are not in a tabbed pane. They are in LayeredPanes, though.

Here is one of the button icon SVG files (the others are very similar variations on this one) and a profiler screen shot with the method call counts included:

![file_document_icon](https://github.com/JFormDesigner/FlatLaf/assets/69611648/ec049909-3868-4ff5-ae4e-d1ab9e02e40c)

<img width="1037" alt="Screenshot 2024-01-23 at 7 01 22 PM" src="https://github.com/JFormDesigner/FlatLaf/assets/69611648/f29f5138-e47b-4410-8d98-df083b63b2b3">

**Comment by DevCharly** [comment]
> I should also note that this is FlatLaf 3.2.5, not 3.3.0 since I don't yet see 3.3.0 at Maven Central.

FlatLaf 3.3 (without trailing '.0') is on Maven Central.

Don't think that the endless repainting has something to do with the SVG icons.

Are you using RSyntaxTextArea?

Or is there a progress bar shown somewhere?
Maybe with indeterminate set to true.
This can cause a lot of repaints...

To find out what causes the repaints, you could set a breakpoint at method `javax.swing.RepaintManager.addDirtyRegion0()` and check the call stack.

**Comment by garthhenning** [comment]
The tip to put a breakpoint on addDirtyRegion0() was a great one! Thank you! I've been debugging Java repaint issues for decades without knowing to put a breakpoint there. The repaint trigger **was** somewhere else. So, the more expensive SVG repaint is not noticeable when it isn't being called incessantly.
