### ISSUE TITLE
Make FlatComboPopup accessible and do not ignore prototype display value

### ISSUE THREAD

**Issue by etsinko** [JFormDesigner/FlatLaf#80]
There are cases when `FlatComboBoxUI` and `FlatComboPopup` need to be customized (i.e. to fix this problem: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4618607) 

Currently `FlatComboPopup` is private and cannot be overriden by any class that inherits from `FlatComobBoxUI`. This leads to unnecessary copy/paste.

**Comment by DevCharly** [comment]
Good idea. Changed in master branch.

But FlatLaf uses wider popup for comboboxes by default:

![image](https://user-images.githubusercontent.com/5604048/78044867-82bcca80-7375-11ea-96ec-a8695738daed.png)

Does this not work for you?

**Comment by etsinko** [comment]
Hmm.. This is exactly what we need! But, for some reason, I thought FlatLaf didn't implement it.

**Comment by etsinko** [comment]
Also, this is not related to the issue here, but in `FlatComboPopup` there are these lines:
https://github.com/JFormDesigner/FlatLaf/blob/97d5792341b91397d3fb647b8eaefacf7ecdbf0a/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatComboBoxUI.java#L484-L489

The problem for us is that we use prototype to speed up these calculations. Unfortunately, here it is set to `null` and then `getDisplaySize()` is called which, iterates over all items in combo box if there is no prototype. 

Is there any specific reason why prototype display value is set to `null` here?

**Comment by DevCharly** [comment]
I think the idea was to use the prototype to calculate the width of the combobox itself and then ignore it when computing popup width to get wider popup.

But this contrary to what the prototype is mainly there: increase performance.

I think I should change this...

**Comment by etsinko** [comment]
I agree, 
the most important function of prototype is to improve the performance of scroll pane width/height calculation.

**Comment by DevCharly** [comment]
Now changed in master branch.
Thanks for pointing out the issue 👍

**Comment by DevCharly** [comment]
fixed in 0.29
