### ISSUE TITLE
How do I set macOS light theme border colour

### ISSUE THREAD

**Issue by ctipper** [JFormDesigner/FlatLaf#805]
On macOS 14.3 JDK 17 I have a light theme with a dark border around the JFrame and context menus and combo box popups. Is there a way to set this to white, if there is any property I can set?
<img width="301" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/959564/f6deb215-8a0f-4157-a085-55d742bc1803">

**Comment by DevCharly** [comment]
These are native borders provided by macOS. 
Don't know a way to change them...

Why would you like to do that?

**Comment by ctipper** [comment]
If you look at screenshots in [PR 772](https://github.com/JFormDesigner/FlatLaf/pull/772) they are not black borders, why an I seeing this?

**Comment by ctipper** [comment]
Yes the JFrame does, which is particularly obvious with new button placement PR but on second thoughts I think it's because of system theme being dark mode, I will examine when I get back to my computer, but I think I will be able to confirm
