### ISSUE TITLE
How to offer a tip?

### ISSUE THREAD

**Issue by Corionis** [JFormDesigner/FlatLaf#807]
I've spent a few days knocking my head on a bug involving the event thread and sorting a table.  The short version was that FlatLaF was using the DefaultTableModel because table models were being set after ``initComponents();``

Discovered in FormDesigner: (form), this, Code Generation, **Pre-Initialization Code** that made all the difference.

Adding, for example:  ``myTable.setModel(new MyTableModel(args ...));``

When pack() is called the correct table model is used, instead of DefaultTableModel.

Not sure this is explained anywhere. If there is "Tip 'n Tricks" documentation this capability should be highlighted. And probably explained better :smile:  Sorry if it's obvious and I just missed it.

Thanks again for a great tool.

**Comment by DevCharly** [comment]
Thanks for the tip. But this issue tracker is for FlatLaf, not for JFormDesigner.
