### ISSUE TITLE
Set opacity on the JFrame and JDialog without the undecorated problem

### ISSUE THREAD

**Issue by Kokecena** [JFormDesigner/FlatLaf#808]
A while ago I saw that you closed this issue, I had commented on a possible solution, although I don't know if you saw it, in any case I put the link referring to the comment https://github.com/JFormDesigner/FlatLaf/issues/285#issuecomment-1888377550

I don't know if that is viable in this project, I see it more as a utility like

`FlatAnimatedLafChange.showSnapshot();`

and be something like

`FlatWindowOpacity.set(frame, 0.5f);`

or maybe a `FlatFrame` and `FlatDialog`  class and have the setOpacity method overwritten idk

In addition, I mentioned that a little trick of reflection is required, I also forgot to mention, there are certain scenarios where even the JMenuBar Popup were also affected by the opacity, although it has not happened to me anymore, I think since I am on Windows 11, I suspect it's because of the rounded edges that are activated now, but it's not like I care much, I just wanted to add opacity to the window.

I also found a [project](https://github.com/TheWeirdDev/JTaskbarLib/tree/master) where it places the opacity natively but that would require making (I suppose, I haven't ventured into doing this type of thing) a code for each platform. This is the code responsible for [opacity](https://github.com/TheWeirdDev/JTaskbarLib/blob/master/cpp_lib/dll.cpp#L17C1-L23C2)

Feel free to close this issue if it is not viable for this project I just wanted to let you know that it is possible in some way 😄

**Comment by DevCharly** [comment]
Thanks. I've seen you comment on the other issue, but had no plans to add something to FlatLaf.

This is very special use.
Using reflection works only of older Java versions.
And there was probably a reason why the JDK does not allow/support this... 😉
