### ISSUE TITLE
FlatLaf in Netbeans does not support Unicode characters

### ISSUE THREAD

**Issue by Makishima** [JFormDesigner/FlatLaf#81]
Netbeans 11.3, Windows 10
For example, Search for ALT+6103 will be shown as
![изображение](https://user-images.githubusercontent.com/5548003/78784141-7bb53e00-79ad-11ea-9abb-d04afd4b9a60.png)
Switching back to Windows theme will fix display of that character
![изображение](https://user-images.githubusercontent.com/5548003/78784379-ebc3c400-79ad-11ea-9b4e-91de810c66a7.png)

On macOS works properly

**Comment by DevCharly** [comment]
Thanks for reporting.
Fixed in FlatLaf 0.30.

Should be fixed in NetBeans 12.0 beta 3:
https://github.com/apache/netbeans/pull/2060

**Comment by DevCharly** [comment]
Fixed in NetBeans 12.0 beta 3, which is now available:
https://builds.apache.org/view/M-R/view/NetBeans/job/netbeans-TLP/job/netbeans/job/release120/12/artifact/dist/netbeans/
