### ISSUE TITLE
FlatLaf not applied to swingx component in app

### ISSUE THREAD

**Issue by pejax** [JFormDesigner/FlatLaf#811]
When using a swingx JXDatePicker component it is not styled by FlatLaf in an assembled jar application. When I run/debug from within IntelliJ it works and I can apply all themes.

Using an sbt Scala build with JDK21 and running the jar does not work - i.e. the JXDatePicker is not FlatLaf styled. The jar file contains all dependencies 'com/formdev/flatlaf/swingx/*' and 'org.jdesktop/swingx/.*' (1.6.5-1) and looks correct to me.

Do I have to manually force FlatLaf to check or announce swingx components?

Thanks

**Comment by DevCharly** [comment]
Do you "repackage" FlatLaf JARs into own JAR?

Then make sure that `META-INF/services/` from FlatLaf JARs is not lost.
Also keep `META-INF/versions/` from flatlaf.jar.

**Comment by pejax** [comment]
Yes, I use an sbt assembly plugin. I managed to change the assembly strategy to include "services" and "versions" - styling the JXDatePicker now works. Thanks!
With this modification all JFrame/JDialog title bars changed from dark to light (on macOS).  Again, running from IntelliJ it is fine.
Any idea what causes this?

**Comment by DevCharly** [comment]
> With this modification all JFrame/JDialog title bars changed from dark to light (on macOS). Again, running from IntelliJ it is fine. Any idea what causes this?

No.
Can you post screenshots?

**Comment by pejax** [comment]
Never mind - I found the problem. I had to move
```
    System.setProperty("apple.awt.application.appearance", "system")
```
to the global package object which obviously has to be initialized before Main (a Scala issue). The jar startup initialization seems to be different from running/debugging in IntelliJ.
Thanks for you help - you can close the ticket.
