### ISSUE TITLE
How do I change border thickness of checkbox icon on hover?

### ISSUE THREAD

**Issue by RishabhRavindran2601** [JFormDesigner/FlatLaf#813]
Currently I get a simple change in border color of checkbox icon upon hovering. Is there a way I can change the border thickness upon hovering.

On hover i want the checkbox to look like this - 
<img width="125" alt="hover" src="https://github.com/JFormDesigner/FlatLaf/assets/76875424/833a90b3-c3d3-46f9-93fa-c15c8c4ec123">

**Comment by DevCharly** [comment]
No, this is not supported.

But you can subclass `FlatCheckBoxIcon` and implement this yourself.

To "install" your subclass use:

~~~java
UIManager.put( "CheckBox.icon", new MyFlatCheckBoxIcon() );
~~~
