### ISSUE TITLE
Calling Repaint from component UI is not opening the jtree node editor in custom JTreeTable

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#814]
![image](https://github.com/JFormDesigner/FlatLaf/assets/55906470/11c3c783-bb93-40c0-b1a3-448e2d16d373)

We have a complex structure like above wherein a dialog we have a Panel, and inside the JPanel, there is a tabbed-pane and inside the tabbed-pane, there is a JPanel… as shown in the above picture. 
The table has a cell render -> Tree. We are using something similar to this implementation of tree tables present in [TreeTables - 1 (nus.edu.sg)](https://www.comp.nus.edu.sg/~cs3283/ftp/Java/swingConnect/tech_topics/tables-trees/tables-trees.html).
We are returning the tree as a Table cell renderer. Everything works fine until we change our application's look and feel. We want to get a good flat modern look and feel to the application that already exists (legacy one). The structure of the dialog that I have shown above is a pretty old legacy implementation. We are facing the following issues and want help to fix them as it is important to our work.

Issue 1:
When we double-click on the node and want to open the cell editor to edit the node, the editor opens and goes away in a flick of time. (Editor is not opening at all). We found out the issue that the text field is opaque and EditorContainer is calling the repaint when we double click. So we derive the extended class from FlatTextField and override the property. That solves the issue.
```
public class FlatCustomTextFieldUI extends FlatTextFieldUI
{
   public static ComponentUI createUI(JComponent c) {
      return new FlatCustomTextFieldUI();
   }

   @Override protected void installDefaults()
   {
      super.installDefaults();
      LookAndFeel.installProperty(this.getComponent(), "opaque", true);
   }
}
```

Issue 2:
Now the main issue is, that the tree is located in a cell inside the table. When the focus and focus gain events on the ScrollPane and Table trigger repaint on the tree since the tree is the cell renderer of the table. The following codes are responsible for the repaint which is new after the library integration. (BasicUIL&F/WindowsL&F doesn’t have them)
ScrollPaneUI
```
private class Handler
   implements ContainerListener, FocusListener
{
   @Override
   public void componentAdded( ContainerEvent e ) {
      e.getChild().addFocusListener( this );
   }

   @Override
   public void componentRemoved( ContainerEvent e ) {
      e.getChild().removeFocusListener( this );
   }

   @Override
   public void focusGained( FocusEvent e ) {
      // necessary to update focus border
      scrollpane.repaint();
   }

   @Override
   public void focusLost( FocusEvent e ) {
      // necessary to update focus border
      scrollpane.repaint();
   }
}

```
TableUI
```
protected FocusListener createFocusListener() {
   return new BasicTableUI.FocusHandler() {
      @Override
      public void focusGained( FocusEvent e ) {
         super.focusGained( e );
         toggleSelectionColors();
      }

      @Override
      public void focusLost( FocusEvent e ) {
         super.focusLost( e );

         // use invokeLater for the case that the window is deactivated
         EventQueue.invokeLater( () -> {
            toggleSelectionColors();
         } );
      }
   };
}
```

Along with these, since the permanent focus owner is the Tabbedpane -> the FlatSelectedTabRepainter is triggering repaint on the entire tab content pane which again triggers repaint on all the components.
```
private void repaintSelectedTab( JTabbedPane tabbedPane ) {
   TabbedPaneUI ui = tabbedPane.getUI();
   if( ui instanceof FlatTabbedPaneUI )
      ((FlatTabbedPaneUI) ui).repaintTab( tabbedPane.getSelectedIndex() );
}
```

When this happens the Editor opens and goes in a fraction of a second without allowing the user to edit it. Can you please suggest some workaround to come out of this situation? The Flatlaf is integrated with all the other components and dialog so well in our software except in this one situation.

@DevCharly

**Comment by VKaddala** [comment]
Focus lost and gain events are handled after handle the selection event of the tree, that makes the tree editor to stop when repaint from parent (focusgain) is triggered.

**Comment by DevCharly** [comment]
Sorry, but I do not understand what repainting or opaque textfield has to do with stopping/canceling cell editing...

Repainting does not stop editing.

I suggest to set a breakpoint at `JTable.removeEditor()` to find out why editing is immediately stopped.

**Comment by VKaddala** [comment]
Hi @DevCharly ... I put the breakpoint at `JTable.removeEditor()` but it never hit. Let me give a more detailed stack trace of the flows that I mentioned above.

When the Tree Node is double clicked... 

`startEditing(TreePath, MouseEvent):2444, BasicTreeUI (javax.swing.plaf.basic), BasicTreeUI.java
handleSelection(MouseEvent):4015, BasicTreeUI$Handler (javax.swing.plaf.basic), BasicTreeUI.java
mousePressed(MouseEvent):3955, BasicTreeUI$Handler (javax.swing.plaf.basic), BasicTreeUI.java
mousePressed(MouseEvent):3208, BasicTreeUI$MouseHandler (javax.swing.plaf.basic), BasicTreeUI.java
mousePressed(MouseEvent):264, FlatTreeUI$1 (com.formdev.flatlaf.ui), FlatTreeUI.java
mousePressed(MouseEvent):287, AWTEventMulticaster (java.awt), AWTEventMulticaster.java
mousePressed(MouseEvent):287, AWTEventMulticaster (java.awt), AWTEventMulticaster.java
processMouseEvent(MouseEvent):6632, Component (java.awt), Component.java
processMouseEvent(MouseEvent):3342, JComponent (javax.swing), JComponent.java
processEvent(AWTEvent):6400, Component (java.awt), Component.java
processEvent(AWTEvent):2263, Container (java.awt), Container.java
dispatchEventImpl(AWTEvent):5011, Component (java.awt), Component.java
dispatchEventImpl(AWTEvent):2321, Container (java.awt), Container.java
dispatchEvent(AWTEvent):4843, Component (java.awt), Component.java
repostEvent(MouseEvent):967, BasicTableUI$Handler (javax.swing.plaf.basic), BasicTableUI.java
adjustSelection(MouseEvent):1129, BasicTableUI$Handler (javax.swing.plaf.basic), BasicTableUI.java
mousePressed(MouseEvent):1057, BasicTableUI$Handler (javax.swing.plaf.basic), BasicTableUI.java
mousePressed(MouseEvent):288, AWTEventMulticaster (java.awt), AWTEventMulticaster.java
mousePressed(MouseEvent):287, AWTEventMulticaster (java.awt), AWTEventMulticaster.java
processMouseEvent(MouseEvent):6632, Component (java.awt), Component.java
processMouseEvent(MouseEvent):3342, JComponent (javax.swing), JComponent.java
processEvent(AWTEvent):6400, Component (java.awt), Component.java
processEvent(AWTEvent):2263, Container (java.awt), Container.java
dispatchEventImpl(AWTEvent):5011, Component (java.awt), Component.java
dispatchEventImpl(AWTEvent):2321, Container (java.awt), Container.java
dispatchEvent(AWTEvent):4843, Component (java.awt), Component.java
retargetMouseEvent(Component, int, MouseEvent):4918, LightweightDispatcher (java.awt), Container.java
processMouseEvent(MouseEvent):4544, LightweightDispatcher (java.awt), Container.java
dispatchEvent(AWTEvent):4488, LightweightDispatcher (java.awt), Container.java
dispatchEventImpl(AWTEvent):2307, Container (java.awt), Container.java
dispatchEventImpl(AWTEvent):2772, Window (java.awt), Window.java
dispatchEvent(AWTEvent):4843, Component (java.awt), Component.java
dispatchEventImpl(AWTEvent, Object):772, EventQueue (java.awt), EventQueue.java
run():721, EventQueue$4 (java.awt), EventQueue.java
run():715, EventQueue$4 (java.awt), EventQueue.java
doPrivileged(PrivilegedAction, AccessControlContext):-1, AccessController (java.security), AccessController.java
doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext):85, ProtectionDomain$JavaSecurityAccessImpl (java.security), ProtectionDomain.java
doIntersectionPrivilege(PrivilegedAction, AccessControlContext):95, ProtectionDomain$JavaSecurityAccessImpl (java.security), ProtectionDomain.java
run():745, EventQueue$5 (java.awt), EventQueue.java
run():743, EventQueue$5 (java.awt), EventQueue.java
doPrivileged(PrivilegedAction, AccessControlContext):-1, AccessController (java.security), AccessController.java
doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext):85, ProtectionDomain$JavaSecurityAccessImpl (java.security), ProtectionDomain.java
dispatchEvent(AWTEvent):742, EventQueue (java.awt), EventQueue.java
pumpOneEventForFilters(int):203, EventDispatchThread (java.awt), EventDispatchThread.java
pumpEventsForFilter(int, Conditional, EventFilter):124, EventDispatchThread (java.awt), EventDispatchThread.java
pumpEventsForFilter(Conditional, EventFilter):117, EventDispatchThread (java.awt), EventDispatchThread.java
run():190, WaitDispatchSupport$2 (java.awt), WaitDispatchSupport.java
run():235, WaitDispatchSupport$4 (java.awt), WaitDispatchSupport.java
run():233, WaitDispatchSupport$4 (java.awt), WaitDispatchSupport.java
doPrivileged(PrivilegedAction):-1, AccessController (java.security), AccessController.java
enter():233, WaitDispatchSupport (java.awt), WaitDispatchSupport.java
show():1070, Dialog (java.awt), Dialog.java
show():154, BaseJDialog (chs.utilities.ui), BaseJDialog.java
show(boolean):1716, Component (java.awt), Component.java
setVisible(boolean):1663, Component (java.awt), Component.java
setVisible(boolean):1031, Window (java.awt), Window.java
setVisible(boolean):1005, Dialog (java.awt), Dialog.java`

Immediately it calls Stop cell editing, because of the repaint manager. Below is the flow for calling stopCellEditing from the FlatScrollPaneUI$Handler.

`stopCellEditing():302, DefaultTreeCellEditor (javax.swing.tree), DefaultTreeCellEditor.java
completeEditing():2356, BasicTreeUI (javax.swing.plaf.basic), BasicTreeUI.java
propertyChange(PropertyChangeEvent):3848, BasicTreeUI$Handler (javax.swing.plaf.basic), BasicTreeUI.java
lambda$createPropertyChangeListener$0(PropertyChangeListener, PropertyChangeEvent):307, FlatTreeUI (com.formdev.flatlaf.ui), FlatTreeUI.java
propertyChange(PropertyChangeEvent):-1, 205494683 (com.formdev.flatlaf.ui.FlatTreeUI$$Lambda$1384), Unknown Source
fire(PropertyChangeListener[], PropertyChangeEvent):341, PropertyChangeSupport (java.beans), PropertyChangeSupport.java
firePropertyChange(PropertyChangeEvent):333, PropertyChangeSupport (java.beans), PropertyChangeSupport.java
firePropertyChange(String, Object, Object):266, PropertyChangeSupport (java.beans), PropertyChangeSupport.java
firePropertyChange(String, Object, Object):8731, Component (java.awt), Component.java
updateGraphicsData(GraphicsConfiguration):1176, Component (java.awt), Component.java
setGraphicsConfiguration(GraphicsConfiguration):1156, Component (java.awt), Component.java
remove(int):1245, Container (java.awt), Container.java
remove(Component):1289, Container (java.awt), Container.java
addImpl(Component, Object, int):1118, Container (java.awt), Container.java
addImpl(Component, Object, int):108, CellRendererPane (javax.swing), CellRendererPane.java
add(Component):436, Container (java.awt), Container.java
paintComponent(Graphics, Component, Container, int, int, int, int, boolean):148, CellRendererPane (javax.swing), CellRendererPane.java
paintCell(Graphics, Rectangle, int, int):2186, BasicTableUI (javax.swing.plaf.basic), BasicTableUI.java
paintCells(Graphics, int, int, int, int):2087, BasicTableUI (javax.swing.plaf.basic), BasicTableUI.java
paint(Graphics, JComponent):1883, BasicTableUI (javax.swing.plaf.basic), BasicTableUI.java
paint(Graphics, JComponent):408, FlatTableUI (com.formdev.flatlaf.ui), FlatTableUI.java
update(Graphics, JComponent):161, ComponentUI (javax.swing.plaf), ComponentUI.java
paintComponent(Graphics):797, JComponent (javax.swing), JComponent.java
paint(Graphics):1074, JComponent (javax.swing), JComponent.java
paint(Graphics):76, JTreeTable (chs.utilities.ui.table), JTreeTable.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paint(Graphics):737, JViewport (javax.swing), JViewport.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintChildren(Graphics):907, JComponent (javax.swing), JComponent.java
paint(Graphics):1083, JComponent (javax.swing), JComponent.java
paintToOffscreen(Graphics, int, int, int, int, int, int):5255, JComponent (javax.swing), JComponent.java
paintDoubleBufferedFPScales(JComponent, Image, Graphics, int, int, int, int):1707, RepaintManager$PaintManager (javax.swing), RepaintManager.java
paintDoubleBuffered(JComponent, Image, Graphics, int, int, int, int):1616, RepaintManager$PaintManager (javax.swing), RepaintManager.java
paint(JComponent, JComponent, Graphics, int, int, int, int):1556, RepaintManager$PaintManager (javax.swing), RepaintManager.java
paint(JComponent, JComponent, Graphics, int, int, int, int):1323, RepaintManager (javax.swing), RepaintManager.java
_paintImmediately(int, int, int, int):5203, JComponent (javax.swing), JComponent.java
paintImmediately(int, int, int, int):5013, JComponent (javax.swing), JComponent.java
run():865, RepaintManager$4 (javax.swing), RepaintManager.java
run():848, RepaintManager$4 (javax.swing), RepaintManager.java
doPrivileged(PrivilegedAction, AccessControlContext):-1, AccessController (java.security), AccessController.java
doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext):85, ProtectionDomain$JavaSecurityAccessImpl (java.security), ProtectionDomain.java
paintDirtyRegions(Map):848, RepaintManager (javax.swing), RepaintManager.java
paintDirtyRegions():823, RepaintManager (javax.swing), RepaintManager.java
prePaintDirtyRegions():772, RepaintManager (javax.swing), RepaintManager.java
run():1890, RepaintManager$ProcessingRunnable (javax.swing), RepaintManager.java
dispatch$$$capture():313, InvocationEvent (java.awt.event), InvocationEvent.java
dispatch():-1, InvocationEvent (java.awt.event), InvocationEvent.java
 - Async stack trace
<init>:286, InvocationEvent (java.awt.event)
<init>:172, InvocationEvent (java.awt.event)
scheduleProcessingRunnable:1495, RepaintManager (javax.swing)
addDirtyRegion0:482, RepaintManager (javax.swing)
addDirtyRegion:504, RepaintManager (javax.swing)
repaint:4836, JComponent (javax.swing)
repaint:3393, Component (java.awt)
focusLost:459, FlatScrollPaneUI$Handler (com.formdev.flatlaf.ui)
focusLost:238, AWTEventMulticaster (java.awt)
processFocusEvent:6527, Component (java.awt)
processEvent:6391, Component (java.awt)
processEvent:2263, Container (java.awt)
dispatchEventImpl:5011, Component (java.awt)
dispatchEventImpl:2321, Container (java.awt)
dispatchEvent:4843, Component (java.awt)
redispatchEvent:1950, KeyboardFocusManager (java.awt)
typeAheadAssertions:1059, DefaultKeyboardFocusManager (java.awt)
dispatchEvent:725, DefaultKeyboardFocusManager (java.awt)
dispatchEventImpl:4892, Component (java.awt)
dispatchEventImpl:2321, Container (java.awt)
dispatchEvent:4843, Component (java.awt)
dispatchEventImpl:772, EventQueue (java.awt)
run:721, EventQueue$4 (java.awt)
run:715, EventQueue$4 (java.awt)
doPrivileged:-2, AccessController (java.security)
doIntersectionPrivilege:85, ProtectionDomain$JavaSecurityAccessImpl (java.security)
doIntersectionPrivilege:95, ProtectionDomain$JavaSecurityAccessImpl (java.security)
run:745, EventQueue$5 (java.awt)
run:743, EventQueue$5 (java.awt)
doPrivileged:-2, AccessController (java.security)
doIntersectionPrivilege:85, ProtectionDomain$JavaSecurityAccessImpl (java.security)
dispatchEvent:742, EventQueue (java.awt)
pumpOneEventForFilters:203, EventDispatchThread (java.awt)
pumpEventsForFilter:124, EventDispatchThread (java.awt)
pumpEventsForFilter:117, EventDispatchThread (java.awt)
run:190, WaitDispatchSupport$2 (java.awt)
run:235, WaitDispatchSupport$4 (java.awt)
run:233, WaitDispatchSupport$4 (java.awt)
doPrivileged:-2, AccessController (java.security)
enter:233, WaitDispatchSupport (java.awt)
show:1070, Dialog (java.awt)`

**Comment by VKaddala** [comment]
@DevCharly It seems like working for that particular column. The table contains two columns. One contains the tree as editor as well as cell renderer, and the other column with Boolean checkboxes. When I try overriding the FlatTableUI and return when the tree is editable, the entire table is not painting and the checkbox column goes away. What can I do about that, any suggestion?

**Comment by DevCharly** [comment]
> ... when the tree is editable ...

Do not check whether tree is editable.
Check whether it is currently editing!

Use `JTree.isEditing()` instead of `JTree.isEditable()`

**Comment by VKaddala** [comment]
Sorry correction in the above comment. I am checking JTree.isEditing() only.

**Comment by DevCharly** [comment]
> Sorry correction in the above comment. I am checking JTree.isEditing() only.

Then this trick does not work...

> The table contains two columns. One contains the tree as editor as well as cell renderer,

A table cell editor should be some kind of text field!

The stack shows that `mousePressed` is first handled in `BasicTableUI` (which maybe starts table editing) and then reposted to `BasicTreeUI`, which starts tree editing.

Maybe you need to use `JTree.setEditable(false)` to avoid that the tree can start editing...
The table editor should be used.

**Comment by VKaddala** [comment]
@DevCharly so without setting tree to editable one, we cannot resolve the following issue with the workaround or something? right?  We want to edit the tree node, instead of table cell. So, we want to think about better approach. Do you suggest anything to work around over the issue where tree is both renderer and editor of a table cell!

**Comment by DevCharly** [comment]
>  We want to edit the tree node, instead of table cell.

Then implement a table cell editor, that internally uses a tree for editing.
Same concept as using a table cell renderer, that internally uses a tree for rendering 😉
