### ISSUE TITLE
Update embedded menu

### ISSUE THREAD

**Issue by BrunoEberhard** [JFormDesigner/FlatLaf#816]
I have an application with a JMenuBar embedded in the window title bar (Windows 11). Very nice!

But the content of the menu bar is not updated. If I disable an action of a JMenuItem it the bar the menu item is still enabled. If I add an item it's not shown.

FlatLaf.revalidateAndRepaintAllFramesAndDialogs() helped as I added a whole menu but not about items.

What can i do?

**Comment by DevCharly** [comment]
Can not reproduce this. In my applications it works fine.

> If I disable an action of a JMenuItem it the bar the menu item is still enabled

Maybe the action does not update the menu item...
Set a breakpoint at your action's `setEnabled()` method and debug into `firePropertyChange()` to see whether menu item is updated.

> FlatLaf.revalidateAndRepaintAllFramesAndDialogs() helped as I added a whole menu but not about items.

That should be not not necessary. Better use `menuBar.revalidate()` instead.

**Comment by BrunoEberhard** [comment]
Thanks for your help. At moment I think its a threading issue. I have to check that everything about UI is done in EDT.
