### ISSUE TITLE
Question on HiDPI vs. non-HiDPI

### ISSUE THREAD

**Issue by j-dimension** [JFormDesigner/FlatLaf#819]
I have a question on scaling. 

I have a Windows 11 client with two displays:

- 3840 x 2160, landscape, scale set to 125% (OS level)
- 1200 x 1920, portrait, scaled default 100% (OS level)

My application is starte on the 1920px display. When dragged to the other display, the rendering is faulty (see screenshot) and the app is not clickable at all. Once moved back to the original display, the app works fine. 

I suspect I am doing something wrong within my application code, but have no idea where to begin and what role the LaF (FlatLaf) plays in this. 

Do you have any idea where I start tracking this down?

Thank you so much in advance.

![grafik](https://github.com/JFormDesigner/FlatLaf/assets/3729754/f3b7b6c1-4e43-4b2c-809e-c0805eb3b850)

**Comment by DevCharly** [comment]
Hmm, can not reproduced this here...
Could be a Java bug or a graphics driver problem...

What Java version do you use?

If you resize the window, after dragging it to other screen, is it shown correctly and "clickable" again?

> Do you have any idea where I start tracking this down?

- check whether FlatLaf Demo has the same problem (with same JRE as you app)
- try you app with `-Dflatlaf.useWindowDecorations=false`
- also try `-Dflatlaf.useNativeLibrary=false`
- try different Java versions

**Comment by j-dimension** [comment]
Thanks @DevCharly. 

I am using Liberica JRE 17:

java.runtime.name = OpenJDK Runtime Environment
java.runtime.version = 17.0.9+11-LTS
java.specification.version = 17
java.vendor = BellSoft
java.vendor.url = https://bell-sw.com/
java.vendor.url.bug = https://bell-sw.com/support

I will look into your suggestions, thanks.

**Comment by j-dimension** [comment]
I just found a "DPI Awareness" setting in install4j that is applicable for Windows based installations only. It was set to "Never" in my installer, which does not make sense for Java 17 environments. 

I suspect this is the cause and will test it out.

**Comment by DevCharly** [comment]
Yes, that should fix it 👍
