### ISSUE TITLE
JTabbedPane refreh on setBackgroundAt

### ISSUE THREAD

**Issue by AndreZeiler** [JFormDesigner/FlatLaf#820]
Currently if I call JTabbedPane.setBackgroundAt(int index, Color color) to change the color of a Tab background the currently visible tab (so the content component) receives a full refresh and repaints. It does not matter if the visible/selected tab is the same as in the one in the setBackgroundAt() call.

For example I have 3 Tabs
[Tab 1, Index 0], [Tab 2, Index 1], [Tab 3, Index 2] 
Tab 2 is selected
I call setBackgroundAt with index 0 to set the tab color for Tab 1

The tab color for Tab 1 changed
The component inside Tab 2 repaints

This is annoying if JTabbedPane.setBackgroundAt() is called more often.
Is this related to the L&F implementation or is this a general behavior of Swing?
Do you know any way to avoid the repaint of the component and only repaint the tab itself.

**Comment by DevCharly** [comment]
Are you sure that the repaint is triggered by `tabbedPane.setBackgroundAt()`?

This method actually repaints only the changed tab in the tab area, but not the content. See:
https://github.com/openjdk/jdk/blob/9bc1b065db238b7c9d0562f9bd55d2f338c6ff3d/src/java.desktop/share/classes/javax/swing/JTabbedPane.java#L1498-L1508

Here is a test case.  The first tab content uses a random background color so that it is easy to see whether content is repainted (e..g. when resizing the window). Clicking the "set tab 2 background" checkbox changes the color of the second tab, but it does not repaint the content.

~~~java
package test;

import java.awt.*;
import java.util.Random;
import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;

public class TabbedPaneRepaintTest
{
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            FlatLightLaf.setup();

            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );

            JTabbedPane tabbedPane = new JTabbedPane();
            tabbedPane.addTab( "Tab 1", new JLabel( "random background content 1", SwingConstants.CENTER ) {
                Random random = new Random();
                @Override
                protected void paintComponent( Graphics g ) {
                    g.setColor( new Color( random.nextInt() ) );
                    g.fillRect( 0, 0, getWidth(), getHeight() );
                    super.paintComponent( g );
                }
            } );
            tabbedPane.addTab( "Tab 2", new JLabel( "content 2" ) );
            tabbedPane.addTab( "Tab 3", new JLabel( "content 3" ) );

            JCheckBox cb = new JCheckBox( "set tab 2 background" );
            cb.addActionListener( e -> tabbedPane.setBackgroundAt( 1, cb.isSelected() ? Color.green : null ) );

            frame.add( cb, BorderLayout.NORTH );
            frame.add( tabbedPane, BorderLayout.CENTER );
            frame.setSize( 600, 400 );
            frame.setVisible( true );
        } );
    }
}
~~~

**Comment by AndreZeiler** [comment]
I will recheck this on monday.

The setBackgroundAt() method was my first indication, because it was listet in the Stack Trace. I even tried adding a custom component in the tab (setTabCompomemtAt()) and setting the background color for that with the same result.
 
There is a lot of refreshing going on after calling this. 
The refresh of the component then happens in a different thread but it seems that it was initially caused by setBackgroundAt().

I will just remove that call in our method to validate this again but currently I am pretty sure. 

We have not override this method so we use the default JTabbedPane implementation. And based on the code only a refresh of the affected area should be done. 

Maybe something is causing this afterwards but because the stack showed the method this was my initial thought.

**Comment by AndreZeiler** [comment]
Maybe this more specifically only happens with a JTable  used as content? I will investigate this more on Monday but I think I saw something related to the TableHeader in the stack as well.

**Comment by AndreZeiler** [comment]
So I tried to reproduce this with your minimal example and a few modifications but I don’t get the behavior I mentioned. 

I try this at work and will give you feedback

**Comment by DevCharly** [comment]
To find out what causes the repaints, you could set a breakpoint at method `javax.swing.RepaintManager.addDirtyRegion0()` and check the call stack.

**Comment by AndreZeiler** [comment]
Thank your for your help. It actually was very simple but the stack trace was misleading.
There was a repaint hidden elsewhere in our JTabeedPane class that caused the issue. 
The stack was not showing that repaint() instead it was showing setBackgroundAt()
