### ISSUE TITLE
FlatSVGIcon uses logSevere for recoverable errors

### ISSUE THREAD

**Issue by jamescooper-gd** [JFormDesigner/FlatLaf#823]
The `FlatSVGIcon` uses a general logger, so it's not currently possible to disable a log message we don't want without disabling all log messages.

I'm dynamically loading icons, and if the svg document is invalid I get "severe" errors in the log, that are completely recoverable in my app.

Any chance this could log to a customer logger, for instance by `FlatSVGIcon.class` please?

**Comment by DevCharly** [comment]
I've changed used log level from `severe `to `config` and added method `FlatSVGIcon.setLoggingEnabled( boolean )` to allow disabling logging for FlatSVGIcon

implemented in latest `3.4.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by jamescooper-gd** [comment]
Thanks, I appreciate the fix.
