### ISSUE TITLE
3.4 - JVM crash on macOS

### ISSUE THREAD

**Issue by benlapidge** [JFormDesigner/FlatLaf#826]
When upgrading FlatLaf  from 3.2.5 to 3.4, we encountered an issue on macOS: when attempting to open our GUI that uses flatlaf, a JVM crash would occur. This appeared to be caused by the FlatLaf native Mac library setting window button spacing. 

Please see attached crash report. 

**Tested with:**
MacBook Pro:
- M2 Pro
- 23 gb ram
- Sonoma 14.2.1

[hs_err_pid60162.log](https://github.com/JFormDesigner/FlatLaf/files/14746685/hs_err_pid60162.log)

**Comment by DevCharly** [comment]
From the log, it looks like you're running your app in WebSwing, right?

Does it also crash if you run it without WebSwing?

**Comment by DevCharly** [comment]
should be fixed in latest `3.4.1-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Please try that build and report whether it works now. Thanks.

**Comment by DevCharly** [comment]
@benlapidge does it work now?

**Comment by benlapidge** [comment]
Hi @DevCharly, I'm going to be rebuilding and giving this a test this afternoon - I shall report back asap!

**Comment by benlapidge** [comment]
@DevCharly , I've built the app again using the 3.4.1-SNAPSHOT, working like a charm so far!
