### ISSUE TITLE
Global menu for Linux distros

### ISSUE THREAD

**Issue by xxirioxx** [JFormDesigner/FlatLaf#827]
Referring to the MacOS guide page: "_While Windows or Linux applications have there menu bars within the main window, macOS applications show the menu bar on top of the screen._"
This is not completely true because some Linux distros support global menu too.
Is possible to support global menu on some Linux distros like Ubuntu Unity?
Thank you.

**Comment by DevCharly** [comment]
Thanks for pointing this out. On macOS, the screen menu bar is implemented in Java. It is **not** a FlatLaf feature.

> Is possible to support global menu on some Linux distros like Ubuntu Unity?

That's not easy. It would require a **lot of work and native code** to map Swing menus to GTK menus...

Maybe it works if you use AWT menus?
Try to implement a test app that uses `java.awt.MenuBar`, `java.awt.Menu`, `java.awt.MenuItem` and `frame.setMenuBar()`.
I think those AWT menus use GTK menus.
Maybe this works...

**Comment by xxirioxx** [comment]
Thank you for developing this beautiful project. I already tried using awt menu instead of swing but it didn't work.
If can be useful, a project named "jayatana" exists (and the package is present in Ubuntu repository too) but after a research this stopped working a lot of years ago. But maybe this could be a starting point...
Someone said this could be done via dbus,
by the way, I know it would require a lot of effort. Thank you for your reply

**Comment by DevCharly** [comment]
Have you seen/tried this project (last commit is one 3 weeks ago):
https://gitlab.com/vala-panel-project/vala-panel-appmenu/tree/master/subprojects/jayatana

Also seems that JetBrains supports global menu in IntelliJ IDEA:

- Java code: 
  - https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/platform/ide/menu/GlobalMenuLinux.java
  - https://github.com/JetBrains/intellij-community/blob/master/platform/platform-impl/src/com/intellij/platform/ide/menu/LinuxIdeMenuBar.kt
- code of native library: https://github.com/JetBrains/intellij-community/tree/master/native/LinuxGlobalMenu

**Comment by xxirioxx** [comment]
Woooah! Thank you so much! It works!
There's no need to compile all the vala-appmenu-project, only the jayatana subproject.
Here is what I've done:
- install vala-panel-appmenu from ubuntu repository
- compile and install jayatana (follow instruction on https://gitlab.com/vala-panel-project/vala-panel-appmenu)
- run your jar: `java -javaagent:/usr/local/share/java/jayatanaag.jar -jar <yourjar>.jar`

Now I have a question for you. The install command produces 4 files:
Installing java/jayatana.jar to /usr/local/share/java
Installing java/jayatanaag.jar to /usr/local/share/java
Installing lib/libjayatanaag.so to /usr/local/lib/x86_64-linux-gnu/jayatana
Installing lib/libjayatana.so to /usr/local/lib/x86_64-linux-gnu/jayatana

Do you think these files can be embedded in my application (or directly in your FlatLaf project in order to support global menu on Linux too) or this is prohibited by some license?

**Comment by DevCharly** [comment]
Great that it work 😄 

> Do you think these files can be embedded in my application

Yes, the JAyatana subproject seems to use the MIT license, which allows free use:
https://gitlab.com/vala-panel-project/vala-panel-appmenu/-/blob/master/subprojects/jayatana/LICENSE

> ... or directly in your FlatLaf project ...

Currently, I have no plans to do this.
