### ISSUE TITLE
Wrap FileChooser's shortcuts panel in vertical scroll pane

### ISSUE THREAD

**Issue by mbien** [JFormDesigner/FlatLaf#828]
Hello,

The shortcuts panel (`FlatFileChooserUI.FlatShortcutsPanel`) will currently define the height of the `JFileChooser` if it contains many shortcuts - so it can become quite tall.

Would it make sense for FlatLaf to wrap it in a `JScrollPane` for vertical scrolling? Could look like this:
![favs-in-file-chooser_scroll](https://github.com/apache/netbeans/assets/114367/99bbc245-a834-418f-98cd-b7a59531a8d2)

a few more screenshots here: https://github.com/apache/netbeans/pull/7164

**Comment by DevCharly** [comment]
Thanks for the idea. That makes sense 👍 

implemented in latest `3.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
