### ISSUE TITLE
Embedded binaries are not signed on macOS

### ISSUE THREAD

**Issue by Kamik423** [JFormDesigner/FlatLaf#829]
When attempting to notarize an app that uses the latest version of FlatLaf a new error occurs that did not occur before the embedded macOS binaries:

<details><summary><b>The binary is not signed with a valid Developer ID certificate.</b></summary>

```json
{
  "logFormatVersion": 1,
  "jobId": "<censored>",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "myapp.dmg",
  "uploadDate": "2024-03-27T16:42:08.401Z",
  "sha256": "6a31075bc543ee19d41d8c969eba147173a6d04333361ae34f8a2d167a96564a",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "myapp.dmg/myapp.app/Contents/Resources/Java/myapp.jar/com/formdev/flatlaf/natives/libflatlaf-macos-x86_64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "myapp.dmg/myapp.app/Contents/Resources/Java/myapp.jar/com/formdev/flatlaf/natives/libflatlaf-macos-arm64.dylib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    }
  ]
}
```

</details>

This is due to the embedded *.dylib*s not being signed. While it is [technically possible that we sign it ourselves](https://stackoverflow.com/a/71863336/3646485), the *correct* way would be to ship pre-signed binaries, if you have access to an Apple developer account.

**Comment by DevCharly** [comment]
Currently, it is recommended to use the "no-natives" FlatLaf JAR (which does not contain binaries), and distribute (and sign) binaries outside of the JAR. Then it is easy to sign the FlatLaf dylibs with your certificate. This also avoids possible problems with security managers when loading FlatLaf dylibs from temporary directories.

See https://www.formdev.com/flatlaf/native-libraries/
