### ISSUE TITLE
Minimum button width

### ISSUE THREAD

**Issue by vivatNikolay** [JFormDesigner/FlatLaf#83]
Hi. if the value of the variable "Button.minimumWidth" less than 72, then it looks much better.
Example:

![calendar](https://user-images.githubusercontent.com/22859381/79337722-b6c7ec00-7f2e-11ea-9f65-67943e616102.png)

Thanks for your attention!

**Comment by DevCharly** [comment]
Yes, a smaller minimum width is much better in this case.

`Button.minimumWidth` is only used if the button has a `FlatButtonBorder` (the default border).

All the buttons with borders do not look very nice in the calendar. Try using `javax.swing.border.EmptyBorder` or `com.formdev.flatlaf.ui.FlatEmptyBorder` on all calendar buttons to  remove the borders. Then `Button.minimumWidth` is not used in the calendar.

`FlatEmptyBorder` has the advantage that it scales on HiDPI screens or on Linux.
