### ISSUE TITLE
Request: JSplitPane.expandableSide "none" property 

### ISSUE THREAD

**Issue by jokarmus** [JFormDesigner/FlatLaf#831]
I really liked the idea of hiding the expand button in JSplitPane by setting "JSplitPane.expandableSide". However, in my application, it's necessary for both JSplitPane buttons to be invisible because the JSplitPane expansion is controlled from outside the JSplitPane component. Is it possible to add an option like JSplitPane.expandableSide = none, which would hide both buttons?

**Comment by DevCharly** [comment]
Use following to hide all expand buttons:

```java
splitPane.setOneTouchExpandable( false );
```

BTW by default, a split pane does **not show** the expand buttons.

**Comment by jokarmus** [comment]
Actually, that will not fit, because I need this feature but controlled using external button. When splitPane is set to oneTouchExpandable to false it is impossible to do that. For now to control splitpane by external button I am using action on button rendered in SplitPaneUI, when oneTouchExpandable is set to false there is no button so I can't use this action.

**Comment by DevCharly** [comment]
I'm confused...

> Actually, that will not fit, because I need this feature but controlled using external button.

What external button? Where is this button located? In the divider?

> When splitPane is set to oneTouchExpandable to false it is impossible to do that.

Why?

> For now to control splitpane by external button I am using action on button rendered in SplitPaneUI, when oneTouchExpandable is set to false there is no button so I can't use this action.

But the requested JSplitPane.expandableSide "none" value would also hide the two arrow buttons 😕

**Comment by jokarmus** [comment]
In fact, we need to hide the collapse/expand buttons for the user and have the ability to collapse and expand programmatically. Since JSplitPane does not enable this on the API, we use a hack where we take the rendered buttons in JSplitPaneUI and call actions on them. The reason for this solution is that we don't want to allow the user to fully expand, but allow to collapse. If we could HIDE the expand/collapse buttons with JSplitPane.expandableSide "none" and still have ability to call actions on them that would be great, but I suppose that is out of scope of this feature.

**Comment by DevCharly** [comment]
> In fact, we need to hide the collapse/expand buttons for the user and have the ability to collapse and expand programmatically. Since JSplitPane does not enable this on the API, ...

Better use JSplitPane API for this case instead of hacking 😉 

Following works for me:

~~~java
void splitPaneOneTouchLeft( JSplitPane splitPane ) {
    int size = (splitPane.getOrientation() == JSplitPane.HORIZONTAL_SPLIT)
        ? splitPane.getWidth()
        : splitPane.getHeight();
    size -= UIScale.scale( splitPane.getDividerSize() );

    if( splitPane.getDividerLocation() >= size )
        splitPane.setDividerLocation( splitPane.getLastDividerLocation() );
    else
        splitPane.setDividerLocation( 0.0 );
}

void splitPaneOneTouchRight( JSplitPane splitPane ) {
    if( splitPane.getDividerLocation() <= 0 )
        splitPane.setDividerLocation( splitPane.getLastDividerLocation() );
    else
        splitPane.setDividerLocation( 1.0 );
}
~~~
