### ISSUE TITLE
Unable to get table header seperator line.

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#836]
![image](https://github.com/JFormDesigner/FlatLaf/assets/55906470/16aec125-a82b-43f8-bf79-a63194d9b0ce)

After the table is displayed, I can't able to see the border/bottom header table separation line. I mentioned the properties `TableHeader.separatorColor=#B4B4B4
TableHeader.bottomSeparatorColor=#000000` but of no use. I tried to debug and when the table is rendered, 
```java
protected void paintBottomSeparator(Graphics g, JComponent c, int x, int w) {
        float lineWidth = UIScale.scale(1.0F);
        Graphics2D g2 = (Graphics2D)g.create();

        try {
            FlatUIUtils.setRenderingHints(g2);
            g2.setColor(this.bottomSeparatorColor);
            g2.fill(new Rectangle2D.Float((float)x, (float)c.getHeight() - lineWidth, (float)w, lineWidth));
        } finally {
            g2.dispose();
        }

    }
```

this method is called. Am I missing something here? Please help @DevCharly

**Comment by DevCharly** [comment]
Does the screenshot really show a table header?
Looks strange. What are you doing?

**Comment by DevCharly** [comment]
No answer since 3 weeks. Assume that issue is solved...
