### ISSUE TITLE
Laf animation

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#839]
I know there's this for animating a change between two different laf classes:
```
FlatAnimatedLafChange.showSnapshot();
UIManager.setLookAndFeel( lafClassName );
FlatLaf.updateUI();
FlatAnimatedLafChange.hideSnapshotWithAnimation();
```
But is there any way I can do the same for a change to the same laf class?

I have a look and feel class that dynamically supports both light and dark colors, plus has a few colors that can change runtime too...
Can I animate the changes from the same laf class, without having to create different lafs for the different light/dark and different colors combinations?
I don't know if it all makes sense all this...

**Comment by DevCharly** [comment]
Sure. Simply use `FlatAnimatedLafChange` as in your example and do what you want between `showSnapshot()` and `hideSnapshotWithAnimation()`. It is not required to change Laf.

**Comment by Frank-99** [comment]
Ok, I found the issue...
My glitch was that it wasn't transitioning smoothly but it was jumping sharply between states...

With this it works:

```
	FlatAnimatedLafChange.stop();
	FlatAnimatedLafChange.showSnapshot();
        //my edit, like isDark = true;
        
        //start of "reset laf" function
        try {
	        UIManager.setLookAndFeel(UIManager.getLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) { }
        FlatLaf.updateUI();
        //end of "reset laf" function
        
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
```
Before it was like this, and I think I originally copied it from the FlatLaf.reSetLookAndFeel() function without looking too much into it
```
        FlatAnimatedLafChange.stop();
	FlatAnimatedLafChange.showSnapshot();
        //my edit, like isDark = true;
        
        //start of "reset laf" function
        EventQueue.invokeLater(() -> {
                try {
	                PropertyChangeEvent e = new PropertyChangeEvent(UIManager.class, "lookAndFeel", lookAndFeel, lookAndFeel);
	                for (PropertyChangeListener l : UIManager.getPropertyChangeListeners()) {
		                l.propertyChange(e);
	        	}
	        	updateUI();
                } catch (UnsupportedLookAndFeelException e) { }
        });
        //end of "reset laf" function
        
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
```
and I think the `EventQueue.invokeLater()` made it so it would jump to final state instead of smoothly transitioning...
Sorry for my dumb mistake!
