### ISSUE TITLE
How can I set the selected table cell border color? 

### ISSUE THREAD

**Issue by josevjunior** [JFormDesigner/FlatLaf#84]
I'm using the following parameters to change the default properties of LaF:

    UIManager.put("Table.rowHeight", 23);
    UIManager.put("Table.showHorizontalLines", true);
    UIManager.put("Table.showVerticalLines", true);
    UIManager.put("Table.gridColor", new ColorUIResource(0, 0, 0)); 

Everything is going fine but, when the row is selected I want to show the grid color too but is gone:

![image](https://user-images.githubusercontent.com/20262017/79497360-ec87d600-7ffd-11ea-83e9-1acc6375023d.png)

How can I set that color?

**Comment by DevCharly** [comment]
Changing inter-cell spacing should help:
~~~java
UIManager.put( "Table.intercellSpacing", new Dimension( 1, 1 ) );
~~~

If you don't like the "gaps" in the selected row, you could try:
~~~java
UIManager.put( "Table.intercellSpacing", new Dimension( 0, 1 ) );
~~~

**Comment by josevjunior** [comment]
Exactly what I wanted. Worked like a charm. :thumbsup:
