### ISSUE TITLE
feature: Table.selectionArc

### ISSUE THREAD

**Issue by stefanoschalkidis** [JFormDesigner/FlatLaf#844]
Hi,

I don't know if it is possible, but it would be cool to have `Table.selectionArc` for rounded table selections.

Thanks!

**Comment by DevCharly** [comment]
see PR #856

**Comment by stefanoschalkidis** [comment]
awesome, thanks a lot! The snapshot seems to have failed during build, but if this is fixed I will happily test the new feature. Thank you once again for your hard work

**Comment by DevCharly** [comment]
implemented in latest `3.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
