### ISSUE TITLE
JMenu

### ISSUE THREAD

**Issue by awesomennguy** [JFormDesigner/FlatLaf#85]
Hi,
when I open my application once jmenu is working, when I open my application twice jmenu is gone.

**Comment by DevCharly** [comment]
It is difficult to help without additional information.

Can you post a screenshot?

Please also check whether the problem occurs with another look and feel. E.g. with the system LaF:

~~~java
UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
~~~

**Comment by awesomennguy** [comment]
Nevermind, I fixed it!
