### ISSUE TITLE
Using constants in property files ? 

### ISSUE THREAD

**Issue by MerlinUKRhapsody** [JFormDesigner/FlatLaf#853]
Is it possible to use constants somehow in property files ?
I'd like to define a set of colors once and then reference them across different themes. I can do that if I apply the styles programatically using UiManager but I cant seem to find a way to do it using the preferred approach (subclassing FlatLightLaf)

so for example instead of :
# Buttons
Button.background = #01416A

I'd like to use
# Buttons
Button.background = MY_BUTTON_BG_COLOR

**Comment by DevCharly** [comment]
> wrt to the below - how do I reference variables defined in other property files ? If I try to use a variable not defined in 'this' property file I get:
> 
> SEVERE: FlatLaf: Failed to parse: 'RootPane.background=@SOWI_SLATE' java.lang.IllegalArgumentException: variable or property '@SOWI_SLATE' not found

And where is `@SOWI_SLATE` defined?
Variables can be defined in any loaded properties file.

See https://www.formdev.com/flatlaf/how-to-customize/#application_properties
and https://www.formdev.com/flatlaf/how-to-customize/#properties_load_order

Hard to help with that less information...
