### ISSUE TITLE
Tooltips stop working with FlatLaf

### ISSUE THREAD

**Issue by MerlinUKRhapsody** [JFormDesigner/FlatLaf#854]
Dangit here's another weird effect if my app is run as a plugin inside a C++ application. 
If I use Nimbus - tooltips work fine:

<img width="180" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/123633186/f07889df-5b0f-4a2e-ac29-1b037488ae35">

If I use FlatLaf then they dont appear - well they do but as a tiny piece of corrupted UI:

<img width="230" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/123633186/8601ff42-cb22-4b9f-8b27-951311ce48da">

**Comment by DevCharly** [comment]
Please stop opening new issues for same/related problems.
Instead post problems related to your C++ app in #851
