### ISSUE TITLE
Referencing Other Property Files

### ISSUE THREAD

**Issue by MerlinUKRhapsody** [JFormDesigner/FlatLaf#855]
wrt to the below - how do I reference variables defined in other property files ?
If I try to use a variable not defined in 'this' property file I get:

SEVERE: FlatLaf: Failed to parse: 'RootPane.background=@SOWI_SLATE'
java.lang.IllegalArgumentException: variable or property '@SOWI_SLATE' not found

              You can either use "variables": https://www.formdev.com/flatlaf/properties-files/#variables
or "references": https://www.formdev.com/flatlaf/properties-files/#references

_Originally posted by @DevCharly in https://github.com/JFormDesigner/FlatLaf/issues/853#issuecomment-2180048571_

**Comment by DevCharly** [comment]
Please stop opening new issues for follow-up questions on other issues.
Instead post it in original issue #853
