### ISSUE TITLE
Non-Editable Table Cells

### ISSUE THREAD

**Issue by MerlinUKRhapsody** [JFormDesigner/FlatLaf#858]
Is it possible to paint a non-editable (Boolean) table cell differently ? 
eg: 

@Override
			public boolean isCellEditable( int row, int column )
			{
				if ( column == COL_DRAG )
					return false;
				if ( column == COL_CAPTURE && !mainGUI.isQuery )
					return false;
				return true;
			}

This presents a checkbox - but I couldn't find a way to color it differently. I tried the CheckBox properties but these didnt take effect in the table:

CheckBox.icon.checkmarkColor = @Forgeround
CheckBox.icon.background = @TECH_RED
CheckBox.icon.disabledBorderColor = @SLATE
CheckBox.icon.disabledBackground = @SLATE

The Capture cells are all non-editable but they appear the same as the target cells which are editable:

<img width="117" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/123633186/2690d21a-51a0-428c-a1b5-91dc52c5a725">

**Comment by DevCharly** [comment]
Default table cell renderer for Boolean does not check whether cell is editable.

You need to implement your own table cell renderer.
