### ISSUE TITLE
Button Background 

### ISSUE THREAD

**Issue by MerlinUKRhapsody** [JFormDesigner/FlatLaf#862]
I just cannot figure this one out - my JButtons behave correctly wrt to background, hovering, pressing etc - except after a button has been pressed and I move the mouse away - it gains a blue background color. This doesnt show up in the Theme Editor and I've set every 'background' color I can find for JButtons to the same thing:

<img width="671" alt="image" src="https://github.com/JFormDesigner/FlatLaf/assets/123633186/3dd5f503-eb50-40d2-86da-58b30a8ac812">

Has anyone seen this before ?

**Comment by DevCharly** [comment]
Maybe you defined blue background for focused buttons?

**Comment by MerlinUKRhapsody** [comment]
I didnt - and that was the problem - I guess this was coming from the FlatLaf light theme from which mine inherits - i added the property to force it to the same background as an unfocussed one - thanks !
