### ISSUE TITLE
Placeholder for FlatTextArea

### ISSUE THREAD

**Issue by BrunoEberhard** [JFormDesigner/FlatLaf#863]
Would it be possible to support placeholders in FlatTextArea? Maybe with several lines?

**Comment by DevCharly** [comment]
> Would it be possible to support placeholders in FlatTextArea?

Sure, a lot is possible 😉 
It simply needs someone that spends 1-3 days to implement/test/document it... 😒 

I've no plans to do that, except some company (or someone) sponsors development of this feature with a Silver (or larger) sponsorship: https://www.formdev.com/flatlaf/sponsor/

Sorry to ask for sponsorship, but can't implement all the features companies want, for free...
