### ISSUE TITLE
Possibility to show the sub-menu accelerator icon indicator (arrow) on a top-level JMenu

### ISSUE THREAD

**Issue by AndreZeiler** [JFormDesigner/FlatLaf#867]
Currently and in most other SWING L&Fs it is not possible to render the accelerator Icon in a JMenu if it is the TopLevelMenu (JMenu#isTopLevelMenu and FlatMenuItemRenderer#isTopLevelMenu).
But in some situations (I use a vertical JMenuBar with a mix of entries with and without sub-menus)  it would be neat to have the possibility to show the accelerator icon even on the top level.

I previously worked around this situation, by defining the JMenus icon as the accelerator icon with a trailing/left icon position and a calculated icon gap (to align them). But because I now want to define a meaningful icon alongside the accelerator this is no longer possible.

Would be great to hear your opinion on this.

**Comment by DevCharly** [comment]
Sounds like a good idea.

I wonder how you create a vertical JMenuBar?

**Comment by AndreZeiler** [comment]
I used a workaround because there is no "real" vertical option in the JMenuBar.
The JMenuBar uses a GridLayout with 0 rows and 1 column => JMenuBar#setLayout(new GridLayout(0, 1))
This workaround can be found here: https://www.tutorialspoint.com/how-to-create-a-vertical-menu-bar-in-java
