### ISSUE TITLE
Cleanup style attributes for hovered JMenuItem with html text

### ISSUE THREAD

**Issue by dinix2008** [JFormDesigner/FlatLaf#87]
Hi,

Is it possible to cleanup color style attributes for hovered JMenuItem with html text?
now:
<img width="156" alt="Снимок экрана 2020-04-24 в 11 18 47" src="https://user-images.githubusercontent.com/1597289/80191116-ed33f400-861d-11ea-8ca7-b1a88cf20435.png">
expected:
<img width="154" alt="Снимок экрана 2020-04-24 в 11 22 39" src="https://user-images.githubusercontent.com/1597289/80191123-f02ee480-861d-11ea-88a9-342ec138e315.png">

**Comment by DevCharly** [comment]
I'll have a look...

**Comment by DevCharly** [comment]
fixed in master branch

thanks for reporting

**Comment by dinix2008** [comment]
Thank! Excellent work
