### ISSUE TITLE
mis-allignment of jtable and jtextfield 

### ISSUE THREAD

**Issue by Hellf0rg0d** [JFormDesigner/FlatLaf#872]
I was working on an application and found that the allignment of jtable and jtextfield is incorrect but when i build it without using flatlaf it gets aligned correctly see the screenshots below.
without flatlaf :
![image](https://github.com/user-attachments/assets/89fbf498-da28-49d3-9ae3-9e8687d88784)

with flatlaf MacDarkLaf :
![image](https://github.com/user-attachments/assets/a9c66d22-2856-4426-a716-e4be4a745869)

**Comment by poce1don** [comment]
This is not a problem with the FlatLaf library.  Positioning components "freely" is not the best way to build your graphical interface 👎 . Make use of layout managers, such as MigLayout (this is the best) 👏 or GridLayoutManager (IntelliJ) 👍  and you won't have this type of problem with alignments ✌️ .

**Comment by Hellf0rg0d** [comment]
i am using group layout...

**Comment by DevCharly** [comment]
This is not a FlatLaf bug.

Different L&Fs use different fonts which results in different component sizes.

> i am using group layout...

Then tell group layout that the two components should have same width.
