### ISSUE TITLE
ComboBox sometimes "empty"

### ISSUE THREAD

**Issue by rjahn** [JFormDesigner/FlatLaf#879]
I use flatlaf 3.4 and have "standard" Combo boxes.
Sometimes, the poupup is empty but contains all components and is already layouted.
If I click on the popup, the component appears and everything is shown correct.

Screencast:

https://github.com/user-attachments/assets/00d6f58d-41b8-477e-90a1-02bb40a0aef5

I simply open/close the combobox popup by mouse click.
Check: 0:45, 1:31, 1:43

Before the update to 3.4 we didn't notice this problem. Do you have an idea if your code contains something that can trigger this behaviour?

**Comment by DevCharly** [comment]
Seems that the popup list/scrollpane is not layouted (e.g. has size 0x0) 🤔 

On what platform (operating system) does this happen?
Do you see it also on other platforms?

Java version?

> Before the update to 3.4 we didn't notice this problem. Do you have an idea if your code contains something that can trigger this behaviour?

Hard to say without knowing what version you used before 😉 
Could be related to rounded borders...

Please try also latest FlatLaf version 3.5.1

**Comment by rjahn** [comment]
I already tried to layout the popup but this didn't fix the problem.

OS: MacOS
Java: Temurin 19.0.1+10

FlatLaf before: 2.6

Will test with 3.5.1 and Windows 11 asap. Didn't test other OS on my own.

**Comment by rjahn** [comment]
Tried FlatLaf version 3.5.1 and problem is still reproducable.

**Comment by rjahn** [comment]
If you need an easy test case:

```java
package com.sibvisions.menu;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.UIManager;

public class MenuDemo extends JFrame 
{
	public static void main(String[] pArgs)
	{
		try 
		{
		    UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
		} 
		catch( Exception ex ) 
		{
		    System.err.println( "Failed to initialize LaF" );
		}
		
		MenuDemo md = new MenuDemo();
		md.setLocationRelativeTo(null);
		md.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		md.pack();
		md.setVisible(true);
	}
	
	private MenuDemo()
	{
		JMenu m1 = new JMenu("File");
		m1.add(new JMenuItem("Exit"));
		
		JMenuBar mb = new JMenuBar();
		mb.add(m1);
		
		setJMenuBar(mb);
		
		setLayout(new BorderLayout());
		
		FlowLayout flCombo = new FlowLayout();
		flCombo.setHgap(20);
		
		JPanel panCenter = new JPanel();
		panCenter.setLayout(flCombo);
		
		JComboBox cb1 = new JComboBox(new String[] { "Bird", "Cat", "Dog", "Rabbit", "Pig" });
		JComboBox cb2 = new JComboBox(new String[] { "First", "Second", "Third" });
		
		panCenter.add(cb1);
		panCenter.add(cb2);
		
		add(panCenter);
		
		setPreferredSize(new Dimension(400, 200));
	}
}
```

Tested with JDK 19 and FlatLaf 3.5.1

Video:

https://github.com/user-attachments/assets/927bf970-4f01-4257-a56d-2b64afd80b1f

(at the end - 00:16)

A simple mouse over shows the content, so I guess layouting is not the problem.

**Comment by rjahn** [comment]
The empty popup occurs only one time, but it occurs - in standard JComboBoxes.

The right combobox is a JVxComboBase. It's a special combobox from the JVx framework. It's different to the standard JComboBoxes becasue the popupComponent is not re-used and recreated on every popup open. With this special combobox, it's easier to reproduce the problem. If you want this test-case, simply use jvx.jar from our nightly build page:

https://collab.sibvisions.com/jvx.nightly/

and add it to your classpath.

Change above test app:

```java
JVxComboBase cb3 = new JVxComboBase();
cb3.setPopupComponent(new JButton("Press me"));

panCenter.add(cb3);
```

https://github.com/user-attachments/assets/55265816-d5ae-4fe3-aa1e-2f4bf97040e6

The problem also occurs in 2.6... but not so often :(

Maybe a general Java problem, but it works wit standard platform LaF.

**Comment by rjahn** [comment]
Not reproducable with Windows (11) and it's also not reproducable with Java 11, 18, 22.

Looks like a problem with Java 19 only.

**Comment by DevCharly** [comment]
> Looks like a problem with Java 19 only.

So I'll close that issue...
