### ISSUE TITLE
FlatLaf ignores overrides window decorations of the Linux host Os, ignoring GUI conventions and settings made by the user.

### ISSUE THREAD

**Issue by thorfdbg** [JFormDesigner/FlatLaf#880]
If you use applications build against Flatlaf, it overrides all window decorations (or rather, suppresses them), including those generated by the window manager of the host system, e.g. xfwm4. This means that Flatlaf applications integrate poorly into the host desktop, and in particular ignore selections made by the user. For example, if users select to have the window close button on the top left rather top right, Flatlaf will outright ignore this choice, but renders its own button in its own style (and not in the style of the window manager). This makes Flatlaf applications look alien to the host system, and breaks GUI conventions selected by the user.

**Comment by DevCharly** [comment]
This is Linux only.

The FlatLaf window decorations are **not enabled by default on Linux**. 
So if you don't like it, **do not enable it**.

Remove following from your app:
~~~java
JFrame.setDefaultLookAndFeelDecorated(true);
JDialog.setDefaultLookAndFeelDecorated(true);
~~~

On Linux, there are dozens (or hundreds) of different [window managers](https://wiki.archlinux.org/title/Window_manager) available and each of them has it's own "GUI conventions and settings". It is simply not possible to reproduce the look of those window managers in FlatLaf...

see #821
