### ISSUE TITLE
Downloading Flatlaf using link issue

### ISSUE THREAD

**Issue by absolutecoder01** [JFormDesigner/FlatLaf#888]
By clicking [Maven Central](https://maven-badges.herokuapp.com/maven-central/com.formdev/flatlaf) 
I'm getting application error, System: MacOS, Browser Google Chrome
<img width="1280" alt="Screenshot 2024-09-24 at 12 56 46" src="https://github.com/user-attachments/assets/3dbcc2a5-0aa1-4c52-aca9-2869b4346dc6">

**Comment by DevCharly** [comment]
It works for me. Maybe it was a temporary problem.
