### ISSUE TITLE
[Question] Applying color properties to subclasses of components

### ISSUE THREAD

**Issue by TheEntropyShard** [JFormDesigner/FlatLaf#889]
I am making my own navbar and I am subclassing `JToggleButton` because I want to make it look like `JTabbedPane`'s tab buttons, but in `{insert laf class name here}.properties` I can only set colors to all toggle buttons. How can I do that only for my component? I tried subclassing UI, but it does not do anything.

FlatLaf 3.4.1

**Comment by DevCharly** [comment]
> ...I want to make it look like JTabbedPane's tab buttons...

FlatLaf supports the "tab" look for toggle buttons. Set client property `JButton.buttonType` to `tab`.
https://www.formdev.com/flatlaf/client-properties/#JButton

For styling see `ToggleButton.tab.*` UI properties:
https://www.formdev.com/flatlaf/components/button/

> ...I can only set colors to all toggle buttons. How can I do that only for my component?...

Use FlatLaf styling. See PR #341

**Comment by TheEntropyShard** [comment]
Thank you for the help!
