### ISSUE TITLE
FlatLaf 3.5.1 Common Themes Don't Support GridLayout

### ISSUE THREAD

**Issue by harshinioruganti** [JFormDesigner/FlatLaf#891]
When using the FlatLaf common themes (Light, Dark, IntelliJ), GridLayout Java Swing component does not render correctly and has visibility issues. Tested the same GridLayout with a different LAF (Nimbus) to see if the issue persists, and it was visible so it seems to just be specific LAF themes.

**Comment by DevCharly** [comment]
@harshinioruganti If someone would send you such an error report, without any real information, what would you think?

**Comment by harshinioruganti** [comment]
What details would you like? I'd be happy to provide.

There is no error so I didn't have much details. Simply was bringing light to an issue I noticed when playing around with the look and feel of an existing application I am working on. The GridLayout isn't visible with the FlatLaf common themes. I wasn't able to attach images previously but here are some I was able to get showing the issue.

![NimbusLookAndFeel_GridLayout](https://github.com/user-attachments/assets/70ca439d-a4fd-4867-bf2d-c794dd3c70eb)
![FlatLaf_GridLayout](https://github.com/user-attachments/assets/627d00ef-d189-4978-a230-bfbb116666a7)

**Comment by DevCharly** [comment]
This is not GridLayout.
This is a JTable, right?

FlatLaf hides JTable grid lines by default.

To show grid lines for a single JTable use:

~~~java
table.setShowHorizontalLines( true );
table.setShowVerticalLines( true );
table.setIntercellSpacing( new Dimension( 1, 1 ) );
~~~

Or for all tables in application:

~~~java
UIManager.put("Table.showHorizontalLines", true);
UIManager.put("Table.showVerticalLines", true);
UIManager.put("Table.intercellSpacing", new Dimension(1, 1));
~~~
