### ISSUE TITLE
I trying to round Top Left Corner of java swing Panel

### ISSUE THREAD

**Issue by HansaraHettiarachchi** [JFormDesigner/FlatLaf#893]
private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        jLayeredPane1.removeAll();
        JPanel cPanel = new p1();

        Insets insets = jLayeredPane1.getInsets();
        if (insets != null) {
            cPanel.setBounds(insets.left, insets.top, jLayeredPane1.getWidth() - insets.left - insets.right, jLayeredPane1.getHeight() - insets.top - insets.bottom);
        } else {
            cPanel.setBounds(0, 0, jLayeredPane1.getWidth(), jLayeredPane1.getHeight());
        }

        cPanel.putClientProperty(FlatClientProperties.STYLE, "arcTopLeft: 100");

        jLayeredPane1.add(cPanel, JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.repaint();
    }     
    
    But this do not working

**Comment by DJ-Raven** [comment]
FlatLaf don't have `arcTopLeft` style properties. but you can use utilities method in flatlaf to custom the JComponent.

``` java
private class CustomRoundBorder extends JComponent {

        public CustomRoundBorder() {
            setOpaque(true);
        }

        @Override
        protected void paintComponent(Graphics g) {
            if (isOpaque()) {
                FlatUIUtils.paintParentBackground(g, this);
            }
            Graphics2D g2 = (Graphics2D) g.create();
            FlatUIUtils.setRenderingHints(g2);
            int arcTopLeft = 100;
            int arcTopRight = 0;
            int arcBottomLeft = 0;
            int arcBottomRight = 0;
            g2.setColor(getBackground());
            g2.fill(FlatUIUtils.createRoundRectanglePath(0, 0, getWidth(), getHeight(), arcTopLeft, arcTopRight, arcBottomLeft, arcBottomRight));
            g2.dispose();
            super.paintComponent(g);
        }
    }
```

Then use is as your cPanel

``` java
CustomRoundBorder cPanel = new CustomRoundBorder();
```

**Comment by DevCharly** [comment]
thanks @DJ-Raven 👍
