### ISSUE TITLE
I need help, pls everyone speed a little time to look this problem

### ISSUE THREAD

**Issue by sukai-cheng** [JFormDesigner/FlatLaf#896]
I use JScrollPane , it unable to horizontal movement, i tried many ways but i can't resolved this problem, i hope someone can help me > <
<img width="836" alt="image" src="https://github.com/user-attachments/assets/b265da8f-b17d-4b7a-8010-7784a0dc5fb7">

**Comment by DevCharly** [comment]
If your question is "how to enable horizontal scrolling for JTable",
then the answer is `table.setAutoResizeMode( JTable.AUTO_RESIZE_OFF )`.

**Comment by DevCharly** [comment]
BTW instead of using **meaningless titles** like
_"I need help, pls everyone speed a little time to look this problem"_ or
_"Can you tell me how to run this project ?"_
it would be much better to use something more useful that **describes the actual problem/question**.

**Comment by sukai-cheng** [comment]
thank you very much , i will accept you advice
