### ISSUE TITLE
Change TitleBar height Windows 10/11

### ISSUE THREAD

**Issue by Frank-99** [JFormDesigner/FlatLaf#897]
I need to make a taller title bar for a specific `JFrame` in Windows 10/11.
I'd need something along the lines of `JRootPane.titleBarHeight` or `JRootPane.titleBarExtended`.
I've seen there is a `TitlePane.buttonSize`, but I don't think it would do exactly what I need as I think I'm only able to set it via `UIManager` for all JFrames.

To be more specific, this is the desired effect I'm looking to achieve; a taller title bar that makes the buttons squarer, thus leaving more room for a Profile "button" and a search bar, as seen here in all current Office365 apps design:
![image](https://github.com/user-attachments/assets/9e7cd56a-8cbc-4e60-befc-dd4f89a4eeea)
![image](https://github.com/user-attachments/assets/841b46a9-968b-4981-8b59-7fa1a168dfde)

I've also tried to force a custom height on a `JMenu` button in the integrated title bar menu but the close, minimise and maximise buttons don't expand to fill the new height.
This is exaggerated but it shows well what I mean:
![image](https://github.com/user-attachments/assets/2445ea3f-44ac-42c7-a636-a728aec6f474)
![image](https://github.com/user-attachments/assets/66d74119-184d-4d84-b2bc-2297b70c78b8)

Is there a way of doing this that I'm missing, or is it just not supported currently? in the latter case, would it be ever supported in a future version?
Thank you in advance

**Comment by DevCharly** [comment]
fixed/implemented in latest `3.5.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

The iconify/maximize/close buttons now always fill whole title bar height.

Also there is a new client property `JRootPane.titleBarHeight` (or `FlatClientProperties.TITLE_BAR_HEIGHT`) of type `int`.

For your use case, I would suggest the use of "full window content" mode (PR #801).
If you use a "buttons placeholder" (see PR #801) and set `JRootPane.titleBarHeight`,
then the placeholder gets that height as well.
For a nice layout, you could put your top bar into the center of a BorderLayout and the placeholder to the east.

**Comment by DevCharly** [comment]
FlatLaf 3.5.2 is out now 😄
