### ISSUE TITLE
When using menuBarEmbedded=true I can't move the window

### ISSUE THREAD

**Issue by StefanSchmaltz** [JFormDesigner/FlatLaf#898]
Using current 3.5.1, Swing, Jide, JFrame
When I do this:
`FlatLightLaf.setup();
System.setProperty("flatlaf.menuBarEmbedded", "true");`
Then I can't move the Window with my mouse, dragging does not work. Using "false" here, dragging works.
Also when I press Alt+space, I can move the window with my arrow keys.
Is this a known bug?

**Comment by DevCharly** [comment]
Hmm, dragging with mouse and moving by keyboard with Alt+Space works fine for me 😕 

You need to use the area between the menu bar and the min/max/close buttons to drag the window:

![image](https://github.com/user-attachments/assets/d6b37462-3a1a-4023-8a39-05699205e8f1)
