### ISSUE TITLE
FlatJetBrainsMonoFont.install() is slow 500ms

### ISSUE THREAD

**Issue by ryanhamilton** [JFormDesigner/FlatLaf#901]
I try to optimize the startup of my app. Overall my app takes 2000 MilliSeconds, of taht the font install is 350ms.

The simplest example is this Main class below. 
Running Time = 488 milliseconds
Comment out .insatll() = <40ms.

```
import com.formdev.flatlaf.fonts.jetbrains_mono.FlatJetBrainsMonoFont;

public class Main {

	public static void main(String... args) {
        long startT = System.nanoTime();
		FlatJetBrainsMonoFont.install();     
		System.out.println("...");
        System.out.println("Time = " + (System.nanoTime() - startT) / 1000000.0);
	}
}
```

**Comment by DevCharly** [comment]
This is a Swing issue.

All time is spent in following two lines:

https://github.com/JFormDesigner/FlatLaf/blob/c29a2761884a899f59d890b4b97b7f54678d1af8/flatlaf-core/src/main/java/com/formdev/flatlaf/util/FontUtils.java#L103-L104

But only when installing first font. Second font is installed in a few milliseconds.
Seems that Swing does some initialization of internal stuff that needs some time.

Too avoid this I would recommend using `FlatJetBrainsMonoFont.installLazy()`, which installs fonts lazy when first used.

**Comment by ryanhamilton** [comment]
Thanks for investigating.
