### ISSUE TITLE
Make leading component display something in the tabbedpane area.

### ISSUE THREAD

**Issue by VKaddala** [JFormDesigner/FlatLaf#902]
I have a tabbed pane with a scroll layout, and the requirement is to make the first tab always unscrollable. It is a fixed tab with some custom components displayed in the tabbed pane's content area. I considered adding a leading component and setting the tab content, but it is not working. How can I achieve this scenario? @DevCharly

**Comment by DevCharly** [comment]
You could use two "content-less" tabbed panes and manage display of content yourself.

"content-less" tabbed pane means that the tab content components of all tabs is `null`. Then FlatLaf only displays the tabs. See "Tabs" tab in FlatLaf Demo. 

Then you need some listeners to show or hide tab content when selected tab changes.
