### ISSUE TITLE
Option for setting Hover Color of icons in Buttons

### ISSUE THREAD

**Issue by SamKry** [JFormDesigner/FlatLaf#906]
Hi

First, thank you allot for all the effort and great work!

Is there a way to set the color of the icons in a Button? I can set the Color Filter statically for icons, however, i would like to achieve a "hover effect" like already implemented for Text buttons.

I currently do it by changing the Color Filter with a mouse listener but it would be great if we could do this dynamically using the .properties file for the LAF.

The same would be great to have for ToggleButtons to have an icon color for toggled buttons.

**Comment by DevCharly** [comment]
In latest `3.6-SNAPSHOT` (see https://github.com/JFormDesigner/FlatLaf#snapshots), I've extended `FlatSVGIcon` color filters slightly. They now can access painting component to implement component state based color mappings.

Here is an example for a global SVG color filter that changes icon color to red if mouse pointer is over JButton:

~~~java
FlatSVGIcon.ColorFilter.getInstance().setMapperEx( (c, color) -> {
    if( c instanceof JButton && ((JButton)c).getModel().isRollover() )
        return Color.red;
    return color;
} );
~~~
