### ISSUE TITLE
Linux: A bug with cursor capture when resizing the form.

### ISSUE THREAD

**Issue by credos** [JFormDesigner/FlatLaf#907]
Hello. Thank you for your work.  Tell me if there is an opportunity to get rid of the cursor bug when resizing the form in the "JFrame.setDefaultLookAndFeelDecorated(true)" mode (if you do not enable this mode, then the cursor is captured correctly).  More about the problem: when you hover the mouse cursor over the edge of the shape, it takes an image, for example - NW_RESIZE_CURSOR. But when, after pressing the left mouse button, the shape size changes, the cursor begins to change arbitrarily from NW_RESIZE_CURSOR to DEFAULT_CURSOR (arrow) and back. I understand that this happens as a result of slow redrawing of the form, the cursor periodically falls on the contentPane, while changing to an arrow, but I can't figure out how to defeat it...  (flatlaf-3.5.2,  OpenJDK-21.0.1 X)  An example of the bug is shown in the attached video.  
[vokoscreenNG-2024-11-06_00-14-20.webm](https://github.com/user-attachments/assets/5d86e20d-6fda-46e1-9909-1164a766c2da)

**Comment by DevCharly** [comment]
Thanks for reporting. Fixed in latest `3.5.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
