### ISSUE TITLE
Table background painting beyond data.

### ISSUE THREAD

**Issue by StScAllen** [JFormDesigner/FlatLaf#908]
Hello, I cant seem to find anything on this in the documentation.  I appreciate any help you could provide.  I am using the latest FlatLaf paired with J17.  I have the table.background property set to white.  My issue is that the color extends to areas beyond the tables area.  For instance, in the attached image, I want the white to be the background for my table rows but I want the default panel color to show in all areas below the table. It seems like FlatLaf is extending the table to cover the entire panel.  When I remove FlatLaf, and all other things being equal, the table coloring stops at the last data row. Is there anyway to override this behavior in FlatLaf?  I tried the swing 
setFillsViewportHeight(false) method in my java tables and it made no difference. 

![image](https://github.com/user-attachments/assets/b4ba93b7-3baf-45e6-a7e3-fef6901561f6)

Thanks again!

**Comment by StScAllen** [comment]
Can close.  I just decided to subclass FlatTableUI and change the behavior directly. If you wanted to add a boolean setting that was checked in FlatTableUI line 575 in method paintViewport that would be great.  As is, this is serviceable for my needs. Thanks for the great software!

**Comment by DevCharly** [comment]
👍
