### ISSUE TITLE
Possible deadlock with TabbedPane and Full window content

### ISSUE THREAD

**Issue by Punikekk** [JFormDesigner/FlatLaf#909]
### Deadlock in `JTabbedPane` with "FULL_WINDOW_CONTENT" Mode on resize

When using `JTabbedPane` with any bounds in the title pane in `"FULL_WINDOW_CONTENT"` mode, resizing the window sometimes causes the GUI thread to get deadlocked. This issue specifically occurs when resizing from the top-left corner of the GUI while the bottom-right corner is offscreen.

AWT_EventQueue is stuck in native method endValidate(), where AWT_Windows is trying to get the lock i assume

- Windows 11
- JDK 21

![image](https://github.com/user-attachments/assets/59a84ab7-422a-4c4e-b7fa-c9a6c718e309)

**Comment by DevCharly** [comment]
Thanks for reporting. Fixed in latest `3.5.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
