### ISSUE TITLE
Menu Accelerator overlaps sub menu indicator column

### ISSUE THREAD

**Issue by Chrriis** [JFormDesigner/FlatLaf#91]
Hi,

I really like the new menus, especially with the underline style 👍 . There are however a few things that could further improve them. Here is one: the accelerator of a menu is not the same thing as the sub menu indicator, and using the same area for display feels odd, like an overlap:
![MenuAcceleratorOverlap1](https://user-images.githubusercontent.com/1174202/80791660-a0f33180-8b92-11ea-8099-e5ab16d26431.png)

I would recommend keeping the sub-menu indicator (arrow) in its own dedicated column, or at least have a way for a user to define a padding for the accelerator area in order to achieve such display:
![MenuAcceleratorOverlap2](https://user-images.githubusercontent.com/1174202/80791668-a5b7e580-8b92-11ea-80dd-83197f03a133.png)

So you know, in my case it is more than a cosmetic issue because I enhanced regular items to be able to have both a sub-menu and an accelerator (the feature is a jumplist), and I do get a real overlap. Here is the Windows version:
![MenuAcceleratorOverlap3](https://user-images.githubusercontent.com/1174202/80792719-7e164c80-8b95-11ea-8ac8-8952bc0434c4.png)

I can probably hack FlatLaf to fix this but I think the cosmetic aspect mentioned above is valid and it would solve this second problem.

**Comment by DevCharly** [comment]
Gap between menu item accelerator and arrow is now implemented in master branch.
The default value is relative small (2px) which works fine IMHO and does not increase the right margin of the menus.

In your special case (JMenu with accelerator) I would recommend to increase the gap with e.g.:
~~~java
UIManager.put( "MenuItem.acceleratorArrowGap", 4 );
~~~

**Comment by Chrriis** [comment]
@DevCharly Your changes are neat. The defaults are good, and the property to change the gap allows me to achieve exactly what I need! Perfect!
