### ISSUE TITLE
Custom Fonts from .ttf file are not supported

### ISSUE THREAD

**Issue by shayaan-d** [JFormDesigner/FlatLaf#913]
Is there a way we can use .ttf fonts in our form?

**Comment by DevCharly** [comment]
Yes, this is possible in Swing since Java 1.6

FlatLaf even offers a helper method:
https://github.com/JFormDesigner/FlatLaf/blob/ff5bd301ccb2b233ace7ccbe5bd220959a1863ea/flatlaf-core/src/main/java/com/formdev/flatlaf/util/FontUtils.java#L101-L109
