### ISSUE TITLE
Properties files are not working.

### ISSUE THREAD

**Issue by Isoface** [JFormDesigner/FlatLaf#914]
Im following all the instructions i found in the website: https://www.formdev.com/flatlaf/how-to-customize/#new_theme

But properties files are not working. I created my own theme, and it doesn't work. I also tried to override the default FlatLightLaf properties file, but it doesn't work either. This is my code for the theme, the properties file, and the main class:

################################################

VendeMasTheme.java file:
![Screenshot_AAAA](https://github.com/user-attachments/assets/9c9792a7-9bd9-4366-a683-9e7976c538e4)

####################################################
VendeMasTheme.properties File:
![Screenshot_BBBBBBB](https://github.com/user-attachments/assets/33283e4d-5f0d-4761-bce6-14a3c7223c00)

########################################################
VendeMasAdmin.java file:
![Screenshot_CCCCCCCC](https://github.com/user-attachments/assets/cad16e1b-b999-4d91-bdb8-3834303cba67)

###################################
And this is what im getting:
![Screenshot_DDDDDDDDDD](https://github.com/user-attachments/assets/5ad68da9-b930-4c28-82a0-5721b14a2b42)

**Comment by DevCharly** [comment]
The properties file must be in same package as the class `VendeMasTheme`.

**Comment by Isoface** [comment]
It is in the same package. It's right next to it

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DevCharly** [comment]
Ok, then check whether your IDE has copied the properties file to its compiler output folder (where it stores the compiled classes).
It must be in same folder as `VendeMasTheme.class`.

**Comment by Isoface** [comment]
Oh. It didn't. Only the class was compiled. Should i modify something in the pom file?

**Comment by DevCharly** [comment]
Usually the IDE/maven automatically copies resources (e.g. images or properties files) to output folder.
Maybe you have a separate "resource" folder in your project?
Then you need to move `VendeMasTheme.properties` to that folder (keep package).

**Comment by Isoface** [comment]
It worked! Thank you
