### ISSUE TITLE
JComboBox: do not render arrow background if arrow button is not visible

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#915]
Hello. I'm working on migration Consulo (IDEA fork) to FlatLaf, and I added code which hide arrow button (arrowButton.setVisible(false)) - but FlatLafUI anyway draw background. 

Actual (FlatMacDarkLaf)

![{64B20BD3-4B2C-4631-AC4D-794285441059}](https://github.com/user-attachments/assets/22747b0c-ba69-4eaf-a1d7-700f09a4e059)

Expected

![{16715B86-0716-4E23-A4F5-74E3ACC08752}](https://github.com/user-attachments/assets/506e5c12-6e82-4c5c-8e2b-76254a378395)

**Comment by DevCharly** [comment]
Fixed in latest `3.5.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
