### ISSUE TITLE
Add a possibility to have indeterminate checkbox *not* styled as selected

### ISSUE THREAD

**Issue by patric42** [JFormDesigner/FlatLaf#919]
According to FlatCheckBoxIcon.java:183, indeterminate state makes the whole appearance of the CheckBox that of a selected one - even if I could argue that a 'null' value is semantically closer to false than true.

Could you make that 'switchable' or at least have an idea (I'd try to supply a PR for it) on how to approach that change. I just want to avoid doing an approach you'd dislike.

Thanks for the tremendous work :-)

**Comment by DevCharly** [comment]
Implemented in PR #936
