### ISSUE TITLE
Color issues  in NetBean Output Window and JavaDoc wizard

### ISSUE THREAD

**Issue by r-go** [JFormDesigner/FlatLaf#92]
The setup:
NetBeans Preferences / "Fonts and Colors" / "Profile" = "FlatLaf Dark"
NetBeans Preferences / "Appearance" / "Prefered Look and Feel"  = "FlatLaf Dark"
NB 11.3 + Java 13 + macOS High Sierra 

The issues: 
- NetBean's Output Window is rendered with black text on white background, which is in a stark contrast to the the rest of NetBean's  (dark colored) UI
- Tables in JavaDoc popup wizard (within Code Completion wizard  ie on Ctrl+Space) are missing the cell lines (in fact, the color of table lines is the same as the background, which renders them invisible)

**Comment by lamhoangtung** [comment]
+1 having this issue

**Comment by DevCharly** [comment]
> * NetBean's Output Window is rendered with black text on white background, which is in a stark contrast to the the rest of NetBean's  (dark colored) UI

This can have several reasons:

1) a bug in NetBeans (does not change all colors when changing look and feel). Was not yet able to reproduce this for the Output window, but have it for the Terminal window. Then it is necessary to press the "Restore" button in "Options > Miscellaneous > Terminal" to fix the colors.

2) you have changed the color in NetBeans Options dialog (Miscellaneous > Output > Background color). Changes made in Options dialog are not overwritten when switching L&F. 

To fix colors of Output window press the "Restore" button in "Options > Miscellaneous > Output".

> * Tables in JavaDoc popup wizard (within Code Completion wizard  ie on Ctrl+Space) are missing the cell lines (in fact, the color of table lines is the same as the background, which renders them invisible)

HTML tables seem to work fine with plain FlatLaf if using `<table border="1">`:

![image](https://user-images.githubusercontent.com/5604048/86060858-ee423100-ba65-11ea-9e7e-197be699056b.png)

![image](https://user-images.githubusercontent.com/5604048/86060865-f26e4e80-ba65-11ea-86b6-5a7ddee760fc.png)

No border is shown without `border="1"` attribute.

NetBeans also shows the border if using `<table border="1">`:

![image](https://user-images.githubusercontent.com/5604048/86061206-a1128f00-ba66-11ea-9fad-8b02240b69ef.png)

Do you have `border="1"` attribute in your tables?
