### ISSUE TITLE
JTree: wide cell render support

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#922]
Hello I'm working on adapting IDEA like code (fork named Consulo), found some different in cell render for tree:

|  JetBrains implementation TreeUI ([DefaultTreeUI](https://github.com/consulo/consulo/blob/master/modules/desktop-awt/desktop-awt-ide-impl/src/main/java/consulo/desktop/awt/ui/plaf2/DefaultTreeUI.java)) | Flat implementation TreeUI |
|-----|--------|
|![image](https://github.com/user-attachments/assets/0a1b3c1b-fa9f-4b2b-a8d9-62227477e7ba) | ![image](https://github.com/user-attachments/assets/b3f51d6e-50f2-4971-a22c-752ce451f01e) |

It's simple Border panel where icon placed at east.
https://github.com/consulo/consulo/blob/master/modules/desktop-awt/desktop-awt-ide-impl/src/main/java/consulo/desktop/awt/settings/OptionsTree.java

https://github.com/consulo/consulo/blob/master/modules/base/ui-ex-awt-api/src/main/java/consulo/ui/ex/awt/CellRendererPanel.java
```java
    private class MyRenderer extends CellRendererPanel implements TreeCellRenderer {
        final NodeRenderer myTextLabel = new NodeRenderer();
        final JLabel myNodeIcon = new JLabel();
        final JLabel myProjectIcon = new JLabel();

        MyRenderer() {
            setLayout(new BorderLayout());
            add(BorderLayout.CENTER, myTextLabel);
            add(BorderLayout.WEST, myNodeIcon);
            add(BorderLayout.EAST, myProjectIcon);
            setBorder(JBUI.Borders.empty(1, 0, 3, 10));
        }

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            myTextLabel.getTreeCellRendererComponent(tree, value, selected, expanded, leaf, row, hasFocus);
            myTextLabel.setFont(tree.getFont());
            myProjectIcon.setIcon(null);

            Base baseNode = extractNode(value);
            if (baseNode instanceof ConfigurableNode) {
                Configurable configurable = baseNode.getConfigurable();

                if (OptionsEditor.isProjectConfigurable(configurable)) {
                    myProjectIcon.setIcon(TargetAWT.to(PlatformIconGroup.generalProjectconfigurable()));
                }
            }

            return this;
        }
    }
```

**Comment by DevCharly** [comment]
See PR #935

**Comment by VISTALL** [comment]
Tested patch from PR, and works as expected. Thanks you ;)
