### ISSUE TITLE
Font issues with CJK

### ISSUE THREAD

**Issue by wlfbck** [JFormDesigner/FlatLaf#923]
I'm running into some issues using FlatLaf with CJK languages. The thing is, it's not an error across the board (although it does affect the majority of text). Other languages like slovenian or russian are not affected. All texts are UTF8 and interpreted as such.

Here it is in JTabbedPane header (custom class):
![grafik](https://github.com/user-attachments/assets/a8d814d8-98bb-433e-b2bb-568bc733f2dc)

As you can see the "TC" in that one label is rendered correctly.

And here are JButtons (also custom class):
![grafik](https://github.com/user-attachments/assets/8f73b5a4-fd7f-47bd-874a-8bde68da2b27)

This only happens when i activate FlatLaf, here are the same elements without:
![grafik](https://github.com/user-attachments/assets/c3e24759-62d8-42a9-9bdc-3dc532250e35)
![grafik](https://github.com/user-attachments/assets/e78af957-6618-4c66-b131-2e65d0577d74)

I also noticed that the characters without FlatLaf are appear anti-aliased, but not with. I suspect it has something to do with font selection and maybe our custom classes for the GUI objects, but that doesn't explain why the same type of element (the JButton) is working in some instances but not in others.

**Comment by DevCharly** [comment]
Hmm, works for me (on Windows)... 😕 

What OS and Java version do you use?

Please try following test case:

~~~java
package test;

import javax.swing.*;
import com.formdev.flatlaf.FlatLightLaf;

public class CJKTest {
    public static void main( String[] args ) {
        SwingUtilities.invokeLater( () -> {
            FlatLightLaf.setup();

            JFrame frame = new JFrame( "CJKTest" );
            frame.setDefaultCloseOperation( WindowConstants.DISPOSE_ON_CLOSE );

            JButton button = new JButton( "试试这几个字能否正确显示" );
            frame.getContentPane().add( button );
            frame.setBounds( 100, 100, 200, 100 );
            frame.setVisible( true );
        } );
    }
}
~~~

![grafik](https://github.com/user-attachments/assets/7d7c39db-33f8-4145-8bcd-67958a0dabe4)

**Comment by wlfbck** [comment]
Thank your for the quick respones! And, oh, sorry should have mentioned that. Win11 with OpenJDK 17.0.9 (Eclipse Temurin).

I also found the issue. We have some code that iterates over all fonts and sets a certain font size (our users can configure the font size). The way it does this is like this:
```
for (Enumeration<Object> e = UIManager.getDefaults().keys(); e.hasMoreElements();) {
	Object key = e.nextElement();

	Object value = UIManager.get(key);

	// set the standard fonts to fit on the screen
	if (value instanceof Font) {
		Font f = (Font) value;

		UIManager.put(key, new FontUIResource(f.getName(), f.getStyle(), getSuggestedFontSize()));
	}
}
```

I'm honestly not versed enough in Swing to know if this is a good way to do this, but it probably isn't 😆 This part of the code is ancient. Is it possible to do this in a FlatLaf compatible way?

**Comment by DevCharly** [comment]
In FlatLaf, you only need to update `defaultFont`.

Here is the code used in FlatLaf Demo:

https://github.com/JFormDesigner/FlatLaf/blob/16fc3cabf29ca1de197712cdd42b4616322e34fa/flatlaf-demo/src/main/java/com/formdev/flatlaf/demo/DemoFrame.java#L290-L298

It is important to either use `Font.deriveFont()` or `com.formdev.flatlaf.util.FontUtils.getCompositeFont( String family, int style, int size )`. If you use `new Font(..)`, then CJK characters are probably not painted.

**Comment by wlfbck** [comment]
Thank you very much, works nicely!
