### ISSUE TITLE
Suggestion: Preloader class - entry point for initializing FlatLaf

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#924]
Hello. There some options which need call before UI (for faster ui start, etc)

Methods like:
```
com.formdev.flatlaf.util.HiDPIUtils#installHiDPIRepaintManager
```

Also invoking at start can speed up UI (due natives loaded before UI show)
```
com.formdev.flatlaf.ui.FlatNativeWindowsLibrary#isLoaded
com.formdev.flatlaf.ui.FlatNativeMacLibrary#isLoaded
com.formdev.flatlaf.ui.FlatNativeLinuxLibrary#isLoaded - impossible due package-local modifier
```

And it will be like:

```java
public class Preloader {
  public void preloadNatives() {
      FlatNativeWindowsLibrary.isLoaded();
      FlatNativeMacLibrary.isLoaded();
      FlatNativeLinuxLibrary.isLoaded();
  }

  public void patchSwing() {
      HiDPIUtils.installHiDPIRepaintManager();
      // some other methods call
  }

  public void initializeAll() { 
      preloadNatives();
      
      patchSwing();
  }
}

```

**Comment by DevCharly** [comment]
And why do you think that this makes anything faster?

**Comment by VISTALL** [comment]
First of all - this class is aggregator of startup method which need call before app start (for example only, after some time I find #installHiDPIRepaintManager() - one of my user use point scale on `windows)`

About faster - yeah, it milliseconds, but if I can preload natives libraries in parallel thread at start - I'ill do. For example - unpacking natives (if used standalone jar - but its not good). I want better control on native library loading.

**Comment by DevCharly** [comment]
Forking a thread to load a 10k native library is probably slower than loading it on demand on current thread.
Don't have plans to add a "Preloader" class to FlatLaf.
