### ISSUE TITLE
ScrollBar: vertical left side scrollbar position 

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#934]
Hello. IntelliJ IDEA have left-side scroll layout for Diff Windows, etc. They used custom layout before full integration code into UI code.

Maybe reuse their layout (or custom impl)

https://github.com/JetBrains/intellij-community/blob/6ce3f93deffba0bbf45355da53e7ecc3fc0433fb/platform/platform-impl/src/com/intellij/openapi/editor/impl/LeftHandScrollbarLayout.java

In new scrollbar code, there option `JBScrollPane.Alignment`

https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ui/components/DefaultScrollBarUI.kt#L132

**Comment by DevCharly** [comment]
There is no need to do this in FlatLaf.

You can simply use `scrollPane.setLayout( new LeftHandScrollbarLayout() )`

BTW there is another implementation in `JBScrollPane`:
https://github.com/JetBrains/intellij-community/blob/97fea5ca26dfa444807a62e0f2a0a380545428a4/platform/platform-api/src/com/intellij/ui/components/JBScrollPane.java#L491
