### ISSUE TITLE
Subclass of FlatTitlePane setting tooltip for titleLabel locks window in place

### ISSUE THREAD

**Issue by IanKrL** [JFormDesigner/FlatLaf#938]
A combination of JFrame.setDefaultLookAndFeelDecorated(true); and titleLabel.setToolTipText("How are you"); breaks window movement, so when I click and drag the titlebar nothing happens.

I see this in 3.5.1 and 3.5.4. Both Linux (AlmaLinux 8.10 Gnome 3.32.2) and Windows (10 Pro 2004)

other/FlatLaf.properties
```
RootPaneUI = stuffs.MyUI
```
stuffs/SimpleLaf.java
```
package stuffs;

import javax.swing.*;

import com.formdev.flatlaf.*;

public class SimpleLaf {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            // ----Comment this line out and click-and-drag works again----
            JFrame.setDefaultLookAndFeelDecorated(true);
            FlatLaf.registerCustomDefaultsSource( "other" );
            FlatLightLaf.setup();
            final JFrame frame = new JFrame();
            final JLabel label = new JLabel("Howdy there");
            frame.add(label);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setTitle("Some Title");
            frame.setSize(350, 100);
            frame.setVisible(true);
        });

    }
}
```
stuffs/MyUI.java
```
package stuffs;

import java.awt.Dimension;

import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.plaf.ComponentUI;

import com.formdev.flatlaf.ui.FlatRootPaneUI;
import com.formdev.flatlaf.ui.FlatTitlePane;
import com.formdev.flatlaf.ui.FlatWindowResizer;

public class MyUI extends FlatRootPaneUI {

    private static class MyTitlePane extends FlatTitlePane {
        public MyTitlePane(JRootPane rootPane) {
            super(rootPane);
        }

        @Override
        protected void addSubComponents() {
                super.addSubComponents();
                // ----Comment this line out and click-and-drag works again----
                titleLabel.setToolTipText("How are you");
        }
    }

    public static ComponentUI createUI(JComponent c) {
        return new MyUI();
    }

    @Override
    protected FlatTitlePane createTitlePane() {
        return new MyTitlePane(rootPane);
    }

}
```
Run with `javac -cp flatlaf-3.5.4.jar stuffs/*.java&&java -cp flatlaf-3.5.4.jar:other/*:. stuffs.SimpleLaf`

**Comment by IanKrL** [comment]
This code works as expected in 3.3, but fails in 3.4.

**Comment by DevCharly** [comment]
>... also seeing the same issue with other manipulations of titleLabel, such as adding mouse listeners ...

Then do not add tooltips or mouse listeners to title pane 😉 

You can have either:

- Windows 10/11 handles mouse and you can move the window or
- Java handles mouse and tooltips work (require mouse listener) and mouse listener work as expected

but not both.

If a component in title area has mouse listeners (e.g. buttons), then FlatLaf assumes that the component wants process all mouse events itself (e.g. press button), and FlatLaf does not use that component for window moving (see [HTCAPTION](https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-nchittest)).

Component that are used for window moving do not receive all Java mouse events. They receive only MOUSE_MOVED, MOUSE_ENTERED and MOUSE_EXITED. But not pressed/clicked/released.

To force using a component (e.g. titleLabel) as caption use:

~~~java
comp.putClientProperty( COMPONENT_TITLE_BAR_CAPTION, true );
~~~

**Comment by IanKrL** [comment]
> Then do not add tooltips or mouse listeners to title pane 😉

Ok, Dad.

> comp.putClientProperty( COMPONENT_TITLE_BAR_CAPTION, true );

That fixes the issue, and allows both the tool tip and the movement. Thanks.
