### ISSUE TITLE
selectionArc and hoverArc for JButton used in ToolBar/Menu

### ISSUE THREAD

**Issue by AndreZeiler** [JFormDesigner/FlatLaf#940]
I am using the style group "toolBarButton" for a Button that is added inside a JMenuBar.
For the MenuItems and MenuBar I have set the selectionArc property to my desired value.
Can you add the property for the Buttons as well?
Button.toolbar.selectionArc

Currently the buttons are squar (even JButton.arc is set)
The "normal" buttons are using the Button.arc value

**Comment by DevCharly** [comment]
Hmm, works fine for me 😕 

![image](https://github.com/user-attachments/assets/4f4dc065-1d7b-4d25-9c64-8733fc3a4a55)

Slightly modified FlatLaf Demo (DemoFrame.java, line 963):

~~~java
FlatToggleButton usersButton = new FlatToggleButton();
usersButton.setSelected( true );
usersButton.setIcon( new FlatSVGIcon( "com/formdev/flatlaf/demo/icons/users.svg" ) );
usersButton.setButtonType( ButtonType.toolBarButton );
usersButton.setFocusable( false );
menuBar.add( Box.createGlue() );
menuBar.add( usersButton );
~~~

Did you remove/change the border of that button? This could cause this issue.

**Comment by AndreZeiler** [comment]
Yeah I found the problem.
I have assigned a FlatMenuItemBorder in my style group.
The reason is, because my Menu is vertically and the MenuItem border adds a margin or something similar on the left side
I will try to fix that using the FlatButtonBorder

**Comment by AndreZeiler** [comment]
With those properties in my Style Group I can get a very similar look. But not perfekt
[style]Button.menuItem=\
    iconTextGap: $MenuItem.iconTextGap; \
    toolbar.margin: 3,8,3,8; \
    margin: $MenuItem.margin

It is not perfekt. But it is ok for me

**Comment by DevCharly** [comment]
Great
