### ISSUE TITLE
SwingX demo fat jar missing

### ISSUE THREAD

**Issue by VISTALL** [JFormDesigner/FlatLaf#941]
Hello - sometimes I want check swingx reference implementation, but I can't run it like original demo - due no artifact for it.

Will be nice to have - swingx-demo jar too.

Jar for this app
![image](https://github.com/user-attachments/assets/10010748-d362-4dcf-a21e-b9c70befd461)

https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/swingx/FlatSwingXTest.java

Thanks :)

**Comment by DevCharly** [comment]
> ...sometimes I want check swingx reference implementation, but I can't run it like original demo....

You can build and run it from your IDE. Takes only a few minutes...
