### ISSUE TITLE
FlatSVGIcon Error

### ISSUE THREAD

**Issue by GokhanOzpay** [JFormDesigner/FlatLaf#944]
java Project
textField.putClientProperty("JTextField.trailingIcon", new FlatSVGIcon("/src/resources/svg/passkey_24dp.svg"));
When I use it I get this error the same code works without any problems in marven
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/github/weisj/jsvg/parser/SVGLoader

What Might Be Missing
Eclipse Version: 2024-09 (4.33.0)
Packages
flatlaf-3.3
flatlaf-extras-3.5.2
flatlaf-intellij-themes-3.5.2

**Comment by VISTALL** [comment]
Helllo. For using SVG icons need add `jsvg` to dependencies 

https://github.com/weisJ/jsvg

**Comment by GokhanOzpay** [comment]
Error
SVGLoader loader = new SVGLoader();
URL svgUrl = Main.class.getResource("src/resources/svg/passkey_24dp.svg");
System.err.println(new File("src/resources/svg/passkey_24dp.svg").exists()); // true
SVGDocument document = loader.load(Objects.requireNonNull(svgUrl, "SVG file not found"));

java.lang.NullPointerException: SVG file not found

**Comment by VISTALL** [comment]
If your source root is 'src' - resource path must be `/resources/svg/passkey_24dp.svg`. 

This code returns true, because working directory of execution equals to project root. But - if you pack app to jar, file will be not found. 

```java
System.err.println(new File("src/resources/svg/passkey_24dp.svg").exists()); // true
```

Read this https://mkyong.com/java/java-read-a-file-from-resources-folder/

**Comment by DevCharly** [comment]
> URL svgUrl = Main.class.getResource("src/resources/svg/passkey_24dp.svg");

This is wrong resource path. Use:

~~~java
URL svgUrl = Main.class.getResource("svg/passkey_24dp.svg");
~~~

**Comment by GokhanOzpay** [comment]
URL svgUrl = Main.class.getResource("resources/svg/passkey_24dp.svg");
No Error But Icon is not coming
textField.putClientProperty("JTextField.trailingIcon",new ImageIcon("src/resources/png/passkey_24dp.png"));
Same File Path png Image Icon is Coming

full code,
`void Style() {

		SVGLoader loader = new SVGLoader();
		URL svgUrl = Main.class.getResource("resources/svg/passkey_24dp.svg");
		System.err.println(
				new File("src/resources/svg/passkey_24dp.svg").exists());
		// SVGDocument svgDocument = loader.load(svgUrl);
		SVGDocument document = loader
				.load(Objects.requireNonNull(svgUrl, "SVG file not found"));
		textField.putClientProperty("JTextField.trailingIcon",
				new SVGPanel(Objects.requireNonNull(document)));
		// textField.putClientProperty("JTextField.trailingIcon",
		// new FlatSVGIcon("/src/resources/svg/passkey_24dp.svg", 50, 50));
		// textField.putClientProperty("JTextField.trailingIcon",
		// new ImageIcon("src/resources/png/passkey_24dp.png"));

	}
	static class SVGPanel extends JPanel {
		private final SVGDocument document;

		SVGPanel(SVGDocument document) {
			this.document = document;
		}

		@Override
		protected void paintComponent(Graphics g) {
			super.paintComponent(g);
			((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING,
					RenderingHints.VALUE_ANTIALIAS_ON);
			((Graphics2D) g).setRenderingHint(RenderingHints.KEY_STROKE_CONTROL,
					RenderingHints.VALUE_STROKE_PURE);

			document.render(this, (Graphics2D) g,
					new ViewBox(0, 0, getWidth(), getHeight()));
		}
	}`

**Comment by DevCharly** [comment]
Again, you're using the wrong resource path. See https://github.com/JFormDesigner/FlatLaf/issues/944#issuecomment-2549774776

**Comment by GokhanOzpay** [comment]
![Ekran görüntüsü 2024-12-19 145510](https://github.com/user-attachments/assets/7f1f980a-6794-432e-8e70-d7ea046a3a8c)

So how should this file path be in this project?

**Comment by DevCharly** [comment]
Ok, in this case `resources/svg/passkey_24dp.svg` seems to be the right resource path for `..class.getResource(..)` or for `new FlatSVGIcon(...)`.

Following should work:

~~~java
new FlatSVGIcon( "resources/svg/passkey_24dp.svg" );
~~~

If not, check whether Eclipse auto-build is enabled (Menu: Project > Build Automatically).
Also check whether Eclipse copied the svg file to the project output folder.
E.g. `<projectroot>/bin/resources/svg/passkey_24dp.svg`.

**Comment by GokhanOzpay** [comment]
`new FlatSVGIcon( "resources/svg/passkey_24dp.svg" );`
When I first did it, it didn't work. Is it because of the path?


So why didn't the other path work? Thanks for your interest.
`new SVGPanel(Objects.requireNonNull(document))`

**Comment by GokhanOzpay** [comment]
`new FlatSVGIcon( "resources/svg/passkey_24dp.svg" );`

There was another project that made this work, I found that too
When I deleted the module-info.java file, it was fixed

If the file path is not found, it appears as a small red square in my theme cobalt2

**Comment by VISTALL** [comment]
Hello @GokhanOzpay. After java 9 (and project with module file) - all resources of module not accessible outside.

You need add row like this:

```
opens resources.svg;
```

more information here https://stackoverflow.com/a/45173837
