### ISSUE TITLE
Swing. Incorrect GlassPane operation in WindowDecorated mode.

### ISSUE THREAD

**Issue by credos** [JFormDesigner/FlatLaf#948]
Hello.
Swing + Linux +  WindowDecorated

For my application to work, it is necessary to temporarily disable mouse events in the entire window.  (Disable cursor changing when hovering over a resize border.)
To do this, I use the standard GlassPane method:
[](https://docs.oracle.com/javase/tutorial/uiswing/components/rootpane.html#glasspane)

This works great if you use `setDefaultLookAndFeelDecorated(false) `or
`setDefaultLookAndFeelDecorated(true) `+ `swing.plaf.metal.MetalLookAndFeel`

But it does not work correctly if used:
`setDefaultLookAndFeelDecorated(true) `+ `setLookAndFeel(FlatDarkLaf())` or other FlatLaf themes.
In this case, GlassPane does not overlap the window title with the built-in menu and the resize top border. This leads to an unwanted change in the type of the cursor ... All other parts of the window overlap correctly.

Please advise how to act in this situation. Or (if possible) fix this bug.

**Comment by DevCharly** [comment]
This helps:

~~~java
frame.getRootPane().putClientProperty( FlatClientProperties.GLASS_PANE_FULL_HEIGHT, true );
~~~

See https://www.formdev.com/flatlaf/client-properties/#JRootPane.glassPaneFullHeight
