### ISSUE TITLE
Inconsistent table selection / move shortcuts

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#95]
If you press the `Home` key, the selection of the table will go the top of the column. If you press `Shift+Home`, it will select from the current cell to the start of the row, instead of selection to the start of the column.

If you press `Ctrl+Home`, it will jump to the start of the row, but if you press `Ctrl+Shift+Home`, it will select to the start of the column. It seems that this was mixed up somewhat.

Correct would be:

Home: Go to start of row
Ctrl+Home: Go to start of colum
Shift+Home: select from current cell to start of row
Shift+Ctrl+Home: select from current cell to start of column

The same problem exists for the `End` key.

**Comment by DevCharly** [comment]
@Bios-Marcel many thanks for pointing out this inconsistency.

It is now fixed in master branch.

**Comment by Bios-Marcel** [comment]
Cool, thanks for the quick fix.

**Comment by Bios-Marcel** [comment]
Hey, I think there's still something wrong. Maybe my explanation wasn't correct though.

The meaning of Ctrl+Home/End and Home/End still seems to be reversed. Without the modifier it should navigate inside a row (horizontal) and with the control modifier it should navigate inside a column (vertically). The same should count for selection mode, e.g. with Shift modifier.

**Comment by DevCharly** [comment]
> The meaning of Ctrl+Home/End and Home/End still seems to be reversed

Yes, this is intentional.
Compared to other L&Fs they are reversed.

The reason for reversing Ctrl+Home/End and Home/End in JTable was to be consitent with JList and JTree where you can use Home/End to jump to first/last row. Users of the application usually do not know the difference between JTable and JList. Often a JTable looks like a JList (e.g. if not editable), but Home/End seems not to work as expected (in other L&Fs).

Are the reversed keys a problem for the users of your application?

**Comment by Bios-Marcel** [comment]
I see, that totally makes sense. However, in my experience, most users see the Home / End shortcut like it is in text editors. As you also have rows and columns in there.

Either way, our users appear to be confused by this. I'd really appreciate this to be a UIManager setting. Is this easily solvable?

**Comment by DevCharly** [comment]
@Bios-Marcel you can now enabled standard JTable Home/End key behavior with:

~~~java
UIManager.put( "Table.consistentHomeEndKeyBehavior", false );
~~~

**Comment by Bios-Marcel** [comment]
Awesome, thanks a lot :)

Btw, I was eondering whether existing configuration keys are documented anywhere? If not, maybe I could contribute that, in which case the question is: Where to put it?

**Comment by Bios-Marcel** [comment]
Ah, nvm, found it here: https://www.formdev.com/flatlaf/customizing/

Would be nice if this was editable though. Is there a reason for this being embeded in your website?
If this was a .md file in the repository I'd be easier for contributors and you could also easily see when it was last updated.
